{{- if .Values.grafana }}
{{- if .Values.grafana.enabled }}
{{- range $path, $_ := .Files.Glob "grafana/alerts/*.yaml" }}
{{- $filename := base $path }}
{{- $name := trimSuffix ".yaml" $filename }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-{{ $name }}
  labels:
    grafana_alert: "1"
data:
  {{ $filename }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
