[package]
name = "blob"
type = "lib"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
bignum = { path = "../bignum" }
bigcurve = { path = "../bigcurve" }
types = { path = "../types" }
protocol_test_utils = { path = "../protocol-test-utils" }
