#!/usr/bin/env bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

name=$1
cpus=$2
arch=$3

cd $(dirname $0)

bid_per_cpu_hour=0.0433

instance_types_amd64=(
  m6a
  m7a
  m7i
)

instance_types_arm64=(
  m7g
)

# Declare an associative array to map CPU counts to instance type suffixes.
declare -A cpu_map
cpu_map=(
  [2]="large"
  [4]="xlarge"
  [8]="2xlarge"
  [16]="4xlarge"
  [32]="8xlarge"
  [48]="12xlarge"
  [64]="16xlarge"
  [96]="24xlarge"
  [128]="32xlarge"
  [192]="48xlarge"
  [0192]="metal"
)

if [ "$arch" == "x86_64" ] || [ "$arch" == "amd64" ]; then
  instances=("${instance_types_amd64[@]}")
  ami=${AMI:-$(cat ./aws/ami_id_amd64)}
elif [ "$arch" == "arm64" ]; then
  instances=("${instance_types_arm64[@]}")
  ami=${AMI:-$(cat ./aws/ami_id_arm64)}
else
  echo "Unsupported arch: $arch" >&2
  exit 1
fi

if [ -n "${AWS_INSTANCE:-}" ]; then
  instances=("$AWS_INSTANCE")
fi

set +e
IFS=',' read -ra cpu_list <<< "$cpus"
for cpu in "${cpu_list[@]}"; do
  price=$(jq -n "$bid_per_cpu_hour*$cpu*100000 | round / 100000")
  suffix=${cpu_map[$cpu]}
  for inst in "${instances[@]}"; do
    instance_type="$inst.$suffix"
    aws_request_instance_type $name $instance_type $price $ami
    code=$?
    [[ "$code" -eq 0 || "$code" -eq 143 || "$code" -eq 130 ]] && exit $code
  done
done
exit 1
