#!/usr/bin/env bash
source $(git rev-parse --show-toplevel)/ci3/source

ip=$1
sir=${2:-}
ssh_config_path=${SSH_CONFIG_PATH:-aws/build_instance_ssh_config}

echo "Terminating instance: $ip..."
dump_fail ssh -F $ssh_config_path ubuntu@$ip sudo halt -p > /dev/null

if [ -n "$sir" ]; then
    dump_fail aws ec2 cancel-spot-instance-requests --region us-east-2 --spot-instance-request-ids $sir > /dev/null
fi