#!/bin/bash
source $(git rev-parse --show-toplevel)/ci3/source

cmd=${1:-"./bootstrap.sh ci || exec zsh"}
postfix=${2:-}
cores=${CORES:-128}
NO_TERMINATE=${NO_TERMINATE:-0}
BRANCH=${BRANCH:-$(git rev-parse --abbrev-ref HEAD)}

# Trap function to terminate our running instance when the script exits.
function on_exit {
    set +e
    if [ "$NO_TERMINATE" -eq 0 ]; then
      aws_terminate_instance $iid $sir
    else
      echo "Remote machine not terminated, connect with: ./ci.sh attach"
    fi
}

# Verify that the commit exists on the remote. It will be the remote tip of itself if so.
current_commit=$(git rev-parse HEAD)
if [[ "$(git fetch origin --negotiate-only --negotiation-tip=$current_commit)" != *"$current_commit"* ]]; then
  echo "Commit $current_commit is not pushed, exiting."
  exit 1
fi

instance_name="${BRANCH//\//_}"
[ -n "$postfix" ] && instance_name+="_$postfix"

github_group "Request Build Instance"
# Terminate any existing instance with the same name.
existing_instance=$(aws ec2 describe-instances \
  --region us-east-2 \
  --filters "Name=tag:Name,Values=$instance_name" \
  --query "Reservations[].Instances[?State.Name!='terminated'].InstanceId[]" \
  --output text)
if [ -n "$existing_instance" ]; then
  echo "Terminating existing instance: $existing_instance"
  aws ec2 --region us-east-2 terminate-instances --instance-ids $existing_instance > /dev/null 2>&1
fi

# Request new instance.
ip_sir=$(aws_request_instance $instance_name $cores x86_64)
parts=(${ip_sir//:/ })
ip="${parts[0]}"
sir="${parts[1]}"
iid="${parts[2]}"
trap on_exit EXIT
github_endgroup

# If we're asking to not terminate the instance automatically, we also don't want to remove the container.
[ "$NO_TERMINATE" -eq 0 ] && args+=" --rm"

# Interactive if stdin is connected to terminal.
[ -t 0 ] && args+=" -i"

# Use ~/.ssh/build_instance_key to ssh into our requested instance.
# Run in our build container, cloning commit and running bootstrap.sh.
# We mount a volume for the docker-in-docker data as overlayfs would kill performance.
# We mount the entire host home directory into the container, giving us credentials, .bb-crs, and better performance.
# We mount /tmp into the container for performance.
# We enable the test cache, which uses a redis instance for tracking test runs.
# We set SSH_CONNECTION to something to ensure the hostname is shown in the lean prompt.
# We provide the host user and group ids to the entrypoint script to ensure alignment.
# We raise the default pid limit to 32k.
ssh -t -F $ci3/aws/build_instance_ssh_config ubuntu@$ip "
  docker run --privileged $args --name aztec_build -t \
    -v boostrap_ci_local_docker:/var/lib/docker \
    -v \$HOME:/root \
    -v /tmp:/tmp \
    -e USE_TEST_CACHE=1 \
    -e SSH_CONNECTION=' ' \
    -e LOCAL_USER_ID=\$(id -u) \
    -e LOCAL_GROUP_ID=\$(id -g) \
    -e BUILD_SYSTEM_DEBUG=${BUILD_SYSTEM_DEBUG:-} \
    -e GITHUB_LOG='${GITHUB_LOG:-}' \
    -e AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID:-}' \
    -e AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY:-}' \
    --pids-limit=32768 \
    aztecprotocol/devbox:3.0 bash -c '
      set -e
      # When restarting the container, just hang around.
      while [ -f started ]; do sleep 999; done
      touch started
      git init /root/aztec-packages
      cd /root/aztec-packages
      git remote add origin https://github.com/aztecprotocol/aztec-packages
      git fetch --depth 1 origin $current_commit
      git checkout FETCH_HEAD
      $cmd
    '
"
