#!/bin/bash
# Launches our CI image locally and runs the bootstrap.
# This replicates exactly what our CI run experiences.
# We use a volume on /var/lib/docker as overlayfs trashes performance (in fact it just breaks).
# Similarly we use tmpfs for the actual working directory in /home/aztec-dev/aztec-packages.
# We mount in aws credentials to leverage the s3 cache.
# We mount ~/.bb-crs to avoid downloading the CRS.
# The host repository is mounted in read-only, and a clone is taken to ensure a clean start.
# We set SSH_CONNECTION to something, to ensure the hostname is shown in our lean prompt.
# If anything goes wrong during the run, the container will drop into a shell.
source $(git rev-parse --show-toplevel)/ci3/source

cmd=${1:-"./bootstrap.sh ci || exec zsh"}

if ! git diff --quiet; then
  echo -e "${yellow}WARNING: There are local changes to tracked files. They won't be reflected in the build.${reset}"
fi

docker run -ti --rm --privileged \
  --name aztec_build \
  --hostname bootstrap_local \
  -v bootstrap_ci_local_docker:/var/lib/docker \
  -v $root:/aztec-packages-host:ro \
  -v $HOME/.aws:/home/aztec-dev/.aws:ro \
  -v $HOME/.bb-crs:/home/aztec-dev/.bb-crs:ro \
  --tmpfs /home/aztec-dev/aztec-packages:size=16g,exec,uid=1000,gid=1000 \
  -e SSH_CONNECTION=' ' \
  -e LOCAL_USER_ID=$(id -u) \
  -e LOCAL_GROUP_ID=$(id -g) \
  -e BUILD_SYSTEM_DEBUG=${BUILD_SYSTEM_DEBUG:-} \
  --cpus=$(get_num_cpus) \
  --pids-limit=32768 \
  aztecprotocol/devbox:3.0 bash -c "
    set -e
    git config --global --add safe.directory /aztec-packages-host/.git
    git clone --depth 1 file:///aztec-packages-host aztec-packages
    cd aztec-packages
    $cmd
"
