#!/bin/bash
# Launches our CI image locally and runs the bootstrap.
# This replicates exactly what our CI run experiences.
# It uses docker-in-docker as some test flows require it (e.g. e2e).
# We use a volume on /var/lib/docker as overlayfs trashes performance (in fact it just breaks).
# We mount in aws credentials to leverage the s3 cache.
# The host repository is mounted in read-only, and a clone is taken to ensure a clean start.
# If anything goes wrong during the run, the container will drop into a shell.
source $(git rev-parse --show-toplevel)/ci3/source

current_commit=$(git rev-parse HEAD)

if ! git diff --quiet; then
  echo "There are local changes to tracked files."
  exit 1
fi

docker run --name aztec_build -ti --rm \
  --privileged \
  -v boostrap_ci_local_docker:/var/lib/docker \
  -v $root:/aztec-packages-host:ro \
  -v $HOME/.aws:/root/.aws \
  aztecprotocol/ci:2.0 bash -c "
  /usr/local/share/docker-init.sh &> /dev/null
  git config --global --add safe.directory /aztec-packages-host/.git
  mkdir -p /root/aztec-packages && cd /root/aztec-packages
  # Ensure we get a clean clone of the repo.
  git init &>/dev/null
  git remote add origin https://github.com/aztecprotocol/aztec-packages
  git fetch --depth 1 origin $current_commit
  git checkout FETCH_HEAD &>/dev/null
  CI=1 ./bootstrap.sh fast || exec /bin/bash
"