#!/usr/bin/env bash
# Calculate the content hash for an artifact that controls rebuilds.
# Takes a list of rebuild pattern files (regex files that match patterns from repo root) or directories.
# The REPO_PATH env var can be used to point the script at the root of the git repository where the patterns
# are rooted, and where the git commands will be executed, which can be used to compute the hash in a sub repo.
# Two special test-only environment variables can control the cache.
# These are used when iterating on build infrastructure:
# - AZTEC_CACHE_NO_SCRIPTS: Don't include any shell files (namely bootstrap.sh) in cache patterns.
# - AZTEC_CACHE_COMMIT: Compute the content hash for artifacts from an earlier commit.
NO_CD=1 source ${root:-$(git rev-parse --show-toplevel)}/ci3/source

if [[ "$#" = 0 ]]; then
  echo "Error: No arguments provided."
  exit 1
fi

AZTEC_CACHE_COMMIT=${AZTEC_CACHE_COMMIT:-HEAD}
PLATFORM_TAG="${PLATFORM_TAG:-${OSTYPE:-unknown}-$(uname -m)}"

rebuild_patterns=()
for arg in "$@"; do
  if [[ -f "$arg" ]]; then
    # If the file is a rebuild patterns file, read it and add its contents to the patterns.
    rebuild_patterns+=$(cat "$arg")
    rebuild_patterns+=$'\n'
  elif [[ "$arg" == ^* ]]; then
    # Add as pattern literally
    rebuild_patterns+="$arg"$'\n'
  else
    # Ensure the folder exists, and add folder as pattern relative to repo root
    if [[ ! -d "$arg" ]]; then
      echo_stderr "Error: Directory '$arg' does not exist."
      exit 1
    fi
    arg=$(realpath --relative-to="$(git rev-parse --show-toplevel)" "$arg")
    rebuild_patterns+="$arg"$'\n'
  fi
done

GREP_PATTERN=$(echo "$rebuild_patterns" | grep -v '^$')
# Concatenate patterns with '|' and double escape backslashes for AWK filter empty lines
AWK_PATTERN=$(echo "$rebuild_patterns" | grep -v '^$' | sed 's/\\/\\\\/g' | tr '\n' '|' | sed 's/|$//')

# use git repo root because that is where our patterns are focused
cd "${REPO_PATH:-$(git rev-parse --show-toplevel)}"

diff="$({
  git diff --name-only
  git diff --staged --name-only
  git ls-files --others --exclude-standard
} | grep -E "$GREP_PATTERN" || true)"

# Check for uncommitted files/changes.
# Only use this check if AZTEC_CACHE_COMMIT is the default, otherwise the user is being explicit about using git history.
if [ -n "$diff" ] && [ "$AZTEC_CACHE_COMMIT" == "HEAD" ]; then
  # Fail. We shouldn't be changing files during the CI run.
  if [ "$CI" -eq 1 ]; then
    echo_stderr "WARNING: Noticed changes to rebuild patterns: $diff"
  fi
  # Signal to cache_upload and cache_download to not touch this file.
  echo "disabled-cache"
  exit 0
fi

# Calculate a content hash for matched files
# Use git ls-tree and AWK to filter files matching the rebuild patterns and extract their hashes
# Sort the hashes and compute the content hash
CONTENT_HASH="$(
  git ls-tree -r "$AZTEC_CACHE_COMMIT" \
    | awk -v pattern="($AWK_PATTERN)" '$4 ~ pattern {print $3}' \
    | sort \
    | git hash-object --stdin \
    | cut -c1-16
)"

# Check if file list was empty by comparing against the result of
# 'echo '' | git hash-object --stdin | cut -c1-16'
EMPTY_HASH="8b137891791fe969"
if [[ "$CONTENT_HASH" == "$EMPTY_HASH" ]]; then
  echo "No files matched the rebuild patterns $rebuild_patterns."
  echo "Awk pattern expanded: $AWK_PATTERN."
  exit 1
fi

# important: include architecture in content hash because we target x86_64 and arm64
echo $(hash_str $CONTENT_HASH-$PLATFORM_TAG)
