#!/bin/bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

if [ "$#" -lt 1 ]; then
  echo_stderr "Usage: $0 <flag name>"
  exit 1
fi

if [ "${USE_CACHE:-0}" != 1 ] ; then
  # Don't look if CI isn't set. No need to muddle with dev runs.
  echo_stderr "Running test $1 because USE_CACHE is not 1."
  exit 1
fi

NAME=$1

# Read out the build flag as it has the context of the last success.
# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  # Write the flag file to stdout, return exit success if found
  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" - --quiet --no-progress
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
  # Write the flag file to stdout, return exit success if found
  curl -s -f "$S3_ENDPOINT/build-cache/$NAME.flag" || (echo_stderr "Running test $NAME because S3 flag object not found." && exit 1)
fi
