#!/bin/bash
set -eu -o pipefail
[ "${BUILD_SYSTEM_DEBUG:-}" = 1 ] && set -x

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <tar.gz_file_to_download_and_extract>" >&2
  exit 1
fi

if [ "${USE_CACHE:-0}" -lt 1 ]; then
  # Only download if USE_CACHE is 1
  echo "Not using cache for $1 because USE_CACHE=0."
  exit 1
fi
# Get the tar.gz file name from the argument
TAR_FILE="$1"
OUT_DIR="${2:-.}"

mkdir -p "$OUT_DIR"
# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$TAR_FILE" "-" | tar -xzf - -C "$OUT_DIR" 2>/dev/null
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
  # Attempt to download and extract the cache file
  (curl -s -f "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -tzf - -C "$OUT_DIR") || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
fi
echo "Cache download and extraction of $TAR_FILE complete." >&2