#!/bin/bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

if [ -n "${GITHUB_RUN_URL:-}" ]; then
  value="$GITHUB_RUN_URL"
else
  value="Ran outside of Github Actions."
fi

[ "${USE_TEST_CACHE:-0}" -eq 1 ] && redis-cli --raw -h $ci_redis SET $1 $value