#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
set -eu

# Ensure at least one argument is provided
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <my-artifact.tar.gz>" >&2
  exit 1
fi

# Name of the artifact to delete
name="$1"

s3_path="s3://aztec-ci-artifacts/build-cache/$name"

if ! aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 ls "$s3_path" >/dev/null 2>&1; then
  aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 rm "$s3_path" >&2
else
  echo "File not found, skipping delete: $name" >&2
fi
