#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <flag name>"
  exit 1
fi

if [[ "$1" == *"disabled-cache"* ]]; then
  echo "Not uploading test flag $1 due to uncommitted changes/files."
  exit 0
fi
if [ "${CI:-0}" -lt 1 ]; then
  # Don't upload if CI isn't set. No need to muddle with dev runs.
  echo "Not uploading test flag $1 because CI=0."
  exit 0
fi

function on_exit() {
  # Cleanup the temporary tar.gz file
  rm -f .success
}
trap on_exit EXIT

NAME="$1"

shift 1
if [ -n "${GITHUB_RUN_URL:-}" ]; then
  CONTENT="Flag $NAME success cached: See $GITHUB_RUN_URL"
else
  CONTENT="Flag $NAME success cached: Ran outside of Github Actions"
fi

echo "$CONTENT" | aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp - "s3://aztec-ci-artifacts/build-cache/$NAME.flag" --quiet --no-progress
echo "Cache upload of $NAME.flag complete."
