#!/usr/bin/env bash
# List files inside a build-cache artifact through the ci3 API. For debugging.
NO_CD=1 source ${root:-$(git rev-parse --show-toplevel)}/ci3/source

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <tar.file_to_query>" >&2
  exit 1
fi

tar_file="$1"

ci3_client artifact_get "$tar_file" | tar -tzf -
