#!/bin/bash
set -eu
directory="$1"
# Runs our standard CI image with docker-in-docker enabled and the current directory mounted.
# Currently used for continuing containerized builds from earthly in docker, where we can use docker for tests.
# This may be streamlined in the future (i.e. side-stepping earthly).
docker run -ti --rm --privileged -v "$directory:/usr/src/" aztecprotocol/ci:2.0 bash -c "
  /usr/local/share/docker-init.sh &> /dev/null
  cd /usr/src
  $2
"
