#!/bin/bash
# If you want to completely silence a command, unless it fails, wrap with a call to this.
set -uo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <command> [args...]"
  exit 1
fi

output=$(bash -c "$*" 2>&1)
status=$?

if [ "$status" -ne 0 ]; then
  echo "$output"
fi

exit $status
