#!/usr/bin/env bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

# Filters any test cmd that marked to skip in the .test_patterns.yml file.
# Then filter through cache to remove previously successfully run tests.
grep -Ev -f <(yq e '.tests[] | select(.skip == true) | .regex' $root/.test_patterns.yml) | filter_cached_test_cmd
