#!/usr/bin/env bash
set -eu

memory_output_file="${MEMUSAGE_OUT:-/dev/stderr}"

############################################################################
# Run the target command under the time wrapper.
#   %M  — maximum resident set size in kilobytes.
# We redirect that single number to a temporary file so we don’t disturb the
# program’s own stdout/stderr streams.
############################################################################
function gnu_time {
  if command -v gtime >/dev/null 2>&1; then
    # macOS (brew install gnu-time)
    exec gtime "$@"
    return
  fi
  if ! command -v /usr/bin/time >/dev/null 2>&1; then
    # TODO remove this auto-installation once build image is updated properly
    echo "Running: sudo apt install -y time" >&2
    sudo apt install -y time || {
      echo "Tried to auto-install GNU time but couldn't. Do so manually" >&2
      exit 1
    }
  fi
  exec /usr/bin/time "$@"
}

gnu_time -f '%M' -o "$memory_output_file" "$@"
