#!/usr/bin/env bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

ci_log_id=$1

if [[ "$TARGET_BRANCH" == "merge-train/barretenberg" ]]; then
  commit_title=$(git log -1 --pretty=format:'%s')
  commit_author=$(git log -1 --pretty=format:'%an')

  # Send slack message
  read -r -d '' data <<EOF
{
  "channel": "#honk-team",
  "text": "There was [a failure](http://ci.aztec-labs.com/$ci_log_id) in the merge-train!\n$commit_title by $commit_author"
}
EOF

  curl -X POST https://slack.com/api/chat.postMessage \
    -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
    -H "Content-type: application/json" \
    --data "$data" &>/dev/null
fi
