#!/usr/bin/env bash
# For running test cmds that are pathed relative to the repo root.
# Commands are read from stdin.
NO_CD=1 source $ci3/source

[ "${STRICT_SCHEDULING:-0}" -eq 1 ] && exec parallelise_strict "$@"

cd $root

if [ -z "${1:-}" ]; then
  num_cpus=$(get_num_cpus)
  jobs=$((num_cpus / 2))
else
  jobs=$(get_num_cpus_max ${1:-})
fi

parallel_args="-j$jobs --memsuspend $(memsuspend_limit) --line-buffer --joblog joblog.txt"

if [ "${NO_FAIL_FAST:-0}" -eq 0 ]; then
  parallel_args+=" --halt now,fail=1"
fi

echo "Starting parallel run with max $jobs jobs..."

# If we're in a terminal default to a progress bar, and use cache_log to save output to redis.
# Otherwise use denoise to display dots and save output to redis.
if [ -t 1 ]; then
  set +e
  output=$(parallel $parallel_args --bar 'DUMP_FAIL=1 run_test_cmd {}' | DUP=1 cache_log "Test run"; exit ${PIPESTATUS[0]})
  code=$?
  if [ "$code" -ne 0 ]; then
    echo -e "$output"
    exit 1
  fi
  set -e
else
  denoise "parallel $parallel_args 'run_test_cmd {}'"
fi

slow_jobs=$(cat joblog.txt | \
  awk 'NR>1 && $4 > 300 {print | "sort -k4,4"}' | \
  awk '{print $4 ": " substr($0, index($0, $10))}')
if [ -n "$slow_jobs" ]; then
  echo -e "${yellow}WARNING: The following tests exceed 5 minute runtimes. Break them up or rethink them.${reset}"
  echo "$slow_jobs"
fi

echo "Completed run of $(tail -n+2 joblog.txt | wc -l) tests in $SECONDS seconds."
