#!/bin/bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

cmd=$1
test_cmd="${cmd#* }"
key=$(hash_str "$cmd")

if [ "${USE_TEST_CACHE:-0}" -eq 1 ] && [ "$(redis-cli --raw -h $CI_REDIS EXISTS $key)" == "1" ]; then
  exit 0
fi

set +e
output=$(bash -c "$test_cmd" 2>&1)
code=$?

if [ -n "$CI_REDIS" ]; then
  echo "$output" | redis-cli -h $CI_REDIS -x SETEX $key 604800 &>/dev/null
  log_info=" ${yellow}$key${reset}"
fi

if [ $code -eq 0 ]; then
  [ "${VERBOSE:-0}" -eq 1 ] && echo -e "${green}PASSED${reset}${log_info:-}: $test_cmd"
else
  echo -e "${red}FAILED${reset}${log_info:-}: $test_cmd (code: $code)"
  echo "$output"
  echo -e "${red}FAILED${reset}${log_info:-}: $test_cmd (code: $code)"
fi

exit $code