#!/bin/bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source

cmd=$1
test_cmd="${cmd#* }"

key=$(hash_str "$cmd")
# Discard the content hash.
shift

if [ "${USE_TEST_CACHE:-0}" -eq 1 ] && [ "$(redis-cli --raw -h $ci_redis EXISTS $key)" == "1" ]; then
  exit 0
fi

set +e
output=$(dump_fail "$test_cmd")
code=$?

if [ $? -ne 0 ]; then
  echo "$output"
elif [ "${USE_TEST_CACHE:-0}" -eq 1 ]; then
  {
    echo "Command: $*"
    echo "$output"
  } | redis-cli -h $ci_redis -x SETEX $key 604800 &>/dev/null
fi

exit $code