#!/usr/bin/env bash
NO_CD=1 source $(git rev-parse --show-toplevel)/ci3/source
source $ci3/source_redis

if [ -z "${SLACK_BOT_TOKEN:-}" ]; then
  exit 0
fi

channel=${2:-"#aztec3-ci"}
data=$(jq -n --arg channel "$channel" --arg text "$1" '{channel: $channel, text: $text}')

curl -X POST https://slack.com/api/chat.postMessage \
  -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
  -H "Content-type: application/json" \
  --data "$data" &>/dev/null
