#!/bin/bash
# Script base for testing the cache with minio.
# The cache is essentially ephemeral this way.
# Any calls to cache_* functions work with hitting local minio instead of S3.
source "$(git rev-parse --show-toplevel)/ci3/source"

TEST_PORT=9338

# Configure AWS parameters to use MinIO
# S3_BUILD_CACHE_AWS_PARAMS: Used by cache/download and cache/upload
export S3_BUILD_CACHE_AWS_PARAMS="--endpoint-url http://localhost:$TEST_PORT"
export AWS_SECRET_ACCESS_KEY="minioadmin"
export AWS_ACCESS_KEY_ID="minioadmin"

function minio_cleanup() {
  minio_delete_cache
}
trap minio_cleanup EXIT

function minio_delete_cache() {
  aws --endpoint http://localhost:$TEST_PORT \
    s3 rm s3://aztec-ci-artifacts --recursive --include "*" 2>&1 || true
}

function minio_start() {
  echo "Starting MinIO..."
  docker start minio-test-db &>/dev/null || docker run -d --name minio-test-db \
    -p $TEST_PORT:9000 \
    -v minio-data:/data \
    quay.io/minio/minio server /data

  # Wait for MinIO to be ready
  until nc -z 127.0.0.1 $TEST_PORT >/dev/null 2>&1; do
    sleep 1
  done

  # Create the cache bucket
  echo "Creating MinIO bucket for cache..."
  aws --endpoint-url http://localhost:$TEST_PORT s3 mb s3://aztec-ci-artifacts 2>/dev/null || true
}

# If MinIO is already running, ensure the cache is deleted
if nc -z 127.0.0.1 $TEST_PORT >/dev/null 2>&1; then
  minio_delete_cache
fi

minio_start