#!/usr/bin/env bash
# Starts an interactive shell with the build system initialized.
# Good for playing around with build system during development.
NO_CD=1 source $(dirname "$0")/source

PATH=$ci3/internal:$PATH

PROMPT_LEAN_LEFT=augment_prompt exec $SHELL