#pragma once
/**
 * @brief ECFFT domain structure for BaseFold FRI folding.
 *
 * Stores the domain layers L_0, L_1, ..., L_k connected by 2-to-1 rational maps (isogenies).
 * At each layer, the pairing invariant holds:
 *   psi_i(L_i[j]) = psi_i(L_i[j + m/2]) = L_{i+1}[j]
 *
 * The FRI fold uses the ECFFT Part II (BSCKL22) pointwise hash:
 *
 *   For pair (s_0, s_1) = (L_i[j], L_i[j + m/2]) with degree bound d, challenge z:
 *     e = d/2 - 1
 *     a = f(s_0) / s_0^e          (normalize by v(s_0)^e, v(x) = x for our isogeny)
 *     b = f(s_1) / s_1^e
 *     slope = (b - a) / (s_1 - s_0)
 *     fold_z(f)(L_{i+1}[j]) = a + slope * (z - s_0)
 *
 * This is POINTWISE: each output depends on exactly 2 inputs.
 */

#include "barretenberg/ecc/curves/grumpkin/grumpkin.hpp"
#include <cstddef>
#include <string>
#include <vector>

namespace bb::basefold {

// Fq = Grumpkin scalar field = BN254 base field (bb::fq)
// This is the field our ECFFT domains live in.
// Note: grumpkin::fq = bb::fr (BN254 scalar field), which is NOT what we want.
// We need bb::fq = BN254 base field, which is the Grumpkin scalar field.
using Fq = bb::fq;

/**
 * @brief One layer of the ECFFT domain hierarchy.
 */
struct EcfftDomainLevel {
    std::vector<Fq> domain;        // L_i: domain points, size m
    std::vector<Fq> pair_diff_inv; // 1/(s_1 - s_0) for each pair, size m/2

    size_t size() const { return domain.size(); }
    size_t num_pairs() const { return domain.size() / 2; }

    /**
     * @brief Get the pair (s_0, s_1) at index j.
     */
    std::pair<Fq, Fq> pair_at(size_t j) const
    {
        size_t half = domain.size() / 2;
        return { domain[j], domain[j + half] };
    }
};

/**
 * @brief Complete ECFFT domain for FRI folding.
 */
struct EcfftDomain {
    size_t log_n;                         // log2 of initial domain size
    size_t num_rounds;                    // = log_n (number of folding rounds)
    std::vector<EcfftDomainLevel> levels; // levels[0..num_rounds], levels[i].size() = n / 2^i

    /**
     * @brief Compute the expected fold value for a single pair opening.
     *
     * Given f(s_0) and f(s_1) at pair index j in round round_idx with
     * degree bound degree_bound and challenge z, returns the expected
     * value at levels[round_idx + 1].domain[j].
     *
     * Cost: 2 field exponentiations + 2 inversions + O(1) field ops.
     * (The inversions can be precomputed if desired.)
     *
     * @tparam T The value type (Fq for scalar, or a group element type).
     */
    template <typename T>
    T fold_pair(size_t round_idx, size_t degree_bound, size_t j, const T& f_s0, const T& f_s1, const Fq& z) const
    {
        const auto& level = levels[round_idx];
        size_t half = level.size() / 2;
        size_t e = degree_bound / 2 - 1;

        Fq s0 = level.domain[j];
        Fq s1 = level.domain[j + half];
        Fq diff_inv = level.pair_diff_inv[j];

        if (e == 0) {
            // a = f_s0, b = f_s1
            T slope = (f_s1 - f_s0) * diff_inv;
            return f_s0 + slope * (z - s0);
        }

        // Normalize: a = f_s0 * s0^{-e}, b = f_s1 * s1^{-e}
        Fq s0_e_inv = s0.pow(e).invert();
        Fq s1_e_inv = s1.pow(e).invert();

        T a = f_s0 * s0_e_inv;
        T b = f_s1 * s1_e_inv;
        T slope = (b - a) * diff_inv;
        return a + slope * (z - s0);
    }

    /**
     * @brief Load domain from a binary file generated by ecfft_precompute.py.
     */
    static EcfftDomain load_binary(const std::string& path);

    /**
     * @brief Build domain from hardcoded hex string arrays.
     *
     * @param layer_hex_arrays Array of (layer_data_ptr, layer_size) pairs.
     * @param pair_diff_inv_arrays Array of (diff_inv_ptr, half_size) pairs.
     * @param num_rounds Number of folding rounds.
     */
    static EcfftDomain from_hex_arrays(size_t log_n,
                                       const std::vector<std::pair<const char* const*, size_t>>& layer_hex,
                                       const std::vector<std::pair<const char* const*, size_t>>& diff_inv_hex);
};

} // namespace bb::basefold
