VERSION 0.8

format:
  FROM ../+bootstrap
  RUN cargo fmt --check
  RUN cargo clippy

run:
    FROM ubuntu:noble
    COPY +bootstrap/avm-transpiler /usr/src/avm-transpiler
    ENTRYPOINT ["/usr/src/avm-transpiler"]
