// TypeScript twin of noir-projects/aztec-nr/auth_registry_address/src/lib.nr.
//
// While auth_registry remains a protocol contract, this exports the magic slot-1 address. Once
// auth_registry is demoted to a non-protocol contract, this file is regenerated by
// `yarn-project/protocol-contracts/src/scripts/derive_auth_registry.ts` from the compiled
// artifact (salt = Fr(1), deployer = AztecAddress::zero(), public_keys = default).
import { Fr } from '@aztec/foundation/curves/bn254';
import { AztecAddress } from '@aztec/stdlib/aztec-address';

export const AUTH_REGISTRY_ADDRESS: AztecAddress = AztecAddress.fromBigInt(1n);
export const AUTH_REGISTRY_CLASS_ID: Fr = Fr.ZERO;
