/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractInstanceWithAddress,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  FunctionSelectorLike,
  NoirCompiledContract,
  Point,
  PublicKey,
  Wallet,
  WrappedFieldLike,
  loadContractArtifact,
} from '@aztec/aztec.js';

import DocsExampleContractArtifactJson from '../target/docs_example_contract-DocsExample.json' assert { type: 'json' };

export const DocsExampleContractArtifact = loadContractArtifact(
  DocsExampleContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract DocsExample;
 */
export class DocsExampleContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, DocsExampleContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, DocsExampleContract.artifact, wallet) as Promise<DocsExampleContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<DocsExampleContract>(
      Point.ZERO,
      wallet,
      DocsExampleContractArtifact,
      DocsExampleContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet) {
    return new DeployMethod<DocsExampleContract>(
      publicKey,
      wallet,
      DocsExampleContractArtifact,
      DocsExampleContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DocsExampleContractArtifact;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    /** update_legendary_card(randomness: field, points: integer) */
    update_legendary_card: ((randomness: FieldLike, points: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(contract_address: struct, nonce: field, storage_slot: field, serialized_note: array) */
    compute_note_hash_and_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      serialized_note: FieldLike[],
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** simple_macro_example(a: field, b: field) */
    simple_macro_example: ((a: FieldLike, b: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** initialize_stable(points: integer) */
    initialize_stable: ((points: bigint | number) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_leader() */
    get_leader: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** increase_legendary_points() */
    increase_legendary_points: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** simple_macro_example_expanded(a: field, b: field) */
    simple_macro_example_expanded: ((a: FieldLike, b: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** get_stable() */
    get_stable: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** insert_note(amount: integer, randomness: field) */
    insert_note: ((amount: bigint | number, randomness: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_legendary_card() */
    get_legendary_card: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** match_stable(account: struct, points: integer) */
    match_stable: ((account: AztecAddressLike, points: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** insert_notes(amounts: array) */
    insert_notes: ((amounts: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_imm_card() */
    get_imm_card: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_immutable_singleton(randomness: field, points: integer) */
    initialize_immutable_singleton: ((randomness: FieldLike, points: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** initialize_private(randomness: field, points: integer) */
    initialize_private: ((randomness: FieldLike, points: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** view_imm_card() */
    view_imm_card: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** read_note(amount: field, comparator: integer) */
    read_note: ((amount: FieldLike, comparator: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>;

    /** is_imm_initialized() */
    is_imm_initialized: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_legendary_initialized() */
    is_legendary_initialized: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
