[package]
name = "recursive_verification_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { path = "../../../../noir-projects/labs/aztec-nr/aztec" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v6.0.0-nightly.20260812", directory = "barretenberg/noir/bb_proof_verification" }
