// Auto generated module

import { ContractAbi } from '@aztec/foundation/abi';
import ChildJson from './child_contract.json' assert { type: 'json' };
import EasyZkTokenJson from './easy_zk_token_contract.json' assert { type: 'json' };
import LendingJson from './lending_contract.json' assert { type: 'json' };
import ParentJson from './parent_contract.json' assert { type: 'json' };
import EcdsaAccountJson from './ecdsa_account_contract.json' assert { type: 'json' };
import NonNativeTokenJson from './non_native_token_contract.json' assert { type: 'json' };
import PokeableTokenJson from './pokeable_token_contract.json' assert { type: 'json' };
import PendingCommitmentsJson from './pending_commitments_contract.json' assert { type: 'json' };
import SchnorrSingleKeyAccountJson from './schnorr_single_key_account_contract.json' assert { type: 'json' };
import TestJson from './test_contract.json' assert { type: 'json' };
import SchnorrMultiKeyAccountJson from './schnorr_multi_key_account_contract.json' assert { type: 'json' };
export const EasyZkTokenAbi = EasyZkTokenJson as ContractAbi;
import ZkTokenJson from './zk_token_contract.json' assert { type: 'json' };
import UniswapJson from './uniswap_contract.json' assert { type: 'json' };
import PublicTokenJson from './public_token_contract.json' assert { type: 'json' };
export const LendingAbi = LendingJson as ContractAbi;
export const EcdsaAccountAbi = EcdsaAccountJson as ContractAbi;
export const ChildAbi = ChildJson as ContractAbi;
export const ParentAbi = ParentJson as ContractAbi;
export const PendingCommitmentsAbi = PendingCommitmentsJson as ContractAbi;
export const NonNativeTokenAbi = NonNativeTokenJson as ContractAbi;
export const PokeableTokenAbi = PokeableTokenJson as ContractAbi;
export const PublicTokenAbi = PublicTokenJson as ContractAbi;
export const SchnorrSingleKeyAccountAbi = SchnorrSingleKeyAccountJson as ContractAbi;
export const TestAbi = TestJson as ContractAbi;
export const SchnorrMultiKeyAccountAbi = SchnorrMultiKeyAccountJson as ContractAbi;
export const ZkTokenAbi = ZkTokenJson as ContractAbi;
export const UniswapAbi = UniswapJson as ContractAbi;
