services:
  fork:
    image: aztecprotocol/build:3.0
    cpus: 1
    cpuset: ${CPU_LIST:-}
    mem_limit: 2G
    entrypoint: 'anvil --silent -p 8545 --host 0.0.0.0 --chain-id 31337'

  local-network:
    image: aztecprotocol/build:3.0
    cpus: 4
    cpuset: ${CPU_LIST:-}
    mem_limit: 8G
    stop_grace_period: 60s
    volumes:
      - ../../../:/root/aztec-packages
      - ${HOME}/.bb-crs:/root/.bb-crs
    working_dir: /root/aztec-packages/yarn-project/aztec
    command: 'node ./dest/bin start --local-network'
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-verbose}
      ETHEREUM_HOSTS: http://fork:8545
      L1_CHAIN_ID: 31337
      FORCE_COLOR: ${FORCE_COLOR:-1}
      ARCHIVER_POLLING_INTERVAL_MS: 500
      P2P_BLOCK_CHECK_INTERVAL_MS: 500
      SEQ_POLLING_INTERVAL_MS: 500
      WS_BLOCK_CHECK_INTERVAL_MS: 500
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      P2P_MIN_TX_POOL_AGE_MS: 0
      SEQ_ENABLE_PROPOSER_PIPELINING: 'true'
      HARDWARE_CONCURRENCY: ${HARDWARE_CONCURRENCY:-}

  docs-examples:
    image: aztecprotocol/build:3.0
    cpus: 4
    cpuset: ${CPU_LIST:-}
    mem_limit: 8G
    volumes:
      - ../../../:/root/aztec-packages
      - ${HOME}/.bb-crs:/root/.bb-crs
    working_dir: /root/aztec-packages/docs/examples/ts/aztecjs_runner
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-verbose}
      FORCE_COLOR: ${FORCE_COLOR:-1}
      AZTEC_NODE_URL: http://local-network:8080
      ETHEREUM_HOST: http://fork:8545
    entrypoint: >
      bash -c '
        while ! nc -z local-network 8080; do sleep 1; done;
        ./run.sh
      '
    depends_on:
      - local-network
      - fork
