// Native 17x15 CIOS Montgomery multiply generator for BN254 Fq.
// ONE rep (17x15), ONE R=2^255, NATIVE 15-bit reduction (reduces by 2^255).
// NO 13-bit, NO 2^260, NO repack, NO domain correction. In and out are 17x15.
//
// Reuses the canonical REGIME-COLCARRY CIOS body from wt-cios-b15
// (cios_limbgen.mjs genColCarry): per-column inter-column carry normalized at
// each column. STRIPS emitDomainCorrection + emitPackReduce (the div32/halve5
// ×2^-5 + repack-to-20x13). Output stays native 17x15; the surrounding pipeline
// consumes 17x15 so NO correction is ever needed.
//
// Emits:
//   (1) WGSL fn montmul_cios15native(a,b)->BigInt with NAMED scalar accumulators
//       s0..s17 (no dynamic indexing), fully unrolled, compile-time indices.
//   (2) A host JS mirror montmulMirror(a,b) executing the IDENTICAL u32 ops.
//
// Carry bound (B=15, n=17), REGIME-COLCARRY (columns normalized immediately so
// each s_j < 2^15 between columns):
//   multiply col j:  v = s_j + a_i*b_j + c,  s_j<2^15, a_i*b_j<=(2^15-1)^2,
//                    c (carry) <= floor(((2^15-1)+(2^15-1)^2)>>15) < 2^15+1.
//     => v <= (2^15-1) + (2^15-1)^2 + 2^15 < 2^30 + 2^16 < 2^31. fits u32. ✓
//   reduce col j:   v = s_j + m*p_j + c, same bound < 2^31. ✓
//   top-word folds add a single carry < 2^15. ✓
// So every intermediate < 2^31 and single u32 accumulators are safe.

import { readFileSync } from 'node:fs';
const C = JSON.parse(readFileSync(new URL('./constants.json', import.meta.url)));
export const CONST = C;

// ---------------------------------------------------------------------------
// HOST MIRROR — reproduces the emitted WGSL u32 ops EXACTLY. All intermediate
// values are < 2^31 (proven above) so plain JS number arithmetic is exact and
// equals u32 arithmetic; we still & MASK and >> B exactly as the WGSL does.
// REGIME-COLCARRY: multiply pass then reduce pass, both with per-column carry.
// ---------------------------------------------------------------------------
export function montmulMirror(a, b) {
  const B = C.B, N = C.N, MASK = C.MASK, N0 = C.N0, P = C.p_limbs;
  // s0..sN  (N+1 named slots). s[N] holds the top word.
  const s = new Array(N + 1).fill(0);
  for (let i = 0; i < N; i++) {
    const ai = a[i] >>> 0;
    // ---- multiply pass: (c, s_j) = s_j + a_i*b_j + c ; top s_N += c ----
    let c = 0;
    {
      const v = (s[0] + ai * (b[0] >>> 0)) >>> 0;   // j=0 has no incoming c
      s[0] = v & MASK; c = v >> B;
    }
    for (let j = 1; j < N; j++) {
      const v = (s[j] + ai * (b[j] >>> 0) + c) >>> 0;
      s[j] = v & MASK; c = v >> B;
    }
    s[N] = (s[N] + c) & MASK;                        // top absorbs carry

    // ---- reduce pass: m = s0*N0 mod 2^B ; s = (s + m*p)/2^B ----
    const m = (s[0] * N0) & MASK;
    {
      const v = (s[0] + m * P[0]) >>> 0;             // t0 -> 0, only carry out
      c = v >> B;
    }
    for (let j = 1; j < N; j++) {
      const v = (s[j] + m * P[j] + c) >>> 0;
      s[j - 1] = v & MASK; c = v >> B;               // shift down
    }
    {
      const v = (s[N] + c) >>> 0;
      s[N - 1] = v & MASK; c = v >> B;
    }
    s[N] = c;
  }
  // Result in s0..s_{N-1} (in [0,2p)); final conditional subtract p.
  return condSubP(s);
}

// Conditional subtract p if value >= p, native 15-bit limbs. Mirrors WGSL emit.
export function condSubP(sIn) {
  const B = C.B, N = C.N, MASK = C.MASK, P = C.p_limbs;
  const s = sIn.slice(0, N);
  const d = new Array(N);
  let borrow = 0;
  for (let j = 0; j < N; j++) {
    // i32 signed subtract, mirrors WGSL i32(s)-i32(p)-i32(borrow)
    const dd = (s[j] | 0) - (P[j] | 0) - (borrow | 0);
    d[j] = dd & MASK;                 // low B bits
    borrow = dd < 0 ? 1 : 0;
  }
  // if borrow==0 (s>=p) use d else keep s
  const out = new Array(N);
  for (let j = 0; j < N; j++) out[j] = borrow === 0 ? d[j] : (s[j] & MASK);
  return out;
}

// ---------------------------------------------------------------------------
// WGSL EMITTER — fully unrolled, NAMED scalar accumulators s0..sN, compile-time
// indices only. No runtime-indexed array. Only >>15 and &32767 (limb-aligned),
// never a shift/mask crossing a limb bound.
// ---------------------------------------------------------------------------
export function emitWGSL(fnName = 'montmul_cios15native') {
  const N = C.N, B = C.B, MASK = C.MASK, N0 = C.N0, P = C.p_limbs;
  const L = [];
  const w = (x) => L.push(x);
  w(`// AUTO-GENERATED by gen_cios15n.mjs — native 17x15 CIOS, R=2^255, NO correction.`);
  w(`// ONE rep (17x15). NO 13-bit, NO 2^255-repack-to-260, NO div32/halve/correction.`);
  w(`// REGIME-COLCARRY: per-column carry normalized immediately (bound < 2^31).`);
  w(`fn ${fnName}(a: BigInt, b: BigInt) -> BigInt {`);
  // named accumulators s0..sN
  for (let k = 0; k <= N; k++) w(`  var s${k}: u32 = 0u;`);
  // p limbs as named compile-time lets
  for (let j = 0; j < N; j++) w(`  let p${j}: u32 = ${P[j]}u;`);
  w(`  let N0: u32 = ${N0}u;`);
  w(`  var c: u32;`);
  w(`  var v: u32;`);
  w(`  var m: u32;`);

  for (let i = 0; i < N; i++) {
    w(`  // ===== outer i=${i} : multiply then reduce =====`);
    w(`  let a${i}: u32 = a.limbs[${i}];`);
    // multiply pass
    w(`  v = s0 + a${i} * b.limbs[0]; s0 = v & ${MASK}u; c = v >> ${B}u;`);
    for (let j = 1; j < N; j++) {
      w(`  v = s${j} + a${i} * b.limbs[${j}] + c; s${j} = v & ${MASK}u; c = v >> ${B}u;`);
    }
    w(`  s${N} = (s${N} + c) & ${MASK}u;`);
    // reduce pass
    w(`  m = (s0 * N0) & ${MASK}u;`);
    w(`  v = s0 + m * p0; c = v >> ${B}u;`);          // t0 -> 0
    for (let j = 1; j < N; j++) {
      w(`  v = s${j} + m * p${j} + c; s${j - 1} = v & ${MASK}u; c = v >> ${B}u;`);
    }
    w(`  v = s${N} + c; s${N - 1} = v & ${MASK}u; c = v >> ${B}u;`);
    w(`  s${N} = c;`);
  }

  // final conditional subtract of p (native 15-bit, i32 borrow)
  w(`  // ---- final conditional subtract of p (native 15-bit) ----`);
  w(`  var out: BigInt;`);
  w(`  var borrow: i32 = 0;`);
  w(`  var dd: i32;`);
  for (let j = 0; j < N; j++) {
    w(`  dd = i32(s${j}) - ${P[j]} - borrow; out.limbs[${j}] = u32(dd) & ${MASK}u; borrow = select(0, 1, dd < 0);`);
  }
  // if borrow != 0 then value < p, keep original s
  for (let j = 0; j < N; j++) {
    w(`  out.limbs[${j}] = select(out.limbs[${j}], s${j}, borrow != 0);`);
  }
  w(`  return out;`);
  w(`}`);
  return L.join('\n');
}

if (process.argv.includes('--emit')) {
  const wgsl = emitWGSL();
  const { writeFileSync } = await import('node:fs');
  writeFileSync(new URL('./montmul_cios15native.wgsl.gen', import.meta.url), wgsl);
  console.log('emitted', wgsl.split('\n').length, 'lines');
}
