{
 "title": "Aztec Node",
 "description": "Stats from the Aztec Node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "L1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average gas cost gwei",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aztec_l1_publisher_gas_price_gwei_sum[$__rate_interval]) / rate(aztec_l1_publisher_gas_price_gwei_count[$__rate_interval])",
     "legendFormat": "Avg gas price gwei"
    }
   ]
  },
  {
   "title": "L1 transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(aztec_l1_publisher_tx_count{aztec_ok=\"true\"}[$__rate_interval])",
     "legendFormat": "L1 Tx \"{{aztec_l1_tx_type}}\""
    },
    {
     "expr": "sum(increase(aztec_l1_publisher_tx_count{aztec_ok=\"false\"}[$__rate_interval]))",
     "legendFormat": "Failed L1 txs"
    }
   ]
  },
  { "title": "Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(process_cpu_utilization)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{system_memory_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aztec_archiver_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average block size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aztec_archiver_block_size_sum[$__rate_interval]) / rate(aztec_archiver_block_size_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(aztec_node_receive_tx_count[$__rate_interval])",
     "legendFormat": "{{ aztec_ok }}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average transaction size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(aztec_mempool_tx_size_bytes_sum[$__rate_interval]) / rate(aztec_mempool_tx_size_bytes_count[$__rate_interval])",
     "legendFormat": "Tx size"
    }
   ]
  },
  {
   "title": "Transactions in mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aztec_mempool_tx_count", "legendFormat": "__auto" }
   ]
  }
 ]
}