#!/bin/bash
# Runs tests on each module in parallel, in a tmux split
# Use ci3 script base.
source $(git rev-parse --show-toplevel)/ci3/base/source
$ci3/tmux/split ci3-test-all ./avm-transpiler ./bb ./boxes ./l1-contracts ./noir ./noir-projects ./yarn-packages