#!/bin/bash
# An entrypoint tailored to run tests on one module.
# Use ci3 script base.
source $(git rev-parse --show-toplevel)/ci3/base/source

USE_CACHE=1 USE_TESTS=1 ../../avm-transpiler/bootstrap.sh