import { AztecAddress } from '@aztec/aztec.js/addresses';
import { BlockNumber, SlotNumber } from '@aztec/foundation/branded-types';
import { Fr } from '@aztec/foundation/curves/bn254';
import { EthAddress } from '@aztec/foundation/eth-address';
import {
  AZTEC_ADDRESS,
  BIGINT,
  BLOCK_HASH,
  BLOCK_NUMBER,
  BOOL,
  BoundedVec,
  type CompositeMapping,
  DELIVERY_MODE,
  ETH_ADDRESS,
  FIELD,
  FUNCTION_SELECTOR,
  LEAF_INDEX,
  NOTE_SELECTOR,
  Option,
  type OracleRegistryEntry,
  SLOT_NUMBER,
  type StructMapping,
  TX_HASH,
  type TypeMapping,
  U8,
  U32,
  U64,
  U128,
  isArrayMapping,
  isBoundedVecMapping,
  isFixedArrayMapping,
  isFixedBoundedVecMapping,
  isOptionMapping,
  isStructMapping,
  tryFieldWidth,
} from '@aztec/pxe/simulator';
import { EventSelector, FunctionSelector, NoteSelector } from '@aztec/stdlib/abi';
import { BlockHash } from '@aztec/stdlib/block';
import { AppTaggingSecretKind } from '@aztec/stdlib/logs';
import { TxHash } from '@aztec/stdlib/tx';

import { EVENT_SELECTOR } from '../txe_oracle_registry.js';
import type { OracleTestScenario } from './resolver.js';

/**
 * Synthesizes fixture scenarios for every oracle in the registry whose parameters and return are built from scalars,
 * arrays/bounded vecs of them, `Option`s of them, or `STRUCT`s over them. The matching Noir serialization tests are
 * auto-generated by `#[generate_oracle_tests]` from the same seed/scenario convention.
 */
export function synthesizeDefaultFixtures(
  registry: Record<string, OracleRegistryEntry>,
): Record<string, OracleTestScenario[]> {
  const synthesized: Record<string, OracleTestScenario[]> = {};

  for (const [name, entry] of Object.entries(registry)) {
    const scenarios = synthesizeScenarios(entry);
    if (scenarios !== undefined) {
      synthesized[name] = scenarios;
    }
  }

  return synthesized;
}

/**
 * The scalar test-value implementations, mirroring the Noir synthesizer's `scalars` table in
 * `noir-projects/labs/aztec-nr/.../macros/oracle_testing.nr` exactly.
 */
const SCALAR_IMPLS: ScalarImpl[] = [
  scalar(FIELD, seed => new Fr(seed)),
  scalar(U32, seed => seed),
  scalar(BLOCK_NUMBER, seed => BlockNumber(seed)),
  scalar(BIGINT, seed => BigInt(seed)),
  scalar(U64, seed => BigInt(seed)),
  scalar(U128, seed => BigInt(seed)),
  scalar(LEAF_INDEX, seed => seed),
  scalar(U8, seed => seed),
  scalar(BOOL, seed => seed % 2 !== 0),
  scalar(AZTEC_ADDRESS, seed => AztecAddress.fromNumberUnsafe(seed)),
  scalar(ETH_ADDRESS, seed => EthAddress.fromField(new Fr(seed))),
  scalar(FUNCTION_SELECTOR, seed => FunctionSelector.fromField(new Fr(seed))),
  scalar(EVENT_SELECTOR, seed => EventSelector.fromField(new Fr(seed))),
  scalar(NOTE_SELECTOR, seed => NoteSelector.fromField(new Fr(seed))),
  scalar(BLOCK_HASH, seed => new BlockHash(new Fr(seed))),
  scalar(SLOT_NUMBER, seed => SlotNumber(seed)),
  scalar(TX_HASH, seed => TxHash.fromField(new Fr(seed))),
  // Only two delivery modes are valid for tagging, so the seed alternates between them, matching the Noir impl.
  scalar(DELIVERY_MODE, seed =>
    seed % 2 === 0 ? AppTaggingSecretKind.UNCONSTRAINED : AppTaggingSecretKind.CONSTRAINED,
  ),
];

/**
 * The composite test-value implementations, one per combinator, mirroring the Noir synthesizer's `synthesizers` table.
 */
const COMPOSITE_IMPLS: CompositeImpl[] = [
  composite(isOptionMapping, (type, seed) => [
    named(Option.some(testValueFor(type.inner, seed)), 'some'),
    named(Option.none(testValueFor(type.inner, seed)), 'none'),
  ]),
  composite(isArrayMapping, (type, seed) => [unnamed(collectionData(type.inner, seed, DEFAULT_ARRAY_LENGTH))]),
  composite(isBoundedVecMapping, (type, seed) => [
    unnamed(
      BoundedVec.from({
        data: collectionData(type.inner, seed, DEFAULT_ARRAY_LENGTH),
        maxLength: BOUNDED_VEC_MAX_LENGTH,
      }),
    ),
  ]),
  composite(isStructMapping, (type, seed) => [unnamed(structValue(type, seed))]),
  // A fixed-length array uses its real (signature) length, unlike the generic-length ARRAY which is pinned to
  // DEFAULT_ARRAY_LENGTH.
  composite(isFixedArrayMapping, (type, seed) => [unnamed(collectionData(type.inner, seed, type.length))]),
  // Same for a fixed-capacity bounded vec: real capacity, DEFAULT_ARRAY_LENGTH elements (its value type is a plain
  // element array, unlike BOUNDED_VEC), clamped to the capacity so small vecs stay valid.
  composite(isFixedBoundedVecMapping, (type, seed) => [
    unnamed(collectionData(type.inner, seed, Math.min(DEFAULT_ARRAY_LENGTH, type.maxLength))),
  ]),
];

/** The scalar mappings with a registered test-value impl. */
export const SCALAR_MAPPINGS: TypeMapping<any>[] = SCALAR_IMPLS.map(impl => impl.mapping);

/**
 * The base every seed is offset by, applied once where a parameter's position becomes its seed, so generated values
 * stay clear of 0. Must match `SEED_BASE` in the Noir `oracle_testing.nr`.
 */
const SEED_BASE = 10;

/** Elements per synthesized array and bounded vec. Must match `TEST_COLLECTION_LEN` in the Noir `oracle_testing.nr`. */
const DEFAULT_ARRAY_LENGTH = 3;

/**
 * Capacity of synthesized bounded vecs, deliberately larger than the data length so padding is exercised. Must match
 * `TEST_BOUNDED_VEC_CAP` in the Noir `oracle_testing.nr`.
 */
const BOUNDED_VEC_MAX_LENGTH = 5;

/**
 * One canonical test case for a type: the `value` to put on the wire (or expect back), and the `name` of the
 * serialization shape it exercises (unset for single-scenario types). Mirrors the Noir `Scenario<T>`.
 */
interface Scenario {
  value: unknown;
  name?: string;
}

function unnamed(value: unknown): Scenario {
  return { value };
}
function named(value: unknown, name: string): Scenario {
  return { value, name };
}

/** An impl for the single scalar `mapping` it synthesizes for. */
type ScalarImpl = {
  mapping: TypeMapping<any>;
  scenarios: (type: TypeMapping<any>, seed: number) => Scenario[];
};

/** An impl for a whole family of composite mappings, selected by its `kind` type guard. */
type CompositeImpl = {
  match: (type: TypeMapping<any>) => boolean;
  scenarios: (type: TypeMapping<any>, seed: number) => Scenario[];
};

/** A scalar impl yielding a single unnamed scenario. */
function scalar(mapping: TypeMapping<any>, value: (seed: number) => unknown): ScalarImpl {
  return { mapping, scenarios: (_type, seed) => [unnamed(value(seed))] };
}

/** A composite impl, recursing through the matched mapping's element/inner mapping. */
function composite<K extends CompositeMapping>(
  guard: (type: TypeMapping<any>) => type is K,
  scenarios: (type: K, seed: number) => Scenario[],
): CompositeImpl {
  return { match: guard, scenarios: (type, seed) => scenarios(type as K, seed) };
}

/** Synthesized element values for a collection. */
function collectionData(element: TypeMapping<any>, seed: number, length: number): unknown[] {
  return Array.from({ length }, (_, i) => testValueFor(element, seed + i));
}

/**
 * The synthesized prop bag for a struct: each field's first scenario, seeded at the field's flat wire offset so the
 * values depend on the wire layout rather than on how each side groups its fields. Mirrors the Noir reflected impls.
 */
function structValue(type: StructMapping, seed: number): Record<string, unknown> {
  const value: Record<string, unknown> = {};
  let offset = 0;
  for (const field of type.fields) {
    value[field.name] = testValueFor(field.type, seed + offset);
    const width = tryFieldWidth(field.type.shape);
    if (width === undefined) {
      // A variable-width field has no flat offset to seed the next field at, so only this oracle is unsynthesizable.
      throw new UnsynthesizableTypeError(field.type, `struct field '${field.name}' has a variable-width shape`);
    }
    offset += width;
  }
  return value;
}

/**
 * The [`Scenario`]s for `type` at `seed`, one per serialization *shape*, mirroring the Noir `scenarios_for`
 * dispatcher. Throws if the type has no matching impl.
 */
function scenariosForType(type: TypeMapping<any>, seed: number): Scenario[] {
  const impl = SCALAR_IMPLS.find(i => i.mapping === type) ?? COMPOSITE_IMPLS.find(i => i.match(type));
  if (!impl) {
    throw new UnsynthesizableTypeError(type);
  }
  return impl.scenarios(type, seed);
}

/**
 * The test value of `type` at `seed`, matching what the Noir synthesizer produces for the same type and seed. Throws
 * for types without a test-value impl.
 */
export function testValueFor(type: TypeMapping<any>, seed: number): unknown {
  return scenariosForType(type, seed)[0].value;
}

class UnsynthesizableTypeError extends Error {
  constructor(type: TypeMapping<any>, detail?: string) {
    super(detail ?? `No test-value impl for type: ${JSON.stringify(Object.keys(type))}`);
    this.name = 'UnsynthesizableTypeError';
  }
}

/**
 * Synthesizes the scenarios for one oracle by zipping every position's [`Scenario`] list to one case per test (a
 * shorter list wraps around via mod), mirroring the Noir macro. Returns `undefined` if any param or return type is
 * unsynthesizable (ephemeral arrays, structs with a variable-width field).
 */
function synthesizeScenarios(entry: OracleRegistryEntry): OracleTestScenario[] | undefined {
  try {
    return synthesizeScenariosOrThrow(entry);
  } catch (e) {
    if (e instanceof UnsynthesizableTypeError) {
      return undefined;
    }
    throw e;
  }
}

function synthesizeScenariosOrThrow(entry: OracleRegistryEntry): OracleTestScenario[] {
  const params = entry.params.map((param, index) => ({
    name: param.name,
    scenarios: scenariosForType(param.type, SEED_BASE + index),
  }));
  // The return's seed is the slot right after the last parameter, so its value is distinct from every parameter.
  const returnScenarios =
    entry.returnType === undefined ? undefined : scenariosForType(entry.returnType, SEED_BASE + entry.params.length);

  // Positions with more than one scenario drive the test count; their names are zipped together (joined with `+`) per
  // test, matching the announcements the Noir tests emit and the resolver joins.
  const positions = [...params.map(p => p.scenarios), ...(returnScenarios !== undefined ? [returnScenarios] : [])];
  const namedPositions = positions.filter(s => s.length > 1);
  const testCount = Math.max(1, ...positions.map(s => s.length));

  const scenarios: OracleTestScenario[] = [];
  for (let index = 0; index < testCount; index++) {
    const inputs: Record<string, unknown> = {};
    for (const { name, scenarios: cases } of params) {
      inputs[name] = cases[index % cases.length].value;
    }
    const output = returnScenarios === undefined ? undefined : returnScenarios[index % returnScenarios.length].value;
    const scenario =
      namedPositions.length === 0
        ? undefined
        : namedPositions.map(cases => cases[index % cases.length].name!).join('+');
    scenarios.push({ scenario, inputs, output });
  }
  return scenarios;
}
