import { AztecAddress } from '@aztec/aztec.js/addresses';
import { BlockNumber } from '@aztec/foundation/branded-types';
import { Fr } from '@aztec/foundation/curves/bn254';
import {
  AZTEC_ADDRESS,
  BIGINT,
  BLOCK_HASH,
  BLOCK_NUMBER,
  BOOL,
  BYTE,
  BoundedVec,
  FIELD,
  FUNCTION_SELECTOR,
  NOTE_SELECTOR,
  Option,
  type OracleRegistryEntry,
  type TypeMapping,
  U32,
} from '@aztec/pxe/simulator';
import { FunctionSelector, NoteSelector } from '@aztec/stdlib/abi';
import { BlockHash } from '@aztec/stdlib/block';

import type { OracleTestScenario } from './resolver.js';

/**
 * Synthesizes fixture scenarios for every oracle in the registry whose parameters and return are built from scalars,
 * arrays/bounded vecs of them, or `Option`s of them. The matching Noir serialization tests are auto-generated by
 * `#[auto_serialization_test]` from the same seed/scenario convention.
 */
export function synthesizeDefaultFixtures(
  registry: Record<string, OracleRegistryEntry>,
): Record<string, OracleTestScenario[]> {
  const synthesized: Record<string, OracleTestScenario[]> = {};

  for (const [name, entry] of Object.entries(registry)) {
    const scenarios = synthesizeScenarios(entry);
    if (scenarios !== undefined) {
      synthesized[name] = scenarios;
    }
  }

  return synthesized;
}

/**
 * The test-value implementations, one per oracle type, mirroring the Noir `OracleTestValue` trait exactly
 * (`noir-projects/aztec-nr/.../macros/oracle_testing.nr`).
 */
const TEST_VALUE_IMPLS: TestValueImpl[] = [
  scalar(FIELD, seed => new Fr(seed)),
  scalar(U32, seed => seed),
  scalar(BLOCK_NUMBER, seed => BlockNumber(seed)),
  scalar(BIGINT, seed => BigInt(seed)),
  scalar(BYTE, seed => seed),
  scalar(BOOL, seed => seed % 2 !== 0),
  scalar(AZTEC_ADDRESS, seed => AztecAddress.fromNumberUnsafe(seed)),
  scalar(FUNCTION_SELECTOR, seed => FunctionSelector.fromField(new Fr(seed))),
  scalar(NOTE_SELECTOR, seed => NoteSelector.fromField(new Fr(seed))),
  scalar(BLOCK_HASH, seed => new BlockHash(new Fr(seed))),
  composite(isOption, (type, seed) => [
    named(Option.some(firstValue(type.inner, seed)), 'some'),
    named(Option.none(firstValue(type.inner, seed)), 'none'),
  ]),
  composite(isArray, (type, seed) => [unnamed(collectionData(type.inner, seed, DEFAULT_ARRAY_LENGTH))]),
  composite(isBoundedVec, (type, seed) => [
    unnamed(
      BoundedVec.from({
        data: collectionData(type.inner, seed, DEFAULT_ARRAY_LENGTH),
        maxLength: BOUNDED_VEC_MAX_LENGTH,
      }),
    ),
  ]),
];

/**
 * The base every seed is offset by, applied once where a parameter's position becomes its seed, so generated values
 * stay clear of 0. Must match `SEED_BASE` in the Noir `oracle_testing.nr`.
 */
const SEED_BASE = 10;

/** Elements per synthesized array and bounded vec. Must match `TEST_COLLECTION_LEN` in the Noir `oracle_testing.nr`. */
const DEFAULT_ARRAY_LENGTH = 3;

/**
 * Capacity of synthesized bounded vecs, deliberately larger than the data length so padding is exercised. Must match
 * `TEST_BOUNDED_VEC_CAP` in the Noir `oracle_testing.nr`.
 */
const BOUNDED_VEC_MAX_LENGTH = 5;

/**
 * One canonical test case for a type: the `value` to put on the wire (or expect back), and the `name` of the
 * serialization shape it exercises (unset for single-scenario types). Mirrors the Noir `Scenario<T>`.
 */
interface Scenario {
  value: unknown;
  name?: string;
}

function unnamed(value: unknown): Scenario {
  return { value };
}
function named(value: unknown, name: string): Scenario {
  return { value, name };
}

/**
 * One type's test-value implementation, mirroring a Noir `impl OracleTestValue<N> for T`: `match` selects the type and
 * `scenarios` yields its [`Scenario`]s for `seed`, one per serialization shape, like Noir's
 * `oracle_test_value(seed) -> [Scenario<Self>; N]`.
 */
interface TestValueImpl {
  match: (type: TypeMapping<any>) => boolean;
  scenarios: (type: TypeMapping<any>, seed: number) => Scenario[];
}

/** A scalar impl: matches the singleton `type` by identity and yields a single unnamed scenario. */
function scalar(type: TypeMapping<any>, value: (seed: number) => unknown): TestValueImpl {
  return { match: t => t === type, scenarios: (_type, seed) => [unnamed(value(seed))] };
}

/** A composite impl: selected by the `kind` type guard, recursing through its element/inner mapping. */
function composite<K extends CompositeMapping>(
  guard: (type: TypeMapping<any>) => type is K,
  scenarios: (type: K, seed: number) => Scenario[],
): TestValueImpl {
  return { match: guard, scenarios: (type, seed) => scenarios(type as K, seed) };
}

/** Synthesized element values for a collection. */
function collectionData(element: TypeMapping<any>, seed: number, length: number): unknown[] {
  return Array.from({ length }, (_, i) => firstValue(element, seed + i));
}

/**
 * The [`Scenario`]s for `type` at `seed`, one per serialization *shape*, mirroring the Noir
 * `OracleTestValue::oracle_test_value(seed) -> [Scenario<Self>; N]`. Throws if the type has no matching impl.
 */
function scenariosForType(type: TypeMapping<any>, seed: number): Scenario[] {
  const impl = TEST_VALUE_IMPLS.find(i => i.match(type));
  if (!impl) {
    throw new UnsynthesizableTypeError(type);
  }
  return impl.scenarios(type, seed);
}

/** The first (representative) test value of `type`, used for collection elements and `Option` inners. */
function firstValue(type: TypeMapping<any>, seed: number): unknown {
  return scenariosForType(type, seed)[0].value;
}

class UnsynthesizableTypeError extends Error {
  constructor(type: TypeMapping<any>) {
    super(`No test-value impl for type: ${JSON.stringify(Object.keys(type))}`);
    this.name = 'UnsynthesizableTypeError';
  }
}

/**
 * Synthesizes the scenarios for one oracle by zipping every position's [`Scenario`] list to one case per test (a
 * shorter list wraps around via mod), mirroring the Noir macro. Returns `undefined` if any param or return type is
 * unsynthesizable (structs, ephemeral arrays).
 */
function synthesizeScenarios(entry: OracleRegistryEntry): OracleTestScenario[] | undefined {
  try {
    return synthesizeScenariosOrThrow(entry);
  } catch (e) {
    if (e instanceof UnsynthesizableTypeError) {
      return undefined;
    }
    throw e;
  }
}

function synthesizeScenariosOrThrow(entry: OracleRegistryEntry): OracleTestScenario[] {
  const params = entry.params.map((param, index) => ({
    name: param.name,
    scenarios: scenariosForType(param.type, SEED_BASE + index),
  }));
  // The return's seed is the slot right after the last parameter, so its value is distinct from every parameter.
  const returnScenarios =
    entry.returnType === undefined ? undefined : scenariosForType(entry.returnType, SEED_BASE + entry.params.length);

  // Positions with more than one scenario drive the test count; their names are zipped together (joined with `+`) per
  // test, matching the announcements the Noir tests emit and the resolver joins.
  const positions = [...params.map(p => p.scenarios), ...(returnScenarios !== undefined ? [returnScenarios] : [])];
  const namedPositions = positions.filter(s => s.length > 1);
  const testCount = Math.max(1, ...positions.map(s => s.length));

  const scenarios: OracleTestScenario[] = [];
  for (let index = 0; index < testCount; index++) {
    const inputs: Record<string, unknown> = {};
    for (const { name, scenarios: cases } of params) {
      inputs[name] = cases[index % cases.length].value;
    }
    const output = returnScenarios === undefined ? undefined : returnScenarios[index % returnScenarios.length].value;
    const scenario =
      namedPositions.length === 0
        ? undefined
        : namedPositions.map(cases => cases[index % cases.length].name!).join('+');
    scenarios.push({ scenario, inputs, output });
  }
  return scenarios;
}

/**
 * The composite `TypeMapping`s (`ARRAY`/`BOUNDED_VEC`/`OPTION`), discriminated by `kind`. The combinators attach `kind`
 * plus the inner mapping at construction; the registry erases params to the base `TypeMapping`, so the guards below
 * recover the structure for recursion.
 */
type ArrayMapping = TypeMapping & { kind: 'array'; inner: TypeMapping };
type BoundedVecMapping = TypeMapping & { kind: 'bounded-vec'; inner: TypeMapping };
type OptionMapping = TypeMapping & { kind: 'option'; inner: TypeMapping };
type CompositeMapping = ArrayMapping | BoundedVecMapping | OptionMapping;

function isArray(type: TypeMapping<any>): type is ArrayMapping {
  return 'kind' in type && type.kind === 'array';
}
function isBoundedVec(type: TypeMapping<any>): type is BoundedVecMapping {
  return 'kind' in type && type.kind === 'bounded-vec';
}
function isOption(type: TypeMapping<any>): type is OptionMapping {
  return 'kind' in type && type.kind === 'option';
}
