#!/bin/bash
# This script is used to run an e2e type test in CI (see .circleci/config.yml).
# It pulls images and runs docker-compose, which has the test as the entrypoint.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

# Run in script path.
cd `dirname $0`

export COMPOSE_FILE=${1:-docker-compose.yml}

ecr_login

REPO=aztec-sandbox

ensure_repo $REPO $ECR_REGION refresh_lifecycle
CONTENT_HASH=$(calculate_content_hash $REPO)
BASE_TAG=cache-$CONTENT_HASH
SUCCESS_TAG=$BASE_TAG

echo "Content hash: $CONTENT_HASH"
if check_rebuild $SUCCESS_TAG $REPO; then
  echo "No rebuild required."
  exit 0
fi

echo "pulling docker image for $REPO $(calculate_image_uri $REPO)-x86_64"
retry docker pull $(calculate_image_uri $REPO)-x86_64
retry docker tag $(calculate_image_uri $REPO)-x86_64 aztecprotocol/$REPO:latest

REPO=yarn-project
echo "pulling docker image for $REPO $(calculate_image_uri $REPO)"
retry docker pull $(calculate_image_uri $REPO)
retry docker tag $(calculate_image_uri $REPO) aztecprotocol/$REPO:latest

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from boxes-blank
