// AUTOGENERATED FILE - DO NOT EDIT
// Standalone types for Avm service — no barretenberg dependencies.
#pragma once

// Aztec fork of msgpack-c uses THROW/RETHROW macros
#ifndef THROW
#define THROW throw
#endif
#ifndef RETHROW
#define RETHROW throw
#endif

#include <array>
#include <cstdint>
#include <msgpack.hpp>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

/// 32-byte field element (Fr/Fq). Fixed-size, stack-allocated.
using Fr = std::array<uint8_t, 32>;

namespace bb::avm {

struct AvmSimulate {
    std::vector<uint8_t> inputs;
    MSGPACK_DEFINE_MAP(inputs)
};

struct AvmSimulateWithHints {
    std::vector<uint8_t> inputs;
    MSGPACK_DEFINE_MAP(inputs)
};

struct AvmShutdown {

    template <typename Packer> void msgpack_pack(Packer& pk) const { pk.pack_map(0); }
    void msgpack_unpack(msgpack::object const&) {}
};

struct AvmErrorResponse {
    std::string message;
    MSGPACK_DEFINE_MAP(message)
};

struct AvmSimulateResponse {
    std::vector<uint8_t> result;
    MSGPACK_DEFINE_MAP(result)
};

struct AvmSimulateWithHintsResponse {
    std::vector<uint8_t> result;
    MSGPACK_DEFINE_MAP(result)
};

struct AvmShutdownResponse {

    template <typename Packer> void msgpack_pack(Packer& pk) const { pk.pack_map(0); }
    void msgpack_unpack(msgpack::object const&) {}
};

} // namespace bb::avm
