#!/usr/bin/env bash
exit_code=254
ttl=$1
scripts/run_on_tester "
  set -eux;
  sudo shutdown -P $ttl;
  if ! [ -d ~/run-$RUN_ID ]; then
    mkdir -p ~/run-$RUN_ID;
    cd ~/run-$RUN_ID;
    git init >/dev/null 2>&1;
    git remote add origin https://github.com/aztecprotocol/aztec-packages >/dev/null 2>&1;
    git fetch --depth 1 origin $GIT_COMMIT >/dev/null 2>&1;
    git checkout FETCH_HEAD >/dev/null 2>&1;
  fi;
  cd ~/run-$RUN_ID;
  .github/ensure-tester/wrapper $DOCKERHUB_PASSWORD '$INPUT';
"
exit_code=$?
if [ $exit_code = 255 ]; then
  echo "Treating ssh termination as spot eviction."
  exit_code=155
fi
echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
if [ $exit_code = 155 ]; then
  echo "Spot eviction detected - retrying with on-demand."
fi
