#!/usr/bin/env bash
set -u
exit_code=254
ttl=$1
scripts/run_on_tester "
  set -eu;
  sudo shutdown -P $ttl;
  function clone {
    if ! [ -d ~/run-$RUN_ID ]; then
      mkdir -p ~/run-$RUN_ID;
      cd ~/run-$RUN_ID;
      git init >/dev/null 2>&1;
      git remote add origin https://github.com/aztecprotocol/aztec-packages >/dev/null 2>&1;
      git fetch --depth 1 origin $GIT_COMMIT >/dev/null 2>&1;
      git checkout FETCH_HEAD >/dev/null 2>&1;
    fi;
  }
  export RUN_ID GIT_COMMIT
  export -f clone

  # update fs limits for k8s
  sudo sysctl fs.inotify.max_user_watches=65536
  sudo sysctl fs.inotify.max_user_instances=65536
  ulimit -n 32768

  flock /var/lock/clone.lock bash -c clone
  cd ~/run-$RUN_ID
  # reuse script from ensure-builder, but don't set up chron
  flock /var/lock/install.lock .github/ensure-builder/install $DOCKERHUB_PASSWORD
  ci3/aws_handle_evict 'set -eu; $INPUT'
"
exit_code=$?
if [ $exit_code = 255 ]; then
  echo "Treating ssh termination as spot eviction."
  exit_code=155
fi
echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
if [ $exit_code = 155 ]; then
  echo "Spot eviction detected - retrying with on-demand."
fi