{
 "title": "P2P bootnodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(discv5_kad_table_size,network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability by Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Running Bootnodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(network)(discv5_kad_table_size{network!=\"\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage{network=\"$network\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (region)(process_cpu_utilization{network=\"$network\", process_cpu_state!=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KAD table size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discv5_kad_table_size{network=\"$network\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Event loop utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_utilization{network=\"$network\"}",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}