{
 "title": "Cloud Prover Dash",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "System Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(proof_generation_total[5m])",
     "legendFormat": "Proof Generation /s"
    },
    { "expr": "active_proof_generations", "legendFormat": "Active Proof Generations" },
    {
     "expr": "rate(proof_generation_total{status=\"success\"}[5m]) / rate(proof_generation_total[5m]) * 100",
     "legendFormat": "Proof success rate"
    },
    {
     "expr": "histogram_quantile(0.50, rate(proof_generation_duration_seconds_bucket[5m]))",
     "legendFormat": "Average proof generation time"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Prove Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route=\"/prove\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Proof Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_proof_generations", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Failed Http Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{status_code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed http requests - time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_total{status_code!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Average witness generation time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(witness_generation_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average total request time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{route=\"/prove\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Proving Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(proof_generation_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}