{
 "title": "Fisherman",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Service namespace",
    "query": {
     "query": "label_values(target_info,k8s_namespace_name)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(aztec_archiver_l1_block_height,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aztec version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{k8s_namespace_name=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "description": "Count of services running in the selected namespace",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (exported_job) (target_info{k8s_namespace_name=~\"$namespace\", service_name=\"\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\",aztec_status=\"\"}, \"aztec_status\", \"Pending chain\", \"aztec_status\", \"^$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\",aztec_status=\"proven\"}, \"aztec_status\", \"Proven chain\", \"aztec_status\", \"^proven$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_l1_block_height{k8s_namespace_name=\"$namespace\"}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "L1"
    },
    {
     "expr": "max(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\", aztec_status=\"\"}) - max(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\", aztec_status=\"proven\"})",
     "legendFormat": "Pending chain depth"
    },
    {
     "expr": "max(aztec_archiver_prune_count{k8s_namespace_name=\"$namespace\"}) or vector(0)",
     "legendFormat": "Total re-orgs"
    }
   ]
  },
  { "title": "P2P Stats (Node only)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aztec_peer_manager_peer_count_peers{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Mesh Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(gossipsub_mesh_peer_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}, \"topic\", \"$1\", \"topicStr\", \".*/([^/]+)/.*\")",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub Peer Churn/Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(gossipsub_peer_churn_events_bad_score_total{service_namespace=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval])) * 60",
     "legendFormat": "bad score"
    },
    {
     "expr": "sum by(service_name) (rate(gossipsub_peer_churn_events_disconnected_total{service_namespace=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval]) * 60)",
     "legendFormat": "disconnections"
    }
   ]
  },
  {
   "title": "P2P Msgs/Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval])",
     "legendFormat": "accepted - {{topic}}"
    },
    {
     "expr": "rate(gossipsub_msg_forward_peers_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval])",
     "legendFormat": "forwarded - {{topic}}"
    },
    {
     "expr": "rate(gossipsub_rejected_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval])",
     "legendFormat": "rejected - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(gossipsub_topic_peer_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}, \"topic\", \"$1\", \"topicStr\", \".*/([^/]+)/.*\")",
     "legendFormat": "{{service_name}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub Peer Score Thresholds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "gossipsub_peers_by_score_threshold_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}",
     "legendFormat": "{{threshold}}"
    }
   ]
  },
  {
   "title": "Gossipsub Total Penalties",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "gossipsub_scoring_penalties_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}",
     "legendFormat": "{{penalty}}"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"}",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"}",
     "legendFormat": "p6"
    },
    {
     "expr": "gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"}",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"}",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"}",
     "legendFormat": "p6"
    },
    {
     "expr": "gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"}",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"}",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"}",
     "legendFormat": "p6"
    },
    {
     "expr": "gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"}",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub I Haves For Unseen Messages (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(gossipsub_ihave_rcv_not_seen_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval]) * 60",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub I Want Sent/Resolved (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "increase(gossipsub_iwant_promise_resolved_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m])",
     "legendFormat": "Resolved"
    }
   ]
  },
  {
   "title": "Blocks Proposed vs Block Height vs Attestations Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", topic=\"block_proposal\"}",
     "legendFormat": "Proposed"
    },
    {
     "expr": "aztec_archiver_block_height{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", aztec_status!=\"proven\"}",
     "legendFormat": "Block Height"
    },
    {
     "expr": "rate(gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", topic=\"block_attestation\"}[$__rate_interval]) * 60",
     "legendFormat": "Attestations Over Prev Minute"
    }
   ]
  },
  { "title": "Resource use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU use",
   "type": "timeseries",
   "description": "Tracks how much CPU the main process is using (this does not account for bb/acvm)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(service_name) (sum without(process_cpu_state) (process_cpu_utilization{service_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "description": "Tracks how much memory the main process is using (this does not account for bb/acvm)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(service_name) (process_memory_usage{service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Used Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (aztec_db_type) (aztec_db_used_size_bytes{k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (avg by (aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_used_size{service_namespace=\"$namespace\"}))",
     "legendFormat": "world-state"
    }
   ]
  },
  {
   "title": "Memory change 24Hrs",
   "type": "stat",
   "description": "Tracks how much memory the main process is using (this does not account for bb/acvm)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(service_name) (delta(process_memory_usage{service_namespace=\"$namespace\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mempool status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aztec_node_receive_tx_count{service_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total received txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"true\", service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total rejected txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"false\", service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx mempool status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(aztec_status) (aztec_mempool_tx_count{service_namespace=\"$namespace\",exported_job=~\".*validator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mined TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_archiver_tx_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "World state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Approx tree size on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (aztec_merkle_tree_name) (avg by (aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_used_size{service_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative tree sizes",
   "type": "piechart",
   "description": "How big trees are relative to each other. \nNOTE: The L1 to L2 message tree has empty leaves added to it for every block!",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "Leaves" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(aztec_merkle_tree_name) (aztec_world_state_tree_size{service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tree size",
   "type": "timeseries",
   "description": "Tracks tree nodes, indexes, metadata. It's normal for tree sizes to fluctuate even if there are no reorgs (trees garbage collect old data)",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Entries" } },
   "targets": [
    {
     "expr": "sum by (aztec_merkle_tree_name) (avg by(aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_num_items{service_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Archiver status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "max by(service_name, aztec_status) (label_replace(aztec_archiver_block_height{service_namespace=\"$namespace\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks synched from rollup",
   "type": "timeseries",
   "description": "Components synch at different rates, can restart for upgrades (resetting their graph), see multiple reorgs, etc",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(service_name) (aztec_archiver_l1_blocks_synced{service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archiver Sync Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aztec_archiver_sync_duration_milliseconds_bucket{k8s_namespace_name=~\"$namespace\"}[$__rate_interval])) by (le, service_name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}