{
 "title": "Network TPS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Service namespace",
    "query": {
     "query": "label_values(target_info,k8s_namespace_name)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(aztec_archiver_l1_block_height,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GossipSub bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(service_name) (rate(gossipsub_rpc_recv_bytes_total{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "recv-{{service_name}}"
    },
    {
     "expr": "-avg by(service_name) (rate(gossipsub_rpc_sent_bytes_total{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "sent-{{service_name}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aztec version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{k8s_namespace_name=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "description": "Count of services running in the selected namespace",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (exported_job) (target_info{k8s_namespace_name=~\"$namespace\", service_name=\"\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\",aztec_status=\"\"}, \"aztec_status\", \"Pending chain\", \"aztec_status\", \"^$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\",aztec_status=\"proven\"}, \"aztec_status\", \"Proven chain\", \"aztec_status\", \"^proven$\"))",
     "legendFormat": "{{aztec_status}}"
    },
    {
     "expr": "max by (aztec_status) (label_replace(aztec_archiver_l1_block_height{k8s_namespace_name=\"$namespace\"}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "L1"
    },
    {
     "expr": "max(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\", aztec_status=\"\"}) - max(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\", aztec_status=\"proven\"})",
     "legendFormat": "Pending chain depth"
    },
    {
     "expr": "max(aztec_archiver_prune_count{k8s_namespace_name=\"$namespace\"}) or vector(0)",
     "legendFormat": "Total re-orgs"
    }
   ]
  },
  {
   "title": "CPU use",
   "type": "timeseries",
   "description": "Tracks how much CPU the main process is using (this does not account for bb/acvm)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(service_name) (sum without(process_cpu_state) (process_cpu_utilization{service_namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "description": "Tracks how much memory the main process is using (this does not account for bb/acvm)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(service_name) (process_memory_usage{service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mined TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_archiver_tx_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(service_name, aztec_status) (label_replace(aztec_archiver_block_height{service_namespace=\"$namespace\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Stats (selected service only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aztec_peer_manager_peer_count_peers{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Mesh Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(gossipsub_mesh_peer_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}, \"topic\", \"$1\", \"topicStr\", \".*/([^/]+)/.*\")",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub Peer Churn/Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(gossipsub_peer_churn_events_bad_score_total{service_namespace=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "bad score"
    },
    {
     "expr": "sum by(service_name) (increase(gossipsub_peer_churn_events_disconnected_total{service_namespace=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "disconnections"
    }
   ]
  },
  {
   "title": "P2P Msgs/Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "accepted - {{topic}}"
    },
    {
     "expr": "avg by (service_name) (rate(gossipsub_msg_forward_peers_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "forwarded - {{topic}}"
    },
    {
     "expr": "avg by (service_name) (rate(gossipsub_rejected_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "rejected - {{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub Peer Score Thresholds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "gossipsub_peers_by_score_threshold_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", }",
     "legendFormat": "{{threshold}} - {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Gossipsub Total Penalties",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (service_name, penalty) (gossipsub_scoring_penalties_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "{{penalty}}"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "min by (service_name, topic, p) (gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"})",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "min by (service_name, topic) (gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"})",
     "legendFormat": "p5"
    },
    {
     "expr": "min by (service_name, topic) (gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"})",
     "legendFormat": "p6"
    },
    {
     "expr": "gossipsub_score_weights_min{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"}",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 44 },
   "targets": [
    {
     "expr": "max by (service_name, topic, p) (gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"})",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "max by (service_name, topic) (gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"})",
     "legendFormat": "p5"
    },
    {
     "expr": "max by (service_name, topic) (gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"})",
     "legendFormat": "p6"
    },
    {
     "expr": "gossipsub_score_weights_max{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"}",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub P Scores (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 44 },
   "targets": [
    {
     "expr": "avg by(service_name, topic, p) (gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p!=\"p5\", p!=\"p6\", p!=\"p7\"})",
     "legendFormat": "{{topic}} - {{p}}"
    },
    {
     "expr": "avg by(service_name, topic) (gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p5\"})",
     "legendFormat": "p5"
    },
    {
     "expr": "avg by (service_name, topic) (gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p6\"})",
     "legendFormat": "p6"
    },
    {
     "expr": "avg by(service_name, topic) (gossipsub_score_weights_avg{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", p=\"p7\"})",
     "legendFormat": "p7"
    }
   ]
  },
  {
   "title": "Gossipsub I Haves Received / Minute (Nodes receiving IHAVE msgs from other nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (service_name) (increase(gossipsub_ihave_rcv_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub I Haves For Unseen Messages / Minute (Nodes receiving IHAVE messages and they DO NOT have the related msg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(gossipsub_ihave_rcv_not_seen_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub I Want Received vs Don't Have / Minute (Nodes receiving IWANT msgs that we can't fulfil)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(gossipsub_iwant_rcv_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "Received - {{topic}}"
    },
    {
     "expr": "sum by(service_name) (increase(gossipsub_iwant_rcv_dont_have_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "Don't have"
    }
   ]
  },
  {
   "title": "Gossipsub I Want Sent/Resolved / Minute (Nodes sending IWANT msgs and their resolution)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum by(service_name) (increase(gossipsub_iwant_promise_resolved_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "Resolved"
    }
   ]
  },
  {
   "title": "Gossipsub Message Retrieval Efficiency / Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  sum(increase(gossipsub_ihave_rcv_not_seen_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  / \r\n  sum(increase(gossipsub_ihave_rcv_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n) * 100\r\nand\r\nsum(increase(gossipsub_ihave_rcv_msgids_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m])) > 0",
     "legendFormat": "IHAVE Unseen"
    },
    {
     "expr": "(\r\n  sum(increase(gossipsub_iwant_promise_resolved_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  / \r\n  sum(increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n) * 100\r\nand\r\nsum(increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m])) > 0",
     "legendFormat": "IWANT Success Rate"
    },
    {
     "expr": "(\r\n  (\r\n    sum(increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    - \r\n    sum(increase(gossipsub_iwant_promise_resolved_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  )\r\n  / \r\n  sum(increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n) * 100\r\nand\r\nsum(increase(gossipsub_iwant_promise_sent_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m])) > 0",
     "legendFormat": "IWANT Failure Rate"
    }
   ]
  },
  {
   "title": "Gossipsub Accepted Message Delta (Difference in message acceptance rate across nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "max by (topic) (gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}) - min by(topic) (gossipsub_accepted_messages_total{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip Tx Received Count (Count of txs inserted into pool from gossip)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "aztec_p2p_gossip_tx_received_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Successfully Retrieved Transactions (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum by(aztec_tx_collection_method) (increase(aztec_tx_collector_tx_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Failed Transaction Retrievals (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "sum by(service_name) (increase(aztec_tx_collector_missing_txs_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Transaction Retrieval Result (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "(\r\n  sum by(service_name) (increase(aztec_tx_collector_txs_from_mempool_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  /\r\n  (\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_mempool_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_p2p_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_missing_txs_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  )\r\n) * 100",
     "legendFormat": "Mempool %"
    },
    {
     "expr": "(\r\n  sum by(service_name) (increase(aztec_tx_collector_txs_from_p2p_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  /\r\n  (\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_mempool_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_p2p_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_missing_txs_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  )\r\n) * 100",
     "legendFormat": "P2P %"
    },
    {
     "expr": "(\r\n  sum by(service_name) (increase(aztec_tx_collector_missing_txs_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  /\r\n  (\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_mempool_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_txs_from_p2p_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n    +\r\n    sum by(service_name) (increase(aztec_tx_collector_missing_txs_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[1m]))\r\n  )\r\n) * 100",
     "legendFormat": "Missing %"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "max(aztec_sequencer_slot_total_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}) - max(aztec_sequencer_slot_total_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "Missed slots"
    }
   ]
  },
  {
   "title": "Attestations Collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "max (aztec_sequencer_attestations_collected_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "Collected"
    }
   ]
  },
  {
   "title": "Attestation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum by (aztec_error_type) (increase(aztec_validator_attestation_failed_node_issue_count{k8s_namespace_name=\"$namespace\", aztec_is_committee_member=\"true\"}[1m]))",
     "legendFormat": "{{aztec_error_type}}"
    }
   ]
  },
  {
   "title": "Mempool Size (Pending + Mined)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (aztec_mempool_tx_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\", aztec_status=~\"pending|mined\"})",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Mempool status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aztec_node_receive_tx_count{service_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total received txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"true\", service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total rejected txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"false\", service_namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx mempool status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(aztec_status) (aztec_mempool_tx_count{service_namespace=\"$namespace\",exported_job=~\".*validator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "Min P90 message latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(increase(aztec_p2p_gossip_message_latency_milliseconds_bucket{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[5m])) by (le, aztec_gossip_topic_name))",
     "legendFormat": "{{aztec_gossip_topic_name}}"
    }
   ]
  },
  {
   "title": "P99 message latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(aztec_p2p_gossip_message_latency_milliseconds_bucket{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"}[5m])) by (le, aztec_gossip_topic_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max P90 aggregated message latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 193 },
   "targets": [
    {
     "expr": "max by (aztec_gossip_topic_name) (aztec_p2p_gossip_agg_message_latency_p90_milliseconds{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "targets": [
    {
     "expr": "max by(aztec_p2p_peer_score_state) (aztec_p2p_peer_state_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Mesh Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "targets": [
    {
     "expr": "max by(k8s_pod_name) (gossipsub_mesh_peer_count{k8s_namespace_name=\"$namespace\", service_name=\"$service_name\"})",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  }
 ]
}