// Emits `<family>_execution_trace_generated.hpp`: a `<Family>TraceBlock` alias and a
// `<Family>TraceBlockData` struct with members `[traceExtraBlocks..., relation-discovered
// blocks...]` in `flavor.relations` order. Each relation block is constructed with its GateKinds.

import * as fs from "node:fs";
import * as path from "node:path";

import { formatInPlace } from "./format.js";
import type { Flavor } from "./types.js";

// Flavor-entity name → C++ GateKind tag. Shared with flavor codegen (`GATE_KINDS` array).
export const GATE_SELECTOR_TO_GATE_KIND: ReadonlyMap<string, string> = new Map([
    ["q_busread", "BusRead"],
    ["q_lookup", "Lookup"],
    ["q_arith", "Arith"],
    ["q_delta_range", "DeltaRange"],
    ["q_elliptic", "Elliptic"],
    ["q_memory", "Memory"],
    ["q_nnf", "Nnf"],
    ["q_poseidon2_external", "Poseidon2Ext"],
    ["q_poseidon2_internal", "Poseidon2Int"],
    ["q_poseidon2_external_initial", "Poseidon2ExtInitial"],
    ["q_poseidon2_quad_internal", "Poseidon2QuadInt"],
    ["q_poseidon2_quad_internal_terminal", "Poseidon2QuadIntTerminal"],
    ["q_poseidon2_transition_entry", "Poseidon2TransitionEntry"],
]);

// Snake_case → TitleCase ("ultra_keccak" → "UltraKeccak").
function titleCase(family: string): string {
    return family
        .split("_")
        .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
        .join("");
}

function emitTraceHeader(flavor: Flavor): string {
    const Family = titleCase(flavor.family);
    const BlockType = `${Family}TraceBlock`;
    const StructName = `${Family}TraceBlockData`;

    // Discover blocks from relations. `gateBlockName` → ordered list of GateKinds.
    const blockKinds = new Map<string, string[]>();
    const blockOrder: string[] = [];
    for (const r of flavor.relations) {
        if (!r.gateBlockName) continue;
        if (!blockKinds.has(r.gateBlockName)) {
            blockKinds.set(r.gateBlockName, []);
            blockOrder.push(r.gateBlockName);
        }
        const kinds = blockKinds.get(r.gateBlockName)!;
        for (const sel of r.subsets["gate_selectors"] ?? []) {
            const kind = GATE_SELECTOR_TO_GATE_KIND.get(sel);
            if (!kind) {
                throw new Error(
                    `flavor-codegen: gate selector '${sel}' (relation '${r.id}') has no GateKind mapping`
                );
            }
            if (!kinds.includes(kind)) {
                kinds.push(kind);
            }
        }
    }

    const allBlocks: { name: string; kinds: string[] }[] = [
        ...flavor.traceExtraBlocks.map((name) => ({ name, kinds: [] as string[] })),
        ...blockOrder.map((name) => ({ name, kinds: blockKinds.get(name)! })),
    ];

    const lines: string[] = [];
    lines.push("// AUTOGENERATED FILE — do not edit. Regenerate via:");
    lines.push("//   node barretenberg/cpp/scripts/flavor-codegen/dist/main.js");
    lines.push("//");
    lines.push(`// Source: barretenberg/cpp/scripts/flavor-codegen/src/flavors/${flavor.family}.ts`);
    lines.push("#pragma once");
    lines.push("");
    lines.push("#include <array>");
    lines.push("#include <cstddef>");
    lines.push("#include <string_view>");
    lines.push("#include <vector>");
    lines.push("");
    lines.push("#include \"barretenberg/common/log.hpp\"");
    lines.push("#include \"barretenberg/common/ref_array.hpp\"");
    lines.push("#include \"barretenberg/ecc/curves/bn254/fr.hpp\"");
    lines.push("#include \"barretenberg/honk/execution_trace/execution_trace_block.hpp\"");
    lines.push("");
    lines.push("namespace bb {");
    lines.push("");
    lines.push(`using ${BlockType} = ExecutionTraceBlock<fr, 4>;`);
    lines.push("");
    lines.push(`struct ${StructName} {`);
    lines.push(`    using BlockBase = ${BlockType};`);
    lines.push("");
    for (const { name, kinds } of allBlocks) {
        if (kinds.length === 0) {
            lines.push(`    ${BlockType} ${name}{};`);
        } else {
            const list = kinds.map((k) => `GateKind::${k}`).join(", ");
            lines.push(`    ${BlockType} ${name}{ ${list} };`);
        }
    }
    lines.push("");
    lines.push(`    static constexpr size_t NUM_BLOCKS = ${allBlocks.length};`);
    lines.push("");
    lines.push("    std::vector<std::string_view> get_labels() const");
    lines.push("    {");
    lines.push("        return {");
    for (const { name } of allBlocks) {
        lines.push(`            "${name}",`);
    }
    lines.push("        };");
    lines.push("    }");
    lines.push("");
    for (const constness of ["", " const"]) {
        const ptrType = constness ? `const ${BlockType}*` : `${BlockType}*`;
        lines.push(`    auto get()${constness}`);
        lines.push("    {");
        lines.push(`        return RefArray(std::array<${ptrType}, NUM_BLOCKS>{`);
        for (const { name } of allBlocks) {
            lines.push(`            &${name},`);
        }
        lines.push("        });");
        lines.push("    }");
        lines.push("");
    }
    lines.push("    void summarize() const");
    lines.push("    {");
    lines.push("        info(\"Gate blocks summary:\");");
    for (const { name } of allBlocks) {
        lines.push(`        info("${name.padEnd(24)}: ", this->${name}.size());`);
    }
    lines.push("    }");
    lines.push("");
    lines.push(`    bool operator==(const ${StructName}& other) const = default;`);
    lines.push("};");
    lines.push("");
    lines.push("} // namespace bb");
    lines.push("");

    return lines.join("\n");
}

// Write the execution-trace header to disk and return its absolute path.
export function generateTrace(flavor: Flavor, repoRoot: string): string {
    const header = emitTraceHeader(flavor);
    const outDir = path.join(
        repoRoot, "barretenberg", "cpp", "src", "barretenberg", "honk", "execution_trace", "generated"
    );
    const outFile = path.join(outDir, `${flavor.family}_execution_trace_generated.hpp`);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(outFile, header, "utf8");
    formatInPlace(outFile);
    return outFile;
}
