{{- if (get (get .Values "validatorFailure") "enabled") }}
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.targetNamespace }}-validator-failure
  namespace: {{ default .Values.global.chaosMeshNamespace .Values.global.chaosResourceNamespace }}
  labels:
    {{- include "aztec-chaos-scenarios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  action: pod-failure
  {{- if .Values.validatorFailure.percent }}
  mode: fixed-percent
  value: {{ .Values.validatorFailure.percent | quote }}
  {{- else }}
  mode: all
  {{- end }}
  selector:
    namespaces:
      - {{ .Values.global.targetNamespace }}
    labelSelectors:
      app.kubernetes.io/name: validator
  duration: {{ .Values.validatorFailure.duration }}
{{- end }}


