export enum ProvingRequestType {
  PUBLIC_VM,
  PUBLIC_TUBE,
  PRIVATE_BASE_ROLLUP,
  PUBLIC_BASE_ROLLUP,
  MERGE_ROLLUP,
  EMPTY_BLOCK_ROOT_ROLLUP,
  PADDING_BLOCK_ROOT_ROLLUP,
  BLOCK_ROOT_ROLLUP,
  SINGLE_TX_BLOCK_ROOT_ROLLUP,
  BLOCK_MERGE_ROLLUP,
  ROOT_ROLLUP,

  BASE_PARITY,
  ROOT_PARITY,
}
