export enum ProvingRequestType {
  PUBLIC_VM,
  PUBLIC_CHONK_VERIFIER,

  PRIVATE_TX_BASE_ROLLUP,
  PUBLIC_TX_BASE_ROLLUP,
  TX_MERGE_ROLLUP,
  BLOCK_ROOT_FIRST_ROLLUP,
  BLOCK_ROOT_SINGLE_TX_FIRST_ROLLUP,
  BLOCK_ROOT_EMPTY_TX_FIRST_ROLLUP,
  BLOCK_ROOT_ROLLUP,
  BLOCK_ROOT_SINGLE_TX_ROLLUP,
  BLOCK_MERGE_ROLLUP,
  CHECKPOINT_ROOT_ROLLUP,
  CHECKPOINT_ROOT_SINGLE_BLOCK_ROLLUP,
  CHECKPOINT_PADDING_ROLLUP,
  CHECKPOINT_MERGE_ROLLUP,
  ROOT_ROLLUP,

  PARITY_BASE,
  PARITY_ROOT,

  /** Completion marker for a checkpoint sub-tree proving job. Auto-completed by the broker. */
  CHECKPOINT_SUB_TREE_COMPLETE = 100,
  /** Completion marker for a top-tree proving job. Auto-completed by the broker. */
  TOP_TREE_COMPLETE = 101,
}
