/**
 * corpus_seed_tx - Convert TS ExecutionHints JSON to FuzzerTxData corpus entries
 *
 * Usage: corpus_seed_tx <input.json> <corpus_dir> [--verbose] [--dry-run]
 *
 * This tool takes a JSON file generated by TypeScript that contains:
 * - Contract classes with bytecode
 * - Contract instances
 * - Transaction metadata
 * - Global variables
 * - Protocol contracts
 *
 * It decompiles bytecode fields to FuzzerData and produces FuzzerTxData for the tx.fuzzer corpus.
 */

#include "barretenberg/avm_fuzzer/fuzz_lib/bytecode_decompiler.hpp"
#include "barretenberg/avm_fuzzer/fuzz_lib/fuzzer_data.hpp"
#include "barretenberg/avm_fuzzer/tx.fuzzer.hpp"
#include "barretenberg/crypto/sha256/sha256.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"
#include "barretenberg/vm2/common/aztec_types.hpp"

#include <nlohmann/json.hpp>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using json = nlohmann::json;
using namespace bb::avm2;

namespace {

/**
 * Parse hex string to bytes (with or without 0x prefix)
 */
std::vector<uint8_t> hex_to_bytes(const std::string& hex)
{
    std::string h = hex;
    // Remove 0x prefix if present
    if (h.size() >= 2 && h[0] == '0' && (h[1] == 'x' || h[1] == 'X')) {
        h = h.substr(2);
    }

    std::vector<uint8_t> bytes;
    bytes.reserve(h.size() / 2);

    for (size_t i = 0; i + 1 < h.size(); i += 2) {
        auto byte = static_cast<uint8_t>(std::stoul(h.substr(i, 2), nullptr, 16));
        bytes.push_back(byte);
    }

    return bytes;
}

/**
 * Convert bytes to hex string (for filename generation)
 */
std::string bytes_to_hex(const std::vector<uint8_t>& bytes)
{
    std::ostringstream ss;
    for (auto byte : bytes) {
        ss << std::hex << std::setfill('0') << std::setw(2) << static_cast<int>(byte);
    }
    return ss.str();
}

/**
 * Parse hex string to field element
 * Handles arbitrary length hex, pads to 32 bytes on the left
 */
FF hex_to_ff(const std::string& hex)
{
    auto bytes = hex_to_bytes(hex);

    // Pad to 32 bytes (big-endian, so pad on the left)
    while (bytes.size() < 32) {
        bytes.insert(bytes.begin(), 0);
    }

    // Truncate if too long (take the rightmost 32 bytes)
    if (bytes.size() > 32) {
        bytes = std::vector<uint8_t>(bytes.end() - 32, bytes.end());
    }

    return FF::serialize_from_buffer(bytes.data());
}

/**
 * Parse hex string to uint128_t
 */
uint128_t hex_to_u128(const std::string& hex)
{
    auto bytes = hex_to_bytes(hex);

    // Pad to 16 bytes (big-endian, so pad on the left)
    while (bytes.size() < 16) {
        bytes.insert(bytes.begin(), 0);
    }

    // Take the rightmost 16 bytes if too long
    if (bytes.size() > 16) {
        bytes = std::vector<uint8_t>(bytes.end() - 16, bytes.end());
    }

    // Convert to uint128_t (big-endian)
    uint128_t result = 0;
    for (size_t i = 0; i < 16; i++) {
        result = (result << 8) | bytes[i];
    }
    return result;
}

/**
 * Parse a GasFees object from JSON
 */
GasFees parse_gas_fees(const json& j)
{
    GasFees fees;
    if (j.contains("feePerDaGas")) {
        fees.fee_per_da_gas = hex_to_u128(j["feePerDaGas"].get<std::string>());
    }
    if (j.contains("feePerL2Gas")) {
        fees.fee_per_l2_gas = hex_to_u128(j["feePerL2Gas"].get<std::string>());
    }
    return fees;
}

/**
 * Parse a Gas object from JSON
 */
Gas parse_gas(const json& j)
{
    Gas gas;
    if (j.contains("l2Gas")) {
        gas.l2_gas = j["l2Gas"].get<uint32_t>();
    }
    if (j.contains("daGas")) {
        gas.da_gas = j["daGas"].get<uint32_t>();
    }
    return gas;
}

/**
 * Parse a GasSettings object from JSON
 */
GasSettings parse_gas_settings(const json& j)
{
    GasSettings settings;
    if (j.contains("gasLimits")) {
        settings.gas_limits = parse_gas(j["gasLimits"]);
    }
    if (j.contains("teardownGasLimits")) {
        settings.teardown_gas_limits = parse_gas(j["teardownGasLimits"]);
    }
    if (j.contains("maxFeesPerGas")) {
        settings.max_fees_per_gas = parse_gas_fees(j["maxFeesPerGas"]);
    }
    if (j.contains("maxPriorityFeesPerGas")) {
        settings.max_priority_fees_per_gas = parse_gas_fees(j["maxPriorityFeesPerGas"]);
    }
    return settings;
}

/**
 * Parse a PublicKeys object from JSON
 */
PublicKeys parse_public_keys(const json& /* j */)
{
    PublicKeys keys;
    // Public keys are typically points, parse if present
    // For now, leave as default (zeros) if not provided
    // TODO: Implement proper point parsing when needed
    return keys;
}

/**
 * Parse a ContractClass from JSON
 */
ContractClass parse_contract_class(const json& j)
{
    ContractClass contract_class;

    if (j.contains("id")) {
        contract_class.id = hex_to_ff(j["id"].get<std::string>());
    }
    if (j.contains("artifactHash")) {
        contract_class.artifact_hash = hex_to_ff(j["artifactHash"].get<std::string>());
    }
    if (j.contains("privateFunctionsRoot")) {
        contract_class.private_functions_root = hex_to_ff(j["privateFunctionsRoot"].get<std::string>());
    }
    if (j.contains("packedBytecode")) {
        contract_class.packed_bytecode = hex_to_bytes(j["packedBytecode"].get<std::string>());
    }

    return contract_class;
}

/**
 * Parse a ContractInstance from JSON
 */
ContractInstance parse_contract_instance(const json& j)
{
    ContractInstance instance;

    if (j.contains("salt")) {
        instance.salt = hex_to_ff(j["salt"].get<std::string>());
    }
    if (j.contains("deployer")) {
        instance.deployer = hex_to_ff(j["deployer"].get<std::string>());
    }
    if (j.contains("currentContractClassId")) {
        instance.current_contract_class_id = hex_to_ff(j["currentContractClassId"].get<std::string>());
    }
    if (j.contains("originalContractClassId")) {
        instance.original_contract_class_id = hex_to_ff(j["originalContractClassId"].get<std::string>());
    }
    if (j.contains("initializationHash")) {
        instance.initialization_hash = hex_to_ff(j["initializationHash"].get<std::string>());
    }
    if (j.contains("publicKeys")) {
        instance.public_keys = parse_public_keys(j["publicKeys"]);
    }

    return instance;
}

/**
 * Parse a GlobalVariables from JSON
 */
GlobalVariables parse_global_variables(const json& j)
{
    GlobalVariables gv;

    if (j.contains("chainId")) {
        gv.chain_id = hex_to_ff(j["chainId"].get<std::string>());
    }
    if (j.contains("version")) {
        gv.version = hex_to_ff(j["version"].get<std::string>());
    }
    if (j.contains("blockNumber")) {
        gv.block_number = j["blockNumber"].get<uint32_t>();
    }
    if (j.contains("slotNumber")) {
        gv.slot_number = hex_to_ff(j["slotNumber"].get<std::string>());
    }
    if (j.contains("timestamp")) {
        gv.timestamp = j["timestamp"].get<uint64_t>();
    }
    if (j.contains("coinbase")) {
        gv.coinbase = hex_to_ff(j["coinbase"].get<std::string>());
    }
    if (j.contains("feeRecipient")) {
        gv.fee_recipient = hex_to_ff(j["feeRecipient"].get<std::string>());
    }
    if (j.contains("gasFees")) {
        gv.gas_fees = parse_gas_fees(j["gasFees"]);
    }

    return gv;
}

/**
 * Parse a PublicCallRequest from JSON
 */
PublicCallRequest parse_public_call_request(const json& j)
{
    PublicCallRequest req;

    if (j.contains("msgSender")) {
        req.msg_sender = hex_to_ff(j["msgSender"].get<std::string>());
    }
    if (j.contains("contractAddress")) {
        req.contract_address = hex_to_ff(j["contractAddress"].get<std::string>());
    }
    if (j.contains("isStaticCall")) {
        req.is_static_call = j["isStaticCall"].get<bool>();
    }
    if (j.contains("calldataHash")) {
        req.calldata_hash = hex_to_ff(j["calldataHash"].get<std::string>());
    }

    return req;
}

/**
 * Parse a PublicCallRequestWithCalldata from JSON
 */
PublicCallRequestWithCalldata parse_public_call_request_with_calldata(const json& j)
{
    PublicCallRequestWithCalldata req_with_cd;

    if (j.contains("request")) {
        req_with_cd.request = parse_public_call_request(j["request"]);
    }
    if (j.contains("calldata")) {
        for (const auto& cd : j["calldata"]) {
            req_with_cd.calldata.push_back(hex_to_ff(cd.get<std::string>()));
        }
    }

    return req_with_cd;
}

/**
 * Parse a Tx object from JSON
 */
Tx parse_tx(const json& j)
{
    Tx tx;

    if (j.contains("hash")) {
        tx.hash = j["hash"].get<std::string>();
    }
    if (j.contains("gasSettings")) {
        tx.gas_settings = parse_gas_settings(j["gasSettings"]);
    }
    if (j.contains("effectiveGasFees")) {
        tx.effective_gas_fees = parse_gas_fees(j["effectiveGasFees"]);
    }
    if (j.contains("setupEnqueuedCalls")) {
        for (const auto& call : j["setupEnqueuedCalls"]) {
            tx.setup_enqueued_calls.push_back(parse_public_call_request_with_calldata(call));
        }
    }
    if (j.contains("appLogicEnqueuedCalls")) {
        for (const auto& call : j["appLogicEnqueuedCalls"]) {
            tx.app_logic_enqueued_calls.push_back(parse_public_call_request_with_calldata(call));
        }
    }
    if (j.contains("teardownEnqueuedCall") && !j["teardownEnqueuedCall"].is_null()) {
        tx.teardown_enqueued_call = parse_public_call_request_with_calldata(j["teardownEnqueuedCall"]);
    }
    if (j.contains("gasUsedByPrivate")) {
        tx.gas_used_by_private = parse_gas(j["gasUsedByPrivate"]);
    }
    if (j.contains("feePayer")) {
        tx.fee_payer = hex_to_ff(j["feePayer"].get<std::string>());
    }

    return tx;
}

/**
 * Parse ProtocolContracts from JSON
 */
ProtocolContracts parse_protocol_contracts(const json& j)
{
    ProtocolContracts pc;

    if (j.contains("derivedAddresses")) {
        size_t idx = 0;
        for (const auto& addr : j["derivedAddresses"]) {
            if (idx < pc.derived_addresses.size()) {
                pc.derived_addresses[idx] = hex_to_ff(addr.get<std::string>());
                idx++;
            }
        }
    }

    return pc;
}

void print_usage()
{
    std::cerr << "Usage: corpus_seed_tx <input.json> <corpus_dir> [--verbose] [--dry-run]\n\n"
              << "  input.json   - JSON file with TS ExecutionHints-like structure\n"
              << "  corpus_dir   - Directory to write corpus entry\n\n"
              << "Options:\n"
              << "  --verbose    - Print decompiled instruction counts per contract\n"
              << "  --dry-run    - Parse and validate without writing\n\n"
              << "Input JSON format:\n"
              << "  {\n"
              << "    \"contractClasses\": [...],\n"
              << "    \"contractInstances\": [...],\n"
              << "    \"contractAddresses\": [...],\n"
              << "    \"globalVariables\": {...},\n"
              << "    \"tx\": {...},\n"
              << "    \"protocolContracts\": {...}\n"
              << "  }\n";
}

} // namespace

int main(int argc, char** argv)
{
    if (argc < 3) {
        print_usage();
        return 1;
    }

    std::string input_path = argv[1];
    std::string corpus_dir = argv[2];
    bool verbose = false;
    bool dry_run = false;

    // Parse optional flags
    for (int i = 3; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--verbose" || arg == "-v") {
            verbose = true;
        } else if (arg == "--dry-run" || arg == "-n") {
            dry_run = true;
        } else {
            std::cerr << "Unknown option: " << arg << "\n";
            print_usage();
            return 1;
        }
    }

    // Read and parse JSON input
    std::ifstream input_file(input_path);
    if (!input_file) {
        std::cerr << "Error: Cannot open " << input_path << "\n";
        return 1;
    }

    json input_json;
    try {
        input_file >> input_json;
    } catch (const json::parse_error& e) {
        std::cerr << "Error: Failed to parse JSON: " << e.what() << "\n";
        return 1;
    }

    // Build FuzzerTxData
    FuzzerTxData tx_data;

    // Parse contract classes and decompile bytecode
    if (input_json.contains("contractClasses")) {
        for (const auto& cc_json : input_json["contractClasses"]) {
            try {
                ContractClass cc = parse_contract_class(cc_json);
                tx_data.contract_classes.push_back(cc);

                // Decompile bytecode to FuzzerData
                if (!cc.packed_bytecode.empty()) {
                    FuzzerData fuzzer_data = bb::avm_fuzzer::decompile_bytecode(cc.packed_bytecode, {});
                    tx_data.input_programs.push_back(fuzzer_data);

                    if (verbose) {
                        size_t instr_count = 0;
                        for (const auto& block : fuzzer_data.instruction_blocks) {
                            instr_count += block.size();
                        }
                        std::cout << "Contract class " << cc.id << ": " << instr_count << " instructions from "
                                  << cc.packed_bytecode.size() << " bytes\n";
                    }
                }
            } catch (const std::exception& e) {
                std::cerr << "Error parsing contract class: " << e.what() << "\n";
                return 1;
            }
        }
    }

    // Parse contract instances
    if (input_json.contains("contractInstances")) {
        for (const auto& ci_json : input_json["contractInstances"]) {
            try {
                tx_data.contract_instances.push_back(parse_contract_instance(ci_json));
            } catch (const std::exception& e) {
                std::cerr << "Error parsing contract instance: " << e.what() << "\n";
                return 1;
            }
        }
    }

    // Parse contract addresses
    if (input_json.contains("contractAddresses")) {
        for (const auto& addr : input_json["contractAddresses"]) {
            tx_data.contract_addresses.push_back(hex_to_ff(addr.get<std::string>()));
        }
    }

    // Parse global variables
    if (input_json.contains("globalVariables")) {
        try {
            tx_data.global_variables = parse_global_variables(input_json["globalVariables"]);
        } catch (const std::exception& e) {
            std::cerr << "Error parsing global variables: " << e.what() << "\n";
            return 1;
        }
    }

    // Parse tx
    if (input_json.contains("tx")) {
        try {
            tx_data.tx = parse_tx(input_json["tx"]);
        } catch (const std::exception& e) {
            std::cerr << "Error parsing tx: " << e.what() << "\n";
            return 1;
        }
    }

    // Parse protocol contracts
    if (input_json.contains("protocolContracts")) {
        try {
            tx_data.protocol_contracts = parse_protocol_contracts(input_json["protocolContracts"]);
        } catch (const std::exception& e) {
            std::cerr << "Error parsing protocol contracts: " << e.what() << "\n";
            return 1;
        }
    }

    if (verbose) {
        std::cout << "\nFuzzerTxData summary:\n"
                  << "  input_programs: " << tx_data.input_programs.size() << "\n"
                  << "  contract_classes: " << tx_data.contract_classes.size() << "\n"
                  << "  contract_instances: " << tx_data.contract_instances.size() << "\n"
                  << "  contract_addresses: " << tx_data.contract_addresses.size() << "\n";
    }

    if (dry_run) {
        std::cout << "Dry run - not writing output\n";
        return 0;
    }

    // Serialize to msgpack
    msgpack::sbuffer buffer;
    msgpack::pack(buffer, tx_data);

    // Ensure corpus directory exists
    std::filesystem::create_directories(corpus_dir);

    // Generate filename from content hash (first 16 bytes of SHA256)
    auto hash = bb::crypto::sha256(std::vector<uint8_t>(buffer.data(), buffer.data() + buffer.size()));
    std::string filename = bytes_to_hex(std::vector<uint8_t>(hash.begin(), hash.begin() + 16));
    std::string output_path = corpus_dir + "/" + filename;

    // Write output
    std::ofstream output_file(output_path, std::ios::binary);
    if (!output_file) {
        std::cerr << "Error: Cannot write to " << output_path << "\n";
        return 1;
    }

    output_file.write(buffer.data(), static_cast<std::streamsize>(buffer.size()));
    output_file.close();

    std::cout << "Written: " << output_path << "\n";
    return 0;
}
