{
 "title": "Aztec Testnet Block Height Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Pending & Proven Block Number",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rollup_pending_block_number) by (network)",
     "legendFormat": "Pending block height - {{network}}"
    },
    {
     "expr": "max(rollup_proven_block_number) by (network)",
     "legendFormat": "Proven block height - {{network}}"
    }
   ]
  },
  {
   "title": "Pending Block Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rollup_pending_block_number", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Proven Block Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "rollup_proven_block_number", "legendFormat": "{{network}}" }
   ]
  }
 ]
}