/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function getPublicWitness(a: number, b: number, c: number, d: number): void;
export function getPublicParametersWitness(a: number, b: number, c: number, d: number): void;
export function getReturnWitness(a: number, b: number, c: number, d: number): void;
export function executeCircuitWithBlackBoxSolver(a: number, b: number, c: number, d: number, e: number): number;
export function executeCircuit(a: number, b: number, c: number, d: number): number;
export function createBlackBoxSolver(): number;
export function __wbg_wasmblackboxfunctionsolver_free(a: number): void;
export function initLogLevel(a: number): void;
export function ecdsa_secp256r1_verify(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function ecdsa_secp256k1_verify(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function keccak256(a: number, b: number, c: number): void;
export function blake2s256(a: number, b: number, c: number): void;
export function sha256(a: number, b: number, c: number): void;
export function xor(a: number, b: number): number;
export function and(a: number, b: number): number;
export function decompressWitness(a: number, b: number, c: number): void;
export function compressWitness(a: number, b: number): void;
export function buildInfo(): number;
export function __wbg_trap_free(a: number): void;
export function trap___wbgd_downcast_token(): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3d2354449e918783(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__ha676a05262f43687(a: number, b: number, c: number, d: number): void;
