[package]
name = "app_subscription_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
token = { path = "../token_contract" }
public_checks = { path = "../../protocol/public_checks_contract" }
