apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-metrics-collector.fullname" . }}
  labels:
    {{- include "otel-metrics-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "otel-metrics-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-metrics-collector.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: otel-collector
          image: {{ .Values.image | quote }}
          args:
            - --config=/conf/collector.yaml
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "otel-metrics-collector.fullname" . }}
                  key: endpoint
          ports:
            - name: health
              containerPort: 13133
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "otel-metrics-collector.configName" . }}
