apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "otel-metrics-collector.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name | quote }}
    kind: {{ .Values.externalSecret.secretStore.kind | quote }}
  target:
    name: {{ include "otel-metrics-collector.fullname" . }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        endpoint: {{ `{{ .url | trimSuffix "/v1/metrics" | trimSuffix "/" }}` | quote }}
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.externalSecret.gcpSecretName | quote }}
