apiVersion: 1
contactPoints:
  - orgId: 1
    name: "Slack #network-alerts channel by namespace"
    receivers:
      - uid: deexubp9hzpc1b
        type: slack
        settings:
          url: $SLACK_WEBHOOK_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-next-scenario by namespace"
    receivers:
      - uid: alertsnextscenariobynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_NEXT_SCENARIO_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-next-net by namespace"
    receivers:
      - uid: alertsnextnetbynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_NEXT_NET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-staging-public by namespace"
    receivers:
      - uid: alertsstagingpublicbynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_STAGING_PUBLIC_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-staging-public by network"
    receivers:
      - uid: alertsstagingpublicbynetwork
        type: slack
        settings:
          url: $SLACK_WEBHOOK_STAGING_PUBLIC_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_network" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-testnet by namespace"
    receivers:
      - uid: alertstestnetbynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_TESTNET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-mainnet by namespace"
    receivers:
      - uid: alertsmainnetbynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_MAINNET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-testnet by network"
    receivers:
      - uid: alertstestnetbynetwork
        type: slack
        settings:
          url: $SLACK_WEBHOOK_TESTNET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_network" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-mainnet by network"
    receivers:
      - uid: alertsmainnetbynetwork
        type: slack
        settings:
          url: $SLACK_WEBHOOK_MAINNET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_network" . }}
        disableResolveMessage: false

  - orgId: 1
    name: "Slack #alerts-devnet by namespace"
    receivers:
      - uid: alertsdevnetbynamespace
        type: slack
        settings:
          url: $SLACK_WEBHOOK_DEVNET_URL
          mentionUsers: $SLACK_ALERT_MENTION_USER_IDS
          text: |-
            {{ template "aztec.slack.by_namespace" . }}
        disableResolveMessage: false
