apiVersion: 1
templates:
  - orgId: 1
    name: aztec-slack-notifications
    template: |
      {{ define "aztec.slack.by_namespace" -}}
      {{ if gt (len .Alerts) 0 }}
      *Alerts:*
      {{ range .Alerts }}
      - {{ with (index .Labels "k8s_namespace_name") }}{{ . }}{{ else }}unknown-namespace{{ end }}: {{ with (index .Annotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}
      {{ else }}
      *Alerts:*
      - {{ with (index .CommonAnnotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}

      *Grafana overview:*
      {{ .ExternalURL }}d/aztec-network/network-overview?orgId=1&refresh=30s&var-data_source=default&var-namespace={{ if gt (len .Alerts) 0 }}{{ with (index (index .Alerts 0).Labels "k8s_namespace_name") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ else }}{{ with (index .CommonLabels "k8s_namespace_name") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ end }}

      *GKE workloads:*
      https://console.cloud.google.com/kubernetes/workload/overview?project={{ if gt (len .Alerts) 0 }}{{ with (index (index .Alerts 0).Labels "gcp_project") }}{{ . }}{{ else }}unknown{{ end }}{{ else }}{{ with (index .CommonLabels "gcp_project") }}{{ . }}{{ else }}unknown{{ end }}{{ end }}&supportedpurview=project&pageState=%28%22savedViews%22%3A%28%22n%22%3A%5B%22{{ if gt (len .Alerts) 0 }}{{ with (index (index .Alerts 0).Labels "k8s_namespace_name") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ else }}{{ with (index .CommonLabels "k8s_namespace_name") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ end }}%22%5D%29%29
      {{- end }}

      {{ define "aztec.slack.by_network" -}}
      {{ if gt (len .Alerts) 0 }}
      *Alerts:*
      {{ range .Alerts }}
      - {{ with (index .Labels "network") }}{{ . }}{{ else }}unknown-network{{ end }}: {{ with (index .Annotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}
      {{ else }}
      *Alerts:*
      - {{ with (index .CommonAnnotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}

      *Grafana overview:*
      {{ .ExternalURL }}d/bexge5lz3e51cd/p2p-bootnodes?orgId=1&var-network={{ if gt (len .Alerts) 0 }}{{ with (index (index .Alerts 0).Labels "network") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ else }}{{ with (index .CommonLabels "network") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ end }}
      {{- end }}


      {{ define "aztec.slack.by_eth_chain" -}}
      {{ if gt (len .Alerts) 0 }}
      *Alerts:*
      {{ range .Alerts }}
      - {{ with (index .Labels "eth_chain") }}{{ . }}{{ else }}unknown-chain{{ end }}: {{ with (index .Annotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}
      {{ else }}
      *Alerts:*
      - {{ with (index .CommonAnnotations "summary") }}{{ . }}{{ else }}(no summary){{ end }}
      {{ end }}

      *Grafana L1 nodes:*
      {{ .ExternalURL }}d/l1-ethereum-nodes/ethereum-l1-nodes?orgId=1&refresh=30s&var-data_source=default&var-eth_chain={{ if gt (len .Alerts) 0 }}{{ with (index (index .Alerts 0).Labels "eth_chain") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ else }}{{ with (index .CommonLabels "eth_chain") }}{{ urlquery . }}{{ else }}unknown{{ end }}{{ end }}
      {{- end }}
