#!/usr/bin/env bash
# Generates per-network TypeScript configs from .env files.
#
# Source: spartan/environments/{common,devnet,testnet,mainnet}.env
# Output: yarn-project/cli/src/config/generated/networks.ts
set -euo pipefail

cd $(git rev-parse --show-toplevel)
source spartan/scripts/codegen_helper.sh

# Protocol + operational keys included in per-network presets.
# L1 contract params + slasher + operational defaults.
NETWORK_KEYS="
  ETHEREUM_SLOT_DURATION
  AZTEC_SLOT_DURATION
  AZTEC_EPOCH_DURATION
  AZTEC_TARGET_COMMITTEE_SIZE
  AZTEC_LAG_IN_EPOCHS_FOR_VALIDATOR_SET
  AZTEC_LAG_IN_EPOCHS_FOR_RANDAO
  AZTEC_ACTIVATION_THRESHOLD
  AZTEC_EJECTION_THRESHOLD
  AZTEC_LOCAL_EJECTION_THRESHOLD
  AZTEC_EXIT_DELAY_SECONDS
  AZTEC_INBOX_LAG
  AZTEC_PROOF_SUBMISSION_EPOCHS
  AZTEC_MANA_TARGET
  AZTEC_PROVING_COST_PER_MANA
  AZTEC_INITIAL_ETH_PER_FEE_ASSET
  AZTEC_SLASHER_ENABLED
  AZTEC_SLASHING_ROUND_SIZE_IN_EPOCHS
  AZTEC_SLASHING_LIFETIME_IN_ROUNDS
  AZTEC_SLASHING_EXECUTION_DELAY_IN_ROUNDS
  AZTEC_SLASHING_OFFSET_IN_ROUNDS
  AZTEC_SLASHING_VETOER
  AZTEC_SLASHING_DISABLE_DURATION
  AZTEC_SLASHING_QUORUM
  AZTEC_SLASH_AMOUNT_SMALL
  AZTEC_SLASH_AMOUNT_MEDIUM
  AZTEC_SLASH_AMOUNT_LARGE
  AZTEC_GOVERNANCE_PROPOSER_ROUND_SIZE
  AZTEC_GOVERNANCE_PROPOSER_QUORUM
  AZTEC_ENTRY_QUEUE_BOOTSTRAP_VALIDATOR_SET_SIZE
  AZTEC_ENTRY_QUEUE_BOOTSTRAP_FLUSH_SIZE
  AZTEC_ENTRY_QUEUE_FLUSH_SIZE_MIN
  AZTEC_ENTRY_QUEUE_FLUSH_SIZE_QUOTIENT
  AZTEC_ENTRY_QUEUE_MAX_FLUSH_SIZE
  SLASH_OFFENSE_EXPIRATION_ROUNDS
  SLASH_MAX_PAYLOAD_SIZE
  SLASH_EXECUTE_ROUNDS_LOOK_BACK
  SLASH_PRUNE_PENALTY
  SLASH_DATA_WITHHOLDING_PENALTY
  SLASH_INACTIVITY_TARGET_PERCENTAGE
  SLASH_INACTIVITY_CONSECUTIVE_EPOCH_THRESHOLD
  SLASH_INACTIVITY_PENALTY
  SLASH_PROPOSE_INVALID_ATTESTATIONS_PENALTY
  SLASH_ATTEST_DESCENDANT_OF_INVALID_PENALTY
  SLASH_DUPLICATE_PROPOSAL_PENALTY
  SLASH_DUPLICATE_ATTESTATION_PENALTY
  SLASH_UNKNOWN_PENALTY
  SLASH_INVALID_BLOCK_PENALTY
  SLASH_GRACE_PERIOD_L2_SLOTS
  P2P_ENABLED
  BOOTSTRAP_NODES
  P2P_MAX_PENDING_TX_COUNT
  P2P_TX_POOL_DELETE_TXS_AFTER_REORG
  SEQ_MIN_TX_PER_BLOCK
  SEQ_MAX_TX_PER_BLOCK
  SEQ_MAX_TX_PER_CHECKPOINT
  SEQ_BUILD_CHECKPOINT_IF_EMPTY
  SEQ_BLOCK_DURATION_MS
  SEQ_L1_PUBLISHING_TIME_ALLOWANCE_IN_SLOT
  DATA_STORE_MAP_SIZE_KB
  ARCHIVER_STORE_MAP_SIZE_KB
  NOTE_HASH_TREE_MAP_SIZE_KB
  NULLIFIER_TREE_MAP_SIZE_KB
  PUBLIC_DATA_TREE_MAP_SIZE_KB
  PUBLIC_OTEL_INCLUDE_METRICS
  PUBLIC_OTEL_OPT_OUT
  PUBLIC_OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
  PUBLIC_OTEL_COLLECT_FROM
  SENTINEL_ENABLED
  L1_CHAIN_ID
  TEST_ACCOUNTS
  SPONSORED_FPC
  TRANSACTIONS_DISABLED
  PROVER_REAL_PROOFS
  PXE_PROVER_ENABLED
  SYNC_SNAPSHOTS_URLS
  SKIP_ARCHIVER_INITIAL_SYNC
  BLOB_ALLOW_EMPTY_SOURCES
  ENABLE_VERSION_CHECK
"

NETWORKS=(devnet testnet mainnet)
ENV_DIR="spartan/environments"

mkdir -p yarn-project/cli/src/config/generated

echo "Generating networks.ts from spartan/environments/*.env..."

{
  cat << 'HEADER'
// Auto-generated from spartan/environments/*.env
// Do not edit manually - run yarn generate to regenerate

HEADER

  for network in "${NETWORKS[@]}"; do
    echo "export const ${network}Config = {"
    extract_keys "$NETWORK_KEYS" "${ENV_DIR}/${network}.env" | format_ts_properties
    echo "} as const;"
    echo ""
  done
} > yarn-project/cli/src/config/generated/networks.ts

echo "Done!"
