externalSecret:
  gcpSecretName: otel-collector-url

scrapeConfigs:
  - job_name: fixture
    targets:
      - fixture.metrics.svc.cluster.local:9090
    labels:
      component: kong
      network: ethereum

resourceAttributes:
  network: ethereum

irm:
  enabled: true
  endpoint: http://fixture-irm-alloy.metrics.svc.cluster.local:4318
  resourceAttributes:
    rpc_namespace: fixture
  metricCatalog:
    schemaVersion: 1
    resourceAttributes:
      - k8s.namespace.name
      - rpc_namespace
    metrics:
      - otelName: up
        allowedAttributes:
          - component
          - network
          - eth_chain
        includeAttributeSets:
          - component: ethereum-node
            eth_chain: mainnet
          - component: kong
      - otelName: kong_http_requests_total
        allowedAttributes:
          - network
          - route
          - code
        aggregation:
          function: sum
          attributes:
            - network
            - route
            - code
