#!/bin/bash
# Use the minio script base. We ensure minio is running and wipe it.
source "$(git rev-parse --show-toplevel)/cache/test_source"

# Tests the various modes of bootstrap test usage.
# We wrap and mock ci3/cache/should_run to detect when a test tries to run.
# We never return true, as we don't actually want to run tests here.
# - First, with CI=0, we assert that should_run returns true to each test.
# - Then, with CI=1, we assert that should_run returns true to each test, as it is a first pass.
# - Next, with CI=1, we assert that should_run returns false to each test, as it is a second pass.
# We mock ci3/cache/should_run for this purpose.

function run_bootstrap() {
  set +e
  project=$1
  cp $ci3/cache/should_run $ci3/cache/should_run.bkup
  cp $1 $ci3/cache/should_run
  rm -f $ci3/cache/should_run.failure

  USE_CACHE=1 $(git rev-parse --show-toplevel)/$project/bootstrap.sh
  exit_code=$?
  if [ "$exit_code" != 0 ]; then
    echo "Bootstrap had a bad exit code $exit_code."
    all_tests_passed=false
  fi
  rm -f "$ci3/cache/should_run.bkup"
  git checkout -- "$ci3/cache/should_run"
  exit $exit_code
}

function check_for_bad_should_run() {
  if [ -s "$ci3/cache/should_run.failure" ]; then
    echo "Failures detected:"
    cat "$ci3/cache/should_run.failure"
    all_tests_passed=false
    return 1
  fi
}

# Initialize the overall test status
all_tests_passed=true

function test_CI_0() {
  CI=0 run_bootstrap $1 $ci3/tests/should_run_first_pass.sh
  check_for_bad_should_run
}

function test_CI_1_first_pass() {
  CI=1 run_bootstrap $1 $ci3/tests/should_run_first_pass.sh
  check_for_bad_should_run
}

function test_CI_1_second_pass() {
  CI=1 run_bootstrap $1 $ci3/tests/should_run_second_pass.sh
  check_for_bad_should_run
}

PROJECTS=(
  noir
  barretenberg
  l1-contracts
  avm-transpiler
  noir-projects
  yarn-project
  boxes
)

# Build projects.
# Death wrapper ensures no child process exist after exit.
for project in "${PROJECTS[@]}"; do
  echo "**************************************"
  echo -e "\033[1mBootstrapping $project...\033[0m"
  echo "**************************************"
  echo
  (cd $project && ./bootstrap.sh)
  echo
  echo
done

# Run the tests
test_CI_0 | sed 's/^/test_CI_0: /' && echo "test_CI_0 success" || echo "test_CI_0 failure"
test_CI_1_first_pass | sed 's/^/test_CI_1 pass 1: /' && echo "test_CI_1_first_pass success" || echo "test_CI_1_first_pass failure"
test_CI_1_second_pass | sed 's/^/test_CI_0 pass 2: /' && echo "test_CI_1_second_pass success" || echo "test_CI_1_second_pass failure"

# Check overall test status
if [ "$all_tests_passed" = true ]; then
  echo "All tests passed successfully."
  exit 0
else
  echo "Some tests failed."
  exit 1
fi
