#pragma once
/**
 * @file ecfft_domain.hpp
 * @brief ECFFT domain hierarchy for FRI-style folding over non-FFT-friendly fields.
 *
 * # Background
 *
 * Standard FRI uses domains {ω^i} in a field with large 2-adic roots of unity and folds
 * by pairing ω^i with ω^{i+n/2} = -ω^i.  BN254's base field Fq (= Grumpkin scalar field)
 * has 2-adicity 1, so standard FRI doesn't work.
 *
 * Instead we use the ECFFT Part II construction (BSCKL22, Appendix B.2): a chain of
 * 2-to-1 rational maps (isogenies between elliptic curves over Fq) that gives us a
 * "binary tree" of domain points:
 *
 *     L_0  →  L_1  →  L_2  →  ...  →  L_k   (|L_i| = n/2^i)
 *          ψ_0     ψ_1               ψ_{k-1}
 *
 * Each ψ_i maps two points in L_i to one point in L_{i+1}.  The pairing invariant is:
 *
 *     ψ_i(L_i[j])  =  ψ_i(L_i[j + m/2])  =  L_{i+1}[j]
 *
 * where m = |L_i|.  This is first-half/second-half pairing, NOT even/odd.
 *
 * # The pointwise FRI fold formula
 *
 * For our isogenies, v(x) = x (the "denominator function" from ECFFT Part II).
 * Given a pair (s_0, s_1) = (L_i[j], L_i[j + m/2]) with degree bound d and
 * verifier challenge z ∈ Fq:
 *
 *     e = d/2 - 1                       ("degree-aware" normalization exponent)
 *     a = f(s_0) · s_0^{-e}             (normalize by v(s_0)^e = s_0^e)
 *     b = f(s_1) · s_1^{-e}
 *     slope = (b - a) / (s_1 - s_0)     (interpolation slope)
 *     fold_z(f)(t) = a + slope · (z - s_0)
 *
 * where t = ψ(s_0) = ψ(s_1) = L_{i+1}[j].
 *
 * This is POINTWISE: each output depends on exactly 2 inputs, enabling O(1)-per-query
 * verification (vs the O(n) global ECFFT Part I decomposition).
 *
 * # Type genericity
 *
 * fold_pair<T> is templated so T can be:
 *   - Fq (scalar FRI over the field)
 *   - GroupElement (group-valued BaseFold: the · operations become scalar-mul on curve points)
 *
 * In the group case, "f(s_0) · s_0^{-e}" means multiplying a Grumpkin curve point by
 * the field element s_0^{-e}.  This costs one elliptic-curve scalar multiplication.
 *
 * # Precomputed data
 *
 * We store:
 *   - domain[j] for each layer  (the actual Fq elements in L_i)
 *   - pair_diff_inv[j] = 1/(s_1 - s_0) for each pair  (avoids a field inversion per query)
 *
 * These are generated by ecfft_precompute.py from the ECFFT domain construction over Fq.
 */

#include "barretenberg/ecc/curves/grumpkin/grumpkin.hpp"
#include <cstddef>
#include <string>
#include <vector>

namespace bb::basefold {

// The ECFFT domain lives in the Grumpkin scalar field = BN254 base field.
//
// IMPORTANT naming pitfall:
//   grumpkin::fq  =  bb::fr   (BN254 scalar field)  ← NOT what we want
//   bb::fq                     (BN254 base field)    ← this is the Grumpkin scalar field
//
// We use bb::fq because our domain points are elements of BN254 Fq, which is the scalar
// field of the Grumpkin curve.  Scalar multiplication on Grumpkin points (GroupElement * Fq)
// requires Fq to be the Grumpkin scalar field, which is bb::fq.  Using grumpkin::fq would
// give bb::fr (wrong field) and fail to compile.
using Fq = bb::fq;

/**
 * @brief One layer of the ECFFT domain hierarchy.
 *
 * Layer i has |L_i| = n/2^i domain points in Fq.
 * The first half and second half are ψ-paired: ψ(domain[j]) = ψ(domain[j + m/2]).
 */
struct EcfftDomainLevel {
    std::vector<Fq> domain;        ///< L_i: domain points, size m
    std::vector<Fq> pair_diff_inv; ///< 1/(L_i[j + m/2] - L_i[j]) for each pair j, size m/2
    std::vector<Fq> pair_s0_e_inv; ///< s0^(-(m/2 - 1)) for each pair j under the canonical degree schedule
    std::vector<Fq> pair_s1_e_inv; ///< s1^(-(m/2 - 1)) for each pair j under the canonical degree schedule

    size_t size() const { return domain.size(); }
    size_t num_pairs() const { return domain.size() / 2; }

    /**
     * @brief Get the paired domain points (s_0, s_1) at pair index j.
     */
    std::pair<Fq, Fq> pair_at(size_t j) const
    {
        size_t half = domain.size() / 2;
        return { domain[j], domain[j + half] };
    }
};

/**
 * @brief Complete ECFFT domain for FRI folding.
 *
 * Contains num_rounds + 1 levels: levels[0] is the initial domain L_0 of size n,
 * and levels[num_rounds] is the final domain of size 1.
 */
struct EcfftDomain {
    size_t log_n;                         ///< log2(|L_0|)
    size_t num_rounds;                    ///< number of folding rounds (= log_n)
    std::vector<EcfftDomainLevel> levels; ///< levels[0..num_rounds]; levels[i].size() = n / 2^i

    /**
     * @brief Compute the fold coefficients α, β for a single pair.
     *
     * The fold formula reduces to a linear combination of the two opened values:
     *
     *     fold(f_s0, f_s1) = f_s0 · α  +  f_s1 · β
     *
     * where α, β ∈ Fq depend only on the domain points (s0, s1), the degree bound,
     * and the verifier challenge z.  Derivation:
     *
     *     a = f_s0 · s0^{-e},  b = f_s1 · s1^{-e}     (normalization)
     *     slope = (b - a) / (s1 - s0)                   (interpolation)
     *     result = a + slope · (z - s0)                  (evaluate at z)
     *            = f_s0 · [s0^{-e} · (s1 - z) / (s1 - s0)]
     *            + f_s1 · [s1^{-e} · (z - s0) / (s1 - s0)]
     *
     * So:
     *     α = s0^{-e} · (s1 - z) · diff_inv
     *     β = s1^{-e} · (z - s0) · diff_inv
     *
     * When e = 0: α = (s1 - z) · diff_inv,  β = (z - s0) · diff_inv.
     *
     * This formulation is critical for circuit efficiency: it reduces the fold check
     * from 4 group scalar multiplications to 2 (plus cheap field arithmetic for α, β).
     * See OPTIMIZATIONS.md, Optimization 1 for details.
     *
     * @return (α, β) such that fold(f_s0, f_s1) = f_s0 · α + f_s1 · β.
     */
    /**
     * @brief Compute the folded value for a single pair opening (the core verifier check).
     *
     * Given the pair (f(s_0), f(s_1)) at pair index j in round `round_idx`, with
     * current degree bound `degree_bound` and verifier challenge z, computes the
     * expected value at L_{round_idx+1}[j] using the ECFFT Part II fold formula.
     *
     * @tparam T  Fq for scalar FRI, or GroupElement for group-valued BaseFold.
     *            Must support: T - T, T * Fq, T + T.
     *
     * @param round_idx     Which round (0-indexed). Determines the domain layer.
     * @param degree_bound  Current degree bound d. Halves each round. Controls the
     *                      normalization exponent e = d/2 - 1.
     * @param j             Pair index within the layer (0 ≤ j < m/2).
     * @param f_s0          Oracle value at L_i[j]       (the "left" element of the pair).
     * @param f_s1          Oracle value at L_i[j + m/2]  (the "right" element of the pair).
     * @param z             Verifier's fold challenge for this round.
     *
     * @return The expected folded value at L_{i+1}[j].
     *
     * When T = GroupElement, each · is a Grumpkin scalar multiplication:
     *   - e > 0: 4 scalar muls  (normalize both inputs, compute slope, evaluate at z)
     *   - e = 0: 2 scalar muls  (no normalization needed, just slope + evaluate)
     *
     * Note on circuit cost: algebraically, the fold can be rewritten as
     *   fold = f_s0 · α + f_s1 · β  (see OPTIMIZATIONS.md, Opt 1)
     * which looks like 2 scalar muls.  However, α and β depend on the witness
     * challenge z, making them witness bigfield values.  In the current formulation,
     * 3 of the 4 scalar muls use CONSTANT scalars (s0^{-e}, s1^{-e}, diff_inv) which
     * cycle_group handles more cheaply.  Benchmarking shows the 4-mul form at ~6,500
     * gates outperforms the 2-mul α,β form at ~10,200 gates because the bigfield
     * arithmetic for computing witness α,β costs ~5,100 gates.
     */
    template <typename T>
    T fold_pair(size_t round_idx, size_t degree_bound, size_t j, const T& f_s0, const T& f_s1, const Fq& z) const
    {
        const auto& level = levels[round_idx];
        size_t half = level.size() / 2;
        size_t e = degree_bound / 2 - 1;

        Fq s0 = level.domain[j];
        Fq s1 = level.domain[j + half];
        Fq diff_inv = level.pair_diff_inv[j]; // precomputed 1/(s1 - s0)

        if (e == 0) {
            // degree_bound == 2: no normalization needed, just linear interpolation.
            //   slope = (f_s1 - f_s0) / (s1 - s0)           [1 scalar mul: witness × constant]
            //   result = f_s0 + slope · (z - s0)             [1 scalar mul: witness × witness]
            T slope = (f_s1 - f_s0) * diff_inv;
            return f_s0 + slope * (z - s0);
        }

        // General case: normalize by s^{-e}, then interpolate.
        //   a = f_s0 · s0^{-e}                              [1 scalar mul: witness × constant]
        //   b = f_s1 · s1^{-e}                              [1 scalar mul: witness × constant]
        //   slope = (b - a) · (s1 - s0)^{-1}                [1 scalar mul: witness × constant]
        //   result = a + slope · (z - s0)                    [1 scalar mul: witness × witness]
        Fq s0_e_inv = s0.pow(e).invert();
        Fq s1_e_inv = s1.pow(e).invert();

        T a = f_s0 * s0_e_inv;
        T b = f_s1 * s1_e_inv;
        T slope = (b - a) * diff_inv;
        return a + slope * (z - s0);
    }

    /** @brief Load domain from a binary file (generated by ecfft_precompute.py --export-binary). */
    static EcfftDomain load_binary(const std::string& path);

    /**
     * @brief Build domain from hardcoded hex string arrays (generated by ecfft_precompute.py).
     *
     * Used for compile-time embedding of small test domains (e.g. log_n=8).
     * For production (log_n=18), prefer load_binary().
     */
    static EcfftDomain from_hex_arrays(size_t log_n,
                                       const std::vector<std::pair<const char* const*, size_t>>& layer_hex,
                                       const std::vector<std::pair<const char* const*, size_t>>& diff_inv_hex);

    /**
     * @brief Precompute the per-pair normalization inverses for the canonical degree schedule.
     *
     * For round i with layer size m, the canonical degree bound is d = m, hence e = d/2 - 1 = m/2 - 1.
     * These constants are reused by both the native prover and recursive verifier.
     */
    void precompute_round_constants();
};

} // namespace bb::basefold
