VERSION 0.8
FROM node:18.19.0

ARG --global use_local_builds=false

# These args are loaded from the EARTHLY_BUILD_ARGS set in setup_env
ARG --global COMMIT_HASH
ARG --global PULL_REQUEST
ARG --global BRANCH

build:
  FROM ../+scripts-prod --use_local_builds=$use_local_builds
  RUN apt-get update && apt-get install awscli -y
  COPY ../../+scripts/scripts /usr/src/scripts
  WORKDIR /usr/src

download-logs:
  # Downloads logs for the current PR and saves them as an artifact
  FROM +build
  LET LOG_FOLDER=/usr/var/logs
  LET BENCH_FOLDER=/usr/var/bench
  ENV LOG_FOLDER=$LOG_FOLDER
  ENV BENCH_FOLDER=$BENCH_FOLDER
  ENV COMMIT_HASH=$COMMIT_HASH
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY ./scripts/logs/download_logs_from_s3.sh 
  SAVE ARTIFACT $LOG_FOLDER logs

bench-aggregate:
  # Copies logs downloaded from download-logs and aggregates them using bench-aggregate.
  # No aggregation is done if there is a log missing from the benchmark jobs.
  FROM +build
  LET LOG_FOLDER=/usr/var/logs
  LET BENCH_FOLDER=/usr/var/bench
  ENV LOG_FOLDER=$LOG_FOLDER
  ENV BENCH_FOLDER=$BENCH_FOLDER
  ENV COMMIT_HASH=$COMMIT_HASH
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  COPY +download-logs/logs $LOG_FOLDER
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY \
    ./scripts/logs/check_logs_for_benchmark.sh \
    && ((cd /usr/src/yarn-project/scripts && yarn bench-aggregate) && ./scripts/logs/upload_aggregated_benchmarks_to_s3.sh) \
    || (echo "Not all log files from benchmark jobs found"; mkdir -p $BENCH_FOLDER)
  SAVE ARTIFACT $BENCH_FOLDER bench

bench-comment:
  LET BENCH_FOLDER=/usr/var/bench
  # Download base benchmark file locally so we have access to git to find out the right commit
  LOCALLY
  ENV BENCH_FOLDER=$BENCH_FOLDER
  ENV COMMIT_HASH=$COMMIT_HASH
  ENV PULL_REQUEST=$PULL_REQUEST
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY mkdir -p $BENCH_FOLDER && ../../scripts/logs/download_base_benchmark_from_s3.sh
  # Use the scripts image to run bench comment after loading the benchmark from bench-aggregate 
  # and the base benchmark from the local step
  FROM +build
  ENV BENCH_FOLDER=$BENCH_FOLDER
  ENV COMMIT_HASH=$COMMIT_HASH
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  COPY $BENCH_FOLDER/base-benchmark.json $BENCH_FOLDER/base-benchmark.json
  COPY +bench-aggregate/bench $BENCH_FOLDER
  RUN --secret AZTEC_BOT_COMMENTER_GITHUB_TOKEN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY \
    [ -f $BENCH_FOLDER/benchmark.json ] \
      && (cd /usr/src/yarn-project/scripts && yarn bench-comment) \
      || echo "No benchmark file found in $BENCH_FOLDER"
  