import {
  ClientIvcProof,
  PrivateKernelTailCircuitPublicInputs,
  type PrivateToPublicAccumulatedData,
  PublicLog,
} from '@aztec/circuits.js';
import { type Buffer32 } from '@aztec/foundation/buffer';
import { arraySerializedSizeOfNonEmpty } from '@aztec/foundation/collection';
import { BufferReader, serializeArrayOfBufferableToVector, serializeToBuffer } from '@aztec/foundation/serialize';
import { type FieldsOf } from '@aztec/foundation/types';

import { z } from 'zod';

import { type GetPublicLogsResponse } from '../logs/get_logs_response.js';
import { type L2LogsSource } from '../logs/l2_logs_source.js';
import { ContractClassTxL2Logs } from '../logs/tx_l2_logs.js';
import { Gossipable } from '../p2p/gossipable.js';
import { TopicType, createTopicString } from '../p2p/topic_type.js';
import { PublicExecutionRequest } from '../public_execution_request.js';
import { type TxStats } from '../stats/stats.js';
import { TxHash } from './tx_hash.js';

/**
 * The interface of an L2 transaction.
 */
export class Tx extends Gossipable {
  static override p2pTopic: string;

  constructor(
    /**
     * Output of the private kernel circuit for this tx.
     */
    public readonly data: PrivateKernelTailCircuitPublicInputs,
    /**
     * Proof from the private kernel circuit.
     * TODO(#7368): This client IVC object currently contains various VKs that will eventually be more like static data.
     *
     */
    public readonly clientIvcProof: ClientIvcProof,
    /**
     * Public logs generated by the tx.
     * TODO: These do not get filled, but remain here so public_tx_simulator.ts can accumulate public logs
     */
    public publicLogs: PublicLog[],
    /**
     * Contract class logs generated by the tx.
     */
    public contractClassLogs: ContractClassTxL2Logs,
    /**
     * Enqueued public functions from the private circuit to be run by the sequencer.
     */
    public readonly enqueuedPublicFunctionCalls: PublicExecutionRequest[],
    /**
     * Public function call to be run by the sequencer as part of teardown.
     */
    public readonly publicTeardownFunctionCall: PublicExecutionRequest,
  ) {
    super();
  }

  // Gossipable method
  static {
    this.p2pTopic = createTopicString(TopicType.tx);
  }

  // Gossipable method
  override p2pMessageIdentifier(): Buffer32 {
    return this.getTxHash();
  }

  hasPublicCalls() {
    return this.data.numberOfPublicCallRequests() > 0;
  }

  getNonRevertiblePublicExecutionRequests(): PublicExecutionRequest[] {
    const numRevertible = this.data.numberOfRevertiblePublicCallRequests();
    return this.enqueuedPublicFunctionCalls.slice(numRevertible);
  }

  getRevertiblePublicExecutionRequests(): PublicExecutionRequest[] {
    const numRevertible = this.data.numberOfRevertiblePublicCallRequests();
    return this.enqueuedPublicFunctionCalls.slice(0, numRevertible);
  }

  getPublicTeardownExecutionRequest(): PublicExecutionRequest | undefined {
    return this.publicTeardownFunctionCall.isEmpty() ? undefined : this.publicTeardownFunctionCall;
  }

  /**
   * Deserializes the Tx object from a Buffer.
   * @param buffer - Buffer or BufferReader object to deserialize.
   * @returns An instance of Tx.
   */
  static fromBuffer(buffer: Buffer | BufferReader): Tx {
    const reader = BufferReader.asReader(buffer);
    return new Tx(
      reader.readObject(PrivateKernelTailCircuitPublicInputs),
      reader.readObject(ClientIvcProof),
      reader.readVectorUint8Prefix(PublicLog),
      reader.readObject(ContractClassTxL2Logs),
      reader.readVectorUint8Prefix(PublicExecutionRequest),
      reader.readObject(PublicExecutionRequest),
    );
  }

  static newWithTxData(
    data: PrivateKernelTailCircuitPublicInputs,
    publicTeardownExecutionRequest?: PublicExecutionRequest,
  ) {
    return new Tx(
      data,
      ClientIvcProof.empty(),
      [],
      ContractClassTxL2Logs.empty(),
      [],
      publicTeardownExecutionRequest ? publicTeardownExecutionRequest : PublicExecutionRequest.empty(),
    );
  }

  /**
   * Serializes the Tx object into a Buffer.
   * @returns Buffer representation of the Tx object.
   */
  toBuffer() {
    return serializeToBuffer([
      this.data,
      this.clientIvcProof,
      serializeArrayOfBufferableToVector(this.publicLogs, 1),
      this.contractClassLogs,
      serializeArrayOfBufferableToVector(this.enqueuedPublicFunctionCalls, 1),
      this.publicTeardownFunctionCall,
    ]);
  }

  static get schema() {
    return z
      .object({
        data: PrivateKernelTailCircuitPublicInputs.schema,
        clientIvcProof: ClientIvcProof.schema,
        publicLogs: z.array(PublicLog.schema),
        contractClassLogs: ContractClassTxL2Logs.schema,
        enqueuedPublicFunctionCalls: z.array(PublicExecutionRequest.schema),
        publicTeardownFunctionCall: PublicExecutionRequest.schema,
      })
      .transform(Tx.from);
  }

  static from(fields: FieldsOf<Tx>) {
    return new Tx(
      fields.data,
      fields.clientIvcProof,
      fields.publicLogs,
      fields.contractClassLogs,
      fields.enqueuedPublicFunctionCalls,
      fields.publicTeardownFunctionCall,
    );
  }

  /**
   * Gets public logs emitted by this tx.
   * @param logsSource - An instance of `L2LogsSource` which can be used to obtain the logs.
   * @returns The requested logs.
   */
  public getPublicLogs(logsSource: L2LogsSource): Promise<GetPublicLogsResponse> {
    return logsSource.getPublicLogs({ txHash: this.getTxHash() });
  }

  /**
   * Construct & return transaction hash.
   * @returns The transaction's hash.
   */
  getTxHash(): TxHash {
    // Private kernel functions are executed client side and for this reason tx hash is already set as first nullifier
    const firstNullifier = this.data.getNonEmptyNullifiers()[0];
    if (!firstNullifier || firstNullifier.isZero()) {
      throw new Error(`Cannot get tx hash since first nullifier is missing`);
    }
    return new TxHash(firstNullifier.toBuffer());
  }

  /** Returns the tx hash, or undefined if none is set. */
  tryGetTxHash(): TxHash | undefined {
    try {
      return this.getTxHash();
    } catch {
      return undefined;
    }
  }

  /** Returns stats about this tx. */
  getStats(): TxStats {
    return {
      txHash: this.getTxHash().toString(),
      publicLogCount: this.publicLogs.filter(n => !n.isEmpty()).length,

      noteHashCount: this.data.getNonEmptyNoteHashes().length,
      nullifierCount: this.data.getNonEmptyNullifiers().length,
      privateLogCount: this.data.getNonEmptyPrivateLogs().length,

      proofSize: this.clientIvcProof.clientIvcProofBuffer.length,
      size: this.toBuffer().length,

      feePaymentMethod:
        // needsTeardown? then we pay a fee
        this.data.forPublic?.needsTeardown
          ? // needsSetup? then we pay through a fee payment contract
            this.data.forPublic?.needsSetup
            ? // if the first call is to `approve_public_authwit`, then it's a public payment
              this.data.getNonRevertiblePublicCallRequests().at(-1)!.functionSelector.toField().toBigInt() ===
              0x43417bb1n
              ? 'fpc_public'
              : 'fpc_private'
            : 'fee_juice'
          : 'none',
      classRegisteredCount: this.contractClassLogs.unrollLogs().length,
      contractClassLogSize: this.contractClassLogs.getSerializedLength(),
    };
  }

  getSize() {
    return (
      this.data.getSize() +
      this.clientIvcProof.clientIvcProofBuffer.length +
      arraySerializedSizeOfNonEmpty(this.publicLogs) +
      this.contractClassLogs.getSerializedLength() +
      arraySerializedSizeOfNonEmpty(this.enqueuedPublicFunctionCalls) +
      arraySerializedSizeOfNonEmpty([this.publicTeardownFunctionCall])
    );
  }

  /**
   * Convenience function to get a hash out of a tx or a tx-like.
   * @param tx - Tx-like object.
   * @returns - The hash.
   */
  static getHash(tx: Tx | HasHash): TxHash {
    return hasHash(tx) ? tx.hash : tx.getTxHash();
  }

  /**
   * Convenience function to get array of hashes for an array of txs.
   * @param txs - The txs to get the hashes from.
   * @returns The corresponding array of hashes.
   */
  static getHashes(txs: (Tx | HasHash)[]): TxHash[] {
    return txs.map(Tx.getHash);
  }

  /**
   * Clones a tx, making a deep copy of all fields.
   * @param tx - The transaction to be cloned.
   * @returns The cloned transaction.
   */
  static clone(tx: Tx): Tx {
    const publicInputs = PrivateKernelTailCircuitPublicInputs.fromBuffer(tx.data.toBuffer());
    const clientIvcProof = ClientIvcProof.fromBuffer(tx.clientIvcProof.toBuffer());
    const publicLogs = tx.publicLogs.map(l => PublicLog.fromBuffer(l.toBuffer()));
    const contractClassLogs = ContractClassTxL2Logs.fromBuffer(tx.contractClassLogs.toBuffer());
    const enqueuedPublicFunctionCalls = tx.enqueuedPublicFunctionCalls.map(x =>
      PublicExecutionRequest.fromBuffer(x.toBuffer()),
    );
    const publicTeardownFunctionCall = PublicExecutionRequest.fromBuffer(tx.publicTeardownFunctionCall.toBuffer());
    return new Tx(
      publicInputs,
      clientIvcProof,
      publicLogs,
      contractClassLogs,
      enqueuedPublicFunctionCalls,
      publicTeardownFunctionCall,
    );
  }

  static random() {
    return new Tx(
      PrivateKernelTailCircuitPublicInputs.emptyWithNullifier(),
      ClientIvcProof.empty(),
      [PublicLog.random()],
      ContractClassTxL2Logs.random(1, 1),
      [PublicExecutionRequest.random()],
      PublicExecutionRequest.random(),
    );
  }

  /**
   * Filters out logs from functions that are not present in the provided kernel output.
   *
   * The purpose of this is to remove logs that got dropped due to a revert,
   * in which case, we only have the kernel's hashes to go on, as opposed to
   * this grouping by function maintained in this class.
   *
   * The logic therefore is to drop all FunctionLogs if any constituent hash
   * does not appear in the provided hashes: it is impossible for part of a
   * function to revert.
   *
   * @param logHashes the individual log hashes we want to keep
   * @param out the output to put passing logs in, to keep this function abstract
   */
  public filterRevertedLogs(privateNonRevertible: PrivateToPublicAccumulatedData, publicLogs: PublicLog[]) {
    this.contractClassLogs = this.contractClassLogs.filterScoped(
      privateNonRevertible.contractClassLogsHashes,
      ContractClassTxL2Logs.empty(),
    );

    this.publicLogs = this.publicLogs.filter(l => publicLogs.find(givenLog => givenLog.equals(l)));
  }
}

/** Utility type for an entity that has a hash property for a txhash */
type HasHash = { /** The tx hash */ hash: TxHash };

function hasHash(tx: Tx | HasHash): tx is HasHash {
  return (tx as HasHash).hash !== undefined;
}
