VERSION 0.7

FROM ubuntu:22.04
WORKDIR /app

deps:
    RUN apt-get update && apt-get install -y \
        curl \
        git \
        make \
        nodejs \
        npm \
        unzip

    RUN curl -fsSL https://bun.sh/install | bash
    ENV PATH="/root/.bun/bin:${PATH}"

    COPY package.json .
    COPY bun.lockb .

    RUN bun install

test-install:
    FROM +deps

    COPY index.ts .

    RUN yes | bun index.ts install -p 8080 -p2p 40400 -ip 7.7.7.7 -k 0x00 -n test-node


test-functionality:
    FROM +deps

    COPY index.ts .
    COPY index.test.ts .

    RUN curl -fsSL https://get.docker.com | sh

    RUN bun test

