*
# These are copied in so we can perform a "production dependency install" in the release base image.
!/barretenberg/ts/bb.js/package.json
!/barretenberg/ts/bb-avm-sim/package.json
!/barretenberg/ts/bb-avm-sim/packages/*/package.json
!/barretenberg/ts/cdb/package.json
!/noir/packages/*/package.json
!/wsdb/ts/package.json
!/wsdb/ts/packages/*/package.json
!/ipc-runtime/ts/package.json
!/yarn-project/package.json
!/yarn-project/yarn.lock
!/yarn-project/*/package.json
!/yarn-project/.yarn/
!/yarn-project/.yarnrc.yml
