# Build foundry for use in release-image..
FROM aztecprotocol/build:3.0 AS foundry
ENV FOUNDRY_VERSION=v1.4.1
ENV FOUNDRY_BIN_DIR="/root/.foundry/bin"
ENV RUSTUP_HOME=/opt/rust/rustup
ENV CARGO_HOME=/opt/rust/cargo
ENV PATH="/opt/rust/cargo/bin:$PATH"
ENV RUSTFLAGS="-C target-cpu=generic"
RUN curl -L https://foundry.paradigm.xyz | bash \
    && $FOUNDRY_BIN_DIR/foundryup -i $FOUNDRY_VERSION \
    && mkdir -p /opt/foundry/bin \
    && for t in forge cast anvil ; do \
        mv $FOUNDRY_BIN_DIR/$t /opt/foundry/bin/$t; \
        strip /opt/foundry/bin/$t; \
    done \
    && rm -rf $FOUNDRY_BIN_DIR

# Create an image that installs yarn-projects production dependencies.
FROM aztecprotocol/build:3.0 AS build
# Copy files explicitly listed in Dockerfile.base.dockerignore into container.
# Should just be package.json, yarn.lock, and .yarn* files.
COPY . /usr/src
# Install yarn-project production dependencies.
# Explicitly specify projects that we use to keep as slim as possible.
WORKDIR /usr/src/yarn-project
RUN yarn workspaces focus @aztec/aztec @aztec/cli-wallet --production

# Create base of our final slim image.
# This can be cached and will only update if dependencies change.
FROM ubuntu:noble

ENV NODE_MAJOR=22

RUN apt update && apt install -y \
      curl \
      ca-certificates \
      git \
      gnupg \
      jq \
      netcat-openbsd \
      parallel \
      curl \
      gnupg && \
      curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
      echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
      apt update && apt install nodejs && \
      rm -rf /var/lib/apt/lists/*

# Copy forge from foundry install. Currently the only foundry utility used..
COPY --from=foundry /opt/foundry/bin/forge /opt/foundry/bin/forge
ENV PATH="/opt/foundry/bin:$PATH"

# Copy in production dependencies.
COPY --from=build /usr/src/yarn-project/node_modules /usr/src/yarn-project/node_modules
# We install a symlink to yarn-project's node_modules at a location that all portalled packages can find as they
# walk up the tree as part of module resolution. The supposedly idiomatic way of supporting module resolution
# correctly for portalled packages, is to use --preserve-symlinks when running node.
# However I noticed --preserve-symlinks causes duplication of portalled instances such as bb.js, breaking the singleton
# logic by initializing the module more than once. So at present I don't see a viable alternative.
RUN ln -s /usr/src/yarn-project/node_modules /usr/src/node_modules
