*
# These are copied in so we can perform a "production dependency install" in the release base image.
!/barretenberg/ts/bb.js/package.json
!/barretenberg/ts/bb-avm-sim/package.json
!/barretenberg/ts/bb-avm-sim/packages/*/package.json
!/noir/packages/*/package.json
!/native-packages/wsdb/ts/package.json
!/native-packages/wsdb/ts/packages/*/package.json
!/native-packages/kvdb/ts/package.json
!/native-packages/kvdb/ts/packages/*/package.json
!/native-packages/acvm/ts/package.json
!/native-packages/acvm/ts/packages/*/package.json
!/ipc-runtime/ts/package.json
!/yarn-project/package.json
!/yarn-project/yarn.lock
!/yarn-project/*/package.json
# l1-artifacts is a portal dependency of @aztec/aztec but lives outside yarn-project.
!/l1-contracts/l1-artifacts/package.json
!/yarn-project/.yarn/
!/yarn-project/.yarnrc.yml
