# We include just what's needed to run the aztec cli (none of the aztec.sh extensions).
*
!/.release-please-manifest.json
# The two toolchain binaries the image runs, via BB_BINARY_PATH and ACVM_BINARY_PATH.
!/labs-aztec-toolchain/bin/bb-avm
!/labs-aztec-toolchain/bin/acvm
!/yarn-project/package.json
!/yarn-project/yarn.lock
!/yarn-project/*/package.json
!/yarn-project/*/dest/
!/yarn-project/cli/public_include_metric_prefixes.json
!/yarn-project/accounts/artifacts/
!/yarn-project/bb-prover/artifacts/
!/yarn-project/noir-protocol-circuits-types/artifacts/
!/yarn-project/protocol-contracts/artifacts/
!/yarn-project/standard-contracts/artifacts/
!/yarn-project/noir-contracts.js/artifacts/
!/yarn-project/noir-test-contracts.js/artifacts/
!/yarn-project/simulator/artifacts/
