VERSION 0.8
IMPORT .. AS bb
# use common base ubuntu
FROM bb:+base

srs-db:
    # minimum files to download SRS
    COPY ./*.sh .
    RUN ./download_ignition.sh
    RUN ./download_grumpkin.sh
    # export srs-db for runners
    SAVE ARTIFACT ignition
    SAVE ARTIFACT grumpkin

srs-db-local:
    # copy files locally
    COPY +srs-db/ignition ignition
    COPY +srs-db/grumpkin grumpkin 
    SAVE ARTIFACT ignition AS LOCAL ignition
    SAVE ARTIFACT grumpkin AS LOCAL grumpkin