VERSION 0.8
IMPORT .. AS bb
# use common base ubuntu
FROM bb:+base

download:
    # minimum files to download SRS
    COPY ./*.sh .
    RUN ./download_ignition.sh
    RUN ./download_grumpkin.sh
    # export srs-db for runners
    SAVE ARTIFACT /build

download-local:
    # copy files locally
    FROM +download
    SAVE ARTIFACT ignition AS LOCAL ignition
    SAVE ARTIFACT grumpkin AS LOCAL grumpkin