VERSION 0.8
FROM ubuntu:lunar

RUN apt-get update && apt-get install -y curl

download:
    # minimum files to download SRS
    COPY ./*.sh .
    RUN ./download_ignition.sh
    RUN ./download_grumpkin.sh
    # export srs-db for runners
    SAVE ARTIFACT /build

download-local:
    # copy files locally
    FROM +download
    SAVE ARTIFACT ignition AS LOCAL ignition
    SAVE ARTIFACT grumpkin AS LOCAL grumpkin