#!/usr/bin/env bash
# create_doc_update_pr.sh - Create a PR with documentation updates
#
# This script is extracted from check_doc_references.sh for future use.
# It handles:
# - Creating a branch for doc updates
# - Committing changes
# - Pushing to remote
# - Creating/updating a PR
# - Commenting on the original PR
#
# Usage: source this file and call create_doc_update_pr
#
# Required variables (must be set before calling):
#   PR_NUMBER - Original PR number
#   PR_TITLE - Original PR title
#   PR_URL - Original PR URL
#   PR_AUTHOR - Original PR author
#   BASE_BRANCH - Base branch name
#   MODIFIED_FILES - List of modified doc files
#   FILE_TO_DOCS_MAP - Associative array of source files to doc files
#
# Optional variables:
#   DRY_RUN - Set to 1 to skip PR creation

create_doc_update_pr() {
  local pr_number="$1"
  local pr_title="$2"
  local pr_url="$3"
  local pr_author="$4"
  local base_branch="$5"
  local modified_files="$6"

  local doc_update_branch="docs/auto-update-pr-${pr_number}"
  local original_ref=$(git rev-parse HEAD)
  local original_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

  echo "Creating documentation update branch: $doc_update_branch"

  # Configure git for CI (needed for commits)
  git config user.email "aztec-bot@aztecprotocol.com"
  git config user.name "Aztec Bot"

  # Check if branch already exists on remote (from a previous run)
  if git ls-remote --exit-code --heads origin "$doc_update_branch" &>/dev/null; then
    echo "Remote branch $doc_update_branch already exists. Will update it..."
    git fetch origin "$doc_update_branch" 2>/dev/null || true
  fi

  # Delete local branch if it exists
  git branch -D "$doc_update_branch" 2>/dev/null || true

  # Create the new branch from the base branch
  git checkout -b "$doc_update_branch" "origin/$base_branch"

  # Stage and commit the changes
  echo "Committing documentation updates..."

  git add -A
  git commit -m "docs: auto-update documentation for PR #$pr_number

This commit contains automatic documentation updates generated by Claude Code
in response to code changes in PR #$pr_number.

Original PR: $pr_url

The following documentation files were updated based on changes to their
referenced source files:

$(echo "$modified_files" | sed 's/^/- /')

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

  # Check for dry run mode
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    echo ""
    echo "DRY_RUN mode: Skipping PR creation."
    echo "Changes committed to branch: $doc_update_branch"
    git checkout "$original_ref" 2>/dev/null || git checkout "$original_branch" 2>/dev/null || true
    return 0
  fi

  # Push the branch
  echo "Pushing branch to origin..."
  git push -u origin "$doc_update_branch" --force

  # Create the PR
  echo "Creating pull request..."

  local pr_body=$(cat << EOF
## Summary

This PR contains automatic documentation updates generated by Claude Code in response to code changes.

### Original PR
- **PR:** #$pr_number
- **Title:** $pr_title
- **Author:** @$pr_author
- **URL:** $pr_url

### Documentation Updates

The following documentation files were updated based on changes to their referenced source files:

$(echo "$modified_files" | sed 's/^/- `/' | sed 's/$/`/')

---

> **Note:** This PR was automatically generated. Please review the changes carefully before merging.

Generated with [Claude Code](https://claude.ai/code)
EOF
)

  # Check if a PR already exists for this branch
  local existing_pr=$(gh pr list --head "$doc_update_branch" --json number --jq '.[0].number' 2>/dev/null || echo "")
  local doc_pr_url=""

  if [[ -n "$existing_pr" ]]; then
    echo "Updating existing PR #$existing_pr..."
    gh pr edit "$existing_pr" --body "$pr_body"
    doc_pr_url=$(gh pr view "$existing_pr" --json url -q .url)
  else
    doc_pr_url=$(gh pr create \
      --title "docs: auto-update for PR #$pr_number - $pr_title" \
      --body "$pr_body" \
      --base "$base_branch" \
      --head "$doc_update_branch" \
      --label "documentation" \
      --label "auto-generated" 2>/dev/null || echo "")
  fi

  if [[ -n "$doc_pr_url" ]]; then
    echo ""
    echo "Documentation update PR created successfully!"
    echo "  URL: $doc_pr_url"

    # Add a comment to the original PR linking to the docs PR
    local link_comment="**Automatic Documentation Update**

A documentation update PR has been created in response to code changes in this PR:

**Documentation PR:** $doc_pr_url

Please review the documentation changes and merge them after this PR is merged."

    gh pr comment "$pr_number" --body "$link_comment" 2>/dev/null || echo "Warning: Could not add comment to original PR"
  else
    echo "Warning: Could not create documentation update PR"
  fi

  # Return to original ref/branch
  git checkout "$original_ref" 2>/dev/null || git checkout "$original_branch" 2>/dev/null || true

  echo "$doc_pr_url"
}
