import { jsonParseWithSchema, jsonStringify } from '@aztec/foundation/json-rpc';

import {
  AZTEC_INITIALIZER_ATTRIBUTE,
  AZTEC_ONLY_SELF_ATTRIBUTE,
  AZTEC_PRIVATE_ATTRIBUTE,
  AZTEC_PUBLIC_ATTRIBUTE,
  AZTEC_UTILITY_ATTRIBUTE,
  AZTEC_VIEW_ATTRIBUTE,
  type NoirCompiledContract,
} from '../noir/index.js';
import {
  type ABIParameter,
  type ABIParameterVisibility,
  ARTIFACT_VERSION_BEFORE_INJECTION,
  type AbiNamedValue,
  type AbiType,
  type AbiValue,
  type ContractArtifact,
  ContractArtifactSchema,
  type FieldLayout,
  type FunctionAbi,
  type FunctionArtifact,
  FunctionType,
  type IntegerValue,
  type StructValue,
  type TypedStructFieldValue,
} from './abi.js';

/**
 * Serializes a contract artifact to a buffer for storage.
 * @param artifact - Artifact to serialize.
 * @returns A buffer.
 */
export function contractArtifactToBuffer(artifact: ContractArtifact): Buffer {
  return Buffer.from(jsonStringify(artifact), 'utf-8');
}

/**
 * Deserializes a contract artifact from storage.
 * @param buffer - Buffer to deserialize.
 * @returns Deserialized artifact.
 */
export function contractArtifactFromBuffer(buffer: Buffer): ContractArtifact {
  return jsonParseWithSchema(buffer.toString('utf-8'), ContractArtifactSchema);
}

/**
 * Gets nargo build output and returns a valid contract artifact instance.
 * Does not include public bytecode, apart from the public_dispatch function.
 * @param input - Input object as generated by nargo compile.
 * @returns A valid contract artifact instance.
 */
export function loadContractArtifact(input: NoirCompiledContract): ContractArtifact {
  if (isContractArtifact(input)) {
    // TODO(F-557): Remove this fallback once pre-version artifacts are no longer tested.
    if (!(input as unknown as Record<string, unknown>).aztecVersion) {
      return { ...input, aztecVersion: ARTIFACT_VERSION_BEFORE_INJECTION };
    }
    return input;
  }
  return generateContractArtifact(input);
}

/**
 * Gets nargo build output and returns a valid contract artifact instance.
 * Differs from loadContractArtifact() by retaining all bytecode.
 * @param input - Input object as generated by nargo compile.
 * @returns A valid contract artifact instance.
 */
export function loadContractArtifactForPublic(input: NoirCompiledContract): ContractArtifact {
  return generateContractArtifactForPublic(input);
}

/**
 * Checks if the given input looks like a valid ContractArtifact. The check is not exhaustive,
 * and it's just meant to differentiate between nargo raw build artifacts and the ones
 * produced by this compiler.
 * @param input - Input object.
 * @returns True if it looks like a ContractArtifact.
 */
function isContractArtifact(input: any): input is ContractArtifact {
  if (typeof input !== 'object') {
    return false;
  }
  const maybeContractArtifact = input as ContractArtifact;
  if (typeof maybeContractArtifact.name !== 'string') {
    return false;
  }
  if (!Array.isArray(maybeContractArtifact.functions)) {
    return false;
  }
  for (const fn of maybeContractArtifact.functions) {
    if (typeof fn.name !== 'string') {
      return false;
    }
    if (typeof fn.functionType !== 'string') {
      return false;
    }
    if (!retainBytecode(fn) && fn.bytecode.length) {
      // We want to remove the bytecode of public fns (apart from the dispatch fn) to save space
      // If the input is private-only, we don't need to use generateContractArtifact() below
      return false;
    }
  }
  if (!Array.isArray(maybeContractArtifact.nonDispatchPublicFunctions)) {
    return false;
  }
  for (const fn of maybeContractArtifact.nonDispatchPublicFunctions) {
    if (typeof fn.name !== 'string') {
      return false;
    }
    if (typeof fn.functionType !== 'string') {
      return false;
    }
  }
  return true;
}

/** Parameter in a function from a noir contract compilation artifact */
type NoirCompiledContractFunctionParameter = NoirCompiledContractFunction['abi']['parameters'][number];

/**
 * Generates a function parameter out of one generated by a nargo build.
 * @param param - Noir parameter.
 * @returns A function parameter.
 */
function generateFunctionParameter(param: NoirCompiledContractFunctionParameter): ABIParameter {
  const { visibility } = param;
  if ((visibility as string) === 'databus') {
    throw new Error(`Unsupported visibility ${param.visibility} for noir contract function parameter ${param.name}.`);
  }
  return { ...param, visibility: visibility as ABIParameterVisibility };
}

/** Function from a noir contract compilation artifact */
type NoirCompiledContractFunction = NoirCompiledContract['functions'][number];

/**
 * Returns true if we should retain bytecode
 */
export function retainBytecode(input: NoirCompiledContractFunction | FunctionArtifact): boolean {
  const functionType =
    (input as FunctionArtifact).functionType ?? getFunctionType(input as NoirCompiledContractFunction);
  return functionType !== FunctionType.PUBLIC || input.name == 'public_dispatch';
}

/**
 * Generates a function abi.
 * @param fn - Noir function entry.
 * @param contract - Parent contract.
 * @returns Function abi.
 */
function generateFunctionAbi(fn: NoirCompiledContractFunction, contract: NoirCompiledContract): FunctionAbi {
  if (fn.custom_attributes === undefined) {
    throw new Error(
      `No custom attributes found for contract function ${fn.name}. Try rebuilding the contract with the latest nargo version.`,
    );
  }
  const functionType = getFunctionType(fn);
  const isOnlySelf = fn.custom_attributes.includes(AZTEC_ONLY_SELF_ATTRIBUTE);
  const isStatic = fn.custom_attributes.includes(AZTEC_VIEW_ATTRIBUTE);

  // If the function is not a utility function, the first item is inputs or CallContext which we should omit
  let parameters = fn.abi.parameters.map(generateFunctionParameter);
  if (hasKernelFunctionInputs(parameters)) {
    parameters = parameters.slice(1);
  }

  let returnType: AbiType | undefined;
  if (functionType === FunctionType.UTILITY) {
    returnType = fn.abi.return_type?.abi_type;
  } else {
    const pathToFind = `${contract.name}::${fn.name}_abi`;
    const abiStructs: AbiType[] = contract.outputs.structs['functions'];

    const returnStruct = abiStructs.find(a => a.kind === 'struct' && a.path === pathToFind);

    if (returnStruct) {
      if (returnStruct.kind !== 'struct') {
        throw new Error('Could not generate contract function artifact');
      }

      returnType = returnStruct.fields.find(field => field.name === 'return_type')?.type;
    }
  }

  return {
    name: fn.name,
    functionType,
    isOnlySelf,
    isStatic,
    isInitializer: fn.custom_attributes.includes(AZTEC_INITIALIZER_ATTRIBUTE),
    parameters,
    returnType,
    // Old consumers expect `returnTypes` property, not `returnType`. So we write both down for now, until we can
    // safely remove the old version.
    returnTypes: returnType ? [returnType] : [],
    errorTypes: fn.abi.error_types,
    ...(fn.assert_messages ? { assertMessages: fn.assert_messages } : undefined),
  };
}

/**
 * Generates a function build artifact.
 * @param fn - Noir function entry.
 * @param contract - Parent contract.
 * @returns Function artifact.
 */
function generateFunctionArtifact(
  fn: NoirCompiledContractFunction,
  contract: NoirCompiledContract,
): Omit<FunctionArtifact, 'bytecode'> & { bytecode: string } {
  const abi = generateFunctionAbi(fn, contract);
  return {
    ...abi,
    bytecode: fn.bytecode,
    debugSymbols: fn.debug_symbols,
    ...(fn.verification_key ? { verificationKey: fn.verification_key } : undefined),
  };
}

function getFunctionType(fn: NoirCompiledContractFunction): FunctionType {
  if (fn.custom_attributes.includes(AZTEC_PRIVATE_ATTRIBUTE)) {
    return FunctionType.PRIVATE;
  } else if (fn.custom_attributes.includes(AZTEC_PUBLIC_ATTRIBUTE)) {
    return FunctionType.PUBLIC;
  } else if (fn.custom_attributes.includes(AZTEC_UTILITY_ATTRIBUTE)) {
    return FunctionType.UTILITY;
  } else {
    throw new Error(`Invalid function type for a noir contract function ${fn.name}`);
  }
}

/**
 * Returns true if the first parameter is kernel function inputs.
 *
 * Noir macros #[aztec(private|public)] inject the following code
 * fn <name>(inputs: <Public|Private>ContextInputs, ...otherparams) {}
 *
 * Return true if this injected parameter is found
 */
function hasKernelFunctionInputs(params: ABIParameter[]): boolean {
  const firstParam = params[0];
  return firstParam?.type.kind === 'struct' && firstParam.type.path.includes('ContextInputs');
}

/** Name prefix of the storage layout globals emitted by the aztec-nr `#[storage]` macro. */
const STORAGE_LAYOUT_GLOBAL_PREFIX = 'STORAGE_LAYOUT_';

/**
 * Generates a storage layout for the contract artifact.
 * @param contractName - The name of the compiled Noir contract.
 * @param globals - The globals exported by the contract.
 * @returns A storage layout for the contract.
 */
function getStorageLayout(contractName: string, globals: Record<string, AbiNamedValue[]>) {
  // Aztec.nr reserves the `storage` tag for the layouts its macros generate, all named `STORAGE_LAYOUT_<contract>`.
  // Noir happily compiles `#[abi(storage)]` on a user global, so reject it here: it is read below as a malformed
  // layout, and codegen drops the whole tag when building the contract class.
  const reserved = globals.storage?.find(entry => !entry.name.startsWith(STORAGE_LAYOUT_GLOBAL_PREFIX));
  if (reserved) {
    throw new Error(
      `Global '${reserved.name}' is exported under the reserved #[abi(storage)] tag. Aztec.nr reserves that tag for ` +
        `the storage layout generated by the #[storage] macro; export the global under a different tag.`,
    );
  }

  // If another contract is imported by the main contract, its storage layout its going to also show up here.
  // The layout export includes the contract name, so here we can find the one that belongs to the current one and
  // ignore the rest.
  const storageExports = globals.storage?.map(entry => entry.value) ?? [];
  const layoutCandidates = storageExports.filter((storageExport): storageExport is StructValue => {
    if (storageExport.kind !== 'struct') {
      return false;
    }
    const contractNameField = storageExport.fields.find(field => field.name === 'contract_name')?.value;
    return contractNameField?.kind === 'string' && contractNameField.value === contractName;
  });
  // Contract names carry no crate identity, so a dependency contract sharing this contract's unqualified name
  // exports an indistinguishable layout. Bail out rather than silently picking one of the two.
  if (layoutCandidates.length > 1) {
    throw new Error(
      `Ambiguous storage layout: ${layoutCandidates.length} #[abi(storage)] globals declare contract_name ` +
        `'${contractName}'. Rename this contract or the same-named contract it imports.`,
    );
  }
  const storageForContract = layoutCandidates[0];
  const storageFields = storageForContract
    ? ((storageForContract.fields.find(field => field.name == 'fields') as TypedStructFieldValue<StructValue>).value
        .fields as TypedStructFieldValue<StructValue>[])
    : [];

  if (storageFields.length === 0) {
    return {};
  }

  // Built with `fromEntries` rather than by assignment: `acc[name] = ...` goes through the `__proto__` setter,
  // so a field by that name would replace the layout's prototype instead of becoming an own property.
  const entries = storageFields.map(field => {
    const slot = field.value.fields[0].value as IntegerValue;
    return [field.name, { slot: `0x${slot.value}` }] as const;
  });
  return Object.fromEntries(entries) as Record<string, Omit<FieldLayout, 'slot'> & { slot: string }>;
}

/**
 * Returns the globals exported by the contract under an `#[abi(tag)]` attribute, keyed by global name.
 * An unknown tag yields an empty record. Throws if two globals under the same tag share a name.
 */
export function getGlobalsByTag(artifact: ContractArtifact, tag: string): Record<string, AbiValue> {
  const globals = new Map<string, AbiValue>();
  // Read with an own-property check: a plain object inherits `toString`, `constructor`, etc. from
  // `Object.prototype`, so for those absent tags a bare `globals[tag]` returns an inherited function instead of
  // `undefined` and the `?? []` fallback never fires.
  const tagged = Object.hasOwn(artifact.outputs.globals, tag) ? artifact.outputs.globals[tag] : [];
  for (const entry of tagged) {
    // Artifacts compiled before globals carried names hold bare values here. They are admitted unvalidated through
    // the processed-artifact path of `loadContractArtifact`, so report the actual problem instead of returning a
    // record keyed by the string 'undefined'.
    if (typeof entry.name !== 'string') {
      throw new Error(
        `Globals under #[abi(${tag})] in contract ${artifact.name} have no names: the artifact predates named ` +
          `globals and must be recompiled with the current toolchain.`,
      );
    }
    if (globals.has(entry.name)) {
      throw new Error(`Duplicate global '${entry.name}' exported under #[abi(${tag})] in contract ${artifact.name}`);
    }
    globals.set(entry.name, entry.value);
  }
  return Object.fromEntries(globals);
}

/**
 * Given a post-processed Nargo output defined as `contract` generates an Aztec-compatible contract artifact.
 *
 * Does not include public bytecode, apart from the public_dispatch function.
 */
function generateContractArtifact(contract: NoirCompiledContract): ContractArtifact {
  try {
    if (!contract.transpiled) {
      throw new Error("Contract's public bytecode has not been transpiled");
    }
    return ContractArtifactSchema.parse({
      name: contract.name,
      aztecVersion: contract.aztec_version,
      functions: contract.functions.filter(f => retainBytecode(f)).map(f => generateFunctionArtifact(f, contract)),
      nonDispatchPublicFunctions: contract.functions
        .filter(f => !retainBytecode(f))
        .map(f => generateFunctionAbi(f, contract)),
      outputs: contract.outputs,
      storageLayout: getStorageLayout(contract.name, contract.outputs.globals),
      fileMap: contract.file_map,
    });
  } catch (err) {
    throw new Error(`Could not generate contract artifact for ${contract.name}: ${err}`);
  }
}

/**
 * Given a post-processed Nargo output defined as `contract` generates an Aztec-compatible contract artifact.
 *
 * Retains all public bytecode.
 */
function generateContractArtifactForPublic(contract: NoirCompiledContract): ContractArtifact {
  try {
    return ContractArtifactSchema.parse({
      name: contract.name,
      aztecVersion: contract.aztec_version,
      functions: contract.functions.map(f => generateFunctionArtifact(f, contract)),
      nonDispatchPublicFunctions: contract.functions
        .filter(f => !retainBytecode(f))
        .map(f => generateFunctionAbi(f, contract)),
      outputs: contract.outputs,
      storageLayout: getStorageLayout(contract.name, contract.outputs.globals),
      fileMap: contract.file_map,
    });
  } catch (err) {
    throw new Error(`Could not generate contract artifact for ${contract.name}: ${err}`);
  }
}
