FROM aztecprotocol/yarn-project-base
RUN yarn prepare:check && yarn formatting && yarn test

# Avoid pushing some huge container back to ecr.
FROM scratch
COPY --from=builder /usr/src/yarn-project/README.md /usr/src/yarn-project/README.md