# Runs all our typescript package non-e2e tests.
FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/noir-contracts-build as noir
FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/yarn-project-base

# Copy in the entire workspace.
COPY . .

RUN yarn test
