VERSION 0.8

bootstrap:
    FROM ../+bootstrap
    WORKDIR /usr/src/yarn-project

cli-wallet-build:
    FROM +bootstrap
    RUN yarn workspaces focus @aztec/cli-wallet --production && yarn cache clean
    SAVE ARTIFACT /usr/src /usr/src

cli-wallet:
    FROM ubuntu:noble
    RUN apt update && apt install nodejs curl socat -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    COPY +cli-wallet-build/usr/src /usr/src
    ENTRYPOINT ["/usr/src/yarn-project/cli-wallet/wallet-entrypoint.sh"]

# TODO(ci3) move to bootstrap.sh
export-cli-wallet:
    FROM +cli-wallet
    ARG DIST_TAG="latest"
    ARG ARCH
    SAVE IMAGE --push aztecprotocol/cli-wallet:${DIST_TAG}${ARCH:+-$ARCH}

anvil:
    FROM ../build-images+from-registry
    SAVE ARTIFACT /opt/foundry/bin/anvil

scripts-prod:
    FROM +bootstrap
    RUN yarn workspaces focus @aztec/scripts --production && yarn cache clean
    SAVE ARTIFACT /usr/src /usr/src

format-check:
    FROM +bootstrap
    RUN yarn formatting

test:
    FROM +bootstrap
    RUN yarn test
    # TODO move into build image
    ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    RUN cd ivc-integration && npx playwright install && npx playwright install-deps

run-e2e:
    ARG test
    ARG log_level=""
    ARG debug=""
    FROM +bootstrap
    RUN DEBUG=$debug yarn test $test

prover-client-test:
    FROM +bootstrap
    ARG test
    ARG log_level=""
    RUN cd prover-client && LOG_LEVEL=$log_level yarn test $test

publish-npm:
    FROM +bootstrap
    ARG DIST_TAG="latest"
    ARG VERSION
    ARG DRY_RUN=0
    RUN --secret NPM_TOKEN ./publish_npm.sh $DIST_TAG $VERSION $DRY_RUN
