VERSION 0.8
# Building requires foundry.
FROM ghcr.io/foundry-rs/foundry:nightly-4a643801d0b3855934cdec778e33e79c79971783
RUN apk update && apk add git jq bash nodejs npm yarn python3 py3-pip && pip3 install slither-analyzer==0.10.0 slitherin==0.5.0
WORKDIR /build
COPY --keep-ts --dir lib scripts src terraform test *.json *.toml *.sh .

build:
    RUN git init
    RUN forge clean && forge fmt --check && forge build && forge test
    RUN yarn && yarn lint
    RUN git add . && yarn slither && yarn slither-has-diff
    RUN forge build
    SAVE ARTIFACT out build