VERSION 0.8

lint:
    FROM ../+bootstrap
    WORKDIR /usr/src/l1-contracts
    RUN solhint --config ./.solhint.json "src/**/*.sol"
    RUN forge clean && forge fmt --check

test:
    FROM ../+bootstrap
    WORKDIR /usr/src/l1-contracts
    RUN USE_CACHE=1 ./bootstrap.sh test

publish-npm:
    FROM ../+bootstrap
    ARG VERSION
    ARG DIST_TAG
    ARG DRY_RUN=0
    WORKDIR /usr/src/l1-contracts
    RUN --secret NPM_TOKEN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    RUN jq --arg v $VERSION '.version = $v' package.json > _tmp.json && mv  _tmp.json package.json
    RUN if [ "$DRY_RUN" = "1" ]; then \
        npm publish --tag $DIST_TAG --access public --dry-run; \
    else \
        npm publish --tag $DIST_TAG --access public; \
    fi
