#!bin/bash
set -e

# To be called LOCALLY for testing WITHOUT docker.
#
# Contains core logic for collecting test coverage in the current environment.
#
# Run from circuits/cpp/
# Example:
# ./scripts/run_coverage glob
#
# Note: Assumes ignition SRS transcripts have already been downloaded

# TESTS:
# 1. names of test executables to run
#   - (like "aztec3_circuits_kernel_tests aztec3_circuits_abis_tests")
# 2. or "glob" (LOWERCASE) to run all built tests
# 3. or a file containing a list of test
TESTS=$1

# Set coverage build directory
BUILD_DIR="build-coverage"

# Perform coverage build
echo "Setting cmake to run with preset coverage"
cmake -Bbuild-coverage -DCMAKE_BUILD_TYPE=Debug -DUSE_TURBO=true --preset=coverage .

# if TESTS is GLOB or empty, run all built tests
# if TESTS is a file, assume it contains a list of tests to run
# otherwise assume TESTS itself is a list of tests to run
if [ "$TESTS" == "glob" ] || [ -z "$TESTS" ]; then
  echo "    No test file specified. Building all test files."
  TESTS=$(cat ./scripts/a3-tests)
elif [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

cd $BUILD_DIR
for BIN in $TESTS; do
  echo "*** Building $BIN ***"
  cmake --build . --target $BIN
done

echo "Testing $BIN"
echo "*** Collecting Profiling Information ***"
ctest || true

echo "*** Generating Coverage Reports ***"
cmake --build . --target create_full_coverage_report

echo *** Generating VScode line coverage data ***
for BIN in $TESTS; do
  echo "Generating line coverage data for $BIN"
  rm .lcov.info || true
  llvm-cov-15 export ./bin/$BIN  --format=lcov -instr-profile="./merged_profdata/default.profdata" > lcov.info
done

