[package]
name = "map_reduce_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
field_note = { path = "../../../../aztec-nr/field-note" }
bb_proof_verification = { path = "../../../../../barretenberg/noir/bb_proof_verification" }
