[package]
name = "boxreact"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../../noir-projects/labs/aztec-nr/aztec" }
field_note = { path = "../../../../../noir-projects/labs/aztec-nr/field-note" }
