#include "barretenberg/bbapi/bbapi_schema.hpp"

#include "barretenberg/bbapi/generated/bb_types.hpp"
#include "barretenberg/common/named_union.hpp"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl/schema_impl.hpp"

namespace bb::bbapi {
namespace {

using Command = bb::NamedUnion<wire::AvmProve,
                               wire::AvmVerify,
                               wire::AvmCheckCircuit,
                               wire::CircuitProve,
                               wire::CircuitComputeVk,
                               wire::CircuitStats,
                               wire::CircuitVerify,
                               wire::ChonkComputeVk,
                               wire::ChonkStart,
                               wire::ChonkLoad,
                               wire::ChonkAccumulate,
                               wire::ChonkProve,
                               wire::ChonkVerify,
                               wire::ChonkVerifyFromFields,
                               wire::ChonkBatchVerify,
                               wire::VkAsFields,
                               wire::MegaVkAsFields,
                               wire::CircuitWriteSolidityVerifier,
                               wire::ChonkCheckPrecomputedVk,
                               wire::ChonkStats,
                               wire::ChonkCompressProof,
                               wire::ChonkDecompressProof,
                               wire::Poseidon2Hash,
                               wire::Poseidon2Permutation,
                               wire::PedersenCommit,
                               wire::PedersenHash,
                               wire::PedersenHashBuffer,
                               wire::Blake2s,
                               wire::Blake2sToField,
                               wire::AesEncrypt,
                               wire::AesDecrypt,
                               wire::GrumpkinMul,
                               wire::GrumpkinAdd,
                               wire::GrumpkinBatchMul,
                               wire::GrumpkinGetRandomFr,
                               wire::GrumpkinReduce512,
                               wire::Secp256k1Mul,
                               wire::Secp256k1GetRandomFr,
                               wire::Secp256k1Reduce512,
                               wire::Bn254FrSqrt,
                               wire::Bn254FqSqrt,
                               wire::Bn254G1Mul,
                               wire::Bn254G2Mul,
                               wire::Bn254G1IsOnCurve,
                               wire::Bn254G1FromCompressed,
                               wire::SchnorrComputePublicKey,
                               wire::SchnorrConstructSignature,
                               wire::SchnorrVerifySignature,
                               wire::EcdsaSecp256k1ComputePublicKey,
                               wire::EcdsaSecp256r1ComputePublicKey,
                               wire::EcdsaSecp256k1ConstructSignature,
                               wire::EcdsaSecp256r1ConstructSignature,
                               wire::EcdsaSecp256k1RecoverPublicKey,
                               wire::EcdsaSecp256r1RecoverPublicKey,
                               wire::EcdsaSecp256k1VerifySignature,
                               wire::EcdsaSecp256r1VerifySignature,
                               wire::SrsInitSrs,
                               wire::ChonkBatchVerifierStart,
                               wire::ChonkBatchVerifierQueue,
                               wire::ChonkBatchVerifierStop,
                               wire::SrsInitGrumpkinSrs>;

using Response = bb::NamedUnion<wire::ErrorResponse,
                                wire::AvmProveResponse,
                                wire::AvmVerifyResponse,
                                wire::AvmCheckCircuitResponse,
                                wire::CircuitProveResponse,
                                wire::CircuitComputeVkResponse,
                                wire::CircuitInfoResponse,
                                wire::CircuitVerifyResponse,
                                wire::ChonkComputeVkResponse,
                                wire::ChonkStartResponse,
                                wire::ChonkLoadResponse,
                                wire::ChonkAccumulateResponse,
                                wire::ChonkProveResponse,
                                wire::ChonkVerifyResponse,
                                wire::ChonkVerifyFromFieldsResponse,
                                wire::ChonkBatchVerifyResponse,
                                wire::VkAsFieldsResponse,
                                wire::MegaVkAsFieldsResponse,
                                wire::CircuitWriteSolidityVerifierResponse,
                                wire::ChonkCheckPrecomputedVkResponse,
                                wire::ChonkStatsResponse,
                                wire::ChonkCompressProofResponse,
                                wire::ChonkDecompressProofResponse,
                                wire::Poseidon2HashResponse,
                                wire::Poseidon2PermutationResponse,
                                wire::PedersenCommitResponse,
                                wire::PedersenHashResponse,
                                wire::PedersenHashBufferResponse,
                                wire::Blake2sResponse,
                                wire::Blake2sToFieldResponse,
                                wire::AesEncryptResponse,
                                wire::AesDecryptResponse,
                                wire::GrumpkinMulResponse,
                                wire::GrumpkinAddResponse,
                                wire::GrumpkinBatchMulResponse,
                                wire::GrumpkinGetRandomFrResponse,
                                wire::GrumpkinReduce512Response,
                                wire::Secp256k1MulResponse,
                                wire::Secp256k1GetRandomFrResponse,
                                wire::Secp256k1Reduce512Response,
                                wire::Bn254FrSqrtResponse,
                                wire::Bn254FqSqrtResponse,
                                wire::Bn254G1MulResponse,
                                wire::Bn254G2MulResponse,
                                wire::Bn254G1IsOnCurveResponse,
                                wire::Bn254G1FromCompressedResponse,
                                wire::SchnorrComputePublicKeyResponse,
                                wire::SchnorrConstructSignatureResponse,
                                wire::SchnorrVerifySignatureResponse,
                                wire::EcdsaSecp256k1ComputePublicKeyResponse,
                                wire::EcdsaSecp256r1ComputePublicKeyResponse,
                                wire::EcdsaSecp256k1ConstructSignatureResponse,
                                wire::EcdsaSecp256r1ConstructSignatureResponse,
                                wire::EcdsaSecp256k1RecoverPublicKeyResponse,
                                wire::EcdsaSecp256r1RecoverPublicKeyResponse,
                                wire::EcdsaSecp256k1VerifySignatureResponse,
                                wire::EcdsaSecp256r1VerifySignatureResponse,
                                wire::SrsInitSrsResponse,
                                wire::ChonkBatchVerifierStartResponse,
                                wire::ChonkBatchVerifierQueueResponse,
                                wire::ChonkBatchVerifierStopResponse,
                                wire::SrsInitGrumpkinSrsResponse>;

struct ApiSchema {
    Command commands;
    Response responses;
    SERIALIZATION_FIELDS(commands, responses);
};

} // namespace

std::string get_bb_schema_as_json()
{
    return msgpack_schema_to_string(ApiSchema{});
}

} // namespace bb::bbapi
