########################################################################################################################
# A minimal ubuntu setup. Used for testing releases.
FROM ubuntu:noble
RUN apt update && apt install -y \
      curl \
      git \
      build-essential \
      python3 \
      netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
