FROM rust:alpine3.17
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        build-base \
        pkgconfig \
        openssl-dev \
        npm \
        yarn \
        bash \
        jq
WORKDIR /usr/src/noir
COPY scripts/install_wasm-bindgen.sh scripts/install_wasm-bindgen.sh
RUN ./scripts/install_wasm-bindgen.sh
COPY . .
RUN ./scripts/bootstrap_packages.sh