FROM aztecprotocol/barretenberg-x86_64-linux-clang-assert as bb

FROM rust:bullseye
COPY --from=bb /usr/src/barretenberg/cpp/build /usr/src/barretenberg/cpp/build

ARG COMMIT_HASH
ENV COMMIT_HASH=${COMMIT_HASH}
ENV NARGO_BACKEND_PATH=/usr/src/barretenberg/cpp/build/bin/bb
RUN apt update && apt install -y libc++1
WORKDIR /usr/src/noir
COPY . .
RUN ./scripts/test_native.sh

# Don't waste time pushing a huge container back to ECR as nothing needs the output.
FROM scratch
COPY --from=0 /usr/src/noir/README.md /usr/src/noir/README.md