VERSION 0.8
examples:
  FROM ../+bootstrap-noir-bb
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  ENV BACKEND=/usr/src/barretenberg/cpp/build/bin/bb

  WORKDIR /usr/src/noir/noir-repo/examples/codegen_verifier
  RUN ./test.sh

  WORKDIR /usr/src/noir/noir-repo/examples/prove_and_verify
  RUN ./test.sh

  WORKDIR /usr/src/noir/noir-repo/examples/recursion
  RUN ./test.sh
