#!/bin/bash
# Use the minio script base. We ensure minio is running and wipe it.
source $(git rev-parse --show-toplevel)/ci3/cache/test_source
export CI=1
export USE_CACHE=1
# should not exist
! $ci3/cache/download cache-artifact.tar.gz
touch cache-artifact
$ci3/cache/upload cache-artifact.tar.gz cache-artifact
# should not exist
$ci3/cache/download cache-artifact.tar.gz