#!/bin/bash
# Runs tests on each module in parallel, in a tmux split
# Use ci3 script base.
source $(git rev-parse --show-toplevel)/ci3/base/source
export USE_CACHE=1
export TEST=1
$ci3/tmux/split ci3-test-all ./avm-transpiler/bootstrap.sh ./barretenberg/bootstrap.sh ./boxes/bootstrap.sh ./l1-contracts/bootstrap.sh ./noir/bootstrap.sh ./noir-projects/bootstrap.sh ./yarn-packages/bootstrap.sh