FROM ubuntu:lunar AS builder
RUN apt-get update && apt-get install -y build-essential git cmake ninja-build curl
WORKDIR /usr/src/barretenberg/cpp
COPY ./scripts/install-wasi-sdk.sh ./scripts/install-wasi-sdk.sh
RUN ./scripts/install-wasi-sdk.sh
COPY . .
# TODO(https://github.com/AztecProtocol/barretenberg/issues/865) reconsider single-threaded barretenberg
RUN cmake --preset wasm-threads && cmake --build --preset wasm-threads --target goblin_ultra_honk_bench --target ultra_honk_bench --target ivc_bench --target barretenberg.wasm
RUN ./scripts/strip-wasm.sh

FROM ubuntu:lunar
WORKDIR /usr/src/barretenberg/cpp
COPY --from=builder /usr/src/barretenberg/cpp/srs_db /usr/src/barretenberg/cpp/srs_db
# copy to build/ for bench.sh compatibility
COPY --from=builder /usr/src/barretenberg/cpp/scripts/ci /usr/src/barretenberg/cpp/scripts/ci
COPY --from=builder /usr/src/barretenberg/cpp/build-wasm-threads /usr/src/barretenberg/cpp/build
# TODO(https://github.com/AztecProtocol/barretenberg/issues/865) reconsider single-threaded barretenberg
COPY --from=builder /usr/src/barretenberg/cpp/build-wasm-threads/bin/barretenberg.wasm /usr/src/barretenberg/cpp/build-wasm/bin/barretenberg.wasm
COPY --from=builder /usr/src/barretenberg/cpp/build-wasm-threads/bin/barretenberg.wasm /usr/src/barretenberg/cpp/build-wasm-threads/bin/barretenberg.wasm
