FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/barretenberg-wasm-build
WORKDIR /usr/src/barretenberg/cpp
RUN apt-get update && apt-get install -y curl tar xz-utils
RUN curl https://wasmtime.dev/install.sh -sSf | bash
RUN ./scripts/ci/bench_wasm.sh