[package]
name = "simulated_ecdsa_account_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
ecdsa_public_key_note = { path = "../../libs/ecdsa_public_key_note" }
