{
 "title": "Metrics stack",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "OpenTelemetry Collector version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "target_info{job=\"otel-collector\"}",
     "legendFormat": "{{service_version}}"
    }
   ]
  },
  {
   "title": "Prometheus total time series",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aztec targets across all deployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(target_info{service_name!~\"otelcol-contrib|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "New series by job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(scrape_series_added[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples scraped by job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(scrape_samples_scraped[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed scrapes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pools_failed_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Aztec metrics by cardinality",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, count by(__name__) ({job=\"aztec\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aztec targets across all deployments",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sort_desc(count by(service_name) (target_info{service_name!~\"otelcol-contrib|\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenTelemetry collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted data points",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "label_replace(rate(otelcol_receiver_accepted_metric_points[$__rate_interval]), \"_type\", \"metric\", \"\", \"\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(rate(otelcol_receiver_accepted_spans[$__rate_interval]), \"_type\", \"span\", \"\", \"\")",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Refused data points",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "label_replace(rate(otelcol_receiver_refused_metric_points[$__rate_interval]), \"_type\", \"metric\", \"\", \"\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(rate(otelcol_receiver_refused_spans[$__rate_interval]), \"_type\", \"span\", \"\", \"\")",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Batch sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(otelcol_processor_batch_batch_send_size_bucket[$__rate_interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filtered data points",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "rate(otelcol_processor_filter_datapoints_filtered[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent data points",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "label_replace(rate(otelcol_exporter_sent_metric_points[$__rate_interval]), \"_type\", \"metric\", \"\", \"\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(rate(otelcol_exporter_sent_spans[$__rate_interval]), \"_type\", \"span\", \"\", \"\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "label_replace(rate(otelcol_exporter_send_failed_metric_points[$__rate_interval]), \"_type\", \"metric\", \"\", \"\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(rate(otelcol_exporter_send_failed_spans[$__rate_interval]), \"_type\", \"span\", \"\", \"\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}