{
 "title": "Network overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Service namespace",
    "query": {
     "query": "label_values(target_info,k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Services",
   "type": "stat",
   "description": "Count of services running in the selected namespace",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (exported_job) (target_info{k8s_namespace_name=~\"$namespace\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_l1_block_height{k8s_namespace_name=\"$namespace\"}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 sender balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Ξ" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name,aztec_address_sender) (aztec_l1_publisher_balance_eth{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by(service_name) (sum without(process_cpu_state) (process_cpu_utilization{service_namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory use",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(service_name) (process_memory_usage{service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database Used Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (aztec_db_type) (aztec_db_used_size_bytes{k8s_namespace_name=~\"$namespace\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (avg by (aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_used_size{service_namespace=\"$namespace\"}))",
       "legendFormat": "world-state"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aztec_node_receive_tx_count{service_namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total received txs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"true\", service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total rejected txs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aztec_node_receive_tx_count{aztec_ok=\"false\", service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tx mempool status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(aztec_status) (aztec_mempool_tx_count{service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "World state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Approx tree size on disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (aztec_merkle_tree_name) (avg by (aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_used_size{service_namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relative tree sizes",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 10, "x": 14, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(aztec_merkle_tree_name) (aztec_world_state_tree_size{service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tree size",
     "type": "timeseries",
     "description": "Tracks tree nodes, indexes, metadata",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (aztec_merkle_tree_name) (avg by(aztec_merkle_tree_name, aztec_world_state_db_type) (aztec_world_state_db_num_items{service_namespace=\"$namespace\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Archiver status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block height",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "avg by(service_name, aztec_status) (label_replace(aztec_archiver_block_height{service_namespace=\"$namespace\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks synched from rollup",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(service_name) (aztec_archiver_l1_blocks_synced{service_namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Archiver Sync Duration (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(service_name) ((rate(aztec_archiver_sync_duration_milliseconds_sum{k8s_namespace_name=~\"$namespace\"}[$__rate_interval])) / (rate(aztec_archiver_sync_duration_milliseconds_count{k8s_namespace_name=~\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}