{
 "title": "Prover Node Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info,k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prover Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Jobs Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_proving_queue_enqueued_jobs_count{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "Total Jobs"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_proving_queue_resolved_jobs_count{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "Completed Jobs"
    }
   ]
  },
  {
   "title": "Current Queue Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_proving_queue_size{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "Current Queue Size"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aztec_proving_queue_active_jobs_count{k8s_namespace_name=\"$namespace\"})",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_block_height{k8s_namespace_name=\"$namespace\",exported_job=~\".*prover-node.*\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_l1_block_height{k8s_namespace_name=\"$namespace\",exported_job=~\".*prover-node.*\"}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Processed Rate by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(aztec_proving_queue_enqueued_jobs_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_proving_job_type)",
     "legendFormat": "{{aztec_proving_job_type}}"
    }
   ]
  },
  {
   "title": "L1 sender balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Ξ" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name,aztec_address_sender) (aztec_l1_publisher_balance_eth{k8s_namespace_name=\"$namespace\",exported_job=~\".*prover-node.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_memory_usage{k8s_namespace_name=\"$namespace\", exported_job=~\".*prover.*\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(process_cpu_utilization{k8s_namespace_name=\"$namespace\", exported_job=~\".*prover.*\",process_cpu_state=\"user\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Prover Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prover Node Execution Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_prover_node_execution_duration_milliseconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) / sum(rate(aztec_prover_node_execution_duration_milliseconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prover Node Job Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(aztec_prover_node_job_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(aztec_prover_node_job_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(aztec_prover_node_job_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Blocks per epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_prover_node_job_blocks_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) / sum(rate(aztec_prover_node_job_blocks_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transactions per epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_prover_node_job_transactions_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))/sum(rate(aztec_prover_node_job_transactions_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Base Rollup Inputs Preparation Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) / sum(rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Prover Broker & Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Size by Job Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(aztec_proving_queue_size{k8s_namespace_name=\"$namespace\"}) by (aztec_proving_job_type)",
       "legendFormat": "{{aztec_proving_job_type}}"
      }
     ]
    },
    {
     "title": "Active Jobs by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(aztec_proving_queue_active_jobs_count{k8s_namespace_name=\"$namespace\"}) by (aztec_proving_job_type)",
       "legendFormat": "{{aztec_proving_job_type}}"
      }
     ]
    },
    {
     "title": "AVG Job Wait Time by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (aztec_proving_job_type) (rate(aztec_proving_queue_job_wait_milliseconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) / sum by (aztec_proving_job_type) (rate(aztec_proving_queue_job_wait_milliseconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Jobs Rate by Type",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aztec_proving_queue_rejected_jobs_count{k8s_namespace_name=\"$namespace\"}[5m])) by (aztec_proving_job_type)",
       "legendFormat": "{{aztec_proving_job_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prover Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG Job Processing Duration by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_proving_queue_job_duration_milliseconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_proving_job_type) / sum(rate(aztec_proving_queue_job_duration_milliseconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_proving_job_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Agent Idle Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(aztec_proving_queue_agent_idle_milliseconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (k8s_pod_name) /sum(rate(aztec_proving_queue_agent_idle_milliseconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage by Service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_memory_usage{k8s_namespace_name=\"$namespace\", exported_job=~\".*prover.*\"}) by (k8s_pod_name)",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG Witness Generation Time by Protocol Circuit",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aztec_circuit_witness_generation_duration_seconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_circuit_protocol_circuit_name) / sum(rate(aztec_circuit_witness_generation_duration_seconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_circuit_protocol_circuit_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVG Proving Time by Protocol Circuit",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aztec_circuit_proving_duration_seconds_sum{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_circuit_protocol_circuit_name) / sum(rate(aztec_circuit_proving_duration_seconds_count{k8s_namespace_name=\"$namespace\"}[$__rate_interval])) by (aztec_circuit_protocol_circuit_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AVM Proving Time by App Circuit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (aztec_circuit_app_circuit_name) (rate(aztec_circuit_proving_duration_seconds_sum{k8s_namespace_name=\"$namespace\",aztec_circuit_app_circuit_name!=\"\"}[$__rate_interval])) / sum by (aztec_circuit_app_circuit_name) (rate(aztec_circuit_proving_duration_seconds_count{k8s_namespace_name=\"$namespace\",aztec_circuit_app_circuit_name!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Circuit Sizes",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (aztec_circuit_protocol_circuit_name) (aztec_circuit_size{k8s_namespace_name=\"$namespace\",aztec_circuit_protocol_circuit_name!=\"\"})",
       "legendFormat": "{{aztec_circuit_protocol_circuit_name}}"
      }
     ]
    }
   ]
  }
 ]
}