{
 "title": "Validator node overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info,k8s_namespace_name)"
    }
   },
   {
    "name": "service_instance",
    "label": "Sequencer Instance",
    "query": {
     "query": "label_values(target_info{k8s_namespace_name=\"$namespace\", exported_job=~\".*validator.*\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview & Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aztec version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{k8s_namespace_name=\"$namespace\",exported_job=~\".*validator.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(exported_instance) (target_info{k8s_namespace_name=\"$namespace\", exported_job=~\".*validator.*\"}))"
    }
   ]
  },
  {
   "title": "Blocks builder breakdown",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aztec_sequencer_block_count{service_instance_id=~\"$service_instance\",aztec_status=\"built\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "L1 sender balance",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Ξ" } },
   "targets": [
    {
     "expr": "avg by (k8s_pod_name,aztec_address_sender) (aztec_l1_publisher_balance_eth{service_instance_id=~\"$service_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Block Heights",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_block_height{service_instance_id=~\"$service_instance\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (aztec_status) (label_replace(aztec_archiver_l1_block_height{service_instance_id=~\"$service_instance\"}, \"aztec_status\", \"l1\", \"aztec_status\", \"^$\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(aztec_archiver_block_height{service_instance_id=~\"$service_instance\", aztec_status=\"\"}) - avg(aztec_archiver_block_height{service_instance_id=~\"$service_instance\", aztec_status=\"proven\"})",
     "legendFormat": "Pending chain depth"
    }
   ]
  },
  {
   "title": "Block Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "delta(aztec_sequencer_block_count{k8s_namespace_name=\"$namespace\", aztec_status=\"built\"}[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Block Production Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Block Build Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(aztec_sequencer_block_build_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Build Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_sequencer_block_build_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(aztec_sequencer_block_build_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aztec_sequencer_block_build_duration_milliseconds_bucket{k8s_namespace_name=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Mana Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mana/s" } },
   "targets": [
    {
     "expr": "aztec_sequencer_block_build_mana_per_second{k8s_namespace_name=\"$namespace\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Transactions per Block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "targets": [
    {
     "expr": "avg (aztec_sequencer_current_block_size{service_instance_id=~\"$service_instance\", aztec_status=\"built\"})",
     "legendFormat": "Avg txs per block"
    }
   ]
  },
  {
   "title": "Time to Collect Attestations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aztec_sequencer_time_to_collect_attestations{k8s_namespace_name=\"$namespace\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "State Machine Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Tree Insertion Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aztec_sequencer_block_builder_tree_insertion_duration_microseconds_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_sequencer_block_builder_tree_insertion_duration_microseconds_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "World State Tree Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "avg (aztec_world_state_tree_size{service_instance_id=~\"$service_instance\"}) by (aztec_merkle_tree_name)",
     "legendFormat": "{{aztec_merkle_tree_name}}"
    }
   ]
  },
  { "title": "Sequencer Components Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Node Transaction Processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "targets": [
    {
     "expr": "rate(aztec_node_receive_tx_count{service_instance_id=~\"$service_instance\", aztec_ok=\"true\"}[5m])",
     "legendFormat": "Valid Txs"
    },
    {
     "expr": "rate(aztec_node_receive_tx_count{service_instance_id=~\"$service_instance\", aztec_ok=\"false\"}[5m])",
     "legendFormat": "Failed Txs"
    }
   ]
  },
  {
   "title": "Transaction Validation Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aztec_node_receive_tx_duration_milliseconds_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le, aztec_ok))",
     "legendFormat": "{{aztec_ok}}"
    }
   ]
  },
  {
   "title": "Archiver Block Heights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "avg by(aztec_status) (label_replace(aztec_archiver_block_height{service_instance_id=~\"$service_instance\"}, \"aztec_status\", \"pending\", \"aztec_status\", \"^$\"))  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archiver Sync Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(aztec_archiver_sync_duration_milliseconds_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_archiver_sync_duration_milliseconds_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "L1 Publisher Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "targets": [
    {
     "expr": "sum by (aztec_l1_tx_type) (increase (aztec_l1_publisher_tx_count{service_instance_id=~\"$service_instance\", aztec_ok=\"true\"}[$__rate_interval]))",
     "legendFormat": "{{aztec_l1_tx_type}}"
    }
   ]
  },
  {
   "title": "L1 Publisher Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "gwei" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_l1_publisher_gas_price_gwei_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(aztec_l1_publisher_gas_price_gwei_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "L1 Publisher Blob Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "gwei" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(aztec_l1_publisher_tx_blobdata_gas_cost_gwei_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(aztec_l1_publisher_tx_blobdata_gas_cost_gwei_bucket{service_instance_id=~\"$service_instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Avg blob tx inclusion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "rate(aztec_l1_publisher_blob_inclusion_blocks_sum{service_instance_id=~\"$service_instance\"}[$__rate_interval])/rate(aztec_l1_publisher_blob_inclusion_blocks_count{service_instance_id=~\"$service_instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Utilization by Sequencer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(k8s_pod_name) (process_cpu_utilization{service_instance_id=~\"$service_instance\",process_cpu_state=\"user\"})",
     "legendFormat": "{{k8s_pod_name}} - {{process_cpu_state}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Sequencer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage{service_instance_id=~\"$service_instance\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Archiver Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(aztec_db_used_size_bytes{service_instance_id=~\"$service_instance\", aztec_db_type=\"archiver\"})",
     "legendFormat": "Used bytes"
    }
   ]
  },
  {
   "title": "Archiver Database Item Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "avg(aztec_db_num_items{service_instance_id=~\"$service_instance\", aztec_db_type=\"archiver\"})",
     "legendFormat": "Key-Value Pairs"
    }
   ]
  }
 ]
}