/**
 * @brief Generate avm_fixed_vk.hpp from precomputed columns.
 * @details Computes individual precomputed commitments, interleaved group commitments,
 *          and VK hash, then writes them as a C++ header file.
 *
 *          Usage: avm_vk_gen [output_path]
 *          Default output: writes to stdout.
 */
#include "barretenberg/commitment_schemes/commitment_key.hpp"
#include "barretenberg/srs/global_crs.hpp"
#include "barretenberg/vm2/constraining/flavor.hpp"
#include "barretenberg/vm2/constraining/polynomials.hpp"
#include "barretenberg/vm2/tracegen_helper.hpp"

#include <fstream>
#include <iostream>
#include <sstream>

using namespace bb;
using namespace bb::avm2;
using Flavor = AvmFlavor;
using FF = Flavor::FF;
using Commitment = Flavor::Commitment;

static std::string commitment_to_string(const Commitment& c, const std::string& label)
{
    std::ostringstream oss;
    if (c.is_point_at_infinity()) {
        oss << "            Commitment::infinity()";
    } else {
        oss << "            Commitment(\n";
        oss << "                uint256_t(\"" << uint256_t(c.x) << "\"),\n";
        oss << "                uint256_t(\"" << uint256_t(c.y) << "\"))";
    }
    oss << ", // " << label;
    return oss.str();
}

int main(int argc, char** argv)
{
    srs::init_file_crs_factory(srs::bb_crs_path());

    // Compute precomputed polynomials and commitments
    AvmTraceGenHelper tracegen_helper;
    auto trace = tracegen_helper.generate_precomputed_columns();
    auto polynomials = constraining::compute_polynomials(trace);
    auto proving_key = constraining::proving_key_from_polynomials(polynomials);

    auto precomputed = proving_key->get_precomputed();
    auto labels = Flavor::PrecomputedEntities<Commitment>().get_labels();

    // Compute individual commitments
    std::vector<Commitment> individual_comms;
    individual_comms.reserve(precomputed.size());
    for (auto& poly : precomputed) {
        individual_comms.push_back(proving_key->commitment_key.commit(poly));
    }

    // Compute group commitments
    constexpr size_t BS = Flavor::INTERLEAVING_BATCH_SIZE;
    std::vector<Commitment> group_comms;
    group_comms.reserve(Flavor::NUM_PRECOMPUTED_GROUPS);
    for (size_t g = 0; g < Flavor::NUM_PRECOMPUTED_GROUPS; g++) {
        size_t start = g * BS;
        size_t count = std::min(BS, precomputed.size() - start);
        std::vector<PolynomialSpan<const FF>> chunks;
        chunks.reserve(count);
        for (size_t j = 0; j < count; j++) {
            chunks.push_back(precomputed[start + j]);
        }
        group_comms.push_back(proving_key->commitment_key.commit_interleaved<BS>(chunks));
    }

    // Compute VK hash from individual commitments
    std::vector<FF> hash_elements;
    for (const auto& c : individual_comms) {
        auto frs = Flavor::Transcript::Codec::serialize_to_fields(c);
        for (const auto& fr : frs) {
            hash_elements.push_back(fr);
        }
    }
    FF vk_hash = Flavor::Transcript::HashFunction::hash(hash_elements);

    // Generate header
    std::ostringstream out;
    out << "#include \"barretenberg/ecc/curves/bn254/bn254.hpp\"\n";
    out << "#include \"barretenberg/vm2/generated/columns.hpp\"\n";
    out << "\n";
    out << "#pragma once\n";
    out << "\n";
    out << "// AUTO-GENERATED by avm_vk_gen. Do not edit manually.\n";
    out << "// Regenerate with: ./scripts/avm2_gen.sh (or AVM_BATCH_SIZE=N ./scripts/avm2_gen.sh)\n";
    out << "\n";
    out << "namespace bb::avm2::constraining {\n";
    out << "\n";
    out << "class AvmHardCodedVKAndHash {\n";
    out << "  public:\n";
    out << "    using Commitment = bb::curve::BN254::AffineElement;\n";
    out << "    using FF = bb::curve::BN254::ScalarField;\n";
    out << "\n";
    out << "    static FF vk_hash() { return FF(uint256_t(\"" << uint256_t(vk_hash) << "\")); }\n";
    out << "\n";
    out << "    static constexpr std::array<Commitment, NUM_PRECOMPUTED_ENTITIES> get_all()\n";
    out << "    {\n";
    out << "        return {\n";
    for (size_t i = 0; i < individual_comms.size(); i++) {
        out << commitment_to_string(individual_comms[i], labels[i]);
        if (i + 1 < individual_comms.size()) {
            out << "\n";
        }
    }
    out << "\n        };\n";
    out << "    }\n";
    out << "\n";
    out << "    static constexpr std::array<Commitment, NUM_PRECOMPUTED_GROUPS> get_precomputed_group_commitments()\n";
    out << "    {\n";
    out << "        return {\n";
    for (size_t g = 0; g < group_comms.size(); g++) {
        std::string label = "group_" + std::to_string(g);
        out << commitment_to_string(group_comms[g], label);
        if (g + 1 < group_comms.size()) {
            out << "\n";
        }
    }
    out << "\n        };\n";
    out << "    }\n";
    out << "};\n";
    out << "\n";
    out << "} // namespace bb::avm2::constraining\n";

    // Write to file or stdout
    if (argc > 1) {
        std::ofstream file(argv[1]);
        if (!file) {
            std::cerr << "Failed to open " << argv[1] << " for writing\n";
            return 1;
        }
        file << out.str();
        std::cerr << "Wrote " << argv[1] << "\n";
    } else {
        std::cout << out.str();
    }
    return 0;
}
