#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <gtest/gtest.h>

using namespace bb;

// Sanity checking for the SERIALIZATION_FIELDS completeness/overlap checks.
// The schema-reflection tests that used to live here went with the reflection
// itself; wire schemas are now declared in JSON and generated by ipc-codegen.

struct GoodExample {
    fr a;
    fr b;
    SERIALIZATION_FIELDS(a, b);
} good_example;

struct BadExampleOverlap {
    fr a;
    fr b;
    SERIALIZATION_FIELDS(a, a);
} bad_example_overlap;

struct BadExampleIncomplete {
    fr a;
    fr b;
    SERIALIZATION_FIELDS(a);
} bad_example_incomplete;

struct BadExampleCompileTimeError {
    std::vector<int> a;
    fr b;

    SERIALIZATION_FIELDS(b); // Type mismatch, expect 'a', will catch at compile-time
} bad_example_compile_time_error;

struct BadExampleOutOfObject {
    fr a;
    fr b;
    void msgpack(auto ar)
    {
        BadExampleOutOfObject other_object;
        ar("a", other_object.a, "b", other_object.b);
    }
} bad_example_out_of_object;

TEST(msgpack_tests, msgpack_sanity_sanity)
{
    EXPECT_EQ(msgpack::check_msgpack_method(good_example), "");
    EXPECT_EQ(msgpack::check_msgpack_method(bad_example_overlap),
              "Overlap in BadExampleOverlap SERIALIZATION_FIELDS() params detected!");
    EXPECT_EQ(msgpack::check_msgpack_method(bad_example_incomplete),
              "Incomplete BadExampleIncomplete SERIALIZATION_FIELDS() params! Not all of object specified.");

    // If we actually try to msgpack BadExampleCompileTimeError we will statically error
    // This is great, but we need to check the underlying facility *somehow*
    auto checker = [&](auto&... values) {
        std::string incomplete_msgpack_status = "error";
        if constexpr (msgpack_concepts::MsgpackConstructible<BadExampleCompileTimeError, decltype(values)...>) {
            incomplete_msgpack_status = "";
        }
        EXPECT_EQ(incomplete_msgpack_status, "error");
    };
    bad_example_compile_time_error.msgpack(checker);

    EXPECT_EQ(msgpack::check_msgpack_method(bad_example_out_of_object),
              "Some BadExampleOutOfObject SERIALIZATION_FIELDS() params don't exist in object!");
}
