/* eslint-disable */
// GENERATED FILE - DO NOT EDIT, RUN yarn remake-constants
function log2(input: number): number {
  return input < 2 ? 0 : 1 + log2(Math.floor(input / 2));
}
export const ARGS_LENGTH = 16;
export const RETURN_VALUES_LENGTH = 4;
export const READ_REQUESTS_LENGTH = 4;
export const MAX_NEW_COMMITMENTS_PER_CALL = 4;
export const MAX_NEW_NULLIFIERS_PER_CALL = 4;
export const MAX_PRIVATE_CALL_STACK_LENGTH_PER_CALL = 4;
export const MAX_PUBLIC_CALL_STACK_LENGTH_PER_CALL = 4;
export const MAX_NEW_L2_TO_L1_MSGS_PER_CALL = 2;
export const MAX_PUBLIC_DATA_UPDATE_REQUESTS_PER_CALL = 4;
export const MAX_PUBLIC_DATA_READS_PER_CALL = 4;
export const MAX_NEW_COMMITMENTS_PER_TX = MAX_PRIVATE_CALL_STACK_LENGTH_PER_CALL * MAX_NEW_COMMITMENTS_PER_CALL;
export const MAX_NEW_NULLIFIERS_PER_TX = MAX_PRIVATE_CALL_STACK_LENGTH_PER_CALL * MAX_NEW_NULLIFIERS_PER_CALL;
export const MAX_PRIVATE_CALL_STACK_LENGTH_PER_TX = 8;
export const MAX_PUBLIC_CALL_STACK_LENGTH_PER_TX = 8;
export const MAX_NEW_L2_TO_L1_MSGS_PER_TX = 2;
export const MAX_PUBLIC_DATA_UPDATE_REQUESTS_PER_TX = 4;
export const MAX_PUBLIC_DATA_READS_PER_TX = 4;
export const MAX_NEW_CONTRACTS_PER_TX = 1;
export const MAX_OPTIONALLY_REVEALED_DATA_LENGTH_PER_TX = 4;
export const NUM_ENCRYPTED_LOGS_HASHES_PER_TX = 1;
export const NUM_UNENCRYPTED_LOGS_HASHES_PER_TX = 1;
export const NUMBER_OF_L1_L2_MESSAGES_PER_ROLLUP = 16;
export const KERNELS_PER_ROLLUP = 2;
export const VK_TREE_HEIGHT = 3;
export const FUNCTION_TREE_HEIGHT = 4;
export const CONTRACT_TREE_HEIGHT = 8;
export const PRIVATE_DATA_TREE_HEIGHT = 16;
export const PUBLIC_DATA_TREE_HEIGHT = 254;
export const NULLIFIER_TREE_HEIGHT = 16;
export const L1_TO_L2_MSG_TREE_HEIGHT = 8;
export const PRIVATE_DATA_TREE_ROOTS_TREE_HEIGHT = 8;
export const CONTRACT_TREE_ROOTS_TREE_HEIGHT = 8;
export const L1_TO_L2_MSG_TREE_ROOTS_TREE_HEIGHT = 8;
export const ROLLUP_VK_TREE_HEIGHT = 8;
export const CONTRACT_SUBTREE_HEIGHT = 1;
export const CONTRACT_SUBTREE_SIBLING_PATH_LENGTH = CONTRACT_TREE_HEIGHT - CONTRACT_SUBTREE_HEIGHT;
export const PRIVATE_DATA_SUBTREE_HEIGHT = log2(KERNELS_PER_ROLLUP * MAX_NEW_COMMITMENTS_PER_TX);
export const PRIVATE_DATA_SUBTREE_SIBLING_PATH_LENGTH = PRIVATE_DATA_TREE_HEIGHT - PRIVATE_DATA_SUBTREE_HEIGHT;
export const NULLIFIER_SUBTREE_HEIGHT = log2(KERNELS_PER_ROLLUP * MAX_NEW_NULLIFIERS_PER_TX);
export const NULLIFIER_SUBTREE_SIBLING_PATH_LENGTH = NULLIFIER_TREE_HEIGHT - NULLIFIER_SUBTREE_HEIGHT;
export const L1_TO_L2_MSG_SUBTREE_HEIGHT = log2(NUMBER_OF_L1_L2_MESSAGES_PER_ROLLUP);
export const L1_TO_L2_MSG_SUBTREE_SIBLING_PATH_LENGTH = L1_TO_L2_MSG_TREE_HEIGHT - L1_TO_L2_MSG_SUBTREE_HEIGHT;
export const FUNCTION_SELECTOR_NUM_BYTES = 4;
export const MAPPING_SLOT_PEDERSEN_SEPARATOR = 4;
export const NUM_FIELDS_PER_SHA256 = 2;
export enum GeneratorIndex {
  COMMITMENT = 1,
  COMMITMENT_PLACEHOLDER,
  OUTER_COMMITMENT,
  NULLIFIER_HASHED_PRIVATE_KEY,
  NULLIFIER,
  INITIALISATION_NULLIFIER,
  OUTER_NULLIFIER,
  PUBLIC_DATA_READ,
  PUBLIC_DATA_UPDATE_REQUEST,
  FUNCTION_DATA,
  FUNCTION_LEAF,
  CONTRACT_DEPLOYMENT_DATA,
  CONSTRUCTOR,
  CONSTRUCTOR_ARGS,
  CONTRACT_ADDRESS,
  CONTRACT_LEAF,
  CALL_CONTEXT,
  CALL_STACK_ITEM,
  CALL_STACK_ITEM_2,
  L1_TO_L2_MESSAGE_SECRET,
  L2_TO_L1_MSG,
  TX_CONTEXT,
  PUBLIC_LEAF_INDEX,
  PUBLIC_DATA_LEAF,
  SIGNED_TX_REQUEST,
  GLOBAL_VARIABLES,
  PARTIAL_CONTRACT_ADDRESS,
  TX_REQUEST = 33,
  VK = 41,
  PRIVATE_CIRCUIT_PUBLIC_INPUTS,
  PUBLIC_CIRCUIT_PUBLIC_INPUTS,
  FUNCTION_ARGS,
}
export enum StorageSlotGeneratorIndex {
  BASE_SLOT,
  MAPPING_SLOT,
  MAPPING_SLOT_PLACEHOLDER,
}
export enum PrivateStateNoteGeneratorIndex {
  VALUE = 1,
  OWNER,
  CREATOR,
  SALT,
  NONCE,
  MEMO,
  IS_DUMMY,
}
export enum PrivateStateType {
  PARTITIONED = 1,
  WHOLE,
}
