// Type mappings for working with cbind naming differences
export {
  PrivateKernelInputs,
  PrivateKernelPublicInputs,
  AffineElement,
  G1AffineElement,
  AggregationObject as NativeAggregationState,
  NewContractData,
  FunctionData,
  OptionallyRevealedData,
  AccumulatedData,
  HistoricTreeRoots,
  Proof,
  ContractDeploymentData,
  TxContext,
  Fq,
  Fr,
  AztecAddress as Address,
  ConstantData,
  VerificationKey as VerificationKeyData,
  PrivateKernelPublicInputs as PublicInputs,
  PreviousKernelData,
} from '../structs/index.js';
