{{- if not .Values.statefulSet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{ with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
{{ end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: node
  template:
    {{- include "chart.podTemplate" . | nindent 4 }}
{{- end }}
