{{- if and .Values.service.p2p.enabled .Values.service.p2p.nodePortEnabled -}}
{{- range $i, $e := until (.Values.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" $ }}-p2p-node-port-{{ $i }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app: node
    type: p2p
    pod-index: "{{ $i }}"
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ $.Values.service.p2p.port }}
      protocol: TCP
      targetPort: p2p-tcp
    - name: p2p-udp
      port: {{ $.Values.service.p2p.port }}
      protocol: UDP
      targetPort: p2p-udp
  selector:
    {{- include "chart.selectorLabels" $ | nindent 4 }}
    app: node
    statefulset.kubernetes.io/pod-name: "{{ include "chart.fullname" $ }}-{{ $i }}"
{{- end }}
{{- end }}
