#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
ARCH=${2:-$(uname -m)}
CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "$ECR_URL/$REPOSITORY:cache-$CONTENT_HASH-$ARCH"
