#!/usr/bin/env bash
set -euo pipefail
if [ -n $AWS_ACCESS_KEY_ID ] && [ -n $AWS_SECRET_ACCESS_KEY ]; then
  exit 0
elif [ -f ~/.aws/credentials ]; then
  echo "export AWS_ACCESS_KEY_ID=\$(aws configure get default.aws_access_key_id)" >> $BASH_ENV
  echo "export AWS_SECRET_ACCESS_KEY=\$(aws configure get default.aws_secret_access_key)" >> $BASH_ENV
  exit 0
else
  exit 1
fi
