#!/bin/bash
# Returns true if the file at path has changed since the CONTENT_HASH.
CONTENT_HASH=$1

[ -n "$COMMIT_HASH" ] || exit 1

if git diff --name-only $CONTENT_HASH $COMMIT_HASH | grep -q $2; then
  exit 0
else
  exit 1
fi
