#!/bin/bash
# Conditionally runs a script on a remote spot instance if any dependent code has changed between
# the last successful run and the present commit.
#
# It's expected to be run from the project directory, and that there be a directory called `scripts`
# containing the given named script to execute on the remote machine.
#
# This script is only useful if there is nothing to do in the event there is no rebuild. This is fine
# for running a suite of tests for example, but is not useful for performing a build, as even if a
# build has nothing to do, the previous images are retagged with the new commit hash for upstream jobs.
#
# Arguments are:
# 1. REPOSITORY: The project repository name in ECR. Used to determine if there are changes since last success.
# 2... ARGS: Script and arguments to run.
set -eu

REPOSITORY=$1
shift

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
BASE_TAG=cache-$CONTENT_HASH
SUCCESS_TAG=$BASE_TAG-$JOB_NAME

echo "Content hash: $CONTENT_HASH"

if ! check_rebuild $SUCCESS_TAG $REPOSITORY; then
  init_submodules $REPOSITORY
  cd $(query-manifest $REPOSITORY projectDir)
  $@
  retry tag_remote_image $REPOSITORY $BASE_TAG $SUCCESS_TAG
fi
