#!/usr/bin/env bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
SERVICES=${2:-$REPOSITORY}
TO_TAINT=${3:-}

cd $(query_manifest projectDir $REPOSITORY)

# Bail out if nothing changed.
CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "Last successfully deployed commit: $CONTENT_HASH"
if check_rebuild cache-$CONTENT_HASH-$DEPLOY_TAG-deployed $REPOSITORY; then
  echo "No changes detected, skipping deployment."
  exit 0
fi

deploy_terraform $REPOSITORY ./terraform/ "$TO_TAINT"

# Restart services.
for SERVICE in $SERVICES; do
  deploy_service $DEPLOY_TAG-$SERVICE
done

# Tag the image as deployed.
if [ "$DRY_DEPLOY" -eq 1 ]; then
  echo "DRY_DEPLOY: tag_remote_image $REPOSITORY cache-$CONTENT_HASH cache-$CONTENT_HASH-$DEPLOY_TAG-deployed"
else
  retry tag_remote_image $REPOSITORY cache-$CONTENT_HASH cache-$CONTENT_HASH-$DEPLOY_TAG-deployed
fi
