#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
# TODO: Why even provide this? We can just figure it out by probing.
ARCH_LIST=${2:-}

echo "Repo: $REPOSITORY"
echo "Arch List: $ARCH_LIST"

VERSION_TAG=$(extract_tag_version $REPOSITORY true)
MANIFEST_DEPLOY_URI=aztecprotocol/$REPOSITORY:$VERSION_TAG

# Login to dockerhub and ecr
dockerhub_login
ecr_login

IFS=','
for ARCH in $ARCH_LIST
do
  IMAGE_COMMIT_URI=$(calculate_image_uri $REPOSITORY $ARCH)
  retry docker pull $IMAGE_COMMIT_URI

  # Retag and push image.
  IMAGE_DEPLOY_URI=aztecprotocol/$REPOSITORY:$VERSION_TAG-$ARCH
  docker tag $IMAGE_COMMIT_URI $IMAGE_DEPLOY_URI
  docker_or_dryrun push $IMAGE_DEPLOY_URI

  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_DEPLOY_URI..."
  docker manifest create $MANIFEST_DEPLOY_URI --amend $IMAGE_DEPLOY_URI
done

docker tag $MANIFEST_DEPLOY_URI aztecprotocol/$REPOSITORY:latest
docker_or_dryrun push aztecprotocol/$REPOSITORY:latest