#!/usr/bin/env bash
set -euo pipefail

# If already logged in, no need for slower reauth.
aws ecr describe-repositories --registry-id ${ECR_URL%%.*} &> /dev/null && exit

REGION=${1:-$ECR_REGION}
aws ecr get-login-password --region $REGION \
  | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com 2> /dev/null