#!/usr/bin/env bash
set -eu
# Returns true if the given image exists in the current ECR.
#aws ecr describe-images --region=$ECR_REGION --repository-name=$1 --image-ids=imageTag=$2 > /dev/null 2>&1
docker image inspect "$1:$2" > /dev/null 2>&1
