#!/bin/bash
# We are assumed to be in the projectDir.
# IP: The IP address of the system to run the script on.
# FULL_PATH: The path to the script, relative to the projectDir.
set -eu

IP=$1
FULL_PATH=$2
shift 2

SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-$BUILD_SYSTEM_PATH/remote/ssh_config}
# DIR_NAME=$(dirname $FULL_PATH)
# SCRIPT_NAME=$(basename $FULL_PATH)

ROOT_RELATIVE_PATH=$(git rev-parse --show-prefix)$FULL_PATH

# Copy all files in script directory to spot instance.
# scp -F $SSH_CONFIG_PATH $DIR_NAME/* $IP:.
# scp -rF $SSH_CONFIG_PATH $BUILD_SYSTEM_PATH $BUILD_SYSTEM_PATH/../.git $BUILD_SYSTEM_PATH/../build_manifest.json $IP:.
echo "Copying to $ROOT_PATH to $IP..."
scp -rF $SSH_CONFIG_PATH $ROOT_PATH $IP:project

# Run script on remote instance, passing environment variables.
echo "Running $ROOT_RELATIVE_PATH on $IP..."
ssh -A -F $SSH_CONFIG_PATH $IP "COMMIT_HASH=$COMMIT_HASH COMMIT_TAG=$COMMIT_TAG JOB_NAME=$JOB_NAME GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD ECR_DEPLOY_URL=$ECR_DEPLOY_URL ECR_URL=$ECR_URL ./project/$ROOT_RELATIVE_PATH $@"
