#!/bin/bash
# Returns success if we are expected to do a deployment.
# This is if we have a commit tag (release) or if we're on `master` branch (devnet deployment).

set -eu

if [ -n "$COMMIT_TAG" ] || [ "$BRANCH" = "master" ]; then
  exit 0
else
  exit 1
fi
