#!/bin/bash
set -xeu
SCRIPT_PATH=$1
REPOSITORY=$2
shift
shift

cd $(query_manifest projectDir $REPOSITORY)

mkdir -p /tmp/test-logs

set -xo pipefail
spot_run_script 32 $SCRIPT_PATH $@ | tee "/tmp/test-logs/$JOB_NAME.log"
