#pragma once

#include "barretenberg/vm2/common/avm_io.hpp"
#include "barretenberg/vm2/common/aztec_types.hpp"

struct FuzzerTxData;

namespace bb::avm2::fuzzer {

/// @brief Why a transaction was rejected as unprovable, distinguished by the exception type raised
/// by TxExecution::simulate rather than by matching on the message.
enum class UnprovableTxCause : uint8_t {
    // A setup enqueued call failed, a non-revertible side-effect limit was reached, or the fee
    // payer was zero or could not pay.
    TX_EXECUTION,
    // A nullifier that came from private collided.
    NULLIFIER_COLLISION,
};

/// @brief Zero every libFuzzer feedback counter and cumulative histogram, and register the exit dump.
/// Must be called from LLVMFuzzerInitialize.
void reset_counters();

/// @brief Record that an input produced an unprovable transaction. These are expected outcomes worth
/// steering towards, not failures, but they yield no simulation result.
void record_unprovable_tx(UnprovableTxCause cause);

/// @brief Record the static shape of an input: enqueued calls per phase, contracts, programs,
/// CFG instruction count and total generated bytecode size.
///
/// These describe what the mutator produced, independently of how far it executed, which is what
/// makes a change in generated program complexity visible.
void record_tx_shape(const FuzzerTxData& tx_data);

/// @brief Record the observable outcome of a simulated transaction: revert code, gas consumption
/// relative to the limit, call depth and nesting, and the resulting transaction effects.
///
/// An exceptional halt consumes the whole gas limit, so the gas ratio buckets separate inputs that
/// executed to completion from those that faulted early.
///
/// @throws std::runtime_error if an effect array exceeds its protocol maximum. That is unreachable
/// for a well-formed simulation, so it is treated as a finding rather than a counter update.
void record_tx_result(const TxSimulationResult& result, const Gas& gas_limits);

/// @brief Write the cumulative histograms via info().
///
/// Called at process exit, and every AVM_FUZZER_STATS_INTERVAL executions when AVM_FUZZER_STATS is
/// set in the environment.
void dump_fuzzer_stats();

} // namespace bb::avm2::fuzzer
