[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
bignum = { path = "../bignum" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.3.0" }
