#!/usr/bin/env bash
source $(git rev-parse --show-toplevel)/ci3/source

script_dir=$(dirname $0)
if [ ${AVM:-1} -eq 1 ]; then
  echo $root/barretenberg/cpp/$($script_dir/native-preset-build-dir)/bin/bb-avm
else
  echo $root/barretenberg/cpp/$($script_dir/native-preset-build-dir)/bin/bb
fi
