#!/usr/bin/env bash
source $(git rev-parse --show-toplevel)/ci3/source

if [ ${AVM:-1} -eq 1 ]; then
  echo $root/barretenberg/cpp/$(./preset-build-dir)/bin/bb-avm
else
  echo $root/barretenberg/cpp/$(./preset-build-dir)/bin/bb
fi
