#!/usr/bin/env python3
"""Regenerate gate_count_constants.hpp from gate-counts.json.

The JSON file is the source of truth for measured gate-count fixtures. This
script renders the C++ header that consumers include. Run after editing the
JSON manually, or invoked automatically by ci_update_gate_counts.sh after a
refresh round-trip.

Usage:
    barretenberg/cpp/scripts/gen_gate_count_constants.py [--check]

--check exits non-zero if the on-disk header differs from what would be
rendered; CI uses this to detect drift between JSON and header.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import dedent

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent  # cpp/scripts -> cpp -> barretenberg -> repo root
JSON_PATH = SCRIPT_DIR / "gate-counts.json"
HPP_PATH = (
    REPO_ROOT
    / "barretenberg"
    / "cpp"
    / "src"
    / "barretenberg"
    / "dsl"
    / "acir_format"
    / "gate_count_constants.hpp"
)

# Flavors known to HONK_RECURSION_CONSTANTS. Order matches the C++ if/else cascade.
HONK_FLAVORS = [
    ("UltraRecursive_Ultra", "bb::UltraRecursiveFlavor_<UltraCircuitBuilder>"),
    ("UltraZKRecursive_Ultra", "bb::UltraZKRecursiveFlavor_<UltraCircuitBuilder>"),
    ("UltraRecursive_Mega", "bb::UltraRecursiveFlavor_<MegaCircuitBuilder>"),
    ("UltraZKRecursive_Mega", "bb::UltraZKRecursiveFlavor_<MegaCircuitBuilder>"),
    ("MegaZKRecursive_Ultra", "bb::MegaZKRecursiveFlavor_<UltraCircuitBuilder>"),
]


def _load() -> dict:
    with JSON_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def _render_honk_branch(json_flavor: str, cpp_flavor: str, modes: dict[str, list[int]]) -> str:
    lines = [f"    }} else if constexpr (std::is_same_v<RecursiveFlavor, {cpp_flavor}>) {{"]
    has_witness = "Witness" in modes
    has_constant_true = "ConstantTrue" in modes
    if json_flavor == "MegaZKRecursive_Ultra":
        if not has_constant_true:
            raise ValueError(f"MegaZKRecursive_Ultra missing ConstantTrue tuple")
        a, b = modes["ConstantTrue"]
        lines.append(
            "        if (mode != PredicateTestCase::ConstantTrue) {\n"
            "            bb::assert_failure(\"Unhandled mode in MegaZKRecursiveFlavor.\");\n"
            "        }"
        )
        lines.append(f"        return std::make_tuple({a}, {b});")
        return "\n".join(lines)
    if not (has_witness and has_constant_true):
        raise ValueError(f"Flavor {json_flavor} must define ConstantTrue and Witness tuples")
    ct = modes["ConstantTrue"]
    w = modes["Witness"]
    lines.append("        switch (mode) {")
    lines.append("        case PredicateTestCase::ConstantTrue:")
    lines.append(f"            return std::make_tuple({ct[0]}, {ct[1]});")
    lines.append("        case PredicateTestCase::WitnessTrue:")
    lines.append("        case PredicateTestCase::WitnessFalse:")
    lines.append(f"            return std::make_tuple({w[0]}, {w[1]});")
    lines.append("        }")
    return "\n".join(lines)


def _render(data: dict) -> str:
    honk = data["HONK_RECURSION_CONSTANTS"]
    honk_branches = []
    for i, (json_flavor, cpp_flavor) in enumerate(HONK_FLAVORS):
        if json_flavor not in honk:
            raise ValueError(f"HONK_RECURSION_CONSTANTS missing flavor {json_flavor}")
        branch = _render_honk_branch(json_flavor, cpp_flavor, honk[json_flavor])
        if i == 0:
            branch = branch.replace("    } else if constexpr", "    if constexpr", 1)
        honk_branches.append(branch)
    honk_body = "\n".join(honk_branches)

    return dedent(
        """\
        // AUTOGENERATED FROM barretenberg/cpp/scripts/gate-counts.json — DO NOT EDIT BY HAND.
        // Regenerate via: barretenberg/cpp/scripts/gen_gate_count_constants.py
        // To refresh measured values from the test suite, set the PR label `ci-refresh-gates`
        // or include `--ci-refresh-gates` in the head commit message; see
        // barretenberg/cpp/scripts/ci_update_gate_counts.sh.
        #pragma once

        #include "barretenberg/dsl/acir_format/test_class_predicate.hpp"
        #include "barretenberg/stdlib/primitives/circuit_builders/circuit_builders.hpp"
        #include "barretenberg/stdlib_circuit_builders/mega_circuit_builder.hpp"
        #include "barretenberg/stdlib_circuit_builders/ultra_circuit_builder.hpp"
        #include <cstddef>
        #include <tuple>
        #include <type_traits>

        namespace acir_format {

        // ========================================
        // ACIR Opcode Gate Count Constants
        // ========================================

        // Mega adds 3 gates for ECCVM opcode values
        template <typename Builder> inline constexpr size_t MEGA_OFFSET = IsMegaBuilder<Builder> ? 3 : 0;

        // Base gate count for zero gate
        inline constexpr size_t ZERO_GATE = 1;

        // Gate count constants for each ACIR constraint type
        template <typename Builder> inline constexpr size_t ARITHMETIC_TRIPLE = 1 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t QUAD = 1 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BIG_QUAD = 2 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t LOGIC_XOR_32 = 6 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t LOGIC_AND_32 = 6 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t RANGE_32 = 2744 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t SHA256_COMPRESSION = 6702 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t AES128_ENCRYPTION = 1559 + ZERO_GATE + MEGA_OFFSET<Builder>;

        // The mega offset works differently for ECDSA opcodes because of the use of ROM tables, which use indices that
        // overlap with the values added for ECCVM. secp256k1 uses table of size 16 whose indices contain all the 4 values
        // set for ECCVM (hence the same value for Ultra and Mega builders). secp256r1 uses ROM tables of size 4, which
        // contain only 2 of the values set for ECCVM (hence the difference of two gates between Ultra and Mega builders).
        template <typename Builder> inline constexpr size_t ECDSA_SECP256K1 = 42837 + ZERO_GATE;
        template <typename Builder>
        inline constexpr size_t ECDSA_SECP256R1 = 72611 + ZERO_GATE + (IsMegaBuilder<Builder> ? 2 : 0);

        template <typename Builder> inline constexpr size_t BLAKE2S = 2952 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLAKE3 = 2158 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t KECCAK_PERMUTATION = 17387 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder>
        inline constexpr size_t POSEIDON2_PERMUTATION = (IsMegaBuilder<Builder> ? 27 : 73) + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t MULTI_SCALAR_MUL = 3563 + ZERO_GATE;
        template <typename Builder> inline constexpr size_t EC_ADD = 84 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLOCK_ROM_READ = 9 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLOCK_RAM_READ = 9 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLOCK_RAM_WRITE = 18 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLOCK_CALLDATA = 1 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t BLOCK_RETURNDATA = 11 + ZERO_GATE + MEGA_OFFSET<Builder>;
        template <typename Builder> inline constexpr size_t ASSERT_EQUALITY = ZERO_GATE + MEGA_OFFSET<Builder>;

        // ========================================
        // Honk Recursion Constants
        // ========================================

        inline constexpr size_t ROOT_ROLLUP_GATE_COUNT = __ROOT_ROLLUP_GATE_COUNT__;

        template <typename RecursiveFlavor>
        constexpr std::tuple<size_t, size_t> HONK_RECURSION_CONSTANTS(
            const PredicateTestCase& mode = PredicateTestCase::ConstantTrue)
        {
            using UltraCircuitBuilder = bb::UltraCircuitBuilder;
            using MegaCircuitBuilder = bb::MegaCircuitBuilder;

        __HONK_BRANCHES__
            } else {
                bb::assert_failure("Unhandled recursive flavor.");
            }

            throw_or_abort("Unhandled recursive flavor.");
        }

        // ========================================
        // Chonk Recursion Constants
        // ========================================

        // Gate count for Chonk recursive verification (Ultra with RollupIO)
        inline constexpr size_t CHONK_RECURSION_GATES = __CHONK_RECURSION_GATES__;

        // ========================================
        // Hypernova Recursion Constants
        // ========================================

        // MSM rows offset
        inline constexpr size_t MSM_ROWS_OFFSET = 2;

        // Init kernel gate counts (verifies OINK proof)
        inline constexpr size_t INIT_KERNEL_GATE_COUNT = __INIT_KERNEL_GATE_COUNT__;
        inline constexpr size_t INIT_KERNEL_ECC_ROWS = __INIT_KERNEL_ECC_ROWS_BASE__ + MSM_ROWS_OFFSET;
        inline constexpr size_t INIT_KERNEL_ULTRA_OPS = __INIT_KERNEL_ULTRA_OPS__;

        // Inner kernel gate counts (verifies HN proof for previous kernel + HN for app)
        inline constexpr size_t INNER_KERNEL_GATE_COUNT_HN = __INNER_KERNEL_GATE_COUNT_HN__;
        inline constexpr size_t INNER_KERNEL_ECC_ROWS = __INNER_KERNEL_ECC_ROWS_BASE__ + MSM_ROWS_OFFSET;
        inline constexpr size_t INNER_KERNEL_ULTRA_OPS = __INNER_KERNEL_ULTRA_OPS__;

        // Tail kernel gate counts (verifies HN_TAIL proof)
        inline constexpr size_t TAIL_KERNEL_GATE_COUNT = __TAIL_KERNEL_GATE_COUNT__;
        inline constexpr size_t TAIL_KERNEL_ECC_ROWS = __TAIL_KERNEL_ECC_ROWS_BASE__ + MSM_ROWS_OFFSET;
        inline constexpr size_t TAIL_KERNEL_ULTRA_OPS = __TAIL_KERNEL_ULTRA_OPS__;

        // Hiding kernel gate counts (verifies HN_FINAL proof)
        inline constexpr size_t HIDING_KERNEL_GATE_COUNT = __HIDING_KERNEL_GATE_COUNT__;
        inline constexpr size_t HIDING_KERNEL_ECC_ROWS = __HIDING_KERNEL_ECC_ROWS_BASE__ + MSM_ROWS_OFFSET;
        inline constexpr size_t HIDING_KERNEL_ULTRA_OPS = __HIDING_KERNEL_ULTRA_OPS__;

        // ========================================
        // ECCVM Recursive Verifier Constants
        // ========================================

        // Gate count for ECCVM recursive verifier (Ultra-arithmetized)
        inline constexpr size_t ECCVM_RECURSIVE_VERIFIER_GATE_COUNT = __ECCVM_RECURSIVE_VERIFIER_GATE_COUNT__;

        // ========================================
        // Goblin AVM Recursive Verifier Constants
        // ========================================

        inline constexpr size_t GOBLIN_AVM_GATE_COUNT = __GOBLIN_AVM_GATE_COUNT__;
        inline constexpr size_t FINALIZED_GOBLIN_AVM_GATE_COUNT = __FINALIZED_GOBLIN_AVM_GATE_COUNT__;

        } // namespace acir_format
        """
    ).replace("__HONK_BRANCHES__", honk_body).replace(
        "__ROOT_ROLLUP_GATE_COUNT__", str(data["ROOT_ROLLUP_GATE_COUNT"])
    ).replace(
        "__CHONK_RECURSION_GATES__", str(data["CHONK_RECURSION_GATES"])
    ).replace(
        "__ECCVM_RECURSIVE_VERIFIER_GATE_COUNT__",
        str(data["ECCVM_RECURSIVE_VERIFIER_GATE_COUNT"]),
    ).replace(
        "__GOBLIN_AVM_GATE_COUNT__", str(data["GOBLIN_AVM_GATE_COUNT"])
    ).replace(
        "__FINALIZED_GOBLIN_AVM_GATE_COUNT__",
        str(data["FINALIZED_GOBLIN_AVM_GATE_COUNT"]),
    ).replace(
        "__INIT_KERNEL_GATE_COUNT__", str(data["INIT_KERNEL_GATE_COUNT"])
    ).replace(
        "__INIT_KERNEL_ECC_ROWS_BASE__", str(data["INIT_KERNEL_ECC_ROWS_BASE"])
    ).replace(
        "__INIT_KERNEL_ULTRA_OPS__", str(data["INIT_KERNEL_ULTRA_OPS"])
    ).replace(
        "__INNER_KERNEL_GATE_COUNT_HN__", str(data["INNER_KERNEL_GATE_COUNT_HN"])
    ).replace(
        "__INNER_KERNEL_ECC_ROWS_BASE__", str(data["INNER_KERNEL_ECC_ROWS_BASE"])
    ).replace(
        "__INNER_KERNEL_ULTRA_OPS__", str(data["INNER_KERNEL_ULTRA_OPS"])
    ).replace(
        "__TAIL_KERNEL_GATE_COUNT__", str(data["TAIL_KERNEL_GATE_COUNT"])
    ).replace(
        "__TAIL_KERNEL_ECC_ROWS_BASE__", str(data["TAIL_KERNEL_ECC_ROWS_BASE"])
    ).replace(
        "__TAIL_KERNEL_ULTRA_OPS__", str(data["TAIL_KERNEL_ULTRA_OPS"])
    ).replace(
        "__HIDING_KERNEL_GATE_COUNT__", str(data["HIDING_KERNEL_GATE_COUNT"])
    ).replace(
        "__HIDING_KERNEL_ECC_ROWS_BASE__", str(data["HIDING_KERNEL_ECC_ROWS_BASE"])
    ).replace(
        "__HIDING_KERNEL_ULTRA_OPS__", str(data["HIDING_KERNEL_ULTRA_OPS"])
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the rendered header differs from the on-disk file",
    )
    args = parser.parse_args()

    data = _load()
    rendered = _render(data)
    if args.check:
        on_disk = HPP_PATH.read_text(encoding="utf-8") if HPP_PATH.exists() else ""
        if on_disk != rendered:
            print(
                "gate_count_constants.hpp is out of sync with gate-counts.json. "
                "Run barretenberg/cpp/scripts/gen_gate_count_constants.py to regenerate.",
                file=sys.stderr,
            )
            return 1
        return 0

    HPP_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {HPP_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
