#!/usr/bin/env python3
"""
Filter autogenerated serde code to only support msgpack-compact format.

This script modifies autogenerated C++ header files that were generated from Noir's
serde code generation to:
1. Remove bincode serialization methods
2. Simplify msgpack_pack to use array format instead of map format
3. Simplify msgpack_unpack to only support ARRAY format (compact)
4. Remove unused Helpers functions for key-value map handling

Usage:
    python msgpack_compact_filter.py <input_file> [output_file]

    If output_file is not specified, the input file is modified in-place.
"""

import re
import sys


def remove_bincode_include(content: str) -> str:
    """Remove #include "bincode.hpp" line."""
    return re.sub(r'#include "bincode\.hpp"\n', '', content)


def remove_bincode_declarations(content: str) -> str:
    """Remove bincodeSerialize and bincodeDeserialize declarations."""
    # Remove: std::vector<uint8_t> bincodeSerialize() const;
    content = re.sub(
        r'\s*std::vector<uint8_t> bincodeSerialize\(\) const;\n',
        '\n',
        content
    )
    # Remove: static <Type> bincodeDeserialize(std::vector<uint8_t>);
    content = re.sub(
        r'\s*static \w+ bincodeDeserialize\(std::vector<uint8_t>\);\n',
        '',
        content
    )
    return content


def simplify_helpers_struct(content: str) -> str:
    """
    Replace the Helpers struct to only have conv_fld_from_array.
    This is easier than trying to surgically remove functions with nested braces.
    """
    # Pattern to find the complete Helpers struct
    helpers_pattern = re.compile(
        r'(struct Helpers \{)\s*'
        r'static std::map<std::string, msgpack::object const\*> make_kvmap.*?'
        r'(template <typename T>\s*'
        r'static void conv_fld_from_array\(msgpack::object_array const& array,.*?'
        r'throw_or_abort\("error converting into field " \+ struct_name \+ "::" \+ field_name\);\s*\}\s*\})\s*'
        r'(\};)',
        re.DOTALL
    )

    def replace_helpers(match):
        struct_start = match.group(1)
        array_func = match.group(2)
        struct_end = match.group(3)
        return f'{struct_start}\n    {array_func}\n{struct_end}'

    return helpers_pattern.sub(replace_helpers, content)


def simplify_msgpack_pack_struct(content: str) -> str:
    """
    Simplify msgpack_pack for structs to use array format.
    Changes:
        packer.pack_map(N);
        packer.pack(std::make_pair("field", field));
    To:
        packer.pack_array(N);
        packer.pack(field);
    """
    # Replace pack_map with pack_array
    content = re.sub(r'packer\.pack_map\((\d+)\)', r'packer.pack_array(\1)', content)

    # Replace packer.pack(std::make_pair("field", value)) with packer.pack(value)
    content = re.sub(
        r'packer\.pack\(std::make_pair\("[^"]+", ([^)]+)\)\)',
        r'packer.pack(\1)',
        content
    )

    return content


def simplify_msgpack_unpack_struct(content: str) -> str:
    """
    Simplify msgpack_unpack to only support ARRAY format.
    """
    # Pattern to match the full if-else-if-else structure for struct unpacking
    # This matches the pattern where we have both MAP and ARRAY branches
    pattern = re.compile(
        r'void msgpack_unpack\(msgpack::object const& o\)\s*\{\s*'
        r'std::string name = "([^"]+)";\s*'
        r'if \(o\.type == msgpack::type::MAP\) \{\s*'
        r'auto kvmap = Helpers::make_kvmap\(o, name\);\s*'
        r'(?:Helpers::conv_fld_from_kvmap\([^;]+;\s*)*'
        r'\} else if \(o\.type == msgpack::type::ARRAY\) \{\s*'
        r'auto array = o\.via\.array;\s*'
        r'((?:Helpers::conv_fld_from_array\([^;]+;\s*)+)'
        r'\} else \{\s*'
        r'throw_or_abort\("expected MAP or ARRAY for " \+ name\);\s*\}\s*'
        r'\}',
        re.DOTALL
    )

    def replace_func(match):
        struct_name = match.group(1)
        array_calls = match.group(2).strip()
        # Fix indentation of array calls
        array_calls_lines = [line.strip() for line in array_calls.split('\n') if line.strip()]
        array_calls_formatted = '\n        '.join(array_calls_lines)
        return (
            f'void msgpack_unpack(msgpack::object const& o)\n'
            f'    {{\n'
            f'        std::string name = "{struct_name}";\n'
            f'        if (o.type != msgpack::type::ARRAY) {{\n'
            f'            throw_or_abort("expected ARRAY for " + name);\n'
            f'        }}\n'
            f'        auto array = o.via.array;\n'
            f'        {array_calls_formatted}\n'
            f'    }}'
        )

    content = pattern.sub(replace_func, content)
    return content


def process_file(input_path: str, output_path: str = None) -> None:
    """Process a single file."""
    with open(input_path, 'r') as f:
        content = f.read()

    # Apply transformations in order
    content = remove_bincode_include(content)
    content = remove_bincode_declarations(content)
    content = simplify_helpers_struct(content)
    content = simplify_msgpack_pack_struct(content)
    content = simplify_msgpack_unpack_struct(content)

    # Write output
    output_path = output_path or input_path
    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Processed: {input_path} -> {output_path}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    process_file(input_path, output_path)


if __name__ == '__main__':
    main()
