#!/usr/bin/env bash
# This is the default test runner which takes the as arguments:
# 1. The number of ignition transcripts to download.
# 2. The set of gtest binary names to run.
# 3-n. The arguments to pass to the gtest binaries.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

NUM_TRANSCRIPTS=$1
TESTS=$2
shift 2

cd $(dirname $0)

if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

/usr/src/barretenberg/cpp/srs_db/download_ignition.sh $NUM_TRANSCRIPTS
/usr/src/barretenberg/cpp/srs_db/download_grumpkin.sh
cd /usr/src/barretenberg/cpp/build
for BIN in $TESTS; do ./bin/$BIN $@; done
