#pragma once
#include "barretenberg/ecc/curves/bn254/g1.hpp"
#include "barretenberg/ecc/curves/bn254/g2.hpp"
#include "barretenberg/ecc/curves/grumpkin/grumpkin.hpp"
#include "barretenberg/ecc/curves/secp256k1/secp256k1.hpp"
#include "barretenberg/ecc/curves/secp256r1/secp256r1.hpp"
#include <cstdlib>
#include <cxxabi.h>
#include <memory>
#include <string>

/**
 * Converts C++ type information into a human-readable format.
 * This function leverages __cxa_demangle to demangle the name generated by typeid.
 * Special cases are handled for "basic_string" (returns "string") and "i" (returns "int").
 * Template specializations are truncated and only the base type name is returned
 * @tparam T the type.
 * @return the readable schema name.
 */
template <typename T> std::string msgpack_schema_name(T const&)
{
    // If we have a T::MSGPACK_SCHEMA_NAME member, use that.
    if constexpr (requires { T::MSGPACK_SCHEMA_NAME; }) {
        return T::MSGPACK_SCHEMA_NAME;
    }
    std::unique_ptr<char, decltype(&std::free)> demangled(
        abi::__cxa_demangle(typeid(T).name(), nullptr, nullptr, nullptr), &std::free);
    std::string result = demangled.get();
    if (result.find("basic_string") != std::string::npos) {
        return "string";
    }
    if (result == "i") {
        return "int";
    }

    if (result.find('<') != std::string::npos) {
        result = result.substr(0, result.find('<'));
    }
    if (result.rfind(':') != std::string::npos) {
        result = result.substr(result.rfind(':') + 1, result.size());
    }
    return result;
}
