#!/bin/bash
set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <flag name>"
  exit 1
fi

NAME=$1

# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  # Extract URL from S3_BUILD_CACHE_AWS_PARAMS (assumes the format "--endpoint-url <URL>")
  # TODO stop passing with endpoint url
  S3_ENDPOINT=$(echo "$S3_BUILD_CACHE_AWS_PARAMS" | sed -n 's/--endpoint-url \([^ ]*\)/\1/p')
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
fi
# Attempt to download the cache file
curl -s -f -O "${S3_ENDPOINT}/build-cache/$NAME.flag" || exit 1
rm $NAME.flag
exit 0