#!/bin/bash
set -eu
[ "${BUILD_SYSTEM_DEBUG:-}" = 1 ] && set -x

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <tar.gz_file_to_download_and_extract>" >&2
  exit 1
fi

if [ "${USE_CACHE:-0}" -lt 1 ]; then
  # Only download if USE_CACHE is 1
  exit 1
fi
# Get the tar.gz file name from the argument
TAR_FILE="$1"
OUT_DIR="${2:-.}"

function on_exit() {
  # Cleanup the temporary tar.gz file
  rm -f "$TAR_FILE"
}
# Run on any exit
trap on_exit EXIT

# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$TAR_FILE" "$TAR_FILE"
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
  # Attempt to download and extract the cache file
  mkdir -p "$OUT_DIR"
  (curl -s -f -O "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -xzf - -C "$OUT_DIR") || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
fi

echo "Cache download and extraction of $TAR_FILE complete." >&2