#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <flag name>"
  exit 1
fi

if [ "${CI:-0}" -lt 1 ]; then
  # Don't look if CI isn't set. No need to muddle with dev runs.
  echo "Not checking remote test flag $1 because CI=0."
  exit 1
fi

NAME=$1

# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  # Write the flag file to stdout, return exit success if found
  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" - --quiet --no-progress
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
  # Write the flag file to stdout, return exit success if found
  curl -s -f "$S3_ENDPOINT/build-cache/$NAME.flag" -O || (echo "Flag $NAME.flag not found." && exit 1)
fi