#!/bin/bash
set -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <flag name>"
  exit 1
fi

if [ "${CI:-0}" -lt 1 ]; then
  # Don't look if CI isn't set. No need to muddle with dev runs.
  exit 1
fi

NAME=$1

# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" "$NAME.flag" --only-show-errors --no-progress
else
  # Default to AWS S3 URL if no custom endpoint is set
  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
  # Attempt to download the cache file
  curl -s -f -O "$S3_ENDPOINT/build-cache/$NAME.flag" || (echo "Flag $NAME not found." && exit 1)
fi

rm $NAME.flag
echo "Flag $NAME exists."