#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
set -eu

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <my-artifact.tar.gz> <binary_paths_to_tar_gz_and_upload...>" >&2
  exit 1
fi

if [ "${CI:-0}" -lt 1 ]; then
  # Don't upload if CI is not on.
  exit 0
fi

# Name, intended to have .tar.gz ending
NAME="$1"

shift 1

# Pipe tar directly to AWS S3 cp
if tar -czf - "$@" | aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp - "s3://aztec-ci-artifacts/build-cache/$NAME" >&2 ; then
  echo "Cache upload of $NAME complete." >&2
else
  echo "Cache upload of $NAME failed." >&2
  exit 1
fi
