#!/bin/bash
set -eu

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <my-artifact.tar.gz> <binary_paths_to_tar_gz_and_upload...>" >&2
  exit 1
fi

# Name, intended to have .tar.gz ending
name="$1"

shift 1

tar_dir=$(mktemp -d)
tar_file="$tar_dir/${name}"

function on_exit() {
  # Cleanup the temporary folder
  rm -rf "$tar_dir"
}
trap on_exit EXIT

# Create the tar.gz file
# Rest of args are our binary paths
tar -czf "$tar_file" $@

if ! aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 ls "s3://aztec-ci-artifacts/build-cache/$name" >/dev/null 2>&1; then
  aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp "$TAR_FILE" "s3://aztec-ci-artifacts/build-cache/$name" >&2
  echo "Cache upload of $name complete." >&2
else
  echo "Skipping upload, already exists: $name" >&2
fi