// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

#include "barretenberg/cdb/cdb_execute.hpp"
#include "barretenberg/ipc/ipc_server.hpp"
#include "barretenberg/serialize/msgpack.hpp"

#include <cstdint>
#include <functional>
#include <span>
#include <string>
#include <vector>

namespace bb::cdb {

/**
 * @brief Type alias for the dispatch function.
 *
 * Takes a CdbRequest& and a CdbCommand&& and returns a CdbCommandResponse.
 * This is typically the top-level `cdb()` function from cdb_execute.hpp.
 */
using CdbDispatchFn = std::function<CdbCommandResponse(CdbRequest&, CdbCommand&&)>;

/**
 * @brief Create an IPC server handler from a dispatch function.
 *
 * Returns a lambda compatible with ipc::IpcServer::run(). The handler:
 *   1. Deserializes the msgpack request: [[CommandName, {payload}]]
 *   2. Detects shutdown commands (CdbShutdown)
 *   3. Dispatches to the provided function
 *   4. Serializes the response
 *   5. Wraps exceptions in CdbErrorResponse
 */
ipc::IpcServer::Handler make_cdb_handler(CdbRequest& request, CdbDispatchFn dispatch);

} // namespace bb::cdb
