// AUTOGENERATED FILE - DO NOT EDIT

#include "barretenberg/cdb/cdb_ipc_server_gen.hpp"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <iostream>
#include <string_view>

namespace bb::cdb {

ipc::IpcServer::Handler make_cdb_handler(CdbRequest& request, CdbDispatchFn dispatch)
{
    return [&request, dispatch = std::move(dispatch)](int client_id,
                                                      std::span<const uint8_t> raw_request) -> std::vector<uint8_t> {
        try {
            // Deserialize: [[CommandName, {payload}]]
            auto unpacked = msgpack::unpack(reinterpret_cast<const char*>(raw_request.data()), raw_request.size());
            auto obj = unpacked.get();

            if (obj.type != msgpack::type::ARRAY || obj.via.array.size != 1) {
                std::cerr << "Error: Expected array of size 1 from client " << client_id << '\n';
                return {};
            }

            auto& command_obj = obj.via.array.ptr[0];

            // Check for shutdown before converting
            bool is_shutdown = false;
            if (command_obj.type == msgpack::type::ARRAY && command_obj.via.array.size == 2 &&
                command_obj.via.array.ptr[0].type == msgpack::type::STR) {
                std::string_view command_name(command_obj.via.array.ptr[0].via.str.ptr,
                                              command_obj.via.array.ptr[0].via.str.size);
                is_shutdown = (command_name == "CdbShutdown");
            }

            // Convert and dispatch
            CdbCommand command;
            command_obj.convert(command);
            auto response = dispatch(request, std::move(command));

            // Serialize response
            msgpack::sbuffer response_buffer;
            msgpack::pack(response_buffer, response);
            std::vector<uint8_t> result(response_buffer.data(), response_buffer.data() + response_buffer.size());

            if (is_shutdown) {
                throw ipc::ShutdownRequested(std::move(result));
            }

            return result;

        } catch (const ipc::ShutdownRequested&) {
            throw;
        } catch (const std::exception& e) {
            std::cerr << "Error processing request from client " << client_id << ": " << e.what() << '\n';
            std::cerr.flush();

            CdbErrorResponse error_response{ .message = std::string(e.what()) };
            CdbCommandResponse response = error_response;

            msgpack::sbuffer response_buffer;
            msgpack::pack(response_buffer, response);
            return std::vector<uint8_t>(response_buffer.data(), response_buffer.data() + response_buffer.size());
        }
    };
}

} // namespace bb::cdb
