FROM aztecprotocol/noir as noir
FROM aztecprotocol/avm-transpiler as transpiler
FROM aztecprotocol/yarn-project as yarn-project

RUN apt-get update && apt-get install -y parallel

# Copy in nargo
COPY --from=noir /usr/src/noir/noir-repo/target/release/nargo /usr/src/noir/noir-repo/target/release/nargo
ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
# Copy in transpiler
COPY --from=transpiler /usr/src/avm-transpiler/target/release/avm-transpiler /usr/src/avm-transpiler/target/release/avm-transpiler
ENV PATH="/usr/src/avm-transpiler/target/release:${PATH}"

# All built files are ignored, but this build is fast and we're moving to earthly, so we don't bother
WORKDIR /usr/src/yarn-project
RUN yarn workspaces focus @aztec/txe
RUN cd ./txe && yarn build

# Copy in noir projects
COPY --from=noir-contracts /usr/src/noir-projects /usr/src/noir-projects

# Build & test
WORKDIR /usr/src/noir-projects
RUN cd noir-protocol-circuits && nargo test --silence-warnings

RUN cd /usr/src/yarn-project/txe && yarn start & echo $! > /tmp/txe.pid && \ 
    # Wait for TXE to initialize
    sleep 5 && \ 
    cd /usr/src/noir-projects/noir-contracts && \
    nargo test --silence-warnings --oracle-resolver http://localhost:8080 ; \
    kill $(cat /tmp/txe.pid)

RUN cd /usr/src/yarn-project/txe && yarn start & echo $! > /tmp/txe.pid && \ 
    # Wait for TXE to initialize
    sleep 5 && \ 
    cd /usr/src/noir-projects/aztec-nr && \
    nargo test --silence-warnings --oracle-resolver http://localhost:8080