VERSION 0.8
test:
  BUILD +test-protocol-circuits
  BUILD +test-aztec-nr
  BUILD +test-contracts

test-protocol-circuits:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  # TODO(#10754): Remove --skip-brillig-constraints-check
  RUN cd /usr/src/noir-projects/noir-protocol-circuits && nargo test --silence-warnings --skip-brillig-constraints-check

  # Also execute circuits to ensure that `Prover.toml` files are in sync.
  LET circuits = "private-kernel-inner private-kernel-tail private-kernel-reset rollup-root rollup-block-root rollup-block-merge rollup-base-private rollup-base-public"
  FOR circuit IN $circuits
      RUN cd /usr/src/noir-projects/noir-protocol-circuits/crates/$circuit && nargo execute --silence-warnings --skip-brillig-constraints-check
  END

test-aztec-nr:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  RUN cd /usr/src/yarn-project/txe && yarn start & \
      # Wait for TXE to initialize
      sleep 5 && \
      cd /usr/src/noir-projects/aztec-nr && \
      NARGO_FOREIGN_CALL_TIMEOUT=300000 nargo test --silence-warnings --oracle-resolver http://localhost:8080

test-contracts:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  RUN cd /usr/src/yarn-project/txe && yarn start & \
      # Wait for TXE to initialize
      sleep 5 && \
      cd /usr/src/noir-projects/noir-contracts && \
      # We need to increase the timeout since all tests running in parallel hammer TXE at the same time and processing slows down, leading to timeouts
      # The only way we currently have to batch tests is via RAYON_NUM_THREADS, which is not ideal
      NARGO_FOREIGN_CALL_TIMEOUT=300000 nargo test --silence-warnings --oracle-resolver http://localhost:8080

format:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  WORKDIR /usr/src/noir-projects/noir-protocol-circuits
  RUN node ./scripts/generate_variants.js
  RUN nargo fmt --check

  WORKDIR /usr/src/noir-projects/mock-protocol-circuits
  RUN nargo fmt --check

  WORKDIR /usr/src/noir-projects/noir-contracts
  RUN nargo fmt --check

  WORKDIR /usr/src/noir-projects/aztec-nr
  RUN nargo fmt --check

gates-report:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  WORKDIR /usr/src/noir-projects

  # Install bb
  ENV BB_BIN /usr/src/barretenberg/cpp/build/bin/bb

  # TODO(#10754): Remove --skip-brillig-constraints-check
  RUN cd noir-protocol-circuits && yarn && node ./scripts/generate_variants.js tiny && nargo compile --silence-warnings --skip-brillig-constraints-check

  COPY ./gates_report.sh ./gates_report.sh
  RUN ./gates_report.sh

  SAVE ARTIFACT ./noir-protocol-circuits/gates_report.json gates_report.json

public-functions-report:
  FROM ../+bootstrap
  ENV PATH="/usr/src/noir/noir-repo/target/release:${PATH}"
  WORKDIR /usr/src/noir-projects

  RUN cd noir-contracts && node ./scripts/publicFunctionsSizeReport.js ./target/

  SAVE ARTIFACT ./noir-contracts/public_functions_report.json public_functions_report.json
