/**
 * C++ IPC Client Code Generator
 *
 * Generates a C++ IPC client from a CompiledSchema. The generated client:
 *   - Connects to a server over Unix Domain Socket via ipc::IpcClient
 *   - Wraps each command in a NamedUnion, serializes with msgpack, sends, receives, deserializes
 *   - Has one method per command, returning the typed response
 *
 * Usage:
 *   const gen = new CppCodegen({ namespace: 'bb::cdb', prefix: 'Cdb' });
 *   const header = gen.generateHeader(schema);
 *   const impl = gen.generateImpl(schema);
 */

import type { CompiledSchema, Type, Struct, Field, Command } from './schema_visitor.ts';
import { toSnakeCase } from './naming.ts';

export interface CppCodegenOptions {
  /** C++ namespace for generated code, e.g. 'bb::cdb' */
  namespace: string;
  /** Prefix for command/response types, e.g. 'Cdb' */
  prefix: string;
  /** Header path for the *_execute.hpp file that defines Command/CommandResponse NamedUnions */
  executeHeader: string;
  /** Header path for the *_commands.hpp file that defines the command structs */
  commandsHeader: string;
  /**
   * External types: types that already exist in barretenberg headers.
   * Map from type name → header include path.
   * These types will be #included instead of generated.
   */
  externals?: Record<string, string>;
  /**
   * Using-namespace declarations to add at the top of generated commands file.
   * E.g. ['bb::world_state', 'bb::crypto::merkle_tree']
   */
  usingNamespaces?: string[];
  /**
   * Additional headers to include in generated commands file.
   */
  additionalIncludes?: string[];
  /**
   * Override for the generated output directory include path.
   * Used when commandsHeader doesn't point to the generated/ directory
   * (e.g. bb keeps hand-written commands but generates server dispatch).
   */
  generatedIncludeDir?: string;
}

export class CppCodegen {
  constructor(private opts: CppCodegenOptions) {}

  /** Convert a command name to a C++ method name (snake_case without prefix) */
  private methodName(commandName: string): string {
    // Strip prefix: "CdbGetContractInstance" -> "GetContractInstance" -> "get_contract_instance"
    const withoutPrefix = commandName.startsWith(this.opts.prefix)
      ? commandName.slice(this.opts.prefix.length)
      : commandName;
    return toSnakeCase(withoutPrefix);
  }

  /** Check if the response has fields (non-void return) */
  private hasResponseFields(command: Command, schema: CompiledSchema): boolean {
    const resp = schema.responses.get(command.responseType);
    return !!resp && resp.fields.length > 0;
  }

  /** Generate the method signature using command struct types directly */
  private generateMethodSignature(command: Command, schema: CompiledSchema, className?: string): string {
    const method = this.methodName(command.name);
    const hasFields = this.hasResponseFields(command, schema);
    const retType = hasFields ? `${command.name}::Response` : 'void';

    // If the command has fields, take the whole command struct by value
    const params = command.fields.length > 0 ? `${command.name} cmd` : '';

    const prefix = className ? `${className}::` : '';
    const constSuffix = !this.isWriteCommand(command) ? ' const' : '';

    return `${retType} ${prefix}${method}(${params})${constSuffix}`;
  }

  /** Check if a command modifies state (non-const) */
  private isWriteCommand(command: Command): boolean {
    const name = command.name.toLowerCase();
    return name.includes('add') || name.includes('create') ||
      name.includes('commit') || name.includes('revert') ||
      name.includes('register') || name.includes('shutdown') ||
      name.includes('delete') || name.includes('sync') ||
      name.includes('rollback') || name.includes('unwind');
  }

  /** Generate the header file */
  generateHeader(schema: CompiledSchema, schemaHash?: string): string {
    const { namespace: ns, prefix } = this.opts;
    const className = `${prefix}IpcClient`;

    const methods = schema.commands.map(cmd => {
      const sig = this.generateMethodSignature(cmd, schema);
      return `    ${sig};`;
    }).join('\n');

    const hashConstant = schemaHash
      ? `\n/** Schema version hash for compatibility checking */\nstatic constexpr const char SCHEMA_HASH[] = "${schemaHash}";\n`
      : '';

    return `// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

#include "barretenberg/common/try_catch_shim.hpp"
#include "${this.opts.commandsHeader}"
#include "${this.generatedDir()}/ipc_client.hpp"

#include <memory>
#include <string>

namespace ${ns} {
${hashConstant}
/**
 * @brief Auto-generated IPC client.
 *
 * Each method sends a msgpack-serialized command to the server over UDS
 * and returns the typed response. All methods block until the response arrives.
 */
class ${className} {
  public:
    explicit ${className}(const std::string& socket_path);
    ~${className}();

    ${className}(const ${className}&) = delete;
    ${className}& operator=(const ${className}&) = delete;

${methods}

  private:
    template <typename Cmd>
    typename Cmd::Response send(Cmd&& cmd) const;

    mutable std::unique_ptr<::ipc::IpcClient> client_;
};

} // namespace ${ns}
`;
  }

  /** Generate the implementation file — string-based serialization, no NamedUnion */
  generateImpl(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const className = `${prefix}IpcClient`;
    const errorType = schema.errorTypeName || `${prefix}ErrorResponse`;

    const methods = schema.commands.map(cmd => {
      return this.generateMethodImpl(cmd, schema, className);
    }).join('\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT

#include "${this.headerIncludePath()}"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <stdexcept>
#include <string>

namespace ${ns} {

${className}::${className}(const std::string& socket_path)
    : client_(std::make_unique<::ipc::IpcClient>(socket_path.c_str()))
{}

${className}::~${className}() = default;

template <typename Cmd>
typename Cmd::Response ${className}::send(Cmd&& cmd) const
{
    // Serialize as [[CommandName, {payload}]]
    msgpack::sbuffer send_buffer;
    msgpack::packer<msgpack::sbuffer> pk(send_buffer);
    pk.pack_array(1);
    pk.pack_array(2);
    pk.pack(std::string(Cmd::MSGPACK_SCHEMA_NAME));
    pk.pack(std::forward<Cmd>(cmd));

    // Send request, receive response
    std::vector<uint8_t> request_bytes(send_buffer.data(), send_buffer.data() + send_buffer.size());
    auto response_bytes = client_->call(request_bytes);

    if (response_bytes.empty()) {
        throw std::runtime_error("Empty response from server");
    }

    // Parse response: [ResponseName, {payload}]
    auto unpacked = msgpack::unpack(
        reinterpret_cast<const char*>(response_bytes.data()), response_bytes.size());
    auto obj = unpacked.get();

    if (obj.type != msgpack::type::ARRAY || obj.via.array.size != 2 ||
        obj.via.array.ptr[0].type != msgpack::type::STR) {
        throw std::runtime_error("Invalid response format from server");
    }

    std::string resp_name(obj.via.array.ptr[0].via.str.ptr, obj.via.array.ptr[0].via.str.size);
    if (resp_name == "${errorType}") {
        std::string message;
        auto& payload = obj.via.array.ptr[1];
        // Extract message field from the error map
        if (payload.type == msgpack::type::MAP) {
            for (uint32_t i = 0; i < payload.via.map.size; ++i) {
                auto& kv = payload.via.map.ptr[i];
                if (kv.key.type == msgpack::type::STR) {
                    std::string key(kv.key.via.str.ptr, kv.key.via.str.size);
                    if (key == "message" && kv.val.type == msgpack::type::STR) {
                        message = std::string(kv.val.via.str.ptr, kv.val.via.str.size);
                    }
                }
            }
        }
        throw std::runtime_error("Server error: " + message);
    }

    typename Cmd::Response result;
    obj.via.array.ptr[1].convert(result);
    return result;
}

${methods}
} // namespace ${ns}
`;
  }

  /** Generate a single method implementation */
  private generateMethodImpl(command: Command, schema: CompiledSchema, className: string): string {
    const sig = this.generateMethodSignature(command, schema, className);
    const hasFields = this.hasResponseFields(command, schema);

    const cmdExpr = command.fields.length > 0 ? 'std::move(cmd)' : `${command.name}{}`;

    if (!hasFields) {
      return `${sig}
{
    send(${cmdExpr});
}
`;
    }

    return `${sig}
{
    return send(${cmdExpr});
}
`;
  }

  /** Get the generated/ directory include path */
  private generatedDir(): string {
    if (this.opts.generatedIncludeDir) {
      return this.opts.generatedIncludeDir;
    }
    return this.opts.commandsHeader.substring(0, this.opts.commandsHeader.lastIndexOf('/'));
  }

  /** Compute the include path for the generated client header */
  private headerIncludePath(): string {
    return `${this.generatedDir()}/${toSnakeCase(this.opts.prefix)}_ipc_client.hpp`;
  }

  // -----------------------------------------------------------------------
  // Standalone types (no barretenberg dependencies)
  // -----------------------------------------------------------------------

  /** Generate standalone C++ types with MSGPACK_DEFINE_MAP — no barretenberg deps */
  generateStandaloneTypes(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;

    // Map schema types to C++ types
    const mapType = (type: import('./schema_visitor.ts').Type): string => {
      switch (type.kind) {
        case 'primitive':
          switch (type.primitive) {
            case 'bool': return 'bool';
            case 'u8': return 'uint8_t';
            case 'u16': return 'uint16_t';
            case 'u32': return 'uint32_t';
            case 'u64': return 'uint64_t';
            case 'f64': return 'double';
            case 'string': return 'std::string';
            case 'bytes': return 'std::vector<uint8_t>';
            case 'fr': return 'Fr';  // std::array<uint8_t, 32>
            case 'field2': return 'std::array<Fr, 2>';
            case 'enum_u32': return 'uint32_t';
            case 'map_u32_pair': return 'std::unordered_map<uint32_t, std::pair<std::vector<uint8_t>, uint64_t>>';
          }
          break;
        case 'vector': return `std::vector<${mapType(type.element!)}>`;
        case 'array': return `std::array<${mapType(type.element!)}, ${type.size}>`;
        case 'optional': return `std::optional<${mapType(type.element!)}>`;
        case 'struct': return type.struct!.name;
      }
      return 'void';
    };

    const allStructs = [...schema.structs.values(), ...schema.responses.values()];
    const structs = allStructs.map(s => {
      const fields = s.fields.map(f => `    ${mapType(f.type)} ${f.name};`).join('\n');
      const fieldNames = s.fields.map(f => f.name).join(', ');
      const schemaName = `    static constexpr const char MSGPACK_SCHEMA_NAME[] = "${s.name}";`;
      // Use SERIALIZATION_FIELDS (barretenberg macro, supports schema export)
      // For standalone use without barretenberg, define SERIALIZATION_FIELDS as MSGPACK_DEFINE_MAP
      const serialization = fieldNames
        ? `    SERIALIZATION_FIELDS(${fieldNames})`
        : `    void msgpack(auto&& pack_fn) { pack_fn(); }`;
      return `struct ${s.name} {\n${schemaName}\n${fields}\n${serialization}\n    bool operator==(const ${s.name}&) const = default;\n};`;
    }).join('\n\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT
// Standalone types for ${prefix} service — no barretenberg dependencies.
#pragma once

// Aztec fork of msgpack-c uses THROW/RETHROW macros
#ifndef THROW
#define THROW throw
#endif
#ifndef RETHROW
#define RETHROW throw
#endif

#include <msgpack.hpp>
#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

// SERIALIZATION_FIELDS: if not defined by barretenberg, fall back to MSGPACK_DEFINE_MAP
#ifndef SERIALIZATION_FIELDS
#define SERIALIZATION_FIELDS(...) MSGPACK_DEFINE_MAP(__VA_ARGS__)
#endif

/// 32-byte field element (Fr/Fq). Fixed-size, stack-allocated.
using Fr = std::array<uint8_t, 32>;

namespace ${ns} {

${structs}

} // namespace ${ns}
`;
  }

  /** Generate standalone server dispatch (no barretenberg deps) */
  generateStandaloneServer(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const errorType = schema.errorTypeName || `${prefix}ErrorResponse`;

    const dispatchCases = schema.commands
      .filter(c => !c.name.endsWith('Shutdown'))
      .map(c => {
        return `        if (cmd_name == "${c.name}") {
            ${c.name} cmd; cmd_payload.convert(cmd);
            auto resp = handle_${toSnakeCase(c.name.startsWith(prefix) ? c.name.slice(prefix.length) : c.name)}(cmd);
            pk.pack_array(2); pk.pack(std::string("${c.responseType}")); pk.pack(resp);
        }`;
      }).join(' else ');

    const stubs = schema.commands
      .filter(c => !c.name.endsWith('Shutdown'))
      .map(c => {
        const method = toSnakeCase(c.name.startsWith(prefix) ? c.name.slice(prefix.length) : c.name);
        return `// TODO: implement ${c.name}
inline ${c.responseType} handle_${method}(const ${c.name}& /*cmd*/) {
    throw std::runtime_error("not implemented: ${c.name}");
}`;
      }).join('\n\n');

    const shutdownName = schema.commands.find(c => c.name.endsWith('Shutdown'))?.name || `${prefix}Shutdown`;
    const shutdownResp = shutdownName + 'Response';

    return `// AUTOGENERATED FILE - DO NOT EDIT
// ${prefix} server dispatch — standalone, no barretenberg dependencies.
// Implement the handle_* functions to build your ${prefix} service.
#pragma once

#include "types_gen.hpp"
#include "${this.generatedDir()}/ipc_server.hpp"
#include <stdexcept>

namespace ${ns} {

// ---------------------------------------------------------------------------
// Dispatch: routes commands to handler functions
// ---------------------------------------------------------------------------

inline std::vector<uint8_t> dispatch(const std::vector<uint8_t>& payload) {
    auto oh = msgpack::unpack(reinterpret_cast<const char*>(payload.data()), payload.size());
    auto obj = oh.get();
    auto& inner = obj.via.array.ptr[0];
    std::string cmd_name(inner.via.array.ptr[0].via.str.ptr, inner.via.array.ptr[0].via.str.size);
    auto& cmd_payload = inner.via.array.ptr[1];

    msgpack::sbuffer resp_buf;
    msgpack::packer<msgpack::sbuffer> pk(resp_buf);

    try {
        if (cmd_name == "${shutdownName}") {
            pk.pack_array(2); pk.pack(std::string("${shutdownResp}")); pk.pack_map(0);
        } else ${dispatchCases} else {
            pk.pack_array(2); pk.pack(std::string("${errorType}"));
            pk.pack_map(1); pk.pack(std::string("message")); pk.pack(std::string("unknown command: ") + cmd_name);
        }
    } catch (const std::exception& e) {
        resp_buf.clear();
        msgpack::packer<msgpack::sbuffer> epk(resp_buf);
        epk.pack_array(2); epk.pack(std::string("${errorType}"));
        epk.pack_map(1); epk.pack(std::string("message")); epk.pack(std::string(e.what()));
    }

    return std::vector<uint8_t>(resp_buf.data(), resp_buf.data() + resp_buf.size());
}

/// Start the server on the given socket path.
inline void serve(const char* socket_path) {
    ipc::serve(socket_path, dispatch);
}

// ---------------------------------------------------------------------------
// Handler stubs — implement these to build your ${prefix} service.
// ---------------------------------------------------------------------------

${stubs}

} // namespace ${ns}
`;
  }

  /** Generate standalone client wrapper (no barretenberg deps) */
  generateStandaloneClient(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const errorType = schema.errorTypeName || `${prefix}ErrorResponse`;

    const methods = schema.commands
      .filter(c => !c.name.endsWith('Shutdown'))
      .map(c => {
        const method = toSnakeCase(c.name.startsWith(prefix) ? c.name.slice(prefix.length) : c.name);
        const hasFields = c.fields.length > 0;
        const param = hasFields ? `const ${c.name}& cmd` : '';
        const packCmd = hasFields ? 'cmd' : `${c.name}{}`;
        return `    ${c.responseType} ${method}(${param}) {
        msgpack::sbuffer buf;
        msgpack::packer<msgpack::sbuffer> pk(buf);
        pk.pack_array(1); pk.pack_array(2); pk.pack(std::string("${c.name}")); pk.pack(${packCmd});
        auto resp = client_.call(std::vector<uint8_t>(buf.data(), buf.data() + buf.size()));
        auto oh = msgpack::unpack(reinterpret_cast<const char*>(resp.data()), resp.size());
        auto obj = oh.get();
        std::string resp_name(obj.via.array.ptr[0].via.str.ptr, obj.via.array.ptr[0].via.str.size);
        if (resp_name == "${errorType}") throw std::runtime_error("server error");
        ${c.responseType} result; obj.via.array.ptr[1].convert(result);
        return result;
    }`;
      }).join('\n\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT
// ${prefix} typed IPC client — standalone, no barretenberg dependencies.
#pragma once

#include "types_gen.hpp"
#include "${this.generatedDir()}/ipc_client.hpp"
#include <stdexcept>

namespace ${ns} {

class ${prefix}Client {
  public:
    explicit ${prefix}Client(const char* socket_path) : client_(socket_path) {}

${methods}

    void shutdown() {
        msgpack::sbuffer buf;
        msgpack::packer<msgpack::sbuffer> pk(buf);
        pk.pack_array(1); pk.pack_array(2); pk.pack(std::string("${prefix}Shutdown")); pk.pack_map(0);
        client_.call(std::vector<uint8_t>(buf.data(), buf.data() + buf.size()));
    }

  private:
    ipc::IpcClient client_;
};

} // namespace ${ns}
`;
  }

  // -----------------------------------------------------------------------
  // Barretenberg commands generation (uses native bb types, has execute())
  // -----------------------------------------------------------------------

  /**
   * Map an IR type to a barretenberg C++ type.
   * Uses native types (bb::fr, MerkleTreeId, StateReference) instead of
   * standalone equivalents (Fr, uint32_t, std::unordered_map<...>).
   */
  private mapTypeBb(type: import('./schema_visitor.ts').Type): string {
    const externals = this.opts.externals || {};

    switch (type.kind) {
      case 'primitive':
        switch (type.primitive) {
          case 'bool': return 'bool';
          case 'u8': return 'uint8_t';
          case 'u16': return 'uint16_t';
          case 'u32': return 'uint32_t';
          case 'u64': return 'uint64_t';
          case 'f64': return 'double';
          case 'string': return 'std::string';
          case 'bytes': return 'std::vector<uint8_t>';
          case 'fr': return 'bb::fr';
          case 'field2': return 'std::array<bb::fr, 2>';
          case 'enum_u32':
            // Preserve original enum name if available
            return type.originalName || 'uint32_t';
          case 'map_u32_pair':
            // StateReference is the only map type we've seen
            return 'StateReference';
        }
        break;
      case 'vector': return `std::vector<${this.mapTypeBb(type.element!)}>`;
      case 'array': return `std::array<${this.mapTypeBb(type.element!)}, ${type.size}>`;
      case 'optional': return `std::optional<${this.mapTypeBb(type.element!)}>`;
      case 'struct': return type.struct!.name;
    }
    return 'void';
  }

  /**
   * Generate barretenberg-specific commands header.
   *
   * This generates command structs that use native barretenberg types
   * (bb::fr, MerkleTreeId, etc.) and include execute() declarations.
   * External types (NullifierLeafValue, WorldStateRevision, etc.) are
   * imported via #include instead of being generated.
   */
  generateCommands(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const externals = this.opts.externals || {};

    // Collect unique include paths from externals
    const externalIncludes = new Set<string>();
    for (const header of Object.values(externals)) {
      externalIncludes.add(header);
    }
    for (const inc of this.opts.additionalIncludes || []) {
      externalIncludes.add(inc);
    }

    const includeLines = [...externalIncludes].sort().map(h => `#include "${h}"`).join('\n');
    const usingLines = (this.opts.usingNamespaces || []).map(ns => `using namespace ${ns};`).join('\n');

    // Generate non-external struct types (only SiblingPathAndIndex-like types
    // that are NOT commands/responses and NOT external)
    const helperStructs: string[] = [];
    for (const [name, struct] of schema.structs) {
      if (name.startsWith(prefix)) continue; // Commands are generated below
      if (externals[name]) continue; // External — imported via #include
      // Generate this helper struct
      const fields = struct.fields.map(f => `    ${this.mapTypeBb(f.type)} ${f.name};`).join('\n');
      const fieldNames = struct.fields.map(f => f.name).join(', ');
      const serialization = fieldNames
        ? `    SERIALIZATION_FIELDS(${fieldNames});`
        : `    void msgpack(auto&& pack_fn) { pack_fn(); }`;
      helperStructs.push(
        `struct ${name} {\n    static constexpr const char MSGPACK_SCHEMA_NAME[] = "${name}";\n${fields}\n${serialization}\n    bool operator==(const ${name}&) const = default;\n};`
      );
    }
    for (const [name, struct] of schema.responses) {
      if (name.startsWith(prefix)) continue; // Responses generated nested inside commands
      if (externals[name]) continue;
      // Non-prefixed response types (shouldn't normally happen)
    }

    // Generate command structs with nested Response and execute()
    const commandStructs = schema.commands.map(cmd => {
      const respStruct = schema.responses.get(cmd.responseType);

      // Command fields
      const cmdFields = cmd.fields.map(f => `    ${this.mapTypeBb(f.type)} ${f.name};`).join('\n');
      const cmdFieldNames = cmd.fields.map(f => f.name).join(', ');
      const cmdSerialization = cmdFieldNames
        ? `    SERIALIZATION_FIELDS(${cmdFieldNames});`
        : `    void msgpack(auto&& pack_fn) { pack_fn(); }`;

      // Response fields
      let responseBlock: string;
      if (respStruct && respStruct.fields.length > 0) {
        const respFields = respStruct.fields.map(f => `        ${this.mapTypeBb(f.type)} ${f.name};`).join('\n');
        const respFieldNames = respStruct.fields.map(f => f.name).join(', ');
        responseBlock = `    struct Response {
        static constexpr const char MSGPACK_SCHEMA_NAME[] = "${cmd.responseType}";
${respFields}
        SERIALIZATION_FIELDS(${respFieldNames});
        bool operator==(const Response&) const = default;
    };`;
      } else {
        responseBlock = `    struct Response {
        static constexpr const char MSGPACK_SCHEMA_NAME[] = "${cmd.responseType}";
        void msgpack(auto&& pack_fn) { pack_fn(); }
        bool operator==(const Response&) const = default;
    };`;
      }

      return `struct ${cmd.name} {
    static constexpr const char MSGPACK_SCHEMA_NAME[] = "${cmd.name}";
${responseBlock}
${cmdFields}
    Response execute(${prefix}Request& request) &&;
${cmdSerialization}
    bool operator==(const ${cmd.name}&) const = default;
};`;
    }).join('\n\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

${includeLines}
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace ${ns} {

${usingLines}

// Forward declaration
struct ${prefix}Request;

${helperStructs.join('\n\n')}${helperStructs.length > 0 ? '\n\n' : ''}// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

${commandStructs}

} // namespace ${ns}
`;
  }

  // -----------------------------------------------------------------------
  // Server-side code generation (uses standalone ipc_server.hpp template)
  // -----------------------------------------------------------------------

  /** Generate the server dispatch header */
  generateServerHeader(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const requestType = `${prefix}Request`;

    return `// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

#include "${this.opts.commandsHeader}"
#include "${this.generatedDir()}/ipc_server.hpp"
#include "barretenberg/serialize/msgpack.hpp"

#include <atomic>
#include <string>
#include <vector>

namespace ${ns} {

/**
 * @brief Create an IPC handler that dispatches to command execute() methods.
 *
 * Returns a handler compatible with ipc::serve(). The handler:
 *   1. Deserializes the msgpack request: [[CommandName, {payload}]]
 *   2. String-matches the command name
 *   3. Deserializes payload into the specific command struct
 *   4. Calls cmd.execute(request)
 *   5. Serializes the response as [ResponseName, {fields}]
 *   6. Wraps exceptions in error responses
 */
::ipc::Handler make_${toSnakeCase(prefix)}_handler(${requestType}& request);

/**
 * @brief Start the IPC server on the given socket path.
 * @param shutdown_flag Optional atomic flag for external shutdown (e.g. from signal handlers).
 */
inline void serve(const char* socket_path,
                  ${requestType}& request,
                  std::atomic<bool>* shutdown_flag = nullptr)
{
    ::ipc::serve(socket_path, make_${toSnakeCase(prefix)}_handler(request), shutdown_flag);
}

} // namespace ${ns}
`;
  }

  /** Generate the server dispatch implementation — string-based, no NamedUnion */
  generateServerImpl(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const requestType = `${prefix}Request`;
    const shutdownName = `${prefix}Shutdown`;
    const errorTypeName = schema.errorTypeName || `${prefix}ErrorResponse`;

    const serverHeaderPath = `${this.generatedDir()}/${toSnakeCase(prefix)}_ipc_server.hpp`;

    // Generate dispatch cases for each command
    const dispatchCases = schema.commands.map(cmd => {
      const isShutdown = cmd.name.endsWith('Shutdown');
      const deserialize = cmd.fields.length > 0
        ? `${cmd.name} cmd; cmd_payload.convert(cmd);`
        : `${cmd.name} cmd;`;
      const callExecute = `auto resp = std::move(cmd).execute(request);`;
      const serialize = `pk.pack_array(2); pk.pack(std::string("${cmd.responseType}")); pk.pack(resp);`;

      if (isShutdown) {
        return `        if (cmd_name == "${cmd.name}") {
            ${deserialize}
            ${callExecute}
            msgpack::sbuffer shutdown_buf;
            msgpack::packer<msgpack::sbuffer> spk(shutdown_buf);
            spk.pack_array(2); spk.pack(std::string("${cmd.responseType}")); spk.pack(resp);
            throw ::ipc::ShutdownRequested(
                std::vector<uint8_t>(shutdown_buf.data(), shutdown_buf.data() + shutdown_buf.size()));
        }`;
      }
      return `        if (cmd_name == "${cmd.name}") {
            ${deserialize}
            ${callExecute}
            ${serialize}
        }`;
    }).join(' else ');

    return `// AUTOGENERATED FILE - DO NOT EDIT

#include "${serverHeaderPath}"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <iostream>
#include <string>
#include <string_view>

namespace ${ns} {

::ipc::Handler make_${toSnakeCase(prefix)}_handler(${requestType}& request)
{
    return [&request](const std::vector<uint8_t>& raw_request) -> std::vector<uint8_t> {
        // Parse: [[CommandName, {payload}]]
        auto unpacked = msgpack::unpack(
            reinterpret_cast<const char*>(raw_request.data()), raw_request.size());
        auto obj = unpacked.get();

        if (obj.type != msgpack::type::ARRAY || obj.via.array.size != 1) {
            std::cerr << "Error: Expected array of size 1\\n";
            return {};
        }

        auto& inner = obj.via.array.ptr[0];
        if (inner.type != msgpack::type::ARRAY || inner.via.array.size != 2 ||
            inner.via.array.ptr[0].type != msgpack::type::STR) {
            std::cerr << "Error: Expected [CommandName, {payload}]\\n";
            return {};
        }

        std::string cmd_name(inner.via.array.ptr[0].via.str.ptr, inner.via.array.ptr[0].via.str.size);
        auto& cmd_payload = inner.via.array.ptr[1];

        msgpack::sbuffer resp_buf;
        msgpack::packer<msgpack::sbuffer> pk(resp_buf);

        try {
${dispatchCases} else {
                // Unknown command
                pk.pack_array(2);
                pk.pack(std::string("${errorTypeName}"));
                pk.pack_map(1);
                pk.pack(std::string("message"));
                pk.pack(std::string("unknown command: ") + cmd_name);
            }
        } catch (const ::ipc::ShutdownRequested&) {
            throw;
        } catch (const std::exception& e) {
            std::cerr << "Error processing " << cmd_name << ": " << e.what() << '\\n';
            resp_buf.clear();
            msgpack::packer<msgpack::sbuffer> epk(resp_buf);
            epk.pack_array(2);
            epk.pack(std::string("${errorTypeName}"));
            epk.pack_map(1);
            epk.pack(std::string("message"));
            epk.pack(std::string(e.what()));
        }

        return std::vector<uint8_t>(resp_buf.data(), resp_buf.data() + resp_buf.size());
    };
}

} // namespace ${ns}
`;
  }
}
