/**
 * C++ IPC Client Code Generator
 *
 * Generates a C++ IPC client from a CompiledSchema. The generated client:
 *   - Connects to a server over Unix Domain Socket via ipc::IpcClient
 *   - Wraps each command in a NamedUnion, serializes with msgpack, sends, receives, deserializes
 *   - Has one method per command, returning the typed response
 *
 * Usage:
 *   const gen = new CppCodegen({ namespace: 'bb::cdb', prefix: 'Cdb' });
 *   const header = gen.generateHeader(schema);
 *   const impl = gen.generateImpl(schema);
 */

import type { CompiledSchema, Type, Struct, Field, Command } from './schema_visitor.ts';
import { toSnakeCase } from './naming.ts';

export interface CppCodegenOptions {
  /** C++ namespace for generated code, e.g. 'bb::cdb' */
  namespace: string;
  /** Prefix for command/response types, e.g. 'Cdb' */
  prefix: string;
  /** Header path for the *_execute.hpp file that defines Command/CommandResponse NamedUnions */
  executeHeader: string;
  /** Header path for the *_commands.hpp file that defines the command structs */
  commandsHeader: string;
}

export class CppCodegen {
  constructor(private opts: CppCodegenOptions) {}

  /** Convert a command name to a C++ method name (snake_case without prefix) */
  private methodName(commandName: string): string {
    // Strip prefix: "CdbGetContractInstance" -> "GetContractInstance" -> "get_contract_instance"
    const withoutPrefix = commandName.startsWith(this.opts.prefix)
      ? commandName.slice(this.opts.prefix.length)
      : commandName;
    return toSnakeCase(withoutPrefix);
  }

  /** Check if the response has fields (non-void return) */
  private hasResponseFields(command: Command, schema: CompiledSchema): boolean {
    const resp = schema.responses.get(command.responseType);
    return !!resp && resp.fields.length > 0;
  }

  /** Generate the method signature using command struct types directly */
  private generateMethodSignature(command: Command, schema: CompiledSchema, className?: string): string {
    const method = this.methodName(command.name);
    const hasFields = this.hasResponseFields(command, schema);
    const retType = hasFields ? `${command.name}::Response` : 'void';

    // If the command has fields, take the whole command struct by value
    const params = command.fields.length > 0 ? `${command.name} cmd` : '';

    const prefix = className ? `${className}::` : '';
    const constSuffix = !this.isWriteCommand(command) ? ' const' : '';

    return `${retType} ${prefix}${method}(${params})${constSuffix}`;
  }

  /** Check if a command modifies state (non-const) */
  private isWriteCommand(command: Command): boolean {
    const name = command.name.toLowerCase();
    return name.includes('add') || name.includes('create') ||
      name.includes('commit') || name.includes('revert') ||
      name.includes('register') || name.includes('shutdown') ||
      name.includes('delete') || name.includes('sync') ||
      name.includes('rollback') || name.includes('unwind');
  }

  /** Generate the header file */
  generateHeader(schema: CompiledSchema, schemaHash?: string): string {
    const { namespace: ns, prefix } = this.opts;
    const className = `${prefix}IpcClient`;
    const guardName = `${ns.replace(/::/g, '_').toUpperCase()}_${prefix.toUpperCase()}_IPC_CLIENT_GENERATED_HPP`;

    const methods = schema.commands.map(cmd => {
      const sig = this.generateMethodSignature(cmd, schema);
      return `    ${sig};`;
    }).join('\n');

    const hashConstant = schemaHash
      ? `\n/** Schema version hash for compatibility checking */\nstatic constexpr const char SCHEMA_HASH[] = "${schemaHash}";\n`
      : '';

    return `// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

#include "barretenberg/common/try_catch_shim.hpp"
#include "${this.opts.executeHeader}"
#include "barretenberg/ipc/ipc_client.hpp"

#include <memory>
#include <string>

namespace ${ns} {
${hashConstant}
/**
 * @brief Auto-generated IPC client.
 *
 * Each method sends a msgpack-serialized command to the server over UDS
 * and returns the typed response. All methods block until the response arrives.
 */
class ${className} {
  public:
    explicit ${className}(const std::string& socket_path);
    ~${className}();

    ${className}(const ${className}&) = delete;
    ${className}& operator=(const ${className}&) = delete;

${methods}

  private:
    template <typename Cmd>
    typename Cmd::Response send(Cmd&& cmd) const;

    mutable std::unique_ptr<ipc::IpcClient> client_;
};

} // namespace ${ns}
`;
  }

  /** Generate the implementation file */
  generateImpl(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const className = `${prefix}IpcClient`;
    const commandType = `${prefix}Command`;
    const responseType = `${prefix}CommandResponse`;
    const errorType = `${prefix}ErrorResponse`;

    const methods = schema.commands.map(cmd => {
      return this.generateMethodImpl(cmd, schema, className);
    }).join('\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT

#include "${this.headerIncludePath()}"
#include "${this.opts.executeHeader}"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <stdexcept>
#include <tuple>

namespace ${ns} {

${className}::${className}(const std::string& socket_path)
    : client_(ipc::IpcClient::create_socket(socket_path))
{
    if (!client_->connect()) {
        throw std::runtime_error("Failed to connect to server at " + socket_path);
    }
}

${className}::~${className}()
{
    if (client_) {
        client_->close();
    }
}

template <typename Cmd>
typename Cmd::Response ${className}::send(Cmd&& cmd) const
{
    // Wrap command in ${commandType} NamedUnion, then in a 1-element tuple (matches server expectations)
    ${commandType} command = std::forward<Cmd>(cmd);
    auto wrapped = std::make_tuple(std::move(command));

    // Serialize to msgpack
    msgpack::sbuffer send_buffer;
    msgpack::pack(send_buffer, wrapped);

    // Send to server
    constexpr uint64_t timeout_ns = 30'000'000'000ULL; // 30 seconds
    if (!client_->send(send_buffer.data(), send_buffer.size(), timeout_ns)) {
        throw std::runtime_error("Failed to send command to server");
    }

    // Receive response
    auto response_span = client_->receive(timeout_ns);
    if (response_span.empty()) {
        throw std::runtime_error("Empty response from server");
    }

    // Deserialize response
    auto unpacked = msgpack::unpack(reinterpret_cast<const char*>(response_span.data()), response_span.size());
    auto response_obj = unpacked.get();

    ${responseType} response;
    response_obj.convert(response);

    // Release the receive buffer
    client_->release(response_span.size());

    // Check for error response
    return std::move(response).visit([](auto&& resp) -> typename Cmd::Response {
        using RespType = std::decay_t<decltype(resp)>;

        if constexpr (std::is_same_v<RespType, ${errorType}>) {
            throw std::runtime_error("Server error: " + resp.message);
        } else if constexpr (std::is_same_v<RespType, typename Cmd::Response>) {
            return std::forward<decltype(resp)>(resp);
        } else {
            throw std::runtime_error("Unexpected response type from server");
        }
    });
}

${methods}
} // namespace ${ns}
`;
  }

  /** Generate a single method implementation */
  private generateMethodImpl(command: Command, schema: CompiledSchema, className: string): string {
    const sig = this.generateMethodSignature(command, schema, className);
    const hasFields = this.hasResponseFields(command, schema);

    const cmdExpr = command.fields.length > 0 ? 'std::move(cmd)' : `${command.name}{}`;

    if (!hasFields) {
      return `${sig}
{
    send(${cmdExpr});
}
`;
    }

    return `${sig}
{
    return send(${cmdExpr});
}
`;
  }

  /** Compute the include path for the generated header */
  private headerIncludePath(): string {
    // Derive from the executeHeader path: replace _execute.hpp with _ipc_client_generated.hpp
    const dir = this.opts.executeHeader.substring(0, this.opts.executeHeader.lastIndexOf('/'));
    return `${dir}/${toSnakeCase(this.opts.prefix)}_ipc_client_generated.hpp`;
  }

  // -----------------------------------------------------------------------
  // Standalone types (no barretenberg dependencies)
  // -----------------------------------------------------------------------

  /** Generate standalone C++ types with MSGPACK_DEFINE_MAP — no barretenberg deps */
  generateStandaloneTypes(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;

    // Map schema types to C++ types
    const mapType = (type: import('./schema_visitor.ts').Type): string => {
      switch (type.kind) {
        case 'primitive':
          switch (type.primitive) {
            case 'bool': return 'bool';
            case 'u8': return 'uint8_t';
            case 'u16': return 'uint16_t';
            case 'u32': return 'uint32_t';
            case 'u64': return 'uint64_t';
            case 'f64': return 'double';
            case 'string': return 'std::string';
            case 'bytes': return 'std::vector<uint8_t>';
            case 'field2': return 'std::array<std::vector<uint8_t>, 2>';
            case 'enum_u32': return 'uint32_t';
            case 'map_u32_pair': return 'std::unordered_map<uint32_t, std::pair<std::vector<uint8_t>, uint64_t>>';
          }
          break;
        case 'vector': return `std::vector<${mapType(type.element!)}>`;
        case 'array': return `std::array<${mapType(type.element!)}, ${type.size}>`;
        case 'optional': return `std::optional<${mapType(type.element!)}>`;
        case 'struct': return type.struct!.name;
      }
      return 'void';
    };

    const allStructs = [...schema.structs.values(), ...schema.responses.values()];
    const structs = allStructs.map(s => {
      const fields = s.fields.map(f => `    ${mapType(f.type)} ${f.name};`).join('\n');
      const fieldNames = s.fields.map(f => f.name).join(', ');
      // MSGPACK_DEFINE_MAP() with no args doesn't compile; empty structs pack as empty maps
      const define = fieldNames
        ? `    MSGPACK_DEFINE_MAP(${fieldNames})`
        : `    template <typename Packer> void msgpack_pack(Packer& pk) const { pk.pack_map(0); }\n    void msgpack_unpack(msgpack::object const&) {}`;
      return `struct ${s.name} {\n${fields}\n${define}\n};`;
    }).join('\n\n');

    return `// AUTOGENERATED FILE - DO NOT EDIT
// Standalone types for ${prefix} service — no barretenberg dependencies.
#pragma once

// Aztec fork of msgpack-c uses THROW/RETHROW macros
#ifndef THROW
#define THROW throw
#endif
#ifndef RETHROW
#define RETHROW throw
#endif

#include <msgpack.hpp>
#include <array>
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

namespace ${ns} {

${structs}

} // namespace ${ns}
`;
  }

  // -----------------------------------------------------------------------
  // Server-side code generation
  // -----------------------------------------------------------------------

  /** Generate the server dispatch header */
  generateServerHeader(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const commandType = `${prefix}Command`;
    const responseType = `${prefix}CommandResponse`;
    const requestType = `${prefix}Request`;
    const guardName = `${ns.replace(/::/g, '_').toUpperCase()}_${prefix.toUpperCase()}_IPC_SERVER_GENERATED_HPP`;

    return `// AUTOGENERATED FILE - DO NOT EDIT
#pragma once

#include "${this.opts.executeHeader}"
#include "barretenberg/ipc/ipc_server.hpp"
#include "barretenberg/serialize/msgpack.hpp"

#include <cstdint>
#include <functional>
#include <span>
#include <string>
#include <vector>

namespace ${ns} {

/**
 * @brief Type alias for the dispatch function.
 *
 * Takes a ${requestType}& and a ${commandType}&& and returns a ${responseType}.
 * This is typically the top-level \`${toSnakeCase(prefix)}()\` function from ${toSnakeCase(prefix)}_execute.hpp.
 */
using ${prefix}DispatchFn = std::function<${responseType}(${requestType}&, ${commandType}&&)>;

/**
 * @brief Create an IPC server handler from a dispatch function.
 *
 * Returns a lambda compatible with ipc::IpcServer::run(). The handler:
 *   1. Deserializes the msgpack request: [[CommandName, {payload}]]
 *   2. Detects shutdown commands (${prefix}Shutdown)
 *   3. Dispatches to the provided function
 *   4. Serializes the response
 *   5. Wraps exceptions in ${prefix}ErrorResponse
 */
ipc::IpcServer::Handler make_${toSnakeCase(prefix)}_handler(
    ${requestType}& request,
    ${prefix}DispatchFn dispatch);

} // namespace ${ns}
`;
  }

  /** Generate the server dispatch implementation */
  generateServerImpl(schema: CompiledSchema): string {
    const { namespace: ns, prefix } = this.opts;
    const commandType = `${prefix}Command`;
    const responseType = `${prefix}CommandResponse`;
    const errorType = `${prefix}ErrorResponse`;
    const requestType = `${prefix}Request`;
    const shutdownName = `${prefix}Shutdown`;

    const dir = this.opts.executeHeader.substring(0, this.opts.executeHeader.lastIndexOf('/'));
    const serverHeaderPath = `${dir}/${toSnakeCase(prefix)}_ipc_server_generated.hpp`;

    return `// AUTOGENERATED FILE - DO NOT EDIT

#include "${serverHeaderPath}"
#include "barretenberg/serialize/msgpack.hpp"
#include "barretenberg/serialize/msgpack_impl.hpp"

#include <iostream>
#include <string_view>

namespace ${ns} {

ipc::IpcServer::Handler make_${toSnakeCase(prefix)}_handler(
    ${requestType}& request,
    ${prefix}DispatchFn dispatch)
{
    return [&request, dispatch = std::move(dispatch)](
               int client_id, std::span<const uint8_t> raw_request) -> std::vector<uint8_t> {
        try {
            // Deserialize: [[CommandName, {payload}]]
            auto unpacked = msgpack::unpack(
                reinterpret_cast<const char*>(raw_request.data()), raw_request.size());
            auto obj = unpacked.get();

            if (obj.type != msgpack::type::ARRAY || obj.via.array.size != 1) {
                std::cerr << "Error: Expected array of size 1 from client " << client_id << '\\n';
                return {};
            }

            auto& command_obj = obj.via.array.ptr[0];

            // Check for shutdown before converting
            bool is_shutdown = false;
            if (command_obj.type == msgpack::type::ARRAY && command_obj.via.array.size == 2 &&
                command_obj.via.array.ptr[0].type == msgpack::type::STR) {
                std::string_view command_name(
                    command_obj.via.array.ptr[0].via.str.ptr,
                    command_obj.via.array.ptr[0].via.str.size);
                is_shutdown = (command_name == "${shutdownName}");
            }

            // Convert and dispatch
            ${commandType} command;
            command_obj.convert(command);
            auto response = dispatch(request, std::move(command));

            // Serialize response
            msgpack::sbuffer response_buffer;
            msgpack::pack(response_buffer, response);
            std::vector<uint8_t> result(
                response_buffer.data(), response_buffer.data() + response_buffer.size());

            if (is_shutdown) {
                throw ipc::ShutdownRequested(std::move(result));
            }

            return result;

        } catch (const ipc::ShutdownRequested&) {
            throw;
        } catch (const std::exception& e) {
            std::cerr << "Error processing request from client " << client_id
                      << ": " << e.what() << '\\n';
            std::cerr.flush();

            ${errorType} error_response{ .message = std::string(e.what()) };
            ${responseType} response = error_response;

            msgpack::sbuffer response_buffer;
            msgpack::pack(response_buffer, response);
            return std::vector<uint8_t>(
                response_buffer.data(), response_buffer.data() + response_buffer.size());
        }
    };
}

} // namespace ${ns}
`;
  }
}
