/**
 * Multi-service, multi-language code generation from committed schema JSON files.
 *
 * Architecture:
 *   Committed JSON schemas → SchemaVisitor → CompiledSchema IR → Language Codegens → Files
 *
 * No C++ binary dependency at generation time. Schemas are committed as
 * static JSON files in schemas/ and validated against C++ binaries in CI.
 *
 * Usage:
 *   npx tsx src/generate.ts              # Generate all services
 *   npx tsx src/generate.ts bb            # Generate only bb
 *   npx tsx src/generate.ts wsdb cdb      # Generate wsdb and cdb
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { unpack } from 'msgpackr';
import { generateForService, SERVICES } from './service_codegen.js';

// @ts-ignore
const __dirname = dirname(fileURLToPath(import.meta.url));

function generateCurveConstants(outputDir: string) {
  // Read curve constants from committed msgpack file
  const constantsPath = join(__dirname, '../schemas/bb_curve_constants.msgpack');
  const constantsBuffer = readFileSync(constantsPath);
  const constants = unpack(constantsBuffer);

  const toBigInt = (bytes: Uint8Array) => {
    let result = 0n;
    for (const byte of bytes) {
      result = (result << 8n) | BigInt(byte);
    }
    return result;
  };

  const serializeCoordinate = (coord: Uint8Array | Uint8Array[]) => {
    if (Array.isArray(coord)) {
      return `[${coord.map(c => `new Uint8Array([${Array.from(c).join(', ')}])`).join(', ')}]`;
    } else {
      return `new Uint8Array([${Array.from(coord).join(', ')}])`;
    }
  };

  const content = `/**
 * Curve constants generated from barretenberg.
 * DO NOT EDIT - This file is auto-generated by barretenberg/codegen
 */

export const BN254_FR_MODULUS = ${toBigInt(constants.bn254_fr_modulus)}n;
export const BN254_FQ_MODULUS = ${toBigInt(constants.bn254_fq_modulus)}n;

export const BN254_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g1_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g1_generator.y)},
} as const;

export const BN254_G2_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g2_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g2_generator.y)},
} as const;

export const GRUMPKIN_FR_MODULUS = ${toBigInt(constants.grumpkin_fr_modulus)}n;
export const GRUMPKIN_FQ_MODULUS = ${toBigInt(constants.grumpkin_fq_modulus)}n;

export const GRUMPKIN_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.grumpkin_g1_generator.x)},
  y: ${serializeCoordinate(constants.grumpkin_g1_generator.y)},
} as const;

export const SECP256K1_FR_MODULUS = ${toBigInt(constants.secp256k1_fr_modulus)}n;
export const SECP256K1_FQ_MODULUS = ${toBigInt(constants.secp256k1_fq_modulus)}n;

export const SECP256K1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256k1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256k1_g1_generator.y)},
} as const;

export const SECP256R1_FR_MODULUS = ${toBigInt(constants.secp256r1_fr_modulus)}n;
export const SECP256R1_FQ_MODULUS = ${toBigInt(constants.secp256r1_fq_modulus)}n;

export const SECP256R1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256r1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256r1_g1_generator.y)},
} as const;
`;

  mkdirSync(outputDir, { recursive: true });
  const outputPath = join(outputDir, 'curve_constants.ts');
  writeFileSync(outputPath, content);
  console.log(`  [curve_constants] ${outputPath}`);
}

function generate() {
  const args = process.argv.slice(2);
  const requestedServices = args.length > 0 ? args : Object.keys(SERVICES);

  for (const name of requestedServices) {
    if (!SERVICES[name]) {
      console.error(`Unknown service: ${name}. Available: ${Object.keys(SERVICES).join(', ')}`);
      process.exit(1);
    }
  }

  console.log(`Generating bindings for: ${requestedServices.join(', ')}\n`);

  for (const name of requestedServices) {
    console.log(`--- ${name} ---`);
    generateForService(SERVICES[name], __dirname);
    console.log('');
  }

  // Generate curve constants (only if bb is included)
  if (requestedServices.includes('bb')) {
    console.log('--- curve constants ---');
    const outputDir = join(__dirname, '../../ts/src/cbind/generated');
    generateCurveConstants(outputDir);
    console.log('');
  }

  console.log('Generation complete.');
}

generate();
