/**
 * Multi-service, multi-language code generation from committed schema JSON files.
 *
 * Architecture:
 *   Committed JSON schemas → SchemaVisitor → CompiledSchema IR → Language Codegens → Files
 *
 * Zero npm dependencies — runs with just Node.js (v22+ has native TS support via --experimental-strip-types).
 *
 * Usage:
 *   node --experimental-strip-types src/generate.ts         # Node 22+
 *   npx tsx src/generate.ts                                  # With tsx
 *   npx tsx src/generate.ts bb                               # Single service
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { generateForService, SERVICES } from './service_codegen.js';

// @ts-ignore
const __dirname = dirname(fileURLToPath(import.meta.url));

/** Convert hex string to BigInt */
function hexToBigInt(hex: string): bigint {
  return BigInt('0x' + hex);
}

/** Convert hex string to Uint8Array byte list for TS codegen */
function hexToByteList(hex: string): string {
  const bytes: number[] = [];
  for (let i = 0; i < hex.length; i += 2) {
    bytes.push(parseInt(hex.substring(i, i + 2), 16));
  }
  return `new Uint8Array([${bytes.join(', ')}])`;
}

function serializeCoordinate(coord: string | string[]): string {
  if (Array.isArray(coord)) {
    return `[${coord.map(c => hexToByteList(c)).join(', ')}]`;
  }
  return hexToByteList(coord);
}

function generateCurveConstants(outputDir: string) {
  const constantsPath = join(__dirname, '../schemas/bb_curve_constants.json');
  const constants = JSON.parse(readFileSync(constantsPath, 'utf-8'));

  const content = `/**
 * Curve constants generated from barretenberg.
 * DO NOT EDIT - This file is auto-generated by barretenberg/codegen
 */

export const BN254_FR_MODULUS = ${hexToBigInt(constants.bn254_fr_modulus)}n;
export const BN254_FQ_MODULUS = ${hexToBigInt(constants.bn254_fq_modulus)}n;

export const BN254_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g1_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g1_generator.y)},
} as const;

export const BN254_G2_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g2_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g2_generator.y)},
} as const;

export const GRUMPKIN_FR_MODULUS = ${hexToBigInt(constants.grumpkin_fr_modulus)}n;
export const GRUMPKIN_FQ_MODULUS = ${hexToBigInt(constants.grumpkin_fq_modulus)}n;

export const GRUMPKIN_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.grumpkin_g1_generator.x)},
  y: ${serializeCoordinate(constants.grumpkin_g1_generator.y)},
} as const;

export const SECP256K1_FR_MODULUS = ${hexToBigInt(constants.secp256k1_fr_modulus)}n;
export const SECP256K1_FQ_MODULUS = ${hexToBigInt(constants.secp256k1_fq_modulus)}n;

export const SECP256K1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256k1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256k1_g1_generator.y)},
} as const;

export const SECP256R1_FR_MODULUS = ${hexToBigInt(constants.secp256r1_fr_modulus)}n;
export const SECP256R1_FQ_MODULUS = ${hexToBigInt(constants.secp256r1_fq_modulus)}n;

export const SECP256R1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256r1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256r1_g1_generator.y)},
} as const;
`;

  mkdirSync(outputDir, { recursive: true });
  writeFileSync(join(outputDir, 'curve_constants.ts'), content);
  console.log(`  [curve_constants] ${join(outputDir, 'curve_constants.ts')}`);
}

function generate() {
  const args = process.argv.slice(2);
  const requestedServices = args.length > 0 ? args : Object.keys(SERVICES);

  for (const name of requestedServices) {
    if (!SERVICES[name]) {
      console.error(`Unknown service: ${name}. Available: ${Object.keys(SERVICES).join(', ')}`);
      process.exit(1);
    }
  }

  console.log(`Generating bindings for: ${requestedServices.join(', ')}\n`);

  for (const name of requestedServices) {
    console.log(`--- ${name} ---`);
    generateForService(SERVICES[name], __dirname);
    console.log('');
  }

  if (requestedServices.includes('bb')) {
    console.log('--- curve constants ---');
    generateCurveConstants(join(__dirname, '../../ts/src/cbind/generated'));
    console.log('');
  }

  console.log('Generation complete.');
}

generate();
