#!/bin/bash
# Shared CLI configuration for documentation generation scripts
# Source this file to get CLI configuration variables
#
# Usage:
#   source "$(dirname "${BASH_SOURCE[0]}")/cli_config.sh"
#   get_cli_config "aztec"
#   echo "$CLI_DISPLAY_NAME"  # "Aztec CLI"

# Valid CLI names
# Note: bb CLI docs are now in barretenberg/docs - see barretenberg/docs/scripts/generate_bb_cli_docs.sh
readonly VALID_CLIS=("aztec" "aztec-wallet")

# Get configuration for a CLI
# Sets: CLI_DISPLAY_NAME, CLI_TITLE, CLI_COMMAND, CLI_FORMAT,
#       CLI_OUTPUT_FILE, CLI_SIDEBAR_POSITION, CLI_TAGS
#
# CLI_SIDEBAR_POSITION controls the order in Docusaurus sidebar:
#   1 = aztec (primary CLI, listed first)
#   2 = aztec-wallet (secondary CLI)
#   3 = bb (Barretenberg proving backend)
get_cli_config() {
  local cli_name="$1"

  case "$cli_name" in
    aztec)
      CLI_DISPLAY_NAME="Aztec CLI"
      CLI_TITLE="Aztec CLI Reference"
      CLI_COMMAND="aztec"
      CLI_FORMAT="commander"
      CLI_OUTPUT_FILE="aztec_cli_reference.md"
      CLI_SIDEBAR_POSITION="1"
      CLI_TAGS="[cli, reference, autogenerated]"
      ;;
    aztec-wallet)
      CLI_DISPLAY_NAME="Aztec Wallet CLI"
      CLI_TITLE="Aztec Wallet CLI Reference"
      CLI_COMMAND="aztec-wallet"
      CLI_FORMAT="commander"
      CLI_OUTPUT_FILE="aztec_wallet_cli_reference.md"
      CLI_SIDEBAR_POSITION="2"
      CLI_TAGS="[cli, reference, autogenerated, wallet]"
      ;;
    *)
      echo "Error: Unknown CLI '$cli_name'. Valid options: ${VALID_CLIS[*]}" >&2
      return 1
      ;;
  esac
}

# Validate CLI name
validate_cli_name() {
  local cli_name="$1"
  for valid in "${VALID_CLIS[@]}"; do
    if [[ "$cli_name" == "$valid" ]]; then
      return 0
    fi
  done
  echo "Error: Invalid CLI name '$cli_name'. Must be one of: ${VALID_CLIS[*]}" >&2
  return 1
}

# Get install instructions for a CLI
get_cli_install_instructions() {
  local cli_name="$1"
  case "$cli_name" in
    bb)
      echo "Install bb from: https://github.com/AztecProtocol/aztec-packages"
      ;;
    *)
      echo "Run: aztec-up <version>"
      ;;
  esac
}

