FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/yarn-project AS builder
WORKDIR /usr/src/yarn-project/canary
# Productionify. See comment in yarn-project-base/Dockerfile.
RUN yarn cache clean && \
    mv ../.yarnrc.prod.yml ../.yarnrc.yml && \
    yarn workspaces focus --production > /dev/null && \
    rm -rf /usr/src/.yarn

FROM node:18-alpine
COPY --from=builder /usr/src /usr/src
WORKDIR /usr/src/yarn-project/canary
ENTRYPOINT ["yarn", "test"]