VERSION 0.8

start-server:
  LOCALLY
  # TODO(AD): use secrets to decide whether to use s3 backing/storing
  RUN ./start_server.sh

setup-cache-helper:
  FROM scratch
  COPY cache-download-direct.sh cache-upload-direct.sh cache-download.sh cache-upload.sh .
  SAVE ARTIFACT ./*

SETUP_CACHE:
  FUNCTION
  # make sure server is up locally
  WAIT
    BUILD +start-server
  END
  COPY +setup-cache-helper/cache-download-direct.sh +setup-cache-helper/cache-upload-direct.sh +setup-cache-helper/cache-download.sh +setup-cache-helper/cache-upload.sh .
  # configure AWS access (note these can be blank if server started without s3 backing)
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY mkdir -p ~/.aws && \
      bash -c 'echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials'

test:
  FROM ../../build-images/+from-registry
  RUN apt update && apt install -y npm lsof
  RUN git init
  COPY *.sh *.json *.js *.lock build-system/cache-tool/
  COPY tests/*.js build-system/cache-tool/tests/
  WORKDIR build-system/cache-tool
  RUN git config --global user.email "tech@aztecprotocol.com" && git config --global user.name "Aztec CI"
  RUN git add . && git commit -m "."
  # configure AWS access
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY mkdir -p ~/.aws && \
      bash -c 'echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials'
  RUN npm install && npm test

test-earthly-connectivity:
  FROM ../../build-images/+from-registry
  DO +SETUP_CACHE
  RUN --secret AZTEC_CACHE_TOOL_IP \
     nc -vz $AZTEC_CACHE_TOOL_IP 8337