VERSION 0.8

start-server:
  LOCALLY
  # TODO(AD): use secrets to decide whether to use s3 backing/storing
  RUN ./start_server.sh

setup-cache-helper:
  FROM scratch
  COPY cache-download-direct.sh cache-upload-direct.sh cache-download.sh cache-upload.sh .

SETUP_CACHE:
  FUNCTION
  BUILD +start-server
  COPY +setup-cache-helper/cache-download-direct.sh +setup-cache-helper/cache-upload-direct.sh +setup-cache-helper/cache-download.sh +setup-cache-helper/cache-upload.sh .

test:
  FROM ../../build-images/+from-registry
  RUN apt update && apt install -y npm lsof
  RUN git init
  COPY *.sh *.json *.js *.lock tests/*.js build-system/cache-tool
  WORKDIR build-system/cache-tool
  RUN ./start_server.sh
  RUN yarn test