VERSION 0.8

start-server:
  LOCALLY
  # TODO(AD): use secrets to decide whether to use s3 backing/storing
  RUN ./start_server.sh

setup-cache-helper:
  FROM scratch
  COPY cache-download.sh cache-upload.sh .

SETUP_CACHE:
  FUNCTION
  BUILD +start-server
  COPY +setup-cache-helper/cache-download.sh +setup-cache-helper/cache-upload.sh .
