#!/usr/bin/env bash
# Netlify ignore script: Skip builds if no docs-related files changed
# Exit 0 = skip build, Exit 1 = proceed with build
#
# This script runs from the docs/ directory (Netlify base)
#
# Strategy:
# - Production deploys (next branch): Compare against CACHED_COMMIT_REF (last deployed commit)
# - PR previews (other branches): Compare against merge-base with next (changes introduced by PR)
#
# This ensures:
# - Production builds when docs change on next (including nightly releases)
# - PR previews only build when the PR has docs changes (no clutter on non-docs PRs)

set -euo pipefail

BASE_BRANCH="next"

# Determine the comparison reference based on deploy context
if [ "${BRANCH:-}" = "$BASE_BRANCH" ]; then
  # Production deploy on the base branch - use CACHED_COMMIT_REF
  if [ -z "${CACHED_COMMIT_REF:-}" ]; then
    echo "Production deploy without cached commit reference - proceeding with build"
    exit 1
  fi
  COMPARE_REF="$CACHED_COMMIT_REF"
  echo "Production deploy: comparing $COMMIT_REF against last deployed commit $COMPARE_REF"
else
  # PR preview or branch deploy - use merge-base to detect PR-specific changes
  # Fetch the base branch to ensure we have it available for merge-base comparison
  git fetch origin "$BASE_BRANCH" 2>/dev/null || true

  COMPARE_REF=$(git merge-base "origin/$BASE_BRANCH" "$COMMIT_REF" 2>/dev/null || echo "")

  if [ -z "$COMPARE_REF" ]; then
    echo "Could not determine merge base with $BASE_BRANCH - proceeding with build"
    exit 1
  fi
  echo "PR preview: comparing $COMMIT_REF against merge base $COMPARE_REF (from $BASE_BRANCH)"
fi

# Check for ANY changes in the docs/ directory (current directory in Netlify context)
if ! git diff --quiet "$COMPARE_REF" "$COMMIT_REF" -- .; then
  echo "Changes detected in docs/ directory - proceeding with build"
  exit 1
fi

# Check for changes in noir-projects/aztec-nr (source for autogenerated aztec-nr docs)
if ! git diff --quiet "$COMPARE_REF" "$COMMIT_REF" -- ../noir-projects/aztec-nr; then
  echo "Changes detected in noir-projects/aztec-nr - proceeding with build"
  exit 1
fi

# Extract all #include_code file references from markdown files
# Pattern: #include_code identifier /path/to/file language
# Paths are relative to repo root
INCLUDE_CODE_PATHS=$(
  find . -type f \( -name "*.md" -o -name "*.mdx" \) 2>/dev/null | \
  xargs grep -h '^#include_code' 2>/dev/null | \
  awk '{ gsub("^/", "", $3); print $3 }' | \
  sort -u || true
)

# Check each referenced external file for changes
for path in $INCLUDE_CODE_PATHS; do
  if [ -n "$path" ]; then
    if ! git diff --quiet "$COMPARE_REF" "$COMMIT_REF" -- "../$path" 2>/dev/null; then
      echo "Changes detected in included file: $path - proceeding with build"
      exit 1
    fi
  fi
done

echo "No docs-related changes detected - skipping build"
exit 0
