import { ProvingRequestType } from '@aztec/stdlib/proofs';

export const WITGEN_DELAY_MS: Record<ProvingRequestType, number> = {
  [ProvingRequestType.PARITY_BASE]: 60,
  [ProvingRequestType.BLOCK_MERGE_ROLLUP]: 650,
  [ProvingRequestType.BLOCK_ROOT_FIRST_ROLLUP]: 60_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_FIRST_ROLLUP]: 40_000,
  [ProvingRequestType.BLOCK_ROOT_EMPTY_TX_FIRST_ROLLUP]: 20_000,
  [ProvingRequestType.BLOCK_ROOT_ROLLUP]: 40_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_ROLLUP]: 20_000,
  [ProvingRequestType.CHECKPOINT_ROOT_ROLLUP]: 40_000,
  [ProvingRequestType.CHECKPOINT_ROOT_SINGLE_BLOCK_ROLLUP]: 20_000,
  [ProvingRequestType.CHECKPOINT_PADDING_ROLLUP]: 0,
  [ProvingRequestType.CHECKPOINT_MERGE_ROLLUP]: 650,
  [ProvingRequestType.TX_MERGE_ROLLUP]: 0,
  [ProvingRequestType.PRIVATE_TX_BASE_ROLLUP]: 400_000,
  [ProvingRequestType.PUBLIC_TX_BASE_ROLLUP]: 470_000,
  [ProvingRequestType.PARITY_ROOT]: 100,
  [ProvingRequestType.ROOT_ROLLUP]: 650,
  [ProvingRequestType.PUBLIC_TUBE]: 0,
  [ProvingRequestType.PUBLIC_VM]: 0,
};

export const PROOF_DELAY_MS: Record<ProvingRequestType, number> = {
  [ProvingRequestType.PARITY_BASE]: 3_000,
  [ProvingRequestType.BLOCK_MERGE_ROLLUP]: 15_000,
  [ProvingRequestType.BLOCK_ROOT_FIRST_ROLLUP]: 55_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_FIRST_ROLLUP]: 35_000,
  [ProvingRequestType.BLOCK_ROOT_EMPTY_TX_FIRST_ROLLUP]: 15_000,
  [ProvingRequestType.BLOCK_ROOT_ROLLUP]: 35_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_ROLLUP]: 15_000,
  [ProvingRequestType.CHECKPOINT_ROOT_ROLLUP]: 35_000,
  [ProvingRequestType.CHECKPOINT_ROOT_SINGLE_BLOCK_ROLLUP]: 15_000,
  [ProvingRequestType.CHECKPOINT_PADDING_ROLLUP]: 0,
  [ProvingRequestType.CHECKPOINT_MERGE_ROLLUP]: 15_000,
  [ProvingRequestType.TX_MERGE_ROLLUP]: 0,
  [ProvingRequestType.PRIVATE_TX_BASE_ROLLUP]: 145_000,
  [ProvingRequestType.PUBLIC_TX_BASE_ROLLUP]: 160_000,
  [ProvingRequestType.PARITY_ROOT]: 30_000,
  [ProvingRequestType.ROOT_ROLLUP]: 15_000,
  [ProvingRequestType.PUBLIC_TUBE]: 30_000,
  [ProvingRequestType.PUBLIC_VM]: 0,
};
