import { ProvingRequestType } from '@aztec/stdlib/proofs';

export const WITGEN_DELAY_MS: Record<ProvingRequestType, number> = {
  [ProvingRequestType.PARITY_BASE]: 2000,
  [ProvingRequestType.BLOCK_MERGE_ROLLUP]: 30,
  [ProvingRequestType.BLOCK_ROOT_FIRST_ROLLUP]: 60_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_FIRST_ROLLUP]: 40_000,
  [ProvingRequestType.BLOCK_ROOT_EMPTY_TX_FIRST_ROLLUP]: 18,
  [ProvingRequestType.BLOCK_ROOT_ROLLUP]: 40_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_ROLLUP]: 20_000,
  [ProvingRequestType.CHECKPOINT_ROOT_ROLLUP]: 40_000,
  [ProvingRequestType.CHECKPOINT_ROOT_SINGLE_BLOCK_ROLLUP]: 36_000,
  [ProvingRequestType.CHECKPOINT_PADDING_ROLLUP]: 0,
  [ProvingRequestType.CHECKPOINT_MERGE_ROLLUP]: 30,
  [ProvingRequestType.TX_MERGE_ROLLUP]: 0,
  [ProvingRequestType.PRIVATE_TX_BASE_ROLLUP]: 400_000,
  [ProvingRequestType.PUBLIC_TX_BASE_ROLLUP]: 470_000,
  [ProvingRequestType.PARITY_ROOT]: 39,
  [ProvingRequestType.ROOT_ROLLUP]: 35,
  [ProvingRequestType.PUBLIC_CHONK_VERIFIER]: 0,
  [ProvingRequestType.PUBLIC_VM]: 0,
};

export const PROOF_DELAY_MS: Record<ProvingRequestType, number> = {
  [ProvingRequestType.PARITY_BASE]: 14_000,
  [ProvingRequestType.BLOCK_MERGE_ROLLUP]: 15_000,
  [ProvingRequestType.BLOCK_ROOT_FIRST_ROLLUP]: 55_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_FIRST_ROLLUP]: 35_000,
  [ProvingRequestType.BLOCK_ROOT_EMPTY_TX_FIRST_ROLLUP]: 4_000,
  [ProvingRequestType.BLOCK_ROOT_ROLLUP]: 35_000,
  [ProvingRequestType.BLOCK_ROOT_SINGLE_TX_ROLLUP]: 15_000,
  [ProvingRequestType.CHECKPOINT_ROOT_ROLLUP]: 35_000,
  [ProvingRequestType.CHECKPOINT_ROOT_SINGLE_BLOCK_ROLLUP]: 35_000,
  [ProvingRequestType.CHECKPOINT_PADDING_ROLLUP]: 0,
  [ProvingRequestType.CHECKPOINT_MERGE_ROLLUP]: 9_000,
  [ProvingRequestType.TX_MERGE_ROLLUP]: 0,
  [ProvingRequestType.PRIVATE_TX_BASE_ROLLUP]: 145_000,
  [ProvingRequestType.PUBLIC_TX_BASE_ROLLUP]: 160_000,
  [ProvingRequestType.PARITY_ROOT]: 16_000,
  [ProvingRequestType.ROOT_ROLLUP]: 140_000,
  [ProvingRequestType.PUBLIC_CHONK_VERIFIER]: 30_000,
  [ProvingRequestType.PUBLIC_VM]: 0,
};
