# Configuration for example_swap

contracts:
  - example_uniswap-ExampleUniswap

dependencies:
  - "@aztec/aztec.js"
  - "@aztec/accounts"
  - "@aztec/wallets"
  - "@aztec/stdlib"
  - "@aztec/foundation"
  - "@aztec/ethereum"
  - "@aztec/noir-contracts.js"
  - "npm:@aztec/viem@2.38.2"
