#!/usr/bin/env node
// Walks msm_webgpu/wgsl/**/*.wgsl and emits a single
// wgsl/_generated/shaders.ts that exports each shader source as a
// string constant keyed by basename. shader_manager.ts imports from
// that file.
//
// Run as: `yarn generate:wgsl` (wired into package.json's prebuild).

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const wgslRoot = join(__dirname, "..", "wgsl");
const outFile = join(wgslRoot, "_generated", "shaders.ts");

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === "_generated") continue;
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    // `*.wip.wgsl` is a parked variant (stashed, not compiled) — to test one you
    // copy it over a `.template.wgsl` first. Skip it so the scan doesn't choke on
    // the `.wip.` infix (and so parked work-in-progress never reaches the build).
    else if (entry.name.endsWith(".wip.wgsl")) continue;
    else if (entry.name.endsWith(".wgsl")) out.push(p);
  }
  return out;
}

function identFor(filePath) {
  const name = basename(filePath).replace(/\.template\.wgsl$/, "").replace(/\.wgsl$/, "");
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`Bad identifier from ${filePath}: ${name}`);
  }
  return name;
}

const files = (await walk(wgslRoot)).sort();
const idents = new Map();
const entries = [];

for (const f of files) {
  const ident = identFor(f);
  if (idents.has(ident)) {
    throw new Error(
      `Duplicate shader identifier ${ident}: ${idents.get(ident)} and ${f}`,
    );
  }
  idents.set(ident, f);
  const src = await readFile(f, "utf8");
  // String literal via backticks; escape backticks and ${} sequences.
  const escaped = src.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  entries.push(`export const ${ident} = \`${escaped}\`;`);
}

const header = `// AUTO-GENERATED by scripts/inline-wgsl.mjs. DO NOT EDIT.
// Run \`yarn generate:wgsl\` (or \`node scripts/inline-wgsl.mjs\`) to regenerate.
// ${files.length} shader sources inlined.

/* eslint-disable */
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, header + "\n" + entries.join("\n\n") + "\n");
console.log(`Wrote ${outFile} with ${files.length} shaders.`);
