#!/bin/bash
# This script is used to run an e2e test in CI (see .circleci/config.yml).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

export COMPOSE_FILE=${1:-docker-compose.yml}

echo 'getting docker login'
aws ecr get-login-password --region $ECR_DEPLOY_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com 2> /dev/null

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

echo 'pulling docker image for sandbox'
retry docker pull $($calculate_image_uri aztec-sandbox)
retry docker tag $($calculate_image_uri aztec-sandbox) aztecprotocol/$REPO:latest

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up
yarn test
docker-compose down
