#!/bin/bash
# This script is used to run an e2e test in CI (see .circleci/config.yml).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

# Run in script path.
cd `dirname $0`

export COMPOSE_FILE=${1:-docker-compose.yml}

echo 'getting docker login'
aws ecr get-login-password --region $ECR_DEPLOY_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$ECR_DEPLOY_REGION.amazonaws.com 2> /dev/null

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

echo 'pulling docker image for sandbox'
for REPO in aztec-sandbox boxes-blank-react; do
  retry docker pull $($calculate_image_uri $REPO)
  retry docker tag $($calculate_image_uri $REPO) aztecprotocol/$REPO:latest
done
retry docker pull $(calculate_image_uri aztec-sandbox)
retry docker tag $(calculate_image_uri aztec-sandbox) aztecprotocol/aztec-sandbox:latest

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from boxes-blank-react