#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

export COMPOSE_FILE=${1:-docker-compose.yml}

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

retry docker pull $($calculate_image_uri aztec-sandbox)
retry docker tag $($calculate_image_uri aztec-sandbox) aztecprotocol/$REPO:latest

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up
yarn test
docker-compose down
