# WARNING!
#
#
#
#
#
#
#
# THIS FILE IS NO LONGER MAINTAINED.
# Use Dockerfile.
#
#
#
#
#
#
#
# cspell: disable
VERSION 0.8

from-registry:
  ARG TARGETARCH
  # NOTE: match version string above
  FROM aztecprotocol/build:2.0-$TARGETARCH
