//! # Barretenberg Rust Bindings
//!
//! Rust bindings to the Barretenberg cryptographic library using msgpack
//! over a pluggable [`Backend`].
//!
//! Two ready-made backends ship with the crate:
//!
//! * [`FfiBackend`] (default) — links `libbarretenberg` and calls `bbapi`
//!   directly in-process. Required for environments that can't spawn the
//!   `bb` binary (iOS, Android, embedded).
//! * `ipc_runtime::IpcClient` (re-exported, via the [`Backend`] impl in
//!   [`generated::backend`]) — talks to a separately-spawned `bb` over a
//!   Unix domain socket or shared-memory ring. Useful for development and
//!   for hosts that want to isolate the prover in its own process.
//!
//! ## Custom backends
//!
//! Implement the [`Backend`] trait to plug in your own transport (WASM
//! module, RPC, etc.):
//!
//! ```
//! use barretenberg_rs::{Backend, BarretenbergError, Result};
//!
//! struct MyBackend;
//!
//! impl Backend for MyBackend {
//!     fn call(&mut self, request: &[u8]) -> Result<Vec<u8>> {
//!         // request is a msgpack-encoded Vec<Command>; return a
//!         // msgpack-encoded Response.
//!         todo!()
//!     }
//!
//!     fn destroy(&mut self) -> Result<()> {
//!         Ok(())
//!     }
//! }
//! ```

// Bb API bindings produced by `ipc-codegen` from `ipc-codegen/schemas/bb_schema.json`.
// Output lives under src/generated/ and is regenerated by
// `barretenberg/ts/scripts/generate.sh`.
pub mod generated {
    pub mod backend;
    pub mod bb_client;
    pub mod bb_types;
    pub mod error;

    #[cfg(feature = "ffi")]
    pub mod ffi_backend;
}

mod fr_ext;
pub mod legacy;

pub use generated::backend::Backend;
pub use generated::bb_client::BbApi;
pub use generated::bb_types::{
    Bn254G1Point, Bn254G2Point, Command, Fr, GrumpkinPoint, Response, Secp256k1Point,
    Secp256r1Point,
};
pub use generated::error::{IpcError as BarretenbergError, Result};

// Pre-codegen surface kept around so external consumers can migrate at their
// own pace; see [`legacy`] for the deprecation notes and the typed-scalar
// replacements on [`BbApi`].
#[allow(deprecated)]
pub use legacy::BarretenbergApi;

// Preserved alias for callers that imported types directly via
// `barretenberg_rs::generated_types::*`.
pub use generated::bb_types as generated_types;

#[cfg(feature = "ffi")]
pub use generated::ffi_backend::FfiBackend;

// Re-export `ipc_runtime` so callers can write
// `barretenberg_rs::ipc_runtime::IpcClient` without taking a separate dep.
pub use ipc_runtime;
