VERSION 0.8

CACHE:
  FUNCTION
  ARG command
  ARG build_artifacts
  ARG prefix
  DO ../../build-system/s3-cache-scripts/+WITH_CACHE \
    --prefix="bb.js-$prefix" \
    --command="$command" \
    --rebuild_patterns="../cpp/.rebuild_patterns .rebuild_patterns" \
    --build_artifacts="$build_artifacts"

deps:
    FROM ../../+bootstrap-noir-bb
    WORKDIR /usr/src/barretenberg/ts

# WORKTODO(adam) remove once publish-aztec-packages is refactored
publish-npm:
    FROM +deps
    ARG VERSION
    ARG DIST_TAG
    ARG DRY_RUN=0
    RUN --secret NPM_TOKEN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > /usr/src/barretenberg/ts/.npmrc
    WORKDIR /usr/src/barretenberg/ts
    RUN jq --arg v $VERSION '.version = $v' package.json > _tmp.json && mv  _tmp.json package.json
    RUN if [ "$DRY_RUN" = "1" ]; then \
        npm publish --tag $DIST_TAG --access public --dry-run; \
    else \
        npm publish --tag $DIST_TAG --access public; \
    fi
