#!/usr/bin/env bash

set -eux

ARCH=$1
USERNAME=$2

shift 2

if [ "$ARCH" == "arm" ]; then
  PLATFORM=linux/arm64
elif [ "$ARCH" == "x86" ]; then
  PLATFORM=linux/amd64
fi
earthly sat --org aztec launch --size 2xlarge --platform $PLATFORM bench-$USERNAME-$ARCH || true
earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat bench-$USERNAME-$ARCH $@