#!/usr/bin/env bash
# Run earthly with our necesary secrets initialized
# AWS credentials can be blank HOWEVER this will disable S3 caching.
export EARTHLY_ALLOW_PRIVILEGED=true

set -eux

S3_BUILD_CACHE_UPLOAD=${S3_BUILD_CACHE_UPLOAD:-false}
S3_BUILD_CACHE_DOWNLOAD=false
S3_BUILD_CACHE_AWS_PARAMS=""

if ! git diff-index --quiet HEAD --; then
  echo "Warning: You have unstaged changes. Disabling S3 caching for earthly (including mock S3 local caching)." >&2
  S3_BUILD_CACHE_UPLOAD=false
elif [ ! -z "${S3_BUILD_CACHE_MOCK:-}" ] ; then
  mkdir -p ~/.minio/data

  echo "Mocking S3 cache with local file server."
  docker run -d -p 12000:9000 -p 12001:12001 -v ~/.minio/data:/data \
    quay.io/minio/minio server /data --console-address ":12001" || true
  AWS_SECRET_ACCESS_KEY=minioadmin
  AWS_ACCESS_KEY_ID=minioadmin
  S3_BUILD_CACHE_UPLOAD=true
  S3_BUILD_CACHE_DOWNLOAD=true
  S3_BUILD_CACHE_AWS_PARAMS="--endpoint-url http://$(hostname -I | awk '{print $1}'):12000"
  aws --endpoint-url http://localhost:12000 s3 mb s3://aztec-ci-artifacts
elif [ ! -z "${AWS_ACCESS_KEY_ID:-}" ] ; then
  S3_BUILD_CACHE_DOWNLOAD=true
fi

earthly --secret AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-} \
        --secret AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-} \
        --secret S3_BUILD_CACHE_AWS_PARAMS="$S3_BUILD_CACHE_AWS_PARAMS" \
        --secret S3_BUILD_CACHE_UPLOAD="$S3_BUILD_CACHE_UPLOAD" \
        --secret S3_BUILD_CACHE_DOWNLOAD="$S3_BUILD_CACHE_DOWNLOAD" \
        --secret AZTEC_BOT_COMMENTER_GITHUB_TOKEN=${AZTEC_BOT_GITHUB_TOKEN:-} $@