#!/usr/bin/env bash

set -eux

RUNNER_PREFIX=$1
SIZE=$2
USERNAME=$3
ARCH=$4

shift 4

if [ "$ARCH" == "arm" ]; then
  PLATFORM=linux/arm64
elif [ "$ARCH" == "x86" ]; then
  PLATFORM=linux/amd64
fi

# ensure lowercase
USERNAME=$(echo "$USERNAME" | tr '[:upper:]' '[:lower:]')
earthly sat --org aztec launch --size $SIZE --platform $PLATFORM $RUNNER_PREFIX-$USERNAME-$ARCH || true
earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat $RUNNER_PREFIX-$USERNAME-$ARCH $@