#!/usr/bin/env bash
export EARTHLY_ALLOW_PRIVILEGED=true

# Consider instead using setup-earthly-local.sh if using zsh.

# Run earthly with our necesary secrets initialized
# AWS credentials can be blank, only the odd test like build-system/cache-tool/+test need them
# everything else relies on AZTEC_CACHE_TOOL_IP being set.
earthly --secret AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-} \
        --secret AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-} \
        --secret AZTEC_CACHE_TOOL_IP=$(hostname -I | awk '{print $1}') \
        --secret AZTEC_CACHE_MODE="local" \
        --secret AZTEC_BOT_COMMENTER_GITHUB_TOKEN=${AZTEC_BOT_GITHUB_TOKEN:-} $@