#!/usr/bin/env bash
# A wrapper for Earthly that is meant to catch signs of known intermittent failures and continue.
# The silver lining is if Earthly does crash, the cache can pick up the build.
if [ "${CI:-0}" = 0 ]; then
  # only use earthly-ci if local not set.
  echo "Running earthly-local because CI is not 1."
  exec "$(dirname $0)/earthly-local" $@
fi
set -eu -o pipefail

# earthly settings
export EARTHLY_ALLOW_PRIVILEGED=true
export EARTHLY_NO_BUILDKIT_UPDATE=true
# we make our own groupings, ignore earthly's
export GITHUB_ACTIONS=false
export FORCE_COLOR=1
export EARTHLY_CONFIG=$(git rev-parse --show-toplevel)/scripts/earthly-ci-config.yml

# Run earthly with our necesary secrets initialized
# AWS credentials can be blank, however we will not use the S3 cache at all if so.
EARTHLY_ARGS=""

# We abuse secrets with regular config that we don't want to alter the cache (see https://docs.earthly.dev/docs/guides/secrets)
# we do not run with minio in CI
earthly --secret AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-} \
        --secret AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-} \
        --secret S3_BUILD_CACHE_MINIO_URL="" \
        --secret S3_BUILD_CACHE_UPLOAD="true" \
        --secret S3_BUILD_CACHE_DOWNLOAD="true" \
        --secret AZTEC_BOT_COMMENTER_GITHUB_TOKEN=${AZTEC_BOT_GITHUB_TOKEN:-} \
        $EARTHLY_ARGS \
        $@ \
        --GITHUB_RUN_URL="${GITHUB_RUN_URL:-}"
