#!/usr/bin/env bash

set -eux

RUNNER_PREFIX=$1
USERNAME=$2
ARCH=$3

shift 3

if [ "$ARCH" == "arm" ]; then
  PLATFORM=linux/arm64
elif [ "$ARCH" == "x86" ]; then
  PLATFORM=linux/amd64
fi
earthly sat --org aztec launch --size 2xlarge --platform $PLATFORM $RUNNER_PREFIX-$USERNAME-$ARCH || true
earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat $RUNNER_PREFIX-$USERNAME-$ARCH $@