#!/bin/bash
set -eu

# Enter the repo root
cd "$(dirname "$0")/.."

exec ssh -o TCPKeepAlive=no -o ServerAliveInterval=600 -o StrictHostKeyChecking=no -i "$BUILDER_SPOT_KEY" ubuntu@"$BUILDER_SPOT_IP" "$@"