#!/bin/bash
set -eu

# Enter the repo root
cd "$(dirname "$0")/.."

# Define environment variables
ENV_VARS="
  DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  BUILD_INSTANCE_SSH_KEY=$BUILD_INSTANCE_SSH_KEY
  GIT_COMMIT=$GIT_COMMIT
"

# Format the environment variables for the SSH command
ENV_EXPORTS=$(printf 'export %s; ' $ENV_VARS)

ssh -o ControlMaster=auto -o ControlPath=~/.ssh_mux_%h_%p_%r -o ControlPersist=30s -o TCPKeepAlive=no -o ServerAliveCountMax=5 -o ServerAliveInterval=30 -o StrictHostKeyChecking=no -i "$SPOT_KEY" ubuntu@"$SPOT_IP" "$ENV_EXPORTS $@"
