#!/usr/bin/env bash
# CI wrapper for socket-fix: installs dependencies, runs the fix script,
# pushes changes, creates/updates a PR, and sends a Slack notification.
# Called from bootstrap.sh ci-socket-fix after the full build completes.
#
# Usage: socket-fix-ci.sh [severity]
#   severity: critical (default), high, medium, low
set -euo pipefail

SEVERITY="${1:-critical}"
BRANCH_NAME="chore/socket-fix-updates"
REPO="${GITHUB_REPOSITORY:-AztecProtocol/aztec-packages}"

# --- Install socket CLI ---
echo "Installing socket CLI..."
npm install -g socket

# --- Configure socket org (enables server-side bulk analysis) ---
export SOCKET_CLI_ORG_SLUG=AztecProtocol

# --- Configure git ---
git config user.name AztecBot
git config user.email tech@aztecprotocol.com
git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"

# --- Create branch ---
git checkout -B "$BRANCH_NAME"

# --- Run socket-fix.sh ---
# Point GITHUB_OUTPUT at a temp file so we can parse outputs
output_file=$(mktemp)
export GITHUB_OUTPUT="$output_file"

scripts/socket-fix.sh --severity "$SEVERITY" --workspaces "yarn-project"

# --- Parse outputs ---
get_output() {
  grep "^${1}=" "$output_file" | head -1 | cut -d= -f2-
}

commit_count=$(get_output commit_count)
remaining_count=$(get_output remaining_count)
total_found=$(get_output total_found)
qualifying_count=$(get_output qualifying_count)
fixed=$(get_output fixed)
failed=$(get_output failed)
skipped=$(get_output skipped)

echo "Results: commit_count=$commit_count remaining_count=$remaining_count total_found=$total_found"

# --- Push and create PR if there are commits ---
PR_URL=""
if [ "${commit_count:-0}" != "0" ]; then
  echo "Pushing branch $BRANCH_NAME..."
  git push -f origin "$BRANCH_NAME"

  # Check for existing PR
  PR_URL=$(gh pr list --repo "$REPO" --head "$BRANCH_NAME" --state open --json url --jq '.[0].url' || true)

  DATE=$(date -u +%Y-%m-%d)
  PR_TITLE="fix(deps): $SEVERITY dependency vulnerabilities ($DATE)"

  PR_BODY="## Socket Fix: Dependency Updates

| Metric | Count |
|--------|-------|
| Total vulns found | ${total_found} |
| Qualifying (>= ${SEVERITY}) | ${qualifying_count} |
| Fixed | ${commit_count} |
| Remaining | ${remaining_count} |

### Fixed
${fixed:-none}

### Failed (could not apply)
${failed:-none}

### Skipped (below threshold)
${skipped:-none}

---
*Auto-generated by [socket-fix workflow](https://github.com/${REPO}/actions/workflows/socket-fix.yml).
Each commit addresses a single advisory (GHSA) for easy review and revert.*"

  if [ -z "$PR_URL" ]; then
    echo "Creating new PR..."
    PR_URL=$(gh pr create \
      --repo "$REPO" \
      --title "$PR_TITLE" \
      --body "$PR_BODY" \
      --base next \
      --head "$BRANCH_NAME" \
      2>&1 | tail -1)
  else
    echo "Updating existing PR: $PR_URL"
    gh pr edit "$PR_URL" \
      --title "$PR_TITLE" \
      --body "$PR_BODY"
  fi

  echo "PR: $PR_URL"
fi

# --- Slack notification ---
if [ "${commit_count:-0}" != "0" ] || [ "${remaining_count:-0}" != "0" ]; then
  if [ -z "${SLACK_BOT_TOKEN:-}" ]; then
    echo "SLACK_BOT_TOKEN not set, skipping Slack notification"
  else
    LINKS=""
    if [ -n "$PR_URL" ]; then
      LINKS="<${PR_URL}|View PR>"
    fi

    if [ "${remaining_count:-0}" = "0" ]; then
      TEXT="✅ Socket Fix: Fixed ${commit_count} ${SEVERITY} vulnerabilities in yarn-project
${LINKS}"
    elif [ "${commit_count:-0}" != "0" ]; then
      TEXT="⚠️ Socket Fix: Fixed ${commit_count} ${SEVERITY} vulnerabilities, ${remaining_count} could not be auto-fixed
${LINKS}"
    else
      TEXT="❌ Socket Fix: ${remaining_count} ${SEVERITY} vulnerabilities could not be auto-fixed
${LINKS}"
    fi

    data=$(jq -n --arg channel "#team-alpha-ci" --arg text "$TEXT" '{channel: $channel, text: $text}')

    curl -X POST https://slack.com/api/chat.postMessage \
      -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
      -H "Content-type: application/json" \
      --data "$data"
  fi
fi

if [ "${commit_count:-0}" = "0" ]; then
  echo "No dependency vulnerabilities at or above the severity threshold, or all fixes failed. No PR created."
fi

rm -f "$output_file"
