#!/bin/sh
# Add a symlink to this somewhere in your path.
# Now you can run aztec-cli-dev anywhere to execute latest code, no 'yarn build' required.
SCRIPT_PATH=$(dirname $(realpath $0))
export TS_NODE_PROJECT="$SCRIPT_PATH/tsconfig.json"
node --no-warnings --loader ts-node/esm $SCRIPT_PATH/src/bin/index.ts $@
