import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  sidebar: [
    { type: "doc", id: "index" },
    {
      type: "html",
      value: '<div class="divider"></div>',
      defaultStyle: true,
    },
    { type: "doc", id: "getting_started" },
    {
      type: "category",
      label: "How To Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "how_to_guides",
        },
      ],
    },
    {
      type: "html",
      value: '<div class="divider"></div>',
      defaultStyle: true,
    },
    {
      type: "html",
      value: '<a href="/api/index.html" target="_blank" rel="noopener noreferrer" style="color: var(--ifm-menu-color); text-decoration: none; display: block; padding: var(--ifm-menu-link-padding-vertical) var(--ifm-menu-link-padding-horizontal);">C++ API Reference</a>',
      defaultStyle: true,
    },
  ],
};

export default sidebars;
