/**
 * Multi-service, multi-language code generation from msgpack schemas.
 *
 * Architecture:
 *   Service Binaries → `msgpack schema` → SchemaVisitor → CompiledSchema IR → Language Codegens → Files
 *
 * This is the unified entry point. It generates bindings for all services (bb, wsdb, cdb, avm)
 * across all configured language targets (TypeScript, Rust, C++).
 *
 * Usage:
 *   npx tsx src/cbind/generate.ts              # Generate all services
 *   npx tsx src/cbind/generate.ts bb            # Generate only bb
 *   npx tsx src/cbind/generate.ts wsdb cdb      # Generate wsdb and cdb
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { fileURLToPath } from 'url';
import { unpack } from 'msgpackr';
import { generateForService, SERVICES } from './service_codegen.js';

const execAsync = promisify(exec);

// @ts-ignore
const __dirname = dirname(fileURLToPath(import.meta.url));

async function generateCurveConstants(bbBuildPath: string, outputDir: string) {
  // Get curve constants from bb as msgpack binary
  const { stdout: constantsBuffer } = await execAsync(`${bbBuildPath} msgpack curve_constants`, {
    encoding: 'buffer',
    maxBuffer: 10 * 1024 * 1024, // 10MB buffer
  });

  // Decode msgpack
  const constants = unpack(constantsBuffer as Buffer);

  // Helper to convert Uint8Array to bigint (big-endian)
  const toBigInt = (bytes: Uint8Array) => {
    let result = 0n;
    for (const byte of bytes) {
      result = (result << 8n) | BigInt(byte);
    }
    return result;
  };

  // Helper to serialize point coordinate (handles both Uint8Array and array of Uint8Array for field2)
  const serializeCoordinate = (coord: Uint8Array | Uint8Array[]) => {
    if (Array.isArray(coord)) {
      // For field2 (like BN254 G2), we have array of two Uint8Arrays
      return `[${coord.map(c => `new Uint8Array([${Array.from(c).join(', ')}])`).join(', ')}]`;
    } else {
      // For regular fields, single Uint8Array
      return `new Uint8Array([${Array.from(coord).join(', ')}])`;
    }
  };

  // Generate TypeScript file
  const content = `/**
 * Curve constants generated from barretenberg native binary.
 * DO NOT EDIT - This file is auto-generated by generate.ts
 */

/**
 * BN254 curve constants
 */
export const BN254_FR_MODULUS = ${toBigInt(constants.bn254_fr_modulus)}n;
export const BN254_FQ_MODULUS = ${toBigInt(constants.bn254_fq_modulus)}n;

export const BN254_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g1_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g1_generator.y)},
} as const;

export const BN254_G2_GENERATOR = {
  x: ${serializeCoordinate(constants.bn254_g2_generator.x)},
  y: ${serializeCoordinate(constants.bn254_g2_generator.y)},
} as const;

/**
 * Grumpkin curve constants
 */
export const GRUMPKIN_FR_MODULUS = ${toBigInt(constants.grumpkin_fr_modulus)}n;
export const GRUMPKIN_FQ_MODULUS = ${toBigInt(constants.grumpkin_fq_modulus)}n;

export const GRUMPKIN_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.grumpkin_g1_generator.x)},
  y: ${serializeCoordinate(constants.grumpkin_g1_generator.y)},
} as const;

/**
 * Secp256k1 curve constants
 */
export const SECP256K1_FR_MODULUS = ${toBigInt(constants.secp256k1_fr_modulus)}n;
export const SECP256K1_FQ_MODULUS = ${toBigInt(constants.secp256k1_fq_modulus)}n;

export const SECP256K1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256k1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256k1_g1_generator.y)},
} as const;

/**
 * Secp256r1 curve constants
 */
export const SECP256R1_FR_MODULUS = ${toBigInt(constants.secp256r1_fr_modulus)}n;
export const SECP256R1_FQ_MODULUS = ${toBigInt(constants.secp256r1_fq_modulus)}n;

export const SECP256R1_G1_GENERATOR = {
  x: ${serializeCoordinate(constants.secp256r1_g1_generator.x)},
  y: ${serializeCoordinate(constants.secp256r1_g1_generator.y)},
} as const;
`;

  const outputPath = join(outputDir, 'curve_constants.ts');
  writeFileSync(outputPath, content);
  console.log(`  [curve_constants] ${outputPath}`);
}

async function generate() {
  // Parse CLI args: optional list of service names to generate
  const args = process.argv.slice(2);
  const requestedServices = args.length > 0 ? args : Object.keys(SERVICES);

  // Validate service names
  for (const name of requestedServices) {
    if (!SERVICES[name]) {
      console.error(`Unknown service: ${name}. Available: ${Object.keys(SERVICES).join(', ')}`);
      process.exit(1);
    }
  }

  console.log(`Generating bindings for: ${requestedServices.join(', ')}\n`);

  // Generate each requested service
  for (const name of requestedServices) {
    console.log(`--- ${name} ---`);
    await generateForService(SERVICES[name], __dirname);
    console.log('');
  }

  // Generate curve constants (only if bb is included and binary exists)
  if (requestedServices.includes('bb')) {
    const bbBuildPath = process.env.BB_BINARY_PATH || join(__dirname, '../../cpp/build/bin/bb');
    const { existsSync } = await import('fs');
    if (existsSync(bbBuildPath)) {
      console.log('--- curve constants ---');
      const outputDir = join(__dirname, 'generated');
      mkdirSync(outputDir, { recursive: true });
      await generateCurveConstants(bbBuildPath, outputDir);
      console.log('');
    } else {
      console.log('--- curve constants: skipped (bb binary not found) ---\n');
    }
  }

  console.log('Generation complete.');
}

// Run the generator
generate().catch(error => {
  console.error('Generation failed:', error);
  process.exit(1);
});
