/**
 * Rust schema compiler - generates Rust code from msgpack schema
 * Parallels schema_compiler.ts but outputs Rust instead of TypeScript
 */

export type Schema =
  | string
  | ObjectSchema
  | ['tuple', Schema[]]
  | ['map', [Schema, Schema]]
  | ['optional', [Schema]]
  | ['vector', [Schema]]
  | ['variant', Schema[]]
  | ['named_union', Array<[string, Schema]>]
  | ['shared_ptr', [Schema]]
  | ['array', [Schema, number]]
  | ['alias', [string, string]];

export type ObjectSchema = { [key: string]: Schema };

interface TypeInfo {
  rustType: string;
  needsSerde: boolean;
  isCustomType: boolean;
}

interface FunctionMetadata {
  name: string;
  commandType: string;
  responseType: string;
}

function toSnakeCase(s: string): string {
  return s
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

function toPascalCase(s: string): string {
  return s
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.substring(1))
    .join('');
}

export class RustSchemaCompiler {
  private typeCache = new Map<string, TypeInfo>();
  private functionMetadata: FunctionMetadata[] = [];
  private customTypes = new Set<string>();

  processApiSchema(commandsSchema: Schema, responsesSchema: Schema): void {
    // Process types
    this.processSchema(commandsSchema);
    this.processSchema(responsesSchema);

    // Extract function metadata
    if (
      !Array.isArray(commandsSchema) ||
      commandsSchema[0] !== 'named_union' ||
      !Array.isArray(responsesSchema) ||
      responsesSchema[0] !== 'named_union'
    ) {
      throw new Error('Expected named_union schema format');
    }

    const commands = commandsSchema[1] as Array<[string, Schema]>;
    const responses = responsesSchema[1] as Array<[string, Schema]>;

    for (let i = 0; i < commands.length; i++) {
      const [commandName] = commands[i];
      const [responseName] = responses[i];

      this.functionMetadata.push({
        name: toSnakeCase(commandName),
        commandType: toPascalCase(commandName),
        responseType: toPascalCase(responseName),
      });
    }
  }

  compile(): string {
    const parts: string[] = [
      '//! AUTOGENERATED FILE - DO NOT EDIT',
      '//! Generated from msgpack schema',
      '',
      'use serde::{Deserialize, Serialize};',
      '',
      '// Helper module for efficient binary serialization',
      'mod serde_bytes {',
      '    use serde::{Deserialize, Deserializer, Serializer};',
      '',
      '    pub fn serialize<S>(bytes: &Vec<u8>, serializer: S) -> Result<S::Ok, S::Error>',
      '    where',
      '        S: Serializer,',
      '    {',
      '        serializer.serialize_bytes(bytes)',
      '    }',
      '',
      '    pub fn deserialize<\'de, D>(deserializer: D) -> Result<Vec<u8>, D::Error>',
      '    where',
      '        D: Deserializer<\'de>,',
      '    {',
      '        <Vec<u8>>::deserialize(deserializer)',
      '    }',
      '}',
      '',
    ];

    // Generate type definitions
    const sortedTypes = Array.from(this.customTypes).sort();
    for (const typeName of sortedTypes) {
      const typeInfo = this.findTypeByName(typeName);
      if (typeInfo) {
        parts.push(this.generateTypeDefinition(typeName, typeInfo));
        parts.push('');
      }
    }

    // Generate Command enum
    parts.push(this.generateCommandEnum());
    parts.push('');

    // Generate Response enum
    parts.push(this.generateResponseEnum());
    parts.push('');

    return parts.join('\n');
  }

  private processSchema(schema: Schema): TypeInfo {
    const key = this.getSchemaKey(schema);
    if (this.typeCache.has(key)) {
      return this.typeCache.get(key)!;
    }

    const typeInfo = this.generateTypeInfo(schema);
    this.typeCache.set(key, typeInfo);
    return typeInfo;
  }

  private getSchemaKey(schema: Schema): string {
    if (typeof schema === 'string') return schema;
    if (Array.isArray(schema)) return JSON.stringify(schema);
    if (typeof schema === 'object') return (schema as any).__typename || JSON.stringify(schema);
    return String(schema);
  }

  private generateTypeInfo(schema: Schema): TypeInfo {
    if (Array.isArray(schema)) {
      return this.processArraySchema(schema);
    } else if (typeof schema === 'string') {
      return this.processPrimitiveSchema(schema);
    } else if (typeof schema === 'object') {
      return this.processObjectSchema(schema);
    }
    throw new Error(`Unsupported schema type: ${schema}`);
  }

  private processArraySchema(schema: any[]): TypeInfo {
    const [type, ...args] = schema;

    switch (type) {
      case 'array': {
        const [subtype, size] = args[0];
        if (subtype === 'unsigned char') {
          return { rustType: `[u8; ${size}]`, needsSerde: true, isCustomType: false };
        }
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `[${subtypeInfo.rustType}; ${size}]`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'vector': {
        const [subtype] = args[0];
        if (subtype === 'unsigned char') {
          return { rustType: 'Vec<u8>', needsSerde: true, isCustomType: false };
        }
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `Vec<${subtypeInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'map': {
        const [keyType, valueType] = args[0];
        const keyInfo = this.processSchema(keyType);
        const valueInfo = this.processSchema(valueType);
        return {
          rustType: `std::collections::HashMap<${keyInfo.rustType}, ${valueInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'optional': {
        const [subtype] = args[0];
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `Option<${subtypeInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'shared_ptr': {
        const [subtype] = args[0];
        return this.processSchema(subtype);
      }

      case 'alias': {
        const [rawTypeName, msgpackName] = args[0];
        const typeName = toPascalCase(rawTypeName);
        let rustType: string;

        if (msgpackName.startsWith('bin')) {
          rustType = 'Vec<u8>';
        } else if (['int', 'unsigned int', 'unsigned short'].includes(msgpackName)) {
          rustType = 'u32';
        } else {
          throw new Error(`Unsupported alias type: ${msgpackName}`);
        }

        return { rustType, needsSerde: true, isCustomType: false };
      }

      default:
        throw new Error(`Unsupported array schema type: ${type}`);
    }
  }

  private processPrimitiveSchema(schema: string): TypeInfo {
    switch (schema) {
      case 'bool':
        return { rustType: 'bool', needsSerde: true, isCustomType: false };
      case 'int':
      case 'unsigned int':
        return { rustType: 'u32', needsSerde: true, isCustomType: false };
      case 'unsigned short':
        return { rustType: 'u16', needsSerde: true, isCustomType: false };
      case 'unsigned long':
        return { rustType: 'u64', needsSerde: true, isCustomType: false };
      case 'unsigned char':
        return { rustType: 'u8', needsSerde: true, isCustomType: false };
      case 'double':
        return { rustType: 'f64', needsSerde: true, isCustomType: false };
      case 'string':
        return { rustType: 'String', needsSerde: true, isCustomType: false };
      case 'bin32':
        return { rustType: 'Vec<u8>', needsSerde: true, isCustomType: false };
      default: {
        const typeName = toPascalCase(schema);
        this.customTypes.add(typeName);
        return { rustType: typeName, needsSerde: true, isCustomType: true };
      }
    }
  }

  private processObjectSchema(schema: ObjectSchema): TypeInfo {
    const typeName = toPascalCase(schema.__typename as string);
    this.customTypes.add(typeName);
    return { rustType: typeName, needsSerde: true, isCustomType: true };
  }

  private findTypeByName(typeName: string): ObjectSchema | null {
    for (const [key, _] of this.typeCache.entries()) {
      try {
        const schema = JSON.parse(key);
        if (schema.__typename && toPascalCase(schema.__typename) === typeName) {
          return schema;
        }
      } catch {
        // Not a JSON key
      }
    }
    return null;
  }

  private generateTypeDefinition(typeName: string, schema: ObjectSchema): string {
    const fields = Object.entries(schema)
      .filter(([key]) => key !== '__typename')
      .map(([key, value]) => {
        const typeInfo = this.processSchema(value);
        const fieldName = toSnakeCase(key);

        // Add serde attributes
        let serdeAttrs = '';

        // If field name differs from original key, add rename attribute
        if (fieldName !== key) {
          serdeAttrs += `    #[serde(rename = "${key}")]\n`;
        }

        // For Vec<u8> types, use efficient binary serialization
        if (typeInfo.rustType === 'Vec<u8>') {
          serdeAttrs += `    #[serde(with = "serde_bytes")]\n`;
        }

        return `${serdeAttrs}    pub ${fieldName}: ${typeInfo.rustType},`;
      });

    return `/// ${typeName} type from msgpack schema
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ${typeName} {
${fields.join('\n')}
}`;
  }

  private generateCommandEnum(): string {
    const variants = this.functionMetadata.map(m => {
      // Keep original casing for the variant name tag
      const originalName = m.name.split('_').map((part, i) =>
        i === 0 ? part.charAt(0).toUpperCase() + part.slice(1) :
        part.charAt(0).toUpperCase() + part.slice(1)
      ).join('');

      return `    #[serde(rename = "${m.commandType}")]\n    ${m.commandType}(${m.commandType}),`;
    });

    return `/// Command enum wrapping all possible commands
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "0", content = "1")]
pub enum Command {
${variants.join('\n')}
}`;
  }

  private generateResponseEnum(): string {
    const variants = this.functionMetadata.map(m => {
      return `    #[serde(rename = "${m.responseType}")]\n    ${m.responseType}(${m.responseType}),`;
    });

    return `/// Response enum wrapping all possible responses
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "0", content = "1")]
pub enum Response {
${variants.join('\n')}
}`;
  }
}

export function createRustCompiler(): RustSchemaCompiler {
  return new RustSchemaCompiler();
}
