/**
 * Rust schema compiler - generates Rust code from msgpack schema
 * Parallels schema_compiler.ts but outputs Rust instead of TypeScript
 */

import {
  SchemaCompilerBase,
  Schema,
  ObjectSchema,
  toSnakeCase,
  toPascalCase,
} from './schema_compiler_base.js';

interface RustTypeInfo {
  rustType: string;
  needsSerde: boolean;
  isCustomType: boolean;
}

export class RustSchemaCompiler extends SchemaCompilerBase<RustTypeInfo> {
  private customTypes = new Set<string>();
  private commandTypes = new Set<string>();
  private responseTypes = new Set<string>();

  /**
   * Override to track command and response types for constructor generation
   */
  processApiSchema(commandsSchema: Schema, responsesSchema: Schema): void {
    // Call base implementation
    super.processApiSchema(commandsSchema, responsesSchema);

    // Track command and response types for constructor generation
    for (const metadata of this.functionMetadata) {
      this.commandTypes.add(metadata.commandType);
      this.responseTypes.add(metadata.responseType);
    }
  }

  compile(): string {
    const parts: string[] = [
      '//! AUTOGENERATED FILE - DO NOT EDIT',
      '//! Generated from msgpack schema',
      '',
      'use serde::{Deserialize, Serialize};',
      '',
      '// Helper module for efficient binary serialization',
      'mod serde_bytes {',
      '    use serde::{Deserialize, Deserializer, Serializer};',
      '',
      '    pub fn serialize<S>(bytes: &Vec<u8>, serializer: S) -> Result<S::Ok, S::Error>',
      '    where',
      '        S: Serializer,',
      '    {',
      '        serializer.serialize_bytes(bytes)',
      '    }',
      '',
      '    pub fn deserialize<\'de, D>(deserializer: D) -> Result<Vec<u8>, D::Error>',
      '    where',
      '        D: Deserializer<\'de>,',
      '    {',
      '        <Vec<u8>>::deserialize(deserializer)',
      '    }',
      '}',
      '',
    ];

    // Generate type definitions
    const sortedTypes = Array.from(this.customTypes).sort();
    for (const typeName of sortedTypes) {
      const typeInfo = this.findTypeByName(typeName);
      if (typeInfo) {
        parts.push(this.generateTypeDefinition(typeName, typeInfo));
        parts.push('');
      }
    }

    // Generate Command enum
    parts.push(this.generateCommandEnum());
    parts.push('');

    // Generate Response enum
    parts.push(this.generateResponseEnum());
    parts.push('');

    return parts.join('\n');
  }

  /**
   * Convert function name to Rust snake_case convention
   */
  protected convertFunctionName(name: string): string {
    return toSnakeCase(name);
  }

  /**
   * Convert type name to Rust PascalCase convention
   */
  protected convertTypeName(name: string): string {
    return toPascalCase(name);
  }

  /**
   * Process array-based schema types (Rust-specific implementation)
   */
  protected processArraySchema(schema: any[]): RustTypeInfo {
    const [type, ...args] = schema;

    switch (type) {
      case 'array': {
        const [subtype, size] = args[0];
        if (subtype === 'unsigned char') {
          return { rustType: `[u8; ${size}]`, needsSerde: true, isCustomType: false };
        }
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `[${subtypeInfo.rustType}; ${size}]`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'vector': {
        const [subtype] = args[0];
        if (subtype === 'unsigned char') {
          return { rustType: 'Vec<u8>', needsSerde: true, isCustomType: false };
        }
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `Vec<${subtypeInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'map': {
        const [keyType, valueType] = args[0];
        const keyInfo = this.processSchema(keyType);
        const valueInfo = this.processSchema(valueType);
        return {
          rustType: `std::collections::HashMap<${keyInfo.rustType}, ${valueInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'optional': {
        const [subtype] = args[0];
        const subtypeInfo = this.processSchema(subtype);
        return {
          rustType: `Option<${subtypeInfo.rustType}>`,
          needsSerde: true,
          isCustomType: false,
        };
      }

      case 'shared_ptr': {
        const [subtype] = args[0];
        return this.processSchema(subtype);
      }

      case 'alias': {
        const [rawTypeName, msgpackName] = args[0];
        const typeName = toPascalCase(rawTypeName);
        let rustType: string;

        if (msgpackName.startsWith('bin')) {
          rustType = 'Vec<u8>';
        } else if (['int', 'unsigned int', 'unsigned short'].includes(msgpackName)) {
          rustType = 'u32';
        } else {
          throw new Error(`Unsupported alias type: ${msgpackName}`);
        }

        return { rustType, needsSerde: true, isCustomType: false };
      }

      default:
        throw new Error(`Unsupported array schema type: ${type}`);
    }
  }

  /**
   * Process primitive schema types (Rust-specific implementation)
   */
  protected processPrimitiveSchema(schema: string): RustTypeInfo {
    switch (schema) {
      case 'bool':
        return { rustType: 'bool', needsSerde: true, isCustomType: false };
      case 'int':
      case 'unsigned int':
        return { rustType: 'u32', needsSerde: true, isCustomType: false };
      case 'unsigned short':
        return { rustType: 'u16', needsSerde: true, isCustomType: false };
      case 'unsigned long':
        return { rustType: 'u64', needsSerde: true, isCustomType: false };
      case 'unsigned char':
        return { rustType: 'u8', needsSerde: true, isCustomType: false };
      case 'double':
        return { rustType: 'f64', needsSerde: true, isCustomType: false };
      case 'string':
        return { rustType: 'String', needsSerde: true, isCustomType: false };
      case 'bin32':
        return { rustType: 'Vec<u8>', needsSerde: true, isCustomType: false };
      default: {
        const typeName = toPascalCase(schema);
        this.customTypes.add(typeName);
        return { rustType: typeName, needsSerde: true, isCustomType: true };
      }
    }
  }

  /**
   * Process object schema types (Rust-specific implementation)
   */
  protected processObjectSchema(schema: ObjectSchema): RustTypeInfo {
    const typeName = toPascalCase(schema.__typename as string);
    this.customTypes.add(typeName);
    this.objectSchemas.set(typeName, schema);

    // Recursively process all fields to discover nested types
    for (const [key, value] of Object.entries(schema)) {
      if (key !== '__typename') {
        this.processSchema(value);
      }
    }

    return { rustType: typeName, needsSerde: true, isCustomType: true };
  }

  private findTypeByName(typeName: string): ObjectSchema | null {
    return this.objectSchemas.get(typeName) || null;
  }

  private generateTypeDefinition(typeName: string, schema: ObjectSchema): string {
    const fields = Object.entries(schema)
      .map(([key, value]) => {
        const typeInfo = this.processSchema(value);
        const fieldName = toSnakeCase(key);

        // Add serde attributes
        let serdeAttrs = '';

        // Handle __typename specially
        if (key === '__typename') {
          return `    #[serde(rename = "__typename")]\n    pub type_name: String,`;
        }

        // If field name differs from original key, add rename attribute
        if (fieldName !== key) {
          serdeAttrs += `    #[serde(rename = "${key}")]\n`;
        }

        // For Vec<u8> types, use efficient binary serialization
        if (typeInfo.rustType === 'Vec<u8>') {
          serdeAttrs += `    #[serde(with = "serde_bytes")]\n`;
        }

        return `${serdeAttrs}    pub ${fieldName}: ${typeInfo.rustType},`;
      });

    // Generate constructor for command types
    const isCommand = this.commandTypes.has(typeName);
    const constructor = isCommand ? this.generateConstructor(typeName, schema) : '';

    return `/// ${typeName} type from msgpack schema
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ${typeName} {
${fields.join('\n')}
}
${constructor}`;
  }

  private generateConstructor(typeName: string, schema: ObjectSchema): string {
    const typename = schema.__typename as string;
    const params = Object.entries(schema)
      .filter(([key]) => key !== '__typename')
      .map(([key, value]) => {
        const typeInfo = this.processSchema(value);
        const fieldName = toSnakeCase(key);
        return `${fieldName}: ${typeInfo.rustType}`;
      });

    const fieldInits = Object.entries(schema)
      .map(([key]) => {
        if (key === '__typename') {
          return `            type_name: "${typename}".to_string(),`;
        }
        const fieldName = toSnakeCase(key);
        return `            ${fieldName},`;
      });

    return `
impl ${typeName} {
    pub fn new(${params.join(', ')}) -> Self {
        Self {
${fieldInits.join('\n')}
        }
    }
}

impl Default for ${typeName} {
    fn default() -> Self {
        Self::new(${Object.keys(schema).filter(k => k !== '__typename').map(() => 'Default::default()').join(', ')})
    }
}`;
  }

  private generateCommandEnum(): string {
    const variants = this.functionMetadata.map(m => {
      return `    ${m.commandType}(${m.commandType}),`;
    });

    const serializeCases = this.functionMetadata.map(m => {
      return `            Command::${m.commandType}(data) => {
                tuple.serialize_element("${m.commandType}")?;
                tuple.serialize_element(data)?;
            }`;
    });

    const deserializeCases = this.functionMetadata.map(m => {
      return `                    "${m.commandType}" => {
                        let data = seq.next_element()?
                            .ok_or_else(|| serde::de::Error::invalid_length(1, &self))?;
                        Ok(Command::${m.commandType}(data))
                    }`;
    });

    const variantNames = this.functionMetadata.map(m => `"${m.commandType}"`).join(', ');

    return `/// Command enum wrapping all possible commands
/// Serializes as msgpack array: ["VariantName", {...}]
#[derive(Debug, Clone)]
pub enum Command {
${variants.join('\n')}
}

// Custom serialization to create array format: ["CommandName", {...}]
impl Serialize for Command {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeTuple;
        let mut tuple = serializer.serialize_tuple(2)?;

        match self {
${serializeCases.join('\n')}
        }

        tuple.end()
    }
}

// Custom deserialization from array format: ["CommandName", {...}]
impl<'de> Deserialize<'de> for Command {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        use serde::de::{SeqAccess, Visitor};

        struct CommandVisitor;

        impl<'de> Visitor<'de> for CommandVisitor {
            type Value = Command;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("a 2-element array [command_name, payload]")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: SeqAccess<'de>,
            {
                let name: String = seq.next_element()?
                    .ok_or_else(|| serde::de::Error::invalid_length(0, &self))?;

                match name.as_str() {
${deserializeCases.join('\n')}
                    _ => Err(serde::de::Error::unknown_variant(&name, &[
                        ${variantNames}
                    ])),
                }
            }
        }

        deserializer.deserialize_tuple(2, CommandVisitor)
    }
}`;
  }

  private generateResponseEnum(): string {
    const variants = this.functionMetadata.map(m => {
      return `    ${m.responseType}(${m.responseType}),`;
    });

    const serializeCases = this.functionMetadata.map(m => {
      return `            Response::${m.responseType}(data) => {
                tuple.serialize_element("${m.responseType}")?;
                tuple.serialize_element(data)?;
            }`;
    });

    const deserializeCases = this.functionMetadata.map(m => {
      return `                    "${m.responseType}" => {
                        let data = seq.next_element()?
                            .ok_or_else(|| serde::de::Error::invalid_length(1, &self))?;
                        Ok(Response::${m.responseType}(data))
                    }`;
    });

    const variantNames = this.functionMetadata.map(m => `"${m.responseType}"`).join(', ');

    return `/// Response enum wrapping all possible responses
/// Serializes as msgpack array: ["VariantName", {...}]
#[derive(Debug, Clone)]
pub enum Response {
${variants.join('\n')}
}

// Custom serialization to create array format: ["ResponseName", {...}]
impl Serialize for Response {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeTuple;
        let mut tuple = serializer.serialize_tuple(2)?;

        match self {
${serializeCases.join('\n')}
        }

        tuple.end()
    }
}

// Custom deserialization from array format: ["ResponseName", {...}]
impl<'de> Deserialize<'de> for Response {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        use serde::de::{SeqAccess, Visitor};

        struct ResponseVisitor;

        impl<'de> Visitor<'de> for ResponseVisitor {
            type Value = Response;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("a 2-element array [response_name, payload]")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: SeqAccess<'de>,
            {
                let name: String = seq.next_element()?
                    .ok_or_else(|| serde::de::Error::invalid_length(0, &self))?;

                match name.as_str() {
${deserializeCases.join('\n')}
                    _ => Err(serde::de::Error::unknown_variant(&name, &[
                        ${variantNames}
                    ])),
                }
            }
        }

        deserializer.deserialize_tuple(2, ResponseVisitor)
    }
}`;
  }
}

export function createRustCompiler(): RustSchemaCompiler {
  return new RustSchemaCompiler();
}
