/**
 * Zig Code Generator - String template based
 *
 * Philosophy:
 *   - String templates for file structure
 *   - Simple type mapping
 *   - Idiomatic Zig conventions
 *   - No complex abstraction
 */

import type { CompiledSchema, Type, Struct, Field } from './schema_visitor.js';

export class ZigCodegen {
  // Type mapping: Schema type -> Zig type
  private mapType(type: Type): string {
    switch (type.kind) {
      case 'primitive':
        switch (type.primitive) {
          case 'bool': return 'bool';
          case 'u8': return 'u8';
          case 'u16': return 'u16';
          case 'u32': return 'u32';
          case 'u64': return 'u64';
          case 'f64': return 'f64';
          case 'string': return '[]const u8';
          case 'bytes': return '[]const u8';
        }
        break;

      case 'vector':
        return `[]const ${this.mapType(type.element!)}`;

      case 'array':
        return `[${type.size}]${this.mapType(type.element!)}`;

      case 'optional':
        return `?${this.mapType(type.element!)}`;

      case 'struct':
        // Zig uses PascalCase for types
        return this.toPascalCase(type.struct!.name);
    }

    return 'unknown';
  }

  // Convert name to snake_case
  private toSnakeCase(name: string): string {
    return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }

  // Convert type name to PascalCase
  private toPascalCase(name: string): string {
    if (!name.includes('_') && name[0] === name[0].toUpperCase()) {
      return name;
    }
    return name.split('_').map(part =>
      part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()
    ).join('');
  }

  // Generate struct field
  private generateField(field: Field): string {
    const zigName = this.toSnakeCase(field.name);
    const zigType = this.mapType(field.type);
    return `    ${zigName}: ${zigType},`;
  }

  // Generate a struct definition
  private generateStruct(struct: Struct): string {
    const zigName = this.toPascalCase(struct.name);
    const fields = struct.fields.map(f => this.generateField(f)).join('\n');

    // Add empty fields placeholder if no fields
    const fieldsBlock = fields || '    // No fields';

    return `/// ${struct.name}
pub const ${zigName} = struct {
${fieldsBlock}
};`;
  }

  // Generate Command tagged union
  private generateCommandUnion(schema: CompiledSchema): string {
    const names = Array.from(schema.structs.keys());
    const variants = names
      .map(name => {
        const snakeName = this.toSnakeCase(name);
        const pascalName = this.toPascalCase(name);
        return `    ${snakeName}: ${pascalName},`;
      })
      .join('\n');

    return `/// Command union - all possible commands
pub const Command = union(enum) {
${variants}
};`;
  }

  // Generate Response tagged union
  private generateResponseUnion(schema: CompiledSchema): string {
    const responseTypes = Array.from(new Set(schema.commands.map(c => c.responseType)));
    const variants = responseTypes
      .map(name => {
        const snakeName = this.toSnakeCase(name);
        const pascalName = this.toPascalCase(name);
        return `    ${snakeName}: ${pascalName},`;
      })
      .join('\n');

    return `/// Response union - all possible responses
pub const Response = union(enum) {
${variants}
};`;
  }

  // Generate types file
  generateTypes(schema: CompiledSchema): string {
    // Generate all structs (commands first, then responses)
    const commandStructs = Array.from(schema.structs.values())
      .map(s => this.generateStruct(s))
      .join('\n\n');

    const responseStructs = Array.from(schema.responses.values())
      .map(s => this.generateStruct(s))
      .join('\n\n');

    return `//! AUTOGENERATED - DO NOT EDIT
//! Generated from Barretenberg msgpack schema

const std = @import("std");

${commandStructs}

${responseStructs}

${this.generateCommandUnion(schema)}

${this.generateResponseUnion(schema)}
`;
  }

  // Generate API method
  private generateApiMethod(command: {name: string, fields: Field[], responseType: string}): string {
    const methodName = this.toSnakeCase(command.name);
    const cmdZigName = this.toPascalCase(command.name);
    const respZigName = this.toPascalCase(command.responseType);

    const params = command.fields.map(f => {
      const zigType = this.mapType(f.type);
      return `${this.toSnakeCase(f.name)}: ${zigType}`;
    }).join(', ');

    const fieldInits = command.fields.map(f => {
      const name = this.toSnakeCase(f.name);
      return `        .${name} = ${name},`;
    }).join('\n');

    return `    /// Execute ${command.name} command
    pub fn ${methodName}(self: *Self, ${params}) !${respZigName} {
        const cmd = Command {
            .${cmdZigName} = .{
${fieldInits}
            },
        };
        const resp = try self.execute(cmd);
        return resp.${respZigName};
    }`;
  }

  // Generate API file
  generateApi(schema: CompiledSchema): string {
    const apiMethods = schema.commands
      .filter(c => c.name !== 'Shutdown')
      .map(c => this.generateApiMethod(c))
      .join('\n\n');

    return `// AUTOGENERATED - DO NOT EDIT
// High-level Barretenberg API - msgpack details hidden

const std = @import("std");
const types = @import("types.zig");

/// Backend interface
pub const Backend = struct {
    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        call: *const fn (ptr: *anyopaque, input: []const u8) anyerror![]u8,
        destroy: *const fn (ptr: *anyopaque) void,
    };

    pub fn call(self: Backend, input: []const u8) ![]u8 {
        return self.vtable.call(self.ptr, input);
    }

    pub fn destroy(self: Backend) void {
        self.vtable.destroy(self.ptr);
    }
};

/// High-level Barretenberg API
pub const BarretenbergApi = struct {
    const Self = @This();

    backend: Backend,
    allocator: std.mem.Allocator,

    pub fn init(backend: Backend, allocator: std.mem.Allocator) Self {
        return .{
            .backend = backend,
            .allocator = allocator,
        };
    }

    fn execute(self: *Self, command: types.Command) !types.Response {
        // Serialize command with msgpack
        const input_buffer = try msgpack.serialize(self.allocator, command);
        defer self.allocator.free(input_buffer);

        // Call backend
        const output_buffer = try self.backend.call(input_buffer);
        defer self.allocator.free(output_buffer);

        // Deserialize response
        return try msgpack.deserialize(types.Response, output_buffer, self.allocator);
    }

${apiMethods}

    /// Shutdown backend gracefully
    pub fn shutdown(self: *Self) !void {
        const cmd = types.Command {
            .Shutdown = .{},
        };
        _ = try self.execute(cmd);
        self.backend.destroy();
    }

    /// Destroy backend without shutdown command
    pub fn destroy(self: *Self) void {
        self.backend.destroy();
    }
};
`;
  }
}
