/**
 * Zig Code Generator - String template based
 *
 * Philosophy:
 *   - String templates for file structure
 *   - Simple type mapping
 *   - Idiomatic Zig conventions
 *   - No complex abstraction
 */

import type { CompiledSchema, Type, Struct, Field } from './schema_visitor.js';
import { toSnakeCase, toPascalCase } from './naming.js';

export class ZigCodegen {
  // Type mapping: Schema type -> Zig type
  private mapType(type: Type): string {
    switch (type.kind) {
      case 'primitive':
        switch (type.primitive) {
          case 'bool': return 'bool';
          case 'u8': return 'u8';
          case 'u16': return 'u16';
          case 'u32': return 'u32';
          case 'u64': return 'u64';
          case 'f64': return 'f64';
          case 'string': return '[]const u8';
          case 'bytes': return '[]const u8';
          case 'field2': return '[2][]const u8';  // Extension field (Fq2)
        }
        break;

      case 'vector':
        return `[]const ${this.mapType(type.element!)}`;

      case 'array':
        return `[${type.size}]${this.mapType(type.element!)}`;

      case 'optional':
        return `?${this.mapType(type.element!)}`;

      case 'struct':
        // Zig uses PascalCase for types
        return toPascalCase(type.struct!.name);
    }

    return 'unknown';
  }

  // Generate struct field
  private generateField(field: Field): string {
    const zigName = toSnakeCase(field.name);
    const zigType = this.mapType(field.type);
    return `    ${zigName}: ${zigType},`;
  }

  // Generate a struct definition
  private generateStruct(struct: Struct): string {
    const zigName = toPascalCase(struct.name);
    const fields = struct.fields.map(f => this.generateField(f)).join('\n');

    // Add empty fields placeholder if no fields
    const fieldsBlock = fields || '    // No fields';

    return `/// ${struct.name}
pub const ${zigName} = struct {
${fieldsBlock}
};`;
  }

  // Generate Command tagged union
  private generateCommandUnion(schema: CompiledSchema): string {
    const names = Array.from(schema.structs.keys());
    const variants = names
      .map(name => {
        const snakeName = toSnakeCase(name);
        const pascalName = toPascalCase(name);
        return `    ${snakeName}: ${pascalName},`;
      })
      .join('\n');

    return `/// Command union - all possible commands
pub const Command = union(enum) {
${variants}
};`;
  }

  // Generate Response tagged union
  private generateResponseUnion(schema: CompiledSchema): string {
    // Include all response types from commands plus ErrorResponse if it exists
    const commandResponseTypes = Array.from(new Set(schema.commands.map(c => c.responseType)));
    const responseTypes = schema.responses.has('ErrorResponse')
      ? [...commandResponseTypes, 'ErrorResponse']
      : commandResponseTypes;
    const variants = responseTypes
      .map(name => {
        const snakeName = toSnakeCase(name);
        const pascalName = toPascalCase(name);
        return `    ${snakeName}: ${pascalName},`;
      })
      .join('\n');

    return `/// Response union - all possible responses
pub const Response = union(enum) {
${variants}
};`;
  }

  // Generate types file
  generateTypes(schema: CompiledSchema): string {
    // Generate all structs (commands first, then responses)
    const commandStructs = Array.from(schema.structs.values())
      .map(s => this.generateStruct(s))
      .join('\n\n');

    const responseStructs = Array.from(schema.responses.values())
      .map(s => this.generateStruct(s))
      .join('\n\n');

    return `//! AUTOGENERATED - DO NOT EDIT
//! Generated from Barretenberg msgpack schema

const std = @import("std");

${commandStructs}

${responseStructs}

${this.generateCommandUnion(schema)}

${this.generateResponseUnion(schema)}
`;
  }

  // Generate API method
  private generateApiMethod(command: {name: string, fields: Field[], responseType: string}): string {
    const methodName = toSnakeCase(command.name);
    const cmdSnakeName = toSnakeCase(command.name);
    const respSnakeName = toSnakeCase(command.responseType);

    const params = command.fields.map(f => {
      const zigType = this.mapType(f.type);
      return `${toSnakeCase(f.name)}: ${zigType}`;
    }).join(', ');

    const fieldInits = command.fields.map(f => {
      const name = toSnakeCase(f.name);
      return `.${name} = ${name}`;
    }).join(', ');

    const fieldInitBlock = fieldInits ? `{ ${fieldInits} }` : '{}';

    return `    /// Execute ${command.name} command
    pub fn ${methodName}(self: *Self, ${params}) !types.${toPascalCase(command.responseType)} {
        const cmd = types.Command{ .${cmdSnakeName} = ${fieldInitBlock} };
        const resp = try self.execute(cmd);
        if (resp == .error_response) {
            return error.BackendError;
        }
        return resp.${respSnakeName};
    }`;
  }

  // Generate API file
  generateApi(schema: CompiledSchema): string {
    const apiMethods = schema.commands
      .filter(c => c.name !== 'Shutdown')
      .map(c => this.generateApiMethod(c))
      .join('\n\n');

    return `//! AUTOGENERATED - DO NOT EDIT
//! High-level Barretenberg API - msgpack details hidden
//!
//! This module provides:
//! - Backend interface trait for pluggable backends
//! - MockBackend for testing without the BB binary
//! - BarretenbergApi for high-level operations
//!
//! Note: Full msgpack serialization requires a Zig msgpack library.

const std = @import("std");
const types = @import("generated_types.zig");

// Re-export commonly used types
pub const Command = types.Command;
pub const Response = types.Response;

/// Backend interface for msgpack communication.
///
/// Implement this interface to create custom backends (pipe, socket, FFI, etc.)
pub const Backend = struct {
    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Execute a msgpack command and return the msgpack response.
        call: *const fn (ptr: *anyopaque, input: []const u8) anyerror![]u8,
        /// Clean up resources and shutdown the backend.
        destroy: *const fn (ptr: *anyopaque) void,
    };

    pub fn call(self: Backend, input: []const u8) ![]u8 {
        return self.vtable.call(self.ptr, input);
    }

    pub fn destroy(self: Backend) void {
        self.vtable.destroy(self.ptr);
    }
};

/// Mock backend for testing without the BB binary.
///
/// Returns predefined responses for common commands. Useful for:
/// - Unit testing code that uses the Barretenberg API
/// - Development without building the C++ binary
/// - Integration testing of the API layer
pub const MockBackend = struct {
    const Self = @This();

    /// Number of calls made to this backend
    call_count: usize = 0,

    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) Self {
        return .{
            .allocator = allocator,
        };
    }

    pub fn backend(self: *Self) Backend {
        return .{
            .ptr = self,
            .vtable = &.{
                .call = callImpl,
                .destroy = destroyImpl,
            },
        };
    }

    fn callImpl(ptr: *anyopaque, input: []const u8) anyerror![]u8 {
        const self: *Self = @ptrCast(@alignCast(ptr));
        self.call_count += 1;
        _ = input;

        // Return a mock 32-byte response (zeros)
        const response = try self.allocator.alloc(u8, 32);
        @memset(response, 0);
        return response;
    }

    fn destroyImpl(ptr: *anyopaque) void {
        const self: *Self = @ptrCast(@alignCast(ptr));
        _ = self;
    }
};

/// High-level Barretenberg API
pub const BarretenbergApi = struct {
    const Self = @This();

    backend_impl: Backend,
    allocator: std.mem.Allocator,

    pub fn init(backend_impl: Backend, allocator: std.mem.Allocator) Self {
        return .{
            .backend_impl = backend_impl,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *Self) void {
        self.backend_impl.destroy();
    }

    fn execute(self: *Self, command: types.Command) !types.Response {
        // TODO: Implement msgpack serialization
        // For now, this is a placeholder that calls the backend directly
        _ = command;
        const output_buffer = try self.backend_impl.call("");
        defer self.allocator.free(output_buffer);

        // TODO: Deserialize response with msgpack
        // For now, return a placeholder response
        return types.Response{ .blake2s_response = .{ .hash = undefined } };
    }

${apiMethods}

    /// Shutdown backend gracefully
    pub fn shutdown(self: *Self) !void {
        const cmd = types.Command{ .shutdown = .{} };
        _ = try self.execute(cmd);
        self.backend_impl.destroy();
    }

    /// Destroy backend without shutdown command
    pub fn destroy(self: *Self) void {
        self.backend_impl.destroy();
    }
};
`;
  }
}
