// Typescript-land-only constants
export const FEE_FUNDING_FOR_TESTER_ACCOUNT = BigInt(1_000e18);
export const SPONSORED_FPC_SALT = BigInt(0);

// Autogenerated constants loaded from noir-land
export * from './constants.gen.js';
