import { BlockNumber, CheckpointNumber } from '@aztec/foundation/branded-types';
import { Fr } from '@aztec/foundation/curves/bn254';

// Re-export L2 block number constants with proper BlockNumber type
// Note: The generated constants are plain numbers, but we provide typed versions here
import {
  DA_GAS_PER_FIELD,
  GENESIS_BLOCK_HEADER_HASH as GENESIS_BLOCK_HEADER_HASH_BIGINT,
  INITIAL_CHECKPOINT_NUMBER as INITIAL_CHECKPOINT_NUM_RAW,
  INITIAL_L2_BLOCK_NUM as INITIAL_L2_BLOCK_NUM_RAW,
  MAX_TX_BLOB_DATA_SIZE_IN_FIELDS,
} from './constants.gen.js';

// Typescript-land-only constants
export const SPONSORED_FPC_SALT = BigInt(0);

/**
 * The most DA gas a single tx can consume. A tx's effects cannot encode more than
 * MAX_TX_BLOB_DATA_SIZE_IN_FIELDS fields in a blob, each costing DA_GAS_PER_FIELD, so this is the maximum
 * DA gas a tx could ever use; declaring a higher limit is rejected by inbound validation.
 */
export const MAX_TX_DA_GAS = MAX_TX_BLOB_DATA_SIZE_IN_FIELDS * DA_GAS_PER_FIELD;

// Autogenerated constants loaded from noir-land
// eslint-disable-next-line import-x/export
export * from './constants.gen.js';

/** The initial L2 block number (typed as BlockNumber). This is the first block number in the Aztec L2 chain. */
// eslint-disable-next-line import-x/export
export const INITIAL_L2_BLOCK_NUM: BlockNumber = BlockNumber(INITIAL_L2_BLOCK_NUM_RAW);

/** The initial L2 checkpoint number (typed as CheckpointNumber). This is the first checkpoint number in the Aztec L2 chain. */
// eslint-disable-next-line import-x/export
export const INITIAL_CHECKPOINT_NUMBER: CheckpointNumber = CheckpointNumber(INITIAL_CHECKPOINT_NUM_RAW);

/** The block header hash for the genesis block 0. */
// eslint-disable-next-line import-x/export
export const GENESIS_BLOCK_HEADER_HASH = new Fr(GENESIS_BLOCK_HEADER_HASH_BIGINT);
