#!/usr/bin/env bash
set -euo pipefail

# Tests that the default scaffold generated by `aztec new` compiles and passes its tests without any modifications.
# Also tests that a second contract can be added to the workspace with `aztec new`.

export LOG_LEVEL=silent

aztec new my_workspace

# Verify workspace structure with named crate directories.
if [ ! -f my_workspace/Nargo.toml ]; then
  echo "Failed to create workspace Nargo.toml."
  exit 1
fi
if [ ! -f my_workspace/my_workspace_contract/Nargo.toml ] || [ ! -f my_workspace/my_workspace_contract/src/main.nr ]; then
  echo "Failed to create contract crate."
  exit 1
fi
if [ ! -f my_workspace/my_workspace_test/Nargo.toml ] || [ ! -f my_workspace/my_workspace_test/src/lib.nr ]; then
  echo "Failed to create test crate."
  exit 1
fi

cd my_workspace

# This is unfortunate as it makes the test worse but in CI setting the aztec version is 0.0.1 which doesn't exist as
# a remote git tag, so we need to rewrite dependencies to use local aztec-nr.
sed -i 's|aztec = .*git.*AztecProtocol/aztec-nr.*|aztec = { path="/home/ubuntu/aztec-packages/noir-projects/aztec-nr/aztec" }|' \
  my_workspace_contract/Nargo.toml my_workspace_test/Nargo.toml

# Compile the default scaffold contract.
aztec compile

# Run the default scaffold tests.
aztec test

# --- Test adding a second contract to the workspace ---
aztec new token

# Verify token crates were created.
if [ ! -f token_contract/Nargo.toml ] || [ ! -f token_contract/src/main.nr ]; then
  echo "Failed to create token contract crate."
  exit 1
fi
if [ ! -f token_test/Nargo.toml ] || [ ! -f token_test/src/lib.nr ]; then
  echo "Failed to create token test crate."
  exit 1
fi

# Verify workspace Nargo.toml contains all four members.
if ! grep -q '"my_workspace_contract"' Nargo.toml || \
   ! grep -q '"my_workspace_test"' Nargo.toml || \
   ! grep -q '"token_contract"' Nargo.toml || \
   ! grep -q '"token_test"' Nargo.toml; then
  echo "Workspace Nargo.toml does not contain all expected members."
  exit 1
fi

# Rewrite aztec deps for token crates too.
sed -i 's|aztec = .*git.*AztecProtocol/aztec-nr.*|aztec = { path="/home/ubuntu/aztec-packages/noir-projects/aztec-nr/aztec" }|' \
  token_contract/Nargo.toml token_test/Nargo.toml

# Compile and test the full workspace (both contracts).
aztec compile
aztec test
