/**
 * Zig code generator - proves IR works across languages
 *
 * Generates idiomatic Zig bindings from the same IR used for Rust/TypeScript
 */

import type { SchemaIR, StructIR, MethodIR, TypeIR, FieldIR } from '../schema_ir.js';

export class ZigGenerator {
  generate(ir: SchemaIR): { types: string; api: string } {
    return {
      types: this.generateTypes(ir),
      api: this.generateApi(ir),
    };
  }

  private generateTypes(ir: SchemaIR): string {
    const parts: string[] = [
      '//! AUTOGENERATED - DO NOT EDIT',
      '//! Generated from Barretenberg msgpack schema',
      '',
      'const std = @import("std");',
      'const msgpack = @import("msgpack");',
      '',
    ];

    // Generate all struct definitions
    const sortedStructs = Array.from(ir.structs.values()).sort((a, b) => a.name.localeCompare(b.name));
    for (const struct of sortedStructs) {
      parts.push(this.generateStruct(struct));
      parts.push('');
    }

    // Generate Command union
    const commands = Array.from(ir.structs.values()).filter(s => s.isCommand);
    parts.push(this.generateCommandUnion(commands));
    parts.push('');

    // Generate Response union
    const responses = ir.commands.map(cmd => cmd.returnType);
    parts.push(this.generateResponseUnion(responses));
    parts.push('');

    return parts.join('\n');
  }

  private generateApi(ir: SchemaIR): string {
    const parts: string[] = [
      '//! AUTOGENERATED - DO NOT EDIT',
      '//! High-level Barretenberg API for Zig',
      '',
      'const std = @import("std");',
      'const types = @import("generated_types.zig");',
      '',
      '/// Backend interface - implement this for custom backends',
      'pub const Backend = struct {',
      '    call_fn: *const fn (*anyopaque, []const u8) anyerror![]u8,',
      '    destroy_fn: *const fn (*anyopaque) anyerror!void,',
      '    ctx: *anyopaque,',
      '',
      '    pub fn call(self: *Backend, input: []const u8) ![]u8 {',
      '        return self.call_fn(self.ctx, input);',
      '    }',
      '',
      '    pub fn destroy(self: *Backend) !void {',
      '        return self.destroy_fn(self.ctx);',
      '    }',
      '};',
      '',
      '/// High-level Barretenberg API',
      'pub const BarretenbergApi = struct {',
      '    backend: Backend,',
      '    allocator: std.mem.Allocator,',
      '',
      '    pub fn init(backend: Backend, allocator: std.mem.Allocator) BarretenbergApi {',
      '        return .{ .backend = backend, .allocator = allocator };',
      '    }',
      '',
    ];

    // Generate all API methods
    for (const method of ir.commands) {
      if (method.originalName === 'Shutdown') continue;

      parts.push(this.generateApiMethod(method, ir));
      parts.push('');
    }

    parts.push(
      '    pub fn shutdown(self: *BarretenbergApi) !void {',
      '        const cmd = types.Command{ .shutdown = types.Shutdown{} };',
      '        _ = try self.execute(cmd);',
      '        try self.backend.destroy();',
      '    }',
      '',
      '    pub fn destroy(self: *BarretenbergApi) !void {',
      '        try self.backend.destroy();',
      '    }',
      '',
      this.generateExecuteMethod(),
      '};',
    );

    return parts.join('\n');
  }

  private generateStruct(struct: StructIR): string {
    const fields = struct.fields.map(f => this.generateField(f));

    return `/// ${struct.name}\n` +
      `pub const ${struct.name} = struct {\n` +
      `    type_name: []const u8 = "${struct.originalName}",\n` +
      `${fields.join('\n')}\n` +
      `};`;
  }

  private generateField(field: FieldIR): string {
    const zigType = this.typeToZig(field.type);
    return `    ${field.name}: ${zigType},`;
  }

  private generateApiMethod(method: MethodIR, ir: SchemaIR): string {
    const params = method.params.map(p => {
      const zigType = this.makeErgonomic(this.typeToZig(p.type));
      return `${p.name}: ${zigType}`;
    }).join(', ');

    const commandField = this.toSnakeCase(method.originalName);
    const commandType = this.toPascalCase(method.originalName);

    return `    /// ${method.doc || `Execute ${method.originalName}`}\n` +
      `    pub fn ${method.name}(self: *BarretenbergApi, ${params}) !types.${method.returnType} {\n` +
      `        const cmd = types.Command{ .${commandField} = types.${commandType}{ .type_name = "${commandType}", ${this.generateFieldInits(method.params)} } };\n` +
      `        const response = try self.execute(cmd);\n` +
      `        return switch (response) {\n` +
      `            .${this.toSnakeCase(method.returnType)} => |r| r,\n` +
      `            else => error.InvalidResponse,\n` +
      `        };\n` +
      `    }`;
  }

  private generateExecuteMethod(): string {
    return `    fn execute(self: *BarretenbergApi, command: types.Command) !types.Response {\n` +
      `        // Serialize command to msgpack\n` +
      `        var list = std.ArrayList(u8).init(self.allocator);\n` +
      `        defer list.deinit();\n` +
      `        try msgpack.pack(command, list.writer());\n` +
      `\n` +
      `        // Call backend\n` +
      `        const response_bytes = try self.backend.call(list.items);\n` +
      `        defer self.allocator.free(response_bytes);\n` +
      `\n` +
      `        // Deserialize response\n` +
      `        const response = try msgpack.unpack(types.Response, self.allocator, response_bytes);\n` +
      `        return response;\n` +
      `    }`;
  }

  private generateCommandUnion(commands: StructIR[]): string {
    const fields = commands.map(c =>
      `    ${this.toSnakeCase(c.name)}: ${c.name},`
    ).join('\n');

    return `/// Command union - all possible commands\n` +
      `pub const Command = union(enum) {\n` +
      `${fields}\n` +
      `};`;
  }

  private generateResponseUnion(responseTypes: string[]): string {
    const uniqueTypes = [...new Set(responseTypes)];
    const fields = uniqueTypes.map(t =>
      `    ${this.toSnakeCase(t)}: ${t},`
    ).join('\n');

    return `/// Response union - all possible responses\n` +
      `pub const Response = union(enum) {\n` +
      `${fields}\n` +
      `};`;
  }

  private generateFieldInits(params: FieldIR[]): string {
    return params.map(p => `.${p.name} = ${p.name}`).join(', ');
  }

  private typeToZig(type: TypeIR): string {
    switch (type.kind) {
      case 'primitive':
        switch (type.name) {
          case 'bool': return 'bool';
          case 'u8': return 'u8';
          case 'u16': return 'u16';
          case 'u32': return 'u32';
          case 'u64': return 'u64';
          case 'f64': return 'f64';
          case 'String': return '[]const u8';
          case 'bytes': return '[]const u8';
          default: return type.name!;
        }
      case 'vec':
        return `[]${this.typeToZig(type.elementType!)}`;
      case 'array':
        return `[${type.size}]${this.typeToZig(type.elementType!)}`;
      case 'option':
        return `?${this.typeToZig(type.elementType!)}`;
      case 'custom':
        return type.name!;
      default:
        return 'unknown';
    }
  }

  private makeErgonomic(zigType: string): string {
    // Zig already uses slices which are ergonomic
    return zigType;
  }

  private toSnakeCase(s: string): string {
    return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
  }

  private toPascalCase(s: string): string {
    if (!s.includes('_') && s.charAt(0) === s.charAt(0).toUpperCase()) {
      return s;
    }
    return s.split('_').map(part =>
      part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()
    ).join('');
  }
}
