services:
  redis:
    image: redis:latest
    ports:
      - "15233:6379"

  prover:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BB_VERSION: "5.0.0-nightly.20260311"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BB_EXECUTABLE_PATH=/root/.bb/bb
    restart: unless-stopped
    deploy:
      replicas: 4
