# The build context for docs is the root of the repository.
# Be very specific about what we include.
*
!docs
# normally git ignored
**/node_modules
**/.netlify
**/docusaurus
**/processed-docs
**/processed-docs-cache
# rebuild patterns
!**/*.cpp
!**/*.hpp
!**/*.ts
!**/.release-please-manifest.json
!**/noir-version.json
!**/.nr
