# The build context for docs is the root of the repository.
# Be very specific about what we include.
*

!docs/docs
!docs/internal_notes
!docs/scripts
!docs/src
!docs/static
!docs/*.json
!docs/*.js
!docs/yarn.lock
!docs/netlify.toml
# rebuild patterns
!**/*.cpp
!**/*.hpp
!**/*.ts
!**/.release-please-manifest.json
!**/noir-version.json
!**/.nr
