VERSION 0.8
deps:
  FROM ../build-images/+base-slim-node
  WORKDIR /usr/src/docs
  RUN apt update && apt install -y jq curl perl && rm -rf /var/lib/apt/lists/* && apt-get clean
  COPY ./yarn.lock ./yarn.lock
  COPY ./package.json ./package.json
  RUN CI=1 yarn install

build:
  FROM ../+bootstrap
  ARG ENV
  ARG COMMIT_TAG
  ENV COMMIT_TAG=$COMMIT_TAG
  WORKDIR /usr/src/docs
  RUN CI=1 yarn install
  RUN ./scripts/build.sh
  SAVE ARTIFACT build

serve:
  ARG ENV
  FROM +deps
  COPY +build/build build
  COPY ./static static
  COPY ./src src
  COPY ./docusaurus.config.js .
  COPY ./sidebars.js .
  ENTRYPOINT ["yarn", "serve"]
  EXPOSE 3000
  SAVE ARTIFACT /usr/src/docs
  SAVE IMAGE aztecprotocol/docs-server

deploy-preview:
  BUILD ../yarn-project/+scripts-prod
  FROM ../build-images/+base-slim-node
  WORKDIR /usr/src/docs
  ARG ENV
  ARG NETLIFY_AUTH_TOKEN
  ARG NETLIFY_SITE_ID
  ARG AZTEC_BOT_COMMENTER_GITHUB_TOKEN
  ARG PR
  FROM +serve
  COPY --dir ../yarn-project/+scripts-prod/usr/src/yarn-project /usr/src
  COPY ./netlify.toml .
  COPY ./deploy_preview.sh .
  RUN NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN NETLIFY_SITE_ID=$NETLIFY_SITE_ID ./deploy_preview.sh "$PR" "$AZTEC_BOT_COMMENTER_GITHUB_TOKEN"

deploy-prod:
  BUILD ../yarn-project/+scripts-prod
  FROM ../build-images/+base-slim-node
  WORKDIR /usr/src/docs
  ARG NETLIFY_AUTH_TOKEN
  ARG NETLIFY_SITE_ID
  FROM +serve
  COPY ./netlify.toml .
  COPY ./deploy_prod.sh .
  RUN NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN NETLIFY_SITE_ID=$NETLIFY_SITE_ID ./deploy_prod.sh
