VERSION 0.8

deps:
  FROM ../build-images+build
  WORKDIR /usr/src/docs
  COPY ./yarn.lock ./yarn.lock
  COPY ./package.json ./package.json
  RUN yarn install --frozen-lockfile

build:
  ARG ENV
  ARG COMMIT_TAG
  ENV COMMIT_TAG=$COMMIT_TAG
  BUILD ../yarn-project/+build-dev
  BUILD ../+release-meta
  FROM +deps
  COPY --dir ../yarn-project/+build-dev/usr/src /usr
  COPY ../+release-meta/usr/src/.release-please-manifest.json /usr/src
  COPY . .
  RUN ./scripts/build.sh
  SAVE ARTIFACT build

export:
  FROM +build
  ENTRYPOINT ["yarn", "serve"]
  EXPOSE 3000
  SAVE ARTIFACT /usr/src/docs
  SAVE IMAGE aztecprotocol/docs-server

test:
  ARG ENV
  FROM +build
  WORKDIR /usr/src/docs
  RUN npx playwright install --with-deps

  COPY ../noir/+nargo/nargo /usr/local/bin/aztec-nargo
  RUN cp -s /usr/src/yarn-project/builder/aztec-builder-dest /usr/local/bin/aztec-builder
  RUN rm /usr/local/bin/yarn /usr/local/bin/yarnpkg && npm install -g corepack && corepack enable
  EXPOSE 3000
  WITH DOCKER \
    --load aztecprotocol/aztec:latest=../yarn-project/+aztec \
    --compose docker-compose.yml
    RUN docker compose up -d --exit-code-from=aztec --force-recreate && yarn test
  END

deploy-preview:
  BUILD ../yarn-project/+scripts-prod
  ARG ENV
  ARG NETLIFY_AUTH_TOKEN
  ARG NETLIFY_SITE_ID
  ARG AZTEC_BOT_COMMENTER_GITHUB_TOKEN
  ARG PR
  FROM +serve
  COPY --dir ../yarn-project/+scripts-prod/usr/src/yarn-project /usr/src
  COPY ./netlify.toml .
  COPY ./deploy_preview.sh .
  RUN NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN NETLIFY_SITE_ID=$NETLIFY_SITE_ID ./deploy_preview.sh $PR $AZTEC_BOT_COMMENTER_GITHUB_TOKEN

deploy-prod:
  BUILD ../yarn-project/+scripts-prod
  ARG NETLIFY_AUTH_TOKEN
  ARG NETLIFY_SITE_ID
  FROM +serve
  COPY ./netlify.toml .
  COPY ./deploy_prod.sh .
  RUN NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN NETLIFY_SITE_ID=$NETLIFY_SITE_ID ./deploy_prod.sh
