[workspace]
members = [
    "examples/circuits/hello_circuit",
    "examples/contracts/counter_contract",
    "examples/contracts/counter_contract_test",
    "examples/contracts/bob_token_contract",
    "examples/contracts/nft",
    "examples/contracts/nft_bridge",
    "examples/contracts/recursive_verification_contract",
    "examples/contracts/example_uniswap",
    "examples/webapp-tutorial/contracts",
    "examples/contracts/aave_bridge",
    "examples/contracts/logging_example",
    "examples/contracts/logging_example_test",
    "examples/contracts/packing_example"
]
