# disable-compiler-checks.cmake
# Include this file to skip most compiler feature checks and speed up configuration

# Skip compiler verification tests
set(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_C_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_FORCED TRUE CACHE INTERNAL "")

# Common compiler flag checks (Google Benchmark, etc.)
set(HAVE_CXX_FLAG_WALL ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WEXTRA ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WSHADOW ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WFLOAT_EQUAL ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WOLD_STYLE_CAST ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WERROR ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WSUGGEST_OVERRIDE ON CACHE BOOL "")
set(HAVE_CXX_FLAG_PEDANTIC ON CACHE BOOL "")
set(HAVE_CXX_FLAG_PEDANTIC_ERRORS ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WSHORTEN_64_TO_32 ON CACHE BOOL "")
set(HAVE_CXX_FLAG_FSTRICT_ALIASING ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WNO_DEPRECATED ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WSTRICT_ALIASING ON CACHE BOOL "")
set(HAVE_CXX_FLAG_WD654 OFF CACHE BOOL "")
set(HAVE_CXX_FLAG_WTHREAD_SAFETY ON CACHE BOOL "")
set(HAVE_CXX_FLAG_COVERAGE ON CACHE BOOL "")

# Runtime feature checks
set(HAVE_THREAD_SAFETY_ATTRIBUTES ON CACHE BOOL "")
set(HAVE_STD_REGEX ON CACHE BOOL "")
set(HAVE_STEADY_CLOCK ON CACHE BOOL "")

# Suppress try_compile output
set(CMAKE_REQUIRED_QUIET ON CACHE BOOL "")

# Disable testing features that trigger checks
set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "")
set(BENCHMARK_ENABLE_INSTALL OFF CACHE BOOL "")

message(STATUS "Compiler checks disabled via disable-compiler-checks.cmake")
