if(MULTITHREADING)
    message(STATUS "Multithreading is enabled.")
    add_compile_options(-pthread)
    add_link_options(-pthread)
    if(WASM)
        add_compile_options(--target=wasm32-wasi-threads)
        add_link_options(--target=wasm32-wasi-threads -Wl,--shared-memory)
        # Prevent indirect call type mismatch errors in thread_local destructors
        # (without this the benchmark flow fails at destruction point for WASM)
        add_compile_options(-fno-c++-static-destructors)
        # Enable WASM SIMD128. V8 TurboFan ≥ 9.1 (Chrome/Node 91+), wasmtime ≥ 2.0,
        # all modern browsers support v128 — the WASM binary requires a runtime
        # with SIMD enabled. Hot loops in barretenberg (e.g. Phase 5a sched→pts
        # copy in round_parallel_msm) gate v128.load/store on __wasm_simd128__.
        add_compile_options(-msimd128)
    endif()
    #add_compile_options(-fsanitize=thread)
    #add_link_options(-fsanitize=thread)
else()
    message(STATUS "Multithreading is disabled.")
    add_definitions(-DNO_MULTITHREADING)
    set(OMP_MULTITHREADING OFF)
endif()

if(OMP_MULTITHREADING)
    find_package(OpenMP REQUIRED)
    message(STATUS "OMP multithreading is enabled.")
    link_libraries(OpenMP::OpenMP_CXX)
    add_definitions(-DOMP_MULTITHREADING)
else()
    message(STATUS "OMP multithreading is disabled.")
endif()

if(ENABLE_PAR_ALGOS)
    find_package(TBB QUIET OPTIONAL_COMPONENTS tbb)
    if(${TBB_FOUND})
        message(STATUS "std::execution parallel algorithms are enabled.")
        link_libraries(TBB::tbb)
    else()
        message(STATUS "Could not locate Intel TBB, disabling std::execution parallel algorithms.")
        add_definitions(-DNO_PAR_ALGOS)
    endif()
else()
    message(STATUS "std::execution parallel algorithms are disabled.")
    add_definitions(-DNO_PAR_ALGOS)
endif()
