if(MULTITHREADING)
    message(STATUS "Multithreading is enabled.")
    add_compile_options(-pthread)
    add_link_options(-pthread)
    if(WASM)
        add_compile_options(--target=wasm32-wasi-threads)
        add_link_options(--target=wasm32-wasi-threads -Wl,--shared-memory)
    endif()
    #add_compile_options(-fsanitize=thread)
    #add_link_options(-fsanitize=thread)
else()
    message(STATUS "Multithreading is disabled.")
    add_definitions(-DNO_MULTITHREADING)
    set(OMP_MULTITHREADING OFF)
endif()

if(OMP_MULTITHREADING)
    find_package(OpenMP REQUIRED)
    message(STATUS "OMP multithreading is enabled.")
    link_libraries(OpenMP::OpenMP_CXX)
else()
    message(STATUS "OMP multithreading is disabled.")
    add_definitions(-DNO_OMP_MULTITHREADING)
endif()

if(ENABLE_PAR_ALGOS)
    find_package(TBB QUIET OPTIONAL_COMPONENTS tbb)
    if(${TBB_FOUND})
        message(STATUS "std::execution parallel algorithms are enabled.")
    else()
        message(STATUS "Could not locate Intel TBB, disabling std::execution parallel algorithms.")
        add_definitions(-DNO_PAR_ALGOS)
    endif()
else()
    message(STATUS "std::execution parallel algorithms are disabled.")
    add_definitions(-DNO_PAR_ALGOS)
endif()
