
VERSION 0.8

build-artifacts:
    FROM ../+base
    RUN ./bootstrap.sh # TODO mount cache
    # Build web bundle for browser tests
    RUN yarn workspace @aztec/end-to-end run build:web
    RUN yarn workspaces focus @aztec/end-to-end --production && yarn cache clean
    SAVE ARTIFACT /build

build:
    FROM node:18.19.1-slim
    RUN apt-get update && apt-get install jq gnupg wget -y && \
        wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
        sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
        apt-get update && \
        apt-get install google-chrome-stable -y --no-install-recommends && \
        rm -rf /var/lib/apt/lists/*
    ENV CHROME_BIN="/usr/bin/google-chrome-stable"
    COPY +build-artifacts/build /build
    WORKDIR /build/yarn-project/end-to-end

simple:
    FROM node:18.19.1-slim
    ENTRYPOINT echo hello

e2e-sandbox-example:
    # FROM earthly/dind:alpine-3.19-docker-25.0.2-r0 (TODO use docker-in-docker in prod?)
    LOCALLY
    WITH DOCKER --load aztecprotocol/aztec:latest=../+build-aztec --load aztecprotocol/end-to-end:latest=../+build
      RUN docker-compose -f ./scripts/docker-compose.yml up  --exit-code-from=sandbox --force-recreate
    END

#     steps:
#       - *checkout
#       - *setup_env
#       - run:
#           name: "Test"
#           command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_sandbox_example.test.ts
#           aztec_manifest_key: end-to-end
#     <<: *defaults_e2e_test

#   # e2e-state-vars:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_state_vars.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-block-building:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_block_building.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-nested-contract:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_nested_contract.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-static-calls:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_static_calls.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-delegate-calls:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_delegate_calls.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-non-contract-account:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_non_contract_account.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-cross-chain-messaging:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_cross_chain_messaging.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-crowdfunding-and-claim:
#   #   docker:
#   #     - image: aztecprotocol/alpine-build-image
#   #   resource_class: small
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_crowdfunding_and_claim.test.ts
#   #         aztec_manifest_key: end-to-end

#   # e2e-public-cross-chain-messaging:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_public_cross_chain_messaging.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-public-to-private-messaging:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_public_to_private_messaging.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-account-contracts:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_account_contracts.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-escrow-contract:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_escrow_contract.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-inclusion-proofs-contract:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_inclusion_proofs_contract.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-pending-note-hashes-contract:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_pending_note_hashes_contract.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-ordering:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_ordering.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # uniswap-trade-on-l1-from-l2:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=uniswap_trade_on_l1_from_l2.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # integration-archiver-l1-to-l2:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=integration_archiver_l1_to_l2.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # integration-l1-publisher:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=integration_l1_publisher.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-cli:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_cli.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-persistence:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose-no-sandbox.yml TEST=e2e_persistence.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-browser:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_aztec_js_browser.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-card-game:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_card_game.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-avm-simulator:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: AVM_ENABLED=1 cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_avm_simulator.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-fees:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_fees.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-dapp-subscription:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=e2e_dapp_subscription.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # pxe:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=pxe_sandbox.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # cli-docs-sandbox:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=cli_docs_sandbox.test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test

#   # e2e-docs-examples:
#   #   steps:
#   #     - *checkout
#   #     - *setup_env
#   #     - run:
#   #         name: "Test"
#   #         command: AVM_ENABLED=1 cond_spot_run_compose end-to-end 4 ./scripts/docker-compose.yml TEST=docs_examples_test.ts
#   #         aztec_manifest_key: end-to-end
#   #   <<: *defaults_e2e_test
