VERSION 0.8

e2e-p2p:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_p2p_network.test.ts

e2e-l1-with-wall-time:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_l1_with_wall_time.test.ts

e2e-synching:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_synching.test.ts

e2e-2-pxes:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_2_pxes.test.ts

e2e-nft:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_nft.test.ts

e2e-prover-full:
  LOCALLY
  RUN HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32} ./scripts/e2e_test.sh ./src/e2e_prover/full

e2e-prover-with-padding:
  LOCALLY
  RUN HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32} ./scripts/e2e_test.sh ./src/e2e_prover/with_padding

e2e-account-contracts:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_account_contracts.test.ts

e2e-authwit:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_authwit.test.ts

e2e-avm-simulator:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_avm_simulator.test.ts

e2e-blacklist-token-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_blacklist_token_contract

e2e-block-building:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_block_building.test.ts

e2e-bot:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_bot.test.ts

e2e-card-game:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_card_game.test.ts

e2e-cheat-codes:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_cheat_codes.test.ts

e2e-crowdfunding-and-claim:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_crowdfunding_and_claim.test.ts

e2e-delegate-calls:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_delegate_calls

e2e-deploy-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_deploy_contract

e2e-encryption:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_encryption.test.ts

e2e-escrow-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_escrow_contract.test.ts

e2e-keys:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_keys.test.ts

e2e-lending-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_lending_contract.test.ts

e2e-max-block-number:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_max_block_number.test.ts

e2e-multiple-accounts-1-enc-key:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_multiple_accounts_1_enc_key.test.ts

e2e-nested-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_nested_contract

e2e-non-contract-account:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_non_contract_account.test.ts

e2e-note-getter:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_note_getter.test.ts

e2e-ordering:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_ordering.test.ts

e2e-outbox:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_outbox.test.ts

e2e-pending-note-hashes-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_pending_note_hashes_contract.test.ts

e2e-private-voting-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_private_voting_contract.test.ts

e2e-prover-node:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_prover_node.test.ts

e2e-fees-private-payments:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/private_payments.test.ts

e2e-fees-private-refunds:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/private_refunds.test.ts

e2e-fees-gas-estimation:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/gas_estimation.test.ts

e2e-fees-dapp-subscription:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/dapp_subscription.test.ts

e2e-fees-failures:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/failures.test.ts

e2e-fees-fee-juice-payments:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/fee_juice_payments.test.ts

e2e-fees-account-init:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_fees/account_init.test.ts

e2e-cross-chain-messaging:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_cross_chain_messaging

e2e-state-vars:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_state_vars.test.ts

e2e-logs:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_event_logs.test.ts

e2e-static-calls:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_static_calls.test.ts

e2e-token-contract:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/e2e_token_contract

e2e-public-testnet:
  ARG L1_CHAIN_ID="31337"
  # automatically exported as ENV variables for below
  ARG ETHEREUM_HOST
  ARG SEQ_PUBLISHER_PRIVATE_KEY
  ARG PROVER_PUBLISHER_PRIVATE_KEY
  LOCALLY
  RUN ./scripts/e2e_test_public_testnet.sh ./src/public-testnet

flakey-e2e-tests:
  LOCALLY
  RUN ./scripts/e2e_test.sh ./src/flakey || true

e2e-sandbox-example:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh e2e_sandbox_example.test.ts

uniswap-trade-on-l1-from-l2:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh uniswap_trade_on_l1_from_l2.test.ts

integration-l1-publisher:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh integration_l1_publisher.test.ts

# Disabled, TODO https://github.com/AztecProtocol/aztec-packages/issues/6624
# integration-proof-verification:
#   LOCALLY
#   RUN COMPOSE_FILE=./scripts/docker-compose-no-sandbox.yml ./scripts/e2e_compose_test.sh integration_proof_verification.test.ts

e2e-browser:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh e2e_aztec_js_browser.test.ts

pxe:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh pxe.test.ts

e2e-docs-examples:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh docs_examples.test.ts

guides-writing-an-account-contract:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh guides/writing_an_account_contract.test.ts

guides-dapp-testing:
  LOCALLY
  RUN ./scripts/e2e_compose_test.sh guides/dapp_testing.test.ts

# TODO intermittent failure
# guides-sample-dapp:
#   LOCALLY
#   RUN ./scripts/e2e_compose_test.sh sample-dapp

# TODO currently hangs for hour+
# guides-up-quick-start:
#   LOCALLY
#   RUN ./scripts/e2e_compose_test.sh guides/up_quick_start.test.ts

bench-publish-rollup:
  LOCALLY
  ENV COMPOSE_FILE=scripts/docker-compose-no-sandbox.yml
  ENV DEBUG="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees"
  ENV HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32}
  # redundant, but just to be explicit:
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN ./scripts/e2e_compose_test.sh benchmarks/bench_publish_rollup.test.ts
  DO ../../+UPLOAD_LOGS --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-process-history:
  LOCALLY
  ENV COMPOSE_FILE=scripts/docker-compose-no-sandbox.yml
  ENV DEBUG="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees"
  ENV HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32}
  # redundant, but just to be explicit:
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN ./scripts/e2e_compose_test.sh benchmarks/bench_process_history.test.ts
  DO ../../+UPLOAD_LOGS --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-tx-size:
  LOCALLY
  ENV COMPOSE_FILE=scripts/docker-compose-no-sandbox.yml
  ENV DEBUG="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees"
  ENV HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32}
  # redundant, but just to be explicit:
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN ./scripts/e2e_compose_test.sh benchmarks/bench_tx_size_fees.test.ts
  DO ../../+UPLOAD_LOGS --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-prover:
  LOCALLY
  ENV COMPOSE_FILE=scripts/docker-compose-no-sandbox.yml
  ENV DEBUG="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees"
  ENV HARDWARE_CONCURRENCY=${HARDWARE_CONCURRENCY:-32}
  # redundant, but just to be explicit:
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN ./scripts/e2e_compose_test.sh bench_prover
  DO ../../+UPLOAD_LOGS --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

e2e-devnet-smoke:
  LOCALLY
  RUN COMPOSE_FILE=scripts/docker-compose-devnet.yml ./scripts/e2e_compose_test.sh devnet/e2e_smoke.test.ts

e2e-cli-wallet:
  LOCALLY
  RUN COMPOSE_FILE=scripts/docker-compose-wallet.yml ./scripts/e2e_compose_test.sh e2e_cli_wallet

network-smoke:
  LOCALLY
  RUN NAMESPACE=smoke FRESH_INSTALL=true FORCE_BUILD=$force_build VALUES_FILE=${values_file:-default.yaml} ./scripts/network_test.sh ./src/spartan/smoke.test.ts

network-transfer:
  LOCALLY
  RUN NAMESPACE=transfer FRESH_INSTALL=true FORCE_BUILD=$force_build VALUES_FILE=${values_file:-default.yaml} ./scripts/network_test.sh ./src/spartan/transfer.test.ts
