#!/usr/bin/env python3
"""
Generate bn254_g1_chunk_hashes.hpp by downloading g1.dat in 8MB chunks
and computing SHA-256 of each chunk.

Usage:
    python3 generate_srs_chunk_hashes.py [--output path/to/bn254_g1_chunk_hashes.hpp]

Downloads from the CDN using HTTP Range requests, so no local copy of the
full 2GB file is needed.
"""

import argparse
import hashlib
import os
import sys
import urllib.request

PRIMARY_URL = "https://crs.aztec-cdn.foundation/g1.dat"
FALLBACK_URL = "https://crs.aztec-labs.com/g1.dat"

POINT_SIZE = 64  # bytes per G1 affine element
CHUNK_SIZE_POINTS = 131072  # 2^17 points per chunk
CHUNK_SIZE_BYTES = CHUNK_SIZE_POINTS * POINT_SIZE  # 8MB

TOTAL_POINTS = (1 << 25) + 1  # 2^25 + 1 = 33,554,433
TOTAL_BYTES = TOTAL_POINTS * POINT_SIZE


def download_range(url: str, start: int, end: int) -> bytes:
    """Download a byte range from url. Returns the bytes."""
    req = urllib.request.Request(url)
    req.add_header("Range", f"bytes={start}-{end}")
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def download_chunk(chunk_index: int, chunk_start: int, chunk_end: int) -> bytes:
    """Download a chunk with fallback."""
    try:
        return download_range(PRIMARY_URL, chunk_start, chunk_end)
    except Exception as e:
        print(f"  Primary failed for chunk {chunk_index}: {e}. Trying fallback...")
        return download_range(FALLBACK_URL, chunk_start, chunk_end)


def generate_hashes() -> list[tuple[int, str]]:
    """Download all chunks and return list of (chunk_size_bytes, sha256_hex)."""
    hashes = []
    offset = 0
    chunk_index = 0

    while offset < TOTAL_BYTES:
        chunk_end = min(offset + CHUNK_SIZE_BYTES, TOTAL_BYTES) - 1
        chunk_size = chunk_end - offset + 1

        print(f"Chunk {chunk_index}: bytes {offset}-{chunk_end} ({chunk_size} bytes)...", end=" ", flush=True)
        data = download_chunk(chunk_index, offset, chunk_end)

        if len(data) != chunk_size:
            raise RuntimeError(
                f"Chunk {chunk_index}: expected {chunk_size} bytes, got {len(data)}"
            )

        h = hashlib.sha256(data).hexdigest()
        hashes.append((chunk_size, h))
        print(f"SHA-256: {h}")

        offset += CHUNK_SIZE_BYTES
        chunk_index += 1

    return hashes


def write_header(hashes: list[tuple[int, str]], output_path: str):
    """Write the C++ header file."""
    num_chunks = len(hashes)
    full_chunks = sum(1 for size, _ in hashes if size == CHUNK_SIZE_BYTES)
    last_size = hashes[-1][0] if hashes else 0

    with open(output_path, "w") as f:
        f.write("// AUTO-GENERATED by generate_srs_chunk_hashes.py \u2014 do not edit manually\n")
        f.write("#pragma once\n")
        f.write("#include <array>\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace bb::srs {\n\n")
        f.write(f"// CRS file: bn254_g1.dat ({TOTAL_BYTES} bytes = {TOTAL_POINTS} G1 points)\n")
        f.write(f"// Chunk size: {CHUNK_SIZE_BYTES} bytes ({CHUNK_SIZE_POINTS} points per {CHUNK_SIZE_BYTES // (1024*1024)}MB chunk)\n")
        f.write(f"// Total chunks: {num_chunks} ({full_chunks} full + 1 partial of {last_size} bytes)\n")
        f.write("// Regenerate with: barretenberg/scripts/generate_srs_chunk_hashes.py\n\n")
        f.write(f"static constexpr size_t SRS_CHUNK_SIZE_POINTS = {CHUNK_SIZE_POINTS};")
        f.write(f"                      // 2^17\n")
        f.write(f"static constexpr size_t SRS_CHUNK_SIZE_BYTES = SRS_CHUNK_SIZE_POINTS * {POINT_SIZE};")
        f.write(f"   // {CHUNK_SIZE_BYTES // (1024*1024)}MB\n")
        f.write(f"static constexpr size_t SRS_TOTAL_POINTS = {TOTAL_POINTS};")
        f.write(f"                         // 2^25 + 1\n")
        f.write(f"static constexpr size_t SRS_NUM_CHUNKS = {num_chunks};\n")
        f.write(f"static constexpr size_t SRS_NUM_FULL_CHUNKS = {full_chunks};\n\n")
        f.write("// clang-format off\n")
        f.write(f"// SHA-256 hashes of each {CHUNK_SIZE_BYTES // (1024*1024)}MB chunk of g1.dat")
        f.write(f" (last chunk is {last_size} bytes)\n")
        f.write(
            f"static constexpr std::array<std::array<uint8_t, 32>, {num_chunks}> BN254_G1_CHUNK_HASHES = {{{{\n"
        )

        for i, (size, h) in enumerate(hashes):
            hex_bytes = ", ".join(f"0x{h[j:j+2]}" for j in range(0, 64, 2))
            comma = "," if i < num_chunks - 1 else ""
            f.write(f"    {{ {hex_bytes} }}{comma}\n")

        f.write("}};\n")
        f.write("// clang-format on\n\n")
        f.write("} // namespace bb::srs\n")

    print(f"\nWrote {output_path} with {num_chunks} chunk hashes.")


def main():
    parser = argparse.ArgumentParser(description="Generate SRS chunk hash header")
    default_output = os.path.join(
        os.path.dirname(__file__),
        "..",
        "cpp",
        "src",
        "barretenberg",
        "srs",
        "factories",
        "bn254_g1_chunk_hashes.hpp",
    )
    parser.add_argument("--output", "-o", default=default_output, help="Output header path")
    args = parser.parse_args()

    output = os.path.realpath(args.output)
    print(f"Generating chunk hashes for {TOTAL_POINTS} points ({TOTAL_BYTES} bytes)")
    print(f"Chunk size: {CHUNK_SIZE_POINTS} points ({CHUNK_SIZE_BYTES} bytes)")
    print(f"Output: {output}\n")

    hashes = generate_hashes()
    write_header(hashes, output)


if __name__ == "__main__":
    main()
