import { toSnakeCase } from "./naming.ts";

export interface TypeScriptPackageOptions {
  prefix: string;
  packageName: string;
  binaryName: string;
  binaryEnvVar: string;
  ipcRuntimeDependency: string;
  ipcPathArgs: string[];
  transports: string[];
  /** wasm transport: basename of the single-thread module shipped in the package's wasm/ directory. */
  wasmModule?: string;
  /** wasm transport: basename of the threads module shipped in the package's wasm/ directory. */
  wasmThreadsModule?: string;
  /** Whether generated/curve_constants.ts is emitted alongside (re-exported from the entries). */
  curveConstants?: boolean;
}

function className(prefix: string): string {
  return `${prefix}Service`;
}

function binaryFinderName(prefix: string): string {
  return `find${prefix}Binary`;
}

function envName(binaryName: string): string {
  return `${binaryName.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase()}_PATH`;
}

function packageStem(packageName: string): string {
  return packageName.startsWith("@") ? packageName.split("/")[1]! : packageName;
}

function archPackageNames(packageName: string): Record<string, string> {
  return {
    "linux-x64": `${packageName}-linux-x64`,
    "darwin-x64": `${packageName}-darwin-x64`,
    "linux-arm64": `${packageName}-linux-arm64`,
    "darwin-arm64": `${packageName}-darwin-arm64`,
  };
}

const ARCH_PACKAGES = [
  { buildDir: "amd64-linux", suffix: "linux-x64", os: "linux", cpu: "x64" },
  { buildDir: "arm64-linux", suffix: "linux-arm64", os: "linux", cpu: "arm64" },
  { buildDir: "amd64-macos", suffix: "darwin-x64", os: "darwin", cpu: "x64" },
  {
    buildDir: "arm64-macos",
    suffix: "darwin-arm64",
    os: "darwin",
    cpu: "arm64",
  },
] as const;

export function defaultBinaryEnvVar(binaryName: string): string {
  return envName(binaryName);
}

function generatePackageTsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          declaration: true,
          declarationMap: true,
          composite: true,
          outDir: "dest",
          rootDir: "src",
          tsBuildInfoFile: ".tsbuildinfo",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
        },
        include: ["src/**/*.ts"],
      },
      null,
      2,
    ) + "\n"
  );
}

export interface TypeScriptServerPackageOptions {
  prefix: string;
  packageName: string;
  /** Basename of the schema file shipped at the package root (the wire contract). */
  schemaFileName: string;
}

/**
 * Package shell for a server-side binding package: pure generated TS (wire
 * types + Handler/dispatch) plus the schema itself. No binary, no arch
 * packages — the transport is provided by the consumer (e.g. UdsIpcServer
 * from @aztec-foundation/ipc-runtime).
 */
export class TypeScriptServerPackageCodegen {
  constructor(private opts: TypeScriptServerPackageOptions) {}

  generatePackageJson(): string {
    const pkg = {
      name: this.opts.packageName,
      version: "0.1.0",
      type: "module",
      exports: {
        ".": {
          types: "./dest/index.d.ts",
          default: "./dest/index.js",
        },
        // Expose the schema for consumers that want to regenerate bindings
        // or inspect the wire contract.
        [`./${this.opts.schemaFileName}`]: `./${this.opts.schemaFileName}`,
      },
      files: ["dest/", this.opts.schemaFileName, "README.md"],
      scripts: {
        clean: "rm -rf dest .tsbuildinfo",
        build: "tsc -p tsconfig.json",
      },
      dependencies: {
        msgpackr: "^1.11.2",
        tslib: "^2.4.0",
      },
      devDependencies: {
        "@types/node": "^22.15.17",
        typescript: "^5.3.3",
      },
    };
    return JSON.stringify(pkg, null, 2) + "\n";
  }

  generateTsconfig(): string {
    return generatePackageTsconfig();
  }

  generateIndex(): string {
    return `export * from './generated/api_types.js';
export * from './generated/server.js';
`;
  }

  generateReadme(): string {
    return `# ${this.opts.packageName}

Generated TypeScript server bindings for the ${this.opts.prefix} IPC service:
wire types, the \`Handler\` interface, and \`handleRequest\`/\`dispatch\`. The
byte transport is provided by the consumer — e.g. \`UdsIpcServer\` from
\`@aztec-foundation/ipc-runtime\`.

\`\`\`ts
import { UdsIpcServer } from '@aztec-foundation/ipc-runtime';
import { type Handler, handleRequest } from '${this.opts.packageName}';

const handler: Handler = /* implement the generated interface */;
const server = await UdsIpcServer.listen(socketPath, (_clientId, request) =>
  handleRequest(handler, request),
);
\`\`\`

The schema this package was generated from ships at
\`${this.opts.packageName}/${this.opts.schemaFileName}\`; its hash is exported
as \`SCHEMA_HASH\`.

## Build

The whole package (shell and \`src/\`) is generated by ipc-codegen; build
through the owning project's \`./bootstrap.sh\`, which regenerates and then
runs \`yarn build\`.
`;
  }
}

/**
 * Client package shell: one TS package that owns how the service is reached. Its entries
 * (node, browser, react-native — selected by export condition) offer the backends that exist on
 * that host and a `create` that picks one by default, can be forced to one, or takes a backend
 * object of the consumer's own.
 */
export class TypeScriptPackageCodegen {
  constructor(private opts: TypeScriptPackageOptions) {}

  private get wasm(): boolean {
    return this.opts.transports.includes("wasm");
  }

  private get processTransports(): string[] {
    return this.opts.transports.filter((t) => t !== "wasm");
  }

  private get process(): boolean {
    return this.processTransports.length > 0;
  }

  private get shm(): boolean {
    return this.processTransports.includes("shm");
  }

  private generatedExports(): string {
    return `export * from './generated/api_types.js';
export { AsyncApi } from './generated/async.js';
export { SyncApi } from './generated/sync.js';
${this.opts.curveConstants ? "export * from './generated/curve_constants.js';\n" : ""}`;
  }

  generatePackageJson(): string {
    const archPackages = archPackageNames(this.opts.packageName);
    const scripts: Record<string, string> = {
      clean: "rm -rf dest .tsbuildinfo",
      build: "tsc -p tsconfig.json",
      prepare_arch_packages: "./scripts/prepare_arch_packages.sh",
    };
    const entry = (name: string) => ({
      types: `./dest/${name}.d.ts`,
      default: `./dest/${name}.js`,
    });

    const pkg = {
      name: this.opts.packageName,
      version: "0.1.0",
      type: "module",
      // Put the native binary on the consumer's PATH. The bin target is a JS
      // launcher (dest/bin.js), not the binary itself: the binary ships in the
      // per-arch optional-dependency packages and is resolved at runtime, and
      // npm only links the main package's own bin onto PATH.
      ...(this.opts.binaryName
        ? { bin: { [this.opts.binaryName]: "./dest/bin.js" } }
        : {}),
      // main/types for consumers resolving without export conditions (a CommonJS build's
      // TypeScript resolution); `exports` is authoritative everywhere else.
      main: "./dest/index.js",
      types: "./dest/index.d.ts",
      // Metro reads this field; bundlers with export conditions use the entry below.
      "react-native": "./dest/react-native.js",
      exports: {
        // One entry per host, each with its own types: a browser consumer never sees the
        // process backend, a React Native one sees neither process nor wasm.
        ".": {
          ...(this.wasm ? { browser: entry("browser") } : {}),
          "react-native": entry("react-native"),
          types: "./dest/index.d.ts",
          default: "./dest/index.js",
        },
        ...(this.wasm ? { "./browser": entry("browser") } : {}),
        "./react-native": entry("react-native"),
      },
      files: ["dest/", ...(this.wasm ? ["wasm/"] : []), "README.md"],
      scripts,
      dependencies: {
        "@aztec-foundation/ipc-runtime": this.opts.ipcRuntimeDependency,
        msgpackr: "^1.11.2",
        tslib: "^2.4.0",
      },
      optionalDependencies: Object.fromEntries(
        Object.values(archPackages).map((packageName) => [
          packageName,
          "0.1.0",
        ]),
      ),
      devDependencies: {
        "@types/node": "^22.15.17",
        typescript: "^5.3.3",
      },
    };
    return JSON.stringify(pkg, null, 2) + "\n";
  }

  generateBin(): string {
    const findBinary = binaryFinderName(this.opts.prefix);
    return `#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { ${findBinary} } from './platform.js';

const binaryPath = ${findBinary}();
if (!binaryPath) {
  console.error(
    "${this.opts.binaryName}: native binary not found. Install the matching " +
      "'${this.opts.packageName}-<platform>' package, set ${this.opts.binaryEnvVar}, or pass its path.",
  );
  process.exit(1);
}

const result = spawnSync(binaryPath, process.argv.slice(2), { stdio: 'inherit' });
if (result.error) {
  console.error(result.error.message);
  process.exit(1);
}
process.exit(result.status ?? 1);
`;
  }

  generateArchPackageJson(suffix: string, os: string, cpu: string): string {
    const pkg = {
      name: `${this.opts.packageName}-${suffix}`,
      version: "0.1.0",
      description: `Native binary for ${this.opts.packageName} (${suffix})`,
      license: "MIT",
      os: [os],
      cpu: [cpu],
      files: [this.opts.binaryName],
      preferUnplugged: true,
    };
    return JSON.stringify(pkg, null, 2) + "\n";
  }

  generateArchPackageManifests(): Array<{ path: string; content: string }> {
    const stem = packageStem(this.opts.packageName);
    return ARCH_PACKAGES.map(({ suffix, os, cpu }) => ({
      path: `packages/${stem}-${suffix}/package.json`,
      content: this.generateArchPackageJson(suffix, os, cpu),
    }));
  }

  generateTsconfig(): string {
    return generatePackageTsconfig();
  }

  /** The spawned-process backend (node only): options, environment, and the two spawn functions. */
  generateProcess(): string {
    const { prefix, binaryName, packageName } = this.opts;
    const findBinary = binaryFinderName(prefix);
    const transports = this.processTransports.map((t) => `'${t}'`).join(" | ");
    const defaultTransport = this.processTransports.includes("uds")
      ? "uds"
      : this.processTransports[0]!;
    const ipcPathArgs = JSON.stringify(this.opts.ipcPathArgs);
    const shm = this.shm;

    return `import { IpcSpawnError, SpawnedProcessBackend${shm ? ", SpawnedProcessBackendSync" : ""} } from '@aztec-foundation/ipc-runtime';
import type { IpcErrorFactory } from './generated/async.js';
import { ${findBinary} } from './platform.js';

export type ${prefix}Transport = ${transports};

/** Options for running '${binaryName}' as a spawned process (node only). */
export interface ${prefix}ProcessOptions {
  /** Path of the binary. Default: ${this.opts.binaryEnvVar}, then the installed arch package. */
  binaryPath?: string;
  transport?: ${prefix}Transport;
  /** Threads the service may use, exported to it as HARDWARE_CONCURRENCY and RAYON_NUM_THREADS. */
  threads?: number;
  logger?: (msg: string) => void;
  connectTimeoutMs?: number;
  env?: NodeJS.ProcessEnv;
  extraArgs?: string[];
  /**
   * Respawn the server on the next call after it dies, instead of failing all
   * subsequent calls. Only enable for stateless servers: a respawned process
   * remembers nothing, so any server-side session state held by callers would
   * silently dangle.
   */
  respawn?: boolean;
  /** Let node exit while the process is alive (it must exit on its own when its parent does). */
  unref?: boolean;
  /** Also unref the child's stdout/stderr pipes (present with \`logger\`); log lines may then go unread at exit. */
  unrefStdio?: boolean;
  createError?: IpcErrorFactory;
${shm ? "  /** shm: fixed client slot; default: self-allocated (0 for the synchronous backend). */\n  clientId?: number;\n  /** shm: override the ipc-runtime native addon path. */\n  napiPath?: string;\n" : ""}}

/** The name this package's first version used for the spawn options. */
export type ${prefix}ServiceOptions = ${prefix}ProcessOptions;

/** The process's environment: the caller's, plus the thread count under both names services read. */
export function processEnv(options: { threads?: number; env?: NodeJS.ProcessEnv }): NodeJS.ProcessEnv | undefined {
  if (options.threads === undefined) {
    return options.env;
  }
  const threads = String(options.threads);
  return { HARDWARE_CONCURRENCY: threads, RAYON_NUM_THREADS: threads, ...options.env };
}

function resolveBinary(binaryPath?: string): string {
  const resolved = ${findBinary}(binaryPath);
  if (!resolved) {
    throw new IpcSpawnError('${binaryName} binary not found', /*retry=*/ false);
  }
  return resolved;
}

/**
 * Spawn '${binaryName}' and connect to it. Process lifecycle — connectivity, death detection,
 * optional respawn, teardown — is owned by the backend (see SpawnedProcessBackend in ipc-runtime).
 * Failed calls carry a 'retry' property set to true when the failure was environmental.
 */
export async function spawnProcessBackend(options: ${prefix}ProcessOptions = {}): Promise<SpawnedProcessBackend> {
  return SpawnedProcessBackend.spawn({
    binaryPath: resolveBinary(options.binaryPath),
    binaryName: '${binaryName}',
    instancePrefix: '${toSnakeCase(prefix)}',
    ipcPathArgs: ${ipcPathArgs},
    transport: options.transport ?? '${defaultTransport}',
    logger: options.logger,
    connectTimeoutMs: options.connectTimeoutMs,
    env: processEnv(options),
    extraArgs: options.extraArgs,
    respawn: options.respawn,
    unref: options.unref,
    unrefStdio: options.unrefStdio,
${shm ? "    clientId: options.clientId,\n    napiPath: options.napiPath,\n" : ""}  });
}
${
  shm
    ? `
/** The synchronous process backend: shared memory is the one transport with a synchronous client. */
export async function spawnProcessBackendSync(options: ${prefix}ProcessOptions = {}): Promise<SpawnedProcessBackendSync> {
  if (options.transport !== undefined && options.transport !== 'shm') {
    throw new Error('${packageName}: the synchronous backend needs the shm transport');
  }
  return SpawnedProcessBackendSync.spawn({
    binaryPath: resolveBinary(options.binaryPath),
    binaryName: '${binaryName}',
    instancePrefix: '${toSnakeCase(prefix)}-sync',
    ipcPathArgs: ${ipcPathArgs},
    transport: 'shm',
    logger: options.logger,
    connectTimeoutMs: options.connectTimeoutMs,
    env: processEnv(options),
    extraArgs: options.extraArgs,
    unref: options.unref,
    unrefStdio: options.unrefStdio,
    clientId: options.clientId ?? 0,
    napiPath: options.napiPath,
  });
}
`
    : ""
}`;
  }

  /** Shared shape of the create options: a backend name, a backend object, or nothing (defaults). */
  private createOptionTypes(backends: string[]): string {
    const { prefix } = this.opts;
    const process = this.process;
    const wasm = this.wasm;
    const backendType = backends.join(" | ") || "never";
    const defaults = [
      process &&
        `the spawned process when the '${this.opts.binaryName}' binary resolves`,
      wasm && "the wasm module",
    ]
      .filter(Boolean)
      .join(", otherwise ");
    return `export type ${prefix}Backend = ${backendType};

/** Options for ${className(prefix)}.create / createBackend. */
export interface ${prefix}CreateOptions {
  /**
   * Unset: ${defaults}. A name forces that backend, with no fallback. An object (anything with
   * call()/destroy(), e.g. a bridge to a natively linked library) is used as is.
   */
  backend?: ${prefix}Backend | IpcClientAsync;
  /** Threads the service may use: a process reads them from HARDWARE_CONCURRENCY/RAYON_NUM_THREADS; wasm runs that many. */
  threads?: number;
  logger?: (msg: string) => void;
  createError?: IpcErrorFactory;
  /** Let node exit while the backend is alive (a process that watches its parent, or the wasm workers). */
  unref?: boolean;
${process ? `  process?: Omit<${prefix}ProcessOptions, 'threads' | 'logger' | 'createError'>;\n` : ""}${wasm ? `  wasm?: Omit<${prefix}WasmOptions, 'threads' | 'logger' | 'createError'>;\n` : ""}}

/** Options for ${className(prefix)}Sync.create / createBackendSync. */
export interface ${prefix}CreateSyncOptions {
  /** As for the asynchronous form; the synchronous wasm module runs on the calling thread, single-threaded. */
  backend?: ${prefix}Backend | IpcClientSync;
  /** Threads a spawned process may use (the synchronous wasm module always has one). */
  threads?: number;
  logger?: (msg: string) => void;
  createError?: IpcErrorFactory;
  unref?: boolean;
${process ? `  process?: Omit<${prefix}ProcessOptions, 'threads' | 'logger' | 'createError'>;\n` : ""}${wasm ? `  wasm?: Omit<${prefix}WasmOptions, 'threads' | 'worker' | 'logger' | 'createError'>;\n` : ""}}
`;
  }

  /** The service classes over createBackend/createBackendSync, with the direct constructors this entry offers. */
  private serviceClasses(opts: { process: boolean; wasm: boolean }): string {
    const { prefix } = this.opts;
    const svc = className(prefix);
    const { process, wasm } = opts;
    return `/**
 * The ${prefix} service: the generated API over whichever backend \`create\` chose, forced, or was
 * given.${process ? " Process lifecycle stays inside the backend and never leaks onto this API." : ""}
 */
export class ${svc} extends AsyncApi {
  private constructor(backend: IpcClientAsync, createError?: IpcErrorFactory) {
    super(backend, createError);
  }

  static async create(options: ${prefix}CreateOptions = {}): Promise<${svc}> {
    return new ${svc}(await createBackend(options), options.createError);
  }
${
  process
    ? `
  /** The service as a spawned '${this.opts.binaryName}' process (no fallback). */
  static async spawn(options: ${prefix}ProcessOptions = {}): Promise<${svc}> {
    return new ${svc}(await spawnProcessBackend(options), options.createError);
  }
`
    : ""
}${
      wasm
        ? `
  /** The service over the in-process wasm module (no fallback). */
  static async wasm(options: ${prefix}WasmOptions = {}): Promise<${svc}> {
    return new ${svc}(await createWasmBackend(options), options.createError);
  }
`
        : ""
    }${
      process
        ? `
  /** The spawned process behind this service, when that is what backs it. */
  get process(): SpawnedProcessBackend | undefined {
    return this.backend instanceof SpawnedProcessBackend ? this.backend : undefined;
  }

  getIpcPath(): string {
    return this.requireProcess().getIpcPath();
  }

  sendProcessSignal(signal: NodeJS.Signals): void {
    this.requireProcess().sendProcessSignal(signal);
  }

  private requireProcess(): SpawnedProcessBackend {
    const process = this.process;
    if (!process) {
      throw new Error('${svc}: not backed by a spawned process');
    }
    return process;
  }
`
        : ""
    }}

/** The synchronous ${prefix} service: every call blocks the calling thread until the service answers. */
export class ${svc}Sync extends SyncApi {
  private constructor(backend: IpcClientSync, createError?: IpcErrorFactory) {
    super(backend, createError);
  }

  static async create(options: ${prefix}CreateSyncOptions = {}): Promise<${svc}Sync> {
    return new ${svc}Sync(await createBackendSync(options), options.createError);
  }
${
  process && this.shm
    ? `
  /** The service as a spawned '${this.opts.binaryName}' process over shared memory (no fallback). */
  static async spawn(options: ${prefix}ProcessOptions = {}): Promise<${svc}Sync> {
    return new ${svc}Sync(await spawnProcessBackendSync(options), options.createError);
  }
`
    : ""
}${
      wasm
        ? `
  /** The service over the single-threaded in-process wasm module (no fallback). */
  static async wasm(options: ${prefix}WasmOptions = {}): Promise<${svc}Sync> {
    return new ${svc}Sync(await createWasmBackendSync(options), options.createError);
  }
`
        : ""
    }}
`;
  }

  /** Node entry: every backend the package has, and the default policy over them. */
  generateIndex(): string {
    const { prefix, binaryName, packageName } = this.opts;
    const findBinary = binaryFinderName(prefix);
    const process = this.process;
    const wasm = this.wasm;
    const shm = this.shm;
    const backends = [process && "'process'", wasm && "'wasm'"].filter(
      Boolean,
    ) as string[];

    return `import { type IpcClientAsync, type IpcClientSync${process ? ", SpawnedProcessBackend" : ""} } from '@aztec-foundation/ipc-runtime';
${wasm ? "import { type WasmFfiBackend, platform } from '@aztec-foundation/ipc-runtime/wasm/node';\n" : ""}import { AsyncApi, type IpcErrorFactory } from './generated/async.js';
import { SyncApi } from './generated/sync.js';
${process ? `import { type ${prefix}ProcessOptions, spawnProcessBackend${shm ? ", spawnProcessBackendSync" : ""} } from './process.js';\n` : ""}import { ${findBinary} } from './platform.js';
${wasm ? `import { type ${prefix}WasmOptions, createWasmBackendSync, createWasmBackendWith } from './wasm.js';\n` : ""}
${this.generatedExports()}${process ? "export * from './process.js';\n" : ""}${wasm ? "export * from './wasm.js';\n" : ""}export { ${findBinary} } from './platform.js';

${this.createOptionTypes(backends)}${
      wasm
        ? `
/**
 * The ${binaryName} wasm module in-process (node): the main instance in a worker thread by default,
 * wasi threads on further workers.
 */
export function createWasmBackend(options: ${prefix}WasmOptions = {}): Promise<WasmFfiBackend> {
  return createWasmBackendWith(
    {
      createMainWorker: () => platform.createWorker(new URL('./wasm/node/main.worker.js', import.meta.url)),
      createThreadWorker: () => platform.createWorker(new URL('./wasm/thread.worker.js', import.meta.url)),
    },
    options,
  );
}
`
        : ""
    }
/**
 * The backend \`${className(prefix)}.create\` would use for \`options\`, for facades that wrap the
 * generated API themselves. Unset backend: ${process ? `the process when the binary resolves${wasm ? ", falling back to wasm if it cannot be spawned" : ""}` : "the wasm module"}.
 */
export async function createBackend(options: ${prefix}CreateOptions = {}): Promise<IpcClientAsync> {
  if (typeof options.backend === 'object') {
    return options.backend;
  }
  const common = { threads: options.threads, logger: options.logger, unref: options.unref };
${
  process
    ? `  if (options.backend === 'process' || (options.backend === undefined && (!${wasm} || ${findBinary}(options.process?.binaryPath)))) {
    try {
      return await spawnProcessBackend({ ...common, unrefStdio: options.unref, ...options.process });
    } catch (err) {
      if (options.backend === 'process' || !${wasm}) {
        throw err;
      }
      options.logger?.(\`${binaryName} process unavailable (\${(err as Error).message}); falling back to wasm\`);
    }
  }
`
    : ""
}${
      wasm
        ? `  if (options.backend === undefined || options.backend === 'wasm') {
    return createWasmBackend({ ...common, ...options.wasm });
  }
`
        : ""
    }  throw new Error(\`${packageName}: no such backend here: \${String(options.backend)}\`);
}

/** The synchronous counterpart of createBackend${shm ? ": the process over shared memory" : ""}${shm && wasm ? ", else " : ""}${wasm ? "the single-threaded wasm module" : ""}. */
export async function createBackendSync(options: ${prefix}CreateSyncOptions = {}): Promise<IpcClientSync> {
  if (typeof options.backend === 'object') {
    return options.backend;
  }
  const common = { threads: options.threads, logger: options.logger, unref: options.unref };
${
  shm
    ? `  if (options.backend === 'process' || (options.backend === undefined && (!${wasm} || ${findBinary}(options.process?.binaryPath)))) {
    try {
      return await spawnProcessBackendSync({ ...common, unrefStdio: options.unref, ...options.process });
    } catch (err) {
      if (options.backend === 'process' || !${wasm}) {
        throw err;
      }
      options.logger?.(\`${binaryName} process unavailable (\${(err as Error).message}); falling back to wasm\`);
    }
  }
`
    : ""
}${
      wasm
        ? `  if (options.backend === undefined || options.backend === 'wasm') {
    return createWasmBackendSync({ logger: options.logger, unref: options.unref, ...options.wasm });
  }
`
        : ""
    }  throw new Error(\`${packageName}: no such synchronous backend here: \${String(options.backend)}\`);
}

${this.serviceClasses({ process, wasm })}`;
  }

  /** Browser entry: the service runs in-process as a wasm module; there is no process to spawn. */
  generateBrowserIndex(): string {
    const { prefix, packageName } = this.opts;

    return `import type { IpcClientAsync, IpcClientSync } from '@aztec-foundation/ipc-runtime';
import { type WasmFfiBackend, workerHandle } from '@aztec-foundation/ipc-runtime/wasm/browser';
import { AsyncApi, type IpcErrorFactory } from './generated/async.js';
import { SyncApi } from './generated/sync.js';
import { type ${prefix}WasmOptions, createWasmBackendSync, createWasmBackendWith } from './wasm.js';

${this.generatedExports()}export * from './wasm.js';

export type ${prefix}Backend = 'wasm';

/** Options for ${className(prefix)}.create / createBackend (browser: the wasm module, or a backend object). */
export interface ${prefix}CreateOptions {
  backend?: ${prefix}Backend | IpcClientAsync;
  /** Worker threads to run with; more than one needs a cross-origin isolated page (COOP/COEP). */
  threads?: number;
  logger?: (msg: string) => void;
  createError?: IpcErrorFactory;
  unref?: boolean;
  wasm?: Omit<${prefix}WasmOptions, 'threads' | 'logger' | 'createError'>;
}

/** Options for ${className(prefix)}Sync.create / createBackendSync. */
export interface ${prefix}CreateSyncOptions {
  backend?: ${prefix}Backend | IpcClientSync;
  logger?: (msg: string) => void;
  createError?: IpcErrorFactory;
  unref?: boolean;
  wasm?: Omit<${prefix}WasmOptions, 'threads' | 'worker' | 'logger' | 'createError'>;
}

/**
 * The ${this.opts.binaryName} wasm module in-process: the main instance in a web worker by default,
 * wasi threads on further workers when the page is cross-origin isolated (COOP/COEP). The worker
 * scripts are spawned with the literal expression bundlers detect, so they ship as worker chunks
 * of the consuming application.
 */
export function createWasmBackend(options: ${prefix}WasmOptions = {}): Promise<WasmFfiBackend> {
  return createWasmBackendWith(
    {
      createMainWorker: () =>
        workerHandle(new Worker(new URL('./wasm/browser/main.worker.js', import.meta.url), { type: 'module' })),
      createThreadWorker: () =>
        workerHandle(new Worker(new URL('./wasm/thread.worker.js', import.meta.url), { type: 'module' })),
    },
    options,
  );
}

export async function createBackend(options: ${prefix}CreateOptions = {}): Promise<IpcClientAsync> {
  if (typeof options.backend === 'object') {
    return options.backend;
  }
  if (options.backend !== undefined && options.backend !== 'wasm') {
    throw new Error(\`${packageName}: no such backend in a browser: \${String(options.backend)}\`);
  }
  return createWasmBackend({ threads: options.threads, logger: options.logger, unref: options.unref, ...options.wasm });
}

export async function createBackendSync(options: ${prefix}CreateSyncOptions = {}): Promise<IpcClientSync> {
  if (typeof options.backend === 'object') {
    return options.backend;
  }
  if (options.backend !== undefined && options.backend !== 'wasm') {
    throw new Error(\`${packageName}: no such synchronous backend in a browser: \${String(options.backend)}\`);
  }
  return createWasmBackendSync({ logger: options.logger, unref: options.unref, ...options.wasm });
}

${this.serviceClasses({ process: false, wasm: true })}`;
  }

  /**
   * React Native entry: Hermes has no WebAssembly or workers and Metro cannot bundle worker URLs, so
   * this entry ships no backend of its own. A native backend package (a JSI/TurboModule bridge to
   * the service's linked library) registers itself; otherwise the consumer passes a backend object.
   */
  generateReactNativeIndex(): string {
    const { prefix, packageName, binaryName } = this.opts;
    const svc = className(prefix);

    return `import type { IpcClientAsync, IpcClientSync } from '@aztec-foundation/ipc-runtime';
import { AsyncApi, type IpcErrorFactory } from './generated/async.js';
import { SyncApi } from './generated/sync.js';

${this.generatedExports()}
/** Backend factories a native backend package registers for a service, by service name. */
export interface RegisteredBackends {
  async?: () => Promise<IpcClientAsync> | IpcClientAsync;
  sync?: () => Promise<IpcClientSync> | IpcClientSync;
}

// A well-known global rather than an import in either direction, so the native package and this
// one need not depend on each other (a type-only import keeps the runtime free of ipc-runtime).
const REGISTRY_KEY = Symbol.for('@aztec-foundation/ipc-runtime/ffi-backends');

function registry(): Map<string, RegisteredBackends> {
  const global = globalThis as unknown as Record<symbol, Map<string, RegisteredBackends> | undefined>;
  return (global[REGISTRY_KEY] ??= new Map());
}

/** Make \`factories\` the default backends for ${prefix} in this app; a native backend package calls this when imported. */
export function registerBackend(factories: RegisteredBackends): void {
  registry().set('${prefix}', factories);
}

export interface ${prefix}CreateOptions {
  /** A backend object (anything with call()/destroy()); default: the one a native package registered. */
  backend?: IpcClientAsync;
  createError?: IpcErrorFactory;
}

export interface ${prefix}CreateSyncOptions {
  backend?: IpcClientSync;
  createError?: IpcErrorFactory;
}

const NO_BACKEND =
  '${packageName}: no backend for React Native. Install a native backend package for ${binaryName} (it registers itself when imported) or pass one in options.backend.';

export async function createBackend(options: ${prefix}CreateOptions = {}): Promise<IpcClientAsync> {
  if (options.backend) {
    return options.backend;
  }
  const registered = registry().get('${prefix}')?.async;
  if (!registered) {
    throw new Error(NO_BACKEND);
  }
  return await registered();
}

export async function createBackendSync(options: ${prefix}CreateSyncOptions = {}): Promise<IpcClientSync> {
  if (options.backend) {
    return options.backend;
  }
  const registered = registry().get('${prefix}')?.sync;
  if (!registered) {
    throw new Error(NO_BACKEND);
  }
  return await registered();
}

export class ${svc} extends AsyncApi {
  private constructor(backend: IpcClientAsync, createError?: IpcErrorFactory) {
    super(backend, createError);
  }

  static async create(options: ${prefix}CreateOptions = {}): Promise<${svc}> {
    return new ${svc}(await createBackend(options), options.createError);
  }
}

export class ${svc}Sync extends SyncApi {
  private constructor(backend: IpcClientSync, createError?: IpcErrorFactory) {
    super(backend, createError);
  }

  static async create(options: ${prefix}CreateSyncOptions = {}): Promise<${svc}Sync> {
    return new ${svc}Sync(await createBackendSync(options), options.createError);
  }
}
`;
  }

  /** Platform-neutral part of the wasm transport: options, module selection, backend construction. */
  generateWasm(): string {
    const { prefix, packageName } = this.opts;
    const moduleUrl = (name: string | undefined) =>
      name ? `new URL('../wasm/${name}', import.meta.url)` : "undefined";
    // The module's FFI symbols carry the service name (see the FFI entry in SCHEMA_SPEC.md).
    const sym = prefix ? `${toSnakeCase(prefix)}_` : "";
    const ffiExports = `    entry: '${sym}ipc_ffi_entry',`;

    return `import {
  type WasmFfiBackend,
  type WasmFfiBackendSync,
  type WasmModuleSource,
  type WorkerHandle,
  createWasmFfiBackend,
  createWasmFfiBackendSync,
  platform,
  sharedMemoryAvailable,
} from '@aztec-foundation/ipc-runtime/wasm';
import type { IpcErrorFactory } from './generated/async.js';
import { hostImports } from './wasm_host_imports.js';

export { sharedMemoryAvailable } from '@aztec-foundation/ipc-runtime/wasm';

/** Options for running the ${this.opts.binaryName} wasm module in-process. */
export interface ${prefix}WasmOptions {
  /**
   * Threads to run with (1 = no worker threads; selects the single-thread module). Default: the
   * platform's parallelism where a shared memory is available, else 1. More than one thread where
   * no shared memory is available is an error, not a silent downgrade.
   */
  threads?: number;
  /** Linear memory bounds in 64 KiB pages. */
  memory?: { initial?: number; maximum?: number };
  /**
   * The module to run instead of the package's own: a URL or path, gzipped or raw bytes, a fetch
   * Response, or a compiled WebAssembly.Module.
   */
  module?: WasmModuleSource;
  /**
   * Where a call runs. Default (true) is a dedicated worker, so a long call never blocks the
   * caller — the right choice for proving, and the only safe one on a browser's main thread.
   * False runs the module on the calling thread and every call blocks it until the module
   * returns, which is cheaper per call and fine for short work off the main thread. For short
   * work *on* the main thread, prefer the synchronous backend, which always runs there.
   */
  worker?: boolean;
  /** WASI environ for the module. */
  env?: Record<string, string>;
  logger?: (msg: string) => void;
  /** Let node exit while the module's workers are alive. */
  unref?: boolean;
  createError?: IpcErrorFactory;
}

/** Worker factories a platform entry binds (see WasmFfiBinding in ipc-runtime for why factories). */
export interface WasmWorkers {
  createMainWorker: () => WorkerHandle;
  createThreadWorker: () => WorkerHandle;
}

const THREADS_MODULE: URL | undefined = ${moduleUrl(this.opts.wasmThreadsModule)};
const SINGLE_MODULE: URL | undefined = ${moduleUrl(this.opts.wasmModule)};

/**
 * The package's own module for a thread count: the threads build for more than one thread,
 * otherwise the single-thread build (each falls back to the other when the package ships only one).
 */
export function defaultWasmModule(threads: number): URL {
  const module = threads > 1 ? (THREADS_MODULE ?? SINGLE_MODULE) : (SINGLE_MODULE ?? THREADS_MODULE);
  if (!module) {
    throw new Error('${packageName}: no wasm module ships with this package');
  }
  return module;
}

/** The thread count to run with: the default where none was asked for, else the request, checked. */
export function resolveThreads(threads?: number): number {
  if (threads === undefined) {
    return sharedMemoryAvailable() ? platform.hardwareConcurrency() : 1;
  }
  if (threads > 1 && !sharedMemoryAvailable()) {
    throw new Error(
      \`${packageName}: \${threads} threads requested but no shared memory is available here \` +
        '(browsers need a cross-origin isolated page: COOP/COEP headers); pass threads: 1',
    );
  }
  return threads;
}

export async function createWasmBackendWith(workers: WasmWorkers, options: ${prefix}WasmOptions = {}): Promise<WasmFfiBackend> {
  const threads = resolveThreads(options.threads);
  const backend = await createWasmFfiBackend({
    module: options.module ?? defaultWasmModule(threads),
    threads,
    memory: options.memory,
    env: options.env,
    logger: options.logger,
    worker: options.worker,
    hostImports,
${ffiExports}
    createMainWorker: workers.createMainWorker,
    createThreadWorker: workers.createThreadWorker,
  });
  if (options.unref) {
    backend.unref();
  }
  return backend;
}

/**
 * The module on the calling thread, single-threaded: every call blocks until it returns, with no
 * worker and no message passing. This is the form for short synchronous work such as hashing,
 * including on a browser's main thread.
 */
export async function createWasmBackendSync(options: ${prefix}WasmOptions = {}): Promise<WasmFfiBackendSync> {
  const backend = await createWasmFfiBackendSync({
    module: options.module ?? defaultWasmModule(1),
    threads: 1,
    memory: options.memory,
    env: options.env,
    logger: options.logger,
    hostImports,
${ffiExports}
  });
  if (options.unref) {
    backend.unref();
  }
  return backend;
}
`;
  }

  /** wasi-threads worker: one module instance per thread. Platform-neutral (it spawns nothing). */
  generateThreadWorker(): string {
    return `import { runThreadWorker, workerSide } from '@aztec-foundation/ipc-runtime/wasm';
import { hostImports } from '../wasm_host_imports.js';

runThreadWorker(workerSide(), { hostImports });
`;
  }

  /** Main-instance worker for node. */
  generateMainWorker(): string {
    return `import { platform, runMainWorker, workerSide } from '@aztec-foundation/ipc-runtime/wasm/node';
import { hostImports } from '../../wasm_host_imports.js';

runMainWorker(workerSide(), platform, {
  hostImports,
  createThreadWorker: () => platform.createWorker(new URL('../thread.worker.js', import.meta.url)),
});
`;
  }

  /** Main-instance worker for browsers: spawns thread workers with the expression bundlers detect. */
  generateBrowserMainWorker(): string {
    return `import { platform, runMainWorker, workerHandle, workerSide } from '@aztec-foundation/ipc-runtime/wasm/browser';
import { hostImports } from '../../wasm_host_imports.js';

runMainWorker(workerSide(), platform, {
  hostImports,
  createThreadWorker: () =>
    workerHandle(new Worker(new URL('../thread.worker.js', import.meta.url), { type: 'module' })),
});
`;
  }

  /** Placeholder for a module that needs nothing beyond WASI (--package-wasm-host-imports replaces it). */
  generateDefaultHostImports(): string {
    return `import type { HostImportsFactory } from '@aztec-foundation/ipc-runtime/wasm';

/**
 * Imports the module needs beyond WASI and wasi-threads. The FFI contract needs none; a module
 * whose platform layer imports its own hooks ships them via --package-wasm-host-imports.
 */
export const hostImports: HostImportsFactory | undefined = undefined;
`;
  }

  generatePlatform(): string {
    const packageName = this.opts.packageName;
    const findBinary = binaryFinderName(this.opts.prefix);
    const envVar = this.opts.binaryEnvVar;
    const stem = packageStem(packageName);
    const archPackages = archPackageNames(packageName);

    return `import { createRequire } from 'node:module';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

export type Platform = 'x86_64-linux' | 'x86_64-darwin' | 'aarch64-linux' | 'aarch64-darwin';

const PLATFORM_TO_PACKAGE: Record<Platform, string> = {
  'x86_64-linux': '${archPackages["linux-x64"]}',
  'x86_64-darwin': '${archPackages["darwin-x64"]}',
  'aarch64-linux': '${archPackages["linux-arm64"]}',
  'aarch64-darwin': '${archPackages["darwin-arm64"]}',
};

function currentDir(): string {
  return path.dirname(fileURLToPath(import.meta.url));
}

function detectPlatform(): Platform | null {
  if (process.arch === 'x64' && process.platform === 'linux') return 'x86_64-linux';
  if (process.arch === 'x64' && process.platform === 'darwin') return 'x86_64-darwin';
  if (process.arch === 'arm64' && process.platform === 'linux') return 'aarch64-linux';
  if (process.arch === 'arm64' && process.platform === 'darwin') return 'aarch64-darwin';
  return null;
}

function findArchPackageDir(platform: Platform): string | null {
  const packageName = PLATFORM_TO_PACKAGE[platform];
  try {
    const require = createRequire(import.meta.url);
    return path.dirname(require.resolve(packageName + '/package.json'));
  } catch {
    const siblingPackageDir = path.join(currentDir(), '..', 'packages', packageName.split('/').pop()!);
    return fs.existsSync(path.join(siblingPackageDir, 'package.json')) ? siblingPackageDir : null;
  }
}

/**
 * The '${this.opts.binaryName}' binary to run: \`customPath\` if given, else \`${envVar}\`, else the
 * installed arch package for this platform. Null when none of those yields an existing file.
 */
export function ${findBinary}(customPath?: string): string | null {
  if (customPath) {
    return fs.existsSync(customPath) ? path.resolve(customPath) : null;
  }

  const envPath = process.env.${envVar};
  if (envPath) {
    return fs.existsSync(envPath) ? path.resolve(envPath) : null;
  }

  const platform = detectPlatform();
  if (!platform) {
    return null;
  }

  const archDir = findArchPackageDir(platform);
  if (archDir) {
    const candidate = path.join(archDir, '${this.opts.binaryName}');
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return null;
}

export const ARCH_PACKAGE_STEM = '${stem}';
`;
  }

  generatePrepareArchPackagesScript(): string {
    return `#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

declare -A PLATFORMS=(
${ARCH_PACKAGES.map(({ buildDir, suffix, os, cpu }) => `  ["${buildDir}"]="${suffix} ${os} ${cpu}"`).join("\n")}
)

version=$(node -p "require('./package.json').version")

declare -A BINARIES=()
for arg in "$@"; do
  case "$arg" in
    *=*)
      key="\${arg%%=*}"
      value="\${arg#*=}"
      BINARIES["$key"]="$value"
      ;;
    *)
      echo "Usage: npm run prepare_arch_packages -- [<platform>=<binary> ...]" >&2
      echo "Platforms: linux-x64, linux-arm64, darwin-x64, darwin-arm64" >&2
      exit 1
      ;;
  esac
done

for build_dir in "\${!PLATFORMS[@]}"; do
  read -r suffix os cpu <<< "\${PLATFORMS[$build_dir]}"
  pkg_name="${this.opts.packageName}-\${suffix}"
  out_dir="packages/${packageStem(this.opts.packageName)}-\${suffix}"
  binary_path="\${BINARIES[$suffix]:-\${BINARIES[$build_dir]:-}}"

  if [ -z "$binary_path" ]; then
    binary_path="build/\${build_dir}/${this.opts.binaryName}"
  fi

  if [ ! -f "$binary_path" ]; then
    echo "Skipping \${pkg_name}: no binary at \${binary_path}"
    continue
  fi

  rm -rf "\${out_dir}"
  mkdir -p "\${out_dir}"
  cp "$binary_path" "\${out_dir}/${this.opts.binaryName}"
  chmod +x "\${out_dir}/${this.opts.binaryName}" 2>/dev/null || true

  cat > "\${out_dir}/package.json" <<EOF
{
  "name": "\${pkg_name}",
  "version": "\${version}",
  "description": "Native binary for ${this.opts.packageName} (\${suffix})",
  "license": "MIT",
  "os": ["\${os}"],
  "cpu": ["\${cpu}"],
  "files": ["${this.opts.binaryName}"],
  "preferUnplugged": true
}
EOF
done
`;
  }

  generateReadme(): string {
    const svc = className(this.opts.prefix);
    const process = this.process;
    const wasm = this.wasm;
    const backends = [
      process &&
        `- \`'process'\`: spawns the \`${this.opts.binaryName}\` binary (node) and talks to it over ${this.processTransports.join(" or ")}. The binary is resolved from \`${this.opts.binaryEnvVar}\`, an explicit \`process.binaryPath\`, or the installed arch package (one of this package's optional dependencies).`,
      wasm &&
        `- \`'wasm'\`: runs the service's wasm module in-process (node and browsers) through \`@aztec-foundation/ipc-runtime/wasm\`: the main instance in a worker, wasi threads on further workers where a shared memory is available (node, or a browser page served with COOP/COEP headers), otherwise the single-thread module. The worker scripts and the module are referenced with \`new URL(..., import.meta.url)\`, so bundlers emit them as chunks and assets of the application (Vite users: exclude the package from \`optimizeDeps\`).`,
      `- an object: anything with \`call(bytes)\`/\`destroy()\`, for a transport of your own (a bridge to a natively linked library, for instance).`,
    ]
      .filter(Boolean)
      .join("\n");
    const defaultPolicy = [
      process && `the process when the binary resolves`,
      wasm && `the wasm module`,
    ]
      .filter(Boolean)
      .join(", otherwise ");
    const threadsNote = wasm
      ? "(a process reads it from `HARDWARE_CONCURRENCY`/`RAYON_NUM_THREADS`; wasm runs that many\nworker threads, and asking for more than one where no shared memory exists is an error rather than\na silent downgrade)"
      : "(the process reads it from `HARDWARE_CONCURRENCY`/`RAYON_NUM_THREADS`)";
    const syncForm = [
      this.shm && "shared memory for a process",
      wasm && "the single-threaded wasm module on the calling thread",
    ]
      .filter(Boolean)
      .join(", else ");
    const hosts = [
      "node (`default`) has every backend above",
      wasm
        ? "browsers (`browser`) have the wasm module only"
        : "browsers have no backend of their own (this service has no wasm module)",
      "React Native (`react-native`) has no built-in backend, because Hermes has no WebAssembly or workers — a native backend package registers one with `registerBackend`, or the app passes `options.backend`",
    ].join("; ");

    return `# ${this.opts.packageName}

Generated TypeScript package for the ${this.opts.prefix} service: the typed API
(\`AsyncApi\`/\`SyncApi\`, one method per command) over whichever backend reaches
the service on the current host.

\`\`\`ts
import { ${svc} } from '${this.opts.packageName}';

const service = await ${svc}.create();
try {
  const response = await service.bytes({ data: new Uint8Array([1, 2, 3]) });
} finally {
  await service.destroy();
}
\`\`\`

\`create\` picks ${defaultPolicy}. \`options.backend\` forces one, with no fallback:

${backends}

\`threads\` sets the service's parallelism for any backend
${threadsNote}.${syncForm ? ` \`${svc}Sync.create\` is the synchronous form (${syncForm}).` : ""}
\`createBackend\`/\`createBackendSync\` expose the same policy for code that wraps
the generated API itself.
${
  wasm
    ? `
## Which thread the work runs on

The caller chooses. An asynchronous wasm backend runs the module in a worker by
default, so a long call never blocks the caller; \`{ wasm: { worker: false } }\`
runs it on the calling thread instead, blocking until it returns. The
synchronous backend always runs on the calling thread, which is what short work
such as hashing wants, including on a browser's main thread. A spawned process
is off the caller's thread either way.
`
    : ""
}
## Entries per host

The package resolves to a different entry per host through export conditions:
${hosts}.

## Build

The package shell (package.json, tsconfig, \`src/*.ts\`, scripts/) is
generated; build through the owning project's \`./bootstrap.sh\`, which
regenerates and then runs \`npm install --omit=optional && npm run build\`.

To prepare per-architecture binary packages:

\`\`\`sh
npm run prepare_arch_packages -- linux-x64=/path/to/${this.opts.binaryName}
\`\`\`
`;
  }
}
