VERSION 0.8

build:
    ARG TARGETARCH
    FROM DOCKERFILE .
    SAVE IMAGE --push aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113-$TARGETARCH:latest

# Relies on both steps being published
build-multiplatform:
    FROM --platform=linux/amd64 aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113-amd64:latest
    SAVE IMAGE --push aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113:latest
    FROM --platform=linux/arm64 aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113-arm64:latest
    SAVE IMAGE --push aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113:latest

get:
    ARG TARGETARCH
    # If this is failing, we need to run earthly --push +build on both archs then earthly --push +build-multiplatform on any runner
    FROM aztecprotocol/foundry-nightly-9148dbc2fe0c72e249669b11d04caae593fa6113:latest
