name: Auto Rebase PR

on:
  pull_request:
    types: [labeled]

jobs:
  auto-rebase:
    if: contains(github.event.pull_request.labels.*.name, 'auto-rebase-pr')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          token: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}


      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Run auto rebase script
        id: rebase
        env:
          GH_TOKEN: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          set -x
          # ensure we have up to date head/base
          git fetch origin "$PR_BASE_REF" "$PR_HEAD_REF"
          # Be sure to run the auto rebase script such that we don't write to it while it's being read.
          cp ./scripts/auto_rebase_pr.sh .github/temp-script.sh
          bash .github/temp-script.sh "$PR_HEAD_REF" "$PR_BASE_REF"
          rebase_sha=$(git rev-parse HEAD)
          git switch --force-create "$PR_HEAD_REF" "origin/$PR_BASE_REF"
          git reset --hard "$rebase_sha"
          git push origin "$PR_HEAD_REF" --force-with-lease

      - name: Post failure comment
        if: failure() || steps.rebase.outcome == 'failure'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "## Auto-rebase failed ❌. [Github run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Remove label
        if: always()
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --remove-label "auto-rebase-pr"
