name: Build AVM Test Bulk with Sanitizers Container

on:
  push:
    branches:
      - next
  workflow_dispatch:
    inputs:
      commit:
        description: "Git commit SHA to build (leave empty for latest)"
        required: false
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Free up disk space on runner
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          large-packages: false

      # It runs bulk test with ASAN and MSAN sanitizers during the build
      - name: Check build
        run: |
          docker build -t avm-asan-container container-builds/avm-asan-container/
