# CI for Aztec. At a high-level, runs ./bootstrap.sh ci in root. See root README.md for more details.
# Only for internal devs. For external devs, see ci3-external.yml.
#
# CAREFUL! We use "exec" a lot to ensure signal propagation to the child process, to allow proper ec2 cleanup.
name: CI3

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  merge_group: {}

concurrency:
  # Allow full concurrency for merge-train PRs, one-run-per-branch for everything else.
  group: ci3-${{ (startsWith(github.event.pull_request.head.ref, 'merge-train/') && github.run_id) || github.event.merge_group.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    # exclusive with ci3-external.yml: never run on forks
    # (github.event.pull_request.head.repo.fork resolves to nil if not a pull request)
    if: github.event.pull_request.head.repo.fork != true && github.event.pull_request.draft == false
    environment: ${{ startsWith(github.ref, 'refs/tags/v') && 'master' || '' }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: ${{ github.event.pull_request.commits || 0 }}
          persist-credentials: false

      - name: Compute Target Branch
        id: target_branch
        run: |
          if [ "${{ github.event_name }}" == "merge_group" ]; then
            target_branch=${{ github.event.merge_group.base_ref }}
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            target_branch=${{ github.event.pull_request.base.ref }}
          else
            target_branch=${{ github.ref_name }}
          fi
          target_branch=${target_branch#refs/heads/}
          echo "target_branch=$target_branch" >> $GITHUB_OUTPUT

      - name: Set Instance Postfix for merge-train
        if: startsWith(github.event.pull_request.head.ref, 'merge-train/')
        run: echo "INSTANCE_POSTFIX=${{ github.event.pull_request.commits }}" >> $GITHUB_ENV

      - name: Setup
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 --decode > ~/.ssh/build_instance_key
          chmod 600 ~/.ssh/build_instance_key

      - name: Store GCP key
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          set +x
          umask 077
          printf '%s' "$GCP_SA_KEY" > "$GOOGLE_APPLICATION_CREDENTIALS"
          jq -e . "$GOOGLE_APPLICATION_CREDENTIALS" >/dev/null

      - name: Get Tree Hash
        run: echo "TREE_HASH=$(git rev-parse HEAD^{tree})" >> $GITHUB_ENV

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: .ci-cache
          key: ci-${{ env.TREE_HASH }}

      - name: Run
        env:
          CI_INTERNAL: "1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          EXTERNAL_ETHEREUM_HOSTS: "https://json-rpc.${{ secrets.GCP_SEPOLIA_URL }}?key=${{ secrets.GCP_SEPOLIA_API_KEY }},${{ secrets.INFURA_SEPOLIA_URL }}"
          EXTERNAL_ETHEREUM_CONSENSUS_HOST: "https://beacon.${{ secrets.GCP_SEPOLIA_URL }}"
          EXTERNAL_ETHEREUM_CONSENSUS_HOST_API_KEY: ${{ secrets.GCP_SEPOLIA_API_KEY }}
          EXTERNAL_ETHEREUM_CONSENSUS_HOST_API_KEY_HEADER: "X-goog-api-key"
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: ./.github/ci3.sh "${{ join(github.event.pull_request.labels.*.name, ',') }}"

      - name: Save cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: .ci-cache
          key: ci-${{ env.TREE_HASH }}

      - name: Post-Actions
        if: always()
        env:
          SHOULD_SQUASH_MERGE: ${{ contains(github.event.pull_request.labels.*.name, 'ci-squash-and-merge') && '1' || '0' }}
          SHOULD_UPLOAD_BENCHMARKS: ${{ (github.event_name == 'merge_group' || contains(github.event.pull_request.labels.*.name, 'ci-full')) && '1' || '0' }}
          GITHUB_TOKEN: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: ./.github/ci3-post.sh

      - name: Upload benchmarks
        if: github.event_name == 'merge_group' || contains(github.event.pull_request.labels.*.name, 'ci-full')
        uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29
        with:
          name: Aztec Benchmarks
          benchmark-data-dir-path: "bench/${{ steps.target_branch.outputs.target_branch }}"
          tool: "customSmallerIsBetter"
          output-file-path: ./bench-out/bench.json
          github-token: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          auto-push: true
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          alert-threshold: "105%"
          comment-on-alert: false
          fail-on-alert: false
          max-items-in-chart: 100
