name: commitlint

on:
  pull_request:

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install --no-save @commitlint/cli @commitlint/config-conventional
      - run: npx commitlint --from origin/next --to HEAD
;
