# Tags can kick off releases from official channels, this is locked down to admins
# or the usual release flows.
# For now we give a password to those who need to frequent ad-hoc release tagging.
name: Git Tag

on:
  workflow_dispatch:
    inputs:
      password:
        description: "Password to authorize retagging"
        required: true
        type: secret
      commit:
        description: "Commit SHA to tag"
        required: true
        type: string
      tag:
        description: "Tag name to create/update"
        required: true
        type: string

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - name: Verify password
        env:
          INPUT_PASSWORD: ${{ inputs.password }}
        run: |
          INPUT_HASH=$(echo -n "$INPUT_PASSWORD" | sha256sum | cut -d' ' -f1)
          EXPECTED_HASH="9e93bfb416b0a642b5d13bee30c46fb9fae5c5233390270d0568a98e66154f7b"
          if [ "$INPUT_HASH" != "$EXPECTED_HASH" ]; then
            echo "Invalid password"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.commit }}
          token: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}

      - name: Create/update tag
        run: |
          git config user.name "AztecBot"
          git config user.email "tech@aztec-labs.com"
          git tag "${{ inputs.tag }}" "${{ inputs.commit }}"
          git push origin "${{ inputs.tag }}"
