{
 "title": "Aztec Network Block Height Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pending & Proven Checkpoint Number",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rollup_pending_checkpoint_number) by (network)",
     "legendFormat": "Pending checkpoint height - {{network}}"
    },
    {
     "expr": "max(rollup_proven_checkpoint_number) by (network)",
     "legendFormat": "Proven checkpoint height - {{network}}"
    }
   ]
  },
  {
   "title": "Pending Checkpoint Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rollup_pending_checkpoint_number",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Proven Checkpoint Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rollup_proven_checkpoint_number",
     "legendFormat": "{{network}}"
    }
   ]
  }
 ]
}