# Module for deploying Aztec (Layer 2) infrastructure
# Should be configurable/agnostic to
# - network it is deployed to
# - the k8s cluster it is deployed to
# - metrics in use
# - ingress type
# - resource profile


terraform {
  backend "local" {}
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.16.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.38.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "kubernetes" {
  alias          = "gke-cluster"
  config_path    = "~/.kube/config"
  config_context = var.K8S_CLUSTER_CONTEXT
}

provider "helm" {
  alias = "gke-cluster"
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = var.K8S_CLUSTER_CONTEXT
  }
}

provider "google" {
  project = var.GCP_PROJECT_ID
  region  = var.GCP_REGION
}

module "web3signer" {
  # Only deploy web3signer if we have validators or provers that need to publish to L1
  count = tonumber(var.VALIDATOR_REPLICAS) > 0 ? 1 : 0

  source                                   = "../modules/web3signer"
  NAMESPACE                                = var.NAMESPACE
  RELEASE_NAME                             = var.RELEASE_PREFIX
  AZTEC_DOCKER_IMAGE                       = var.AZTEC_DOCKER_IMAGE
  CHAIN_ID                                 = var.L1_CHAIN_ID
  MNEMONIC                                 = var.VALIDATOR_MNEMONIC
  ADDRESS_CONFIGMAP_NAME                   = "${var.RELEASE_PREFIX}-attester-addresses"
  ATTESTERS_PER_NODE                       = tonumber(var.VALIDATORS_PER_NODE)
  NODE_COUNT                               = local.max_validator_nodes
  VALIDATOR_HA_REPLICAS                    = tonumber(var.VALIDATOR_HA_REPLICAS)
  VALIDATOR_MNEMONIC_START_INDEX           = tonumber(var.VALIDATOR_MNEMONIC_START_INDEX)
  VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX = tonumber(var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX)
  VALIDATOR_PUBLISHERS_PER_REPLICA         = var.VALIDATOR_PUBLISHERS_PER_REPLICA
  PROVER_COUNT                             = local.prover_agent_replica_capacity
  PUBLISHERS_PER_PROVER                    = tonumber(var.PROVER_PUBLISHERS_PER_PROVER)
  PROVER_PUBLISHER_MNEMONIC_START_INDEX    = tonumber(var.PROVER_PUBLISHER_MNEMONIC_START_INDEX)

  providers = {
    helm       = helm.gke-cluster
    kubernetes = kubernetes.gke-cluster
  }
}

module "validator_ha_postgres" {
  # Only deploy HA postgres if we have validators and HA replicas > 0
  count = tonumber(var.VALIDATOR_REPLICAS) > 0 && var.VALIDATOR_HA_REPLICAS > 0 ? 1 : 0

  source             = "../modules/validator-ha-postgres"
  NAMESPACE          = var.NAMESPACE
  RELEASE_NAME       = var.RELEASE_PREFIX
  AZTEC_DOCKER_IMAGE = var.AZTEC_DOCKER_IMAGE
  # DB_PASSWORD auto-generated by module

  providers = {
    helm       = helm.gke-cluster
    kubernetes = kubernetes.gke-cluster
  }
}

locals {
  aztec_image = {
    repository = split(":", var.AZTEC_DOCKER_IMAGE)[0]
    tag        = split(":", var.AZTEC_DOCKER_IMAGE)[1]
  }

  prover_agent_image = var.PROVER_AGENT_DOCKER_IMAGE != "" ? {
    repository = split(":", var.PROVER_AGENT_DOCKER_IMAGE)[0]
    tag        = split(":", var.PROVER_AGENT_DOCKER_IMAGE)[1]
  } : local.aztec_image

  validator_ha_image = var.VALIDATOR_HA_DOCKER_IMAGE != "" ? {
    repository = split(":", var.VALIDATOR_HA_DOCKER_IMAGE)[0]
    tag        = split(":", var.VALIDATOR_HA_DOCKER_IMAGE)[1]
  } : local.aztec_image

  prover_agent_replica_capacity = var.PROVER_ENABLED ? (var.PROVER_AGENT_KEDA_ENABLED ? var.PROVER_AGENT_KEDA_MAX_REPLICAS : tonumber(var.PROVER_REPLICAS)) : 0

  # Max node count: max of primary (VALIDATOR_REPLICAS) and HA pod counts
  # Determines how many attester keystores and publisher key ranges to generate
  effective_ha_count  = var.VALIDATOR_HA_REPLICAS > 0 ? coalesce(var.VALIDATOR_HA_REPLICA_COUNT, tonumber(var.VALIDATOR_REPLICAS)) : 0
  max_validator_nodes = max(tonumber(var.VALIDATOR_REPLICAS), local.effective_ha_count)

  # Detect local kind context (e.g., "kind-kind") to gate Service types
  is_kind = can(regex("^kind", var.K8S_CLUSTER_CONTEXT))

  kong_gateway_enabled = var.RPC_GATEWAY_ENABLED || var.PROVER_NODE_RPC_GATEWAY_ENABLED

  rpc_gateway_consumer_group             = "rpc"
  prover_node_rpc_gateway_consumer_group = "prover-node-rpc"

  rpc_gateway_auth_secret_names             = var.RPC_GATEWAY_ENABLED ? var.RPC_GATEWAY_API_KEY_SECRET_NAMES : []
  prover_node_rpc_gateway_auth_secret_names = var.PROVER_NODE_RPC_GATEWAY_ENABLED ? var.PROVER_NODE_RPC_GATEWAY_API_KEY_SECRET_NAMES : []
  rpc_gateway_consumer_secret_names         = toset(concat(local.rpc_gateway_auth_secret_names, local.prover_node_rpc_gateway_auth_secret_names))

  rpc_gateway_consumers = {
    for secret_name in local.rpc_gateway_consumer_secret_names : secret_name => {
      username                       = secret_name
      gcp_secret_manager_secret_name = secret_name
      rate_limit_minute              = 0
      consumer_groups = compact([
        contains(local.rpc_gateway_auth_secret_names, secret_name) ? local.rpc_gateway_consumer_group : "",
        contains(local.prover_node_rpc_gateway_auth_secret_names, secret_name) ? local.prover_node_rpc_gateway_consumer_group : "",
      ])
    }
  }

  rpc_gateway_routes = merge(
    var.RPC_GATEWAY_ENABLED ? {
      rpc = {
        hosts                       = var.RPC_GATEWAY_HOSTS
        route_namespace             = var.NAMESPACE
        upstream_service_name       = "${var.RELEASE_PREFIX}-rpc-aztec-node"
        upstream_service_port       = 8080
        auth_mode                   = var.RPC_GATEWAY_ALLOW_ANONYMOUS ? "keyed_with_anonymous" : "keyed_only"
        anonymous_rate_limit_minute = var.RPC_GATEWAY_ANONYMOUS_RATE_LIMIT_MINUTE
        path                        = "/"
        path_type                   = "Prefix"
        strip_path                  = false
        allowed_consumer_groups     = [local.rpc_gateway_consumer_group]
      }
    } : {},
    var.PROVER_NODE_RPC_GATEWAY_ENABLED ? {
      "prover-node-rpc" = {
        hosts                       = var.PROVER_NODE_RPC_GATEWAY_HOSTS
        route_namespace             = var.NAMESPACE
        upstream_service_name       = "${var.RELEASE_PREFIX}-prover-node"
        upstream_service_port       = 8080
        auth_mode                   = "keyed_only"
        anonymous_rate_limit_minute = 0
        path                        = var.PROVER_NODE_RPC_GATEWAY_PATH
        path_type                   = "Prefix"
        strip_path                  = var.PROVER_NODE_RPC_GATEWAY_STRIP_PATH
        allowed_consumer_groups     = [local.prover_node_rpc_gateway_consumer_group]
      }
    } : {}
  )

  internal_boot_node_url = var.DEPLOY_INTERNAL_BOOTNODE ? "http://${var.RELEASE_PREFIX}-p2p-bootstrap-node.${var.NAMESPACE}.svc.cluster.local:8080" : ""

  internal_rpc_url       = "http://${var.RELEASE_PREFIX}-rpc-aztec-node.${var.NAMESPACE}.svc.cluster.local:8080"
  internal_rpc_admin_url = "http://${var.RELEASE_PREFIX}-rpc-aztec-node-admin.${var.NAMESPACE}.svc.cluster.local:8880"

  # Common settings for all releases
  common_settings = {
    "global.aztecImage.repository"                             = local.aztec_image.repository
    "global.aztecImage.tag"                                    = local.aztec_image.tag
    "global.aztecImage.pullPolicy"                             = local.is_kind ? "IfNotPresent" : "Always"
    "global.useGcloudLogging"                                  = true
    "global.aztecNetwork"                                      = var.NETWORK
    "global.customAztecNetwork.registryContractAddress"        = var.REGISTRY_CONTRACT_ADDRESS
    "global.customAztecNetwork.feeAssetHandlerContractAddress" = var.FEE_ASSET_HANDLER_CONTRACT_ADDRESS
    "global.customAztecNetwork.l1ChainId"                      = var.L1_CHAIN_ID
    "global.otelCollectorEndpoint"                             = var.OTEL_COLLECTOR_ENDPOINT
    "global.sponsoredFPC"                                      = var.SPONSORED_FPC
    "global.testAccounts"                                      = var.TEST_ACCOUNTS
  }

  common_inline_values = yamlencode({
    global = merge(
      length(var.L1_CONSENSUS_HOST_API_KEYS) > 0 ? {
        l1ConsensusHostApiKeys = join(",", var.L1_CONSENSUS_HOST_API_KEYS)
      } : {},
      length(var.L1_CONSENSUS_HOST_API_KEY_HEADERS) > 0 ? {
        l1ConsensusHostApiKeyHeaders = join(",", var.L1_CONSENSUS_HOST_API_KEY_HEADERS)
      } : {}
    )
  })

  common_list_settings = {
    "global.l1ExecutionUrls" = var.L1_RPC_URLS
    "global.l1ConsensusUrls" = var.L1_CONSENSUS_HOST_URLS
  }

  # Generate a set of _external_ host ports to use for P2P
  # K8s will use these values to schedule pods on appropriate machines. Using random ports here will allow it to
  # colocate pods from different services or even pods from different networks onto the same physical machine
  # (so long as the VM has enough resources)
  p2p_port_p2p_bootstrap = 40400 + (parseint(substr(md5("${var.NAMESPACE}-p2p-bootstrap"), 0, 4), 16) % 100)
  p2p_port_prover        = 40400 + (parseint(substr(md5("${var.NAMESPACE}-prover"), 0, 4), 16) % 100)
  p2p_port_rpc           = 40400 + (parseint(substr(md5("${var.NAMESPACE}-rpc"), 0, 4), 16) % 100)
  p2p_port_fisherman     = 40400 + (parseint(substr(md5("${var.NAMESPACE}-fisherman"), 0, 4), 16) % 100)
  p2p_port_full_node     = 40400 + (parseint(substr(md5("${var.NAMESPACE}-full-node"), 0, 4), 16) % 100)

  p2p_port_validators = {
    for idx in range(1 + var.VALIDATOR_HA_REPLICAS) : idx => 40400 + (parseint(substr(md5("${var.NAMESPACE}-validator-${idx}"), 0, 4), 16) % 100)
  }

  # Validator configuration - extracted for dynamic HA release generation
  validator_base_config = {
    chart   = "aztec-validator"
    timeout = 1800
    values = concat([
      "common.yaml",
      "validator.yaml",
      "validator-resources-${var.VALIDATOR_RESOURCE_PROFILE}.yaml"
    ], var.VALIDATOR_HA_REPLICAS > 0 ? ["validator-resources-spot.yaml", "validator-resources-ha.yaml"] : [])
    inline_values = [yamlencode({
      validator = {
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
        node = {
          logLevel = var.LOG_LEVEL
        }
      }
    })]
    boot_node_host_path  = "validator.node.env.BOOT_NODE_HOST"
    bootstrap_nodes_path = "validator.node.env.BOOTSTRAP_NODES"
    wait                 = true
  }

  validator_common_settings = {
    "validator.service.p2p.nodePortEnabled"                                       = var.P2P_NODEPORT_ENABLED
    "validator.service.p2p.hostPortEnabled"                                       = var.P2P_HOSTPORT_ENABLED
    "validator.web3signerUrl"                                                     = "http://${var.RELEASE_PREFIX}-signer-web3signer.${var.NAMESPACE}.svc.cluster.local:9000/"
    "validator.mnemonic"                                                          = var.VALIDATOR_MNEMONIC
    "validator.mnemonicStartIndex"                                                = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.validatorsPerNode"                                                 = var.VALIDATORS_PER_NODE
    "validator.publishersPerReplica"                                              = var.VALIDATOR_PUBLISHERS_PER_REPLICA
    "validator.publisherMnemonicStartIndex"                                       = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX
    "validator.node.env.COINBASE"                                                 = var.VALIDATOR_COINBASE
    "validator.sentinel.enabled"                                                  = var.SENTINEL_ENABLED
    "validator.slash.inactivityTargetPercentage"                                  = var.SLASH_INACTIVITY_TARGET_PERCENTAGE
    "validator.slash.inactivityPenalty"                                           = var.SLASH_INACTIVITY_PENALTY
    "validator.slash.dataWithholdingPenalty"                                      = var.SLASH_DATA_WITHHOLDING_PENALTY
    "validator.slash.dataWithholdingToleranceSlots"                               = var.SLASH_DATA_WITHHOLDING_TOLERANCE_SLOTS
    "validator.slash.proposeInvalidAttestationsPenalty"                           = var.SLASH_PROPOSE_INVALID_ATTESTATIONS_PENALTY
    "validator.slash.duplicateProposalPenalty"                                    = var.SLASH_DUPLICATE_PROPOSAL_PENALTY
    "validator.slash.duplicateAttestationPenalty"                                 = var.SLASH_DUPLICATE_ATTESTATION_PENALTY
    "validator.slash.proposeDescendantOfCheckpointWithInvalidAttestationsPenalty" = var.SLASH_PROPOSE_DESCENDANT_OF_CHECKPOINT_WITH_INVALID_ATTESTATIONS_PENALTY
    "validator.slash.attestInvalidCheckpointProposalPenalty"                      = var.SLASH_ATTEST_INVALID_CHECKPOINT_PROPOSAL_PENALTY
    "validator.slash.unknownPenalty"                                              = var.SLASH_UNKNOWN_PENALTY
    "validator.slash.invalidBlockPenalty"                                         = var.SLASH_INVALID_BLOCK_PENALTY
    "validator.slash.invalidCheckpointProposalPenalty"                            = var.SLASH_INVALID_CHECKPOINT_PROPOSAL_PENALTY
    "validator.slash.offenseExpirationRounds"                                     = var.SLASH_OFFENSE_EXPIRATION_ROUNDS
    "validator.slash.maxPayloadSize"                                              = var.SLASH_MAX_PAYLOAD_SIZE
    "validator.node.env.TRANSACTIONS_DISABLED"                                    = var.TRANSACTIONS_DISABLED
    "validator.node.env.DEBUG_FORCE_TX_PROOF_VERIFICATION"                        = var.DEBUG_FORCE_TX_PROOF_VERIFICATION
    "validator.node.env.KEY_INDEX_START"                                          = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.node.env.PUBLISHER_KEY_INDEX_START"                                = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX
    "validator.node.env.VALIDATORS_PER_NODE"                                      = var.VALIDATORS_PER_NODE
    "validator.node.env.VALIDATOR_PUBLISHERS_PER_REPLICA"                         = var.VALIDATOR_PUBLISHERS_PER_REPLICA
    "validator.node.proverRealProofs"                                             = var.PROVER_REAL_PROOFS
    "validator.node.env.SEQ_MIN_TX_PER_BLOCK"                                     = var.SEQ_MIN_TX_PER_BLOCK
    "validator.node.env.SEQ_MAX_TX_PER_BLOCK"                                     = var.SEQ_MAX_TX_PER_BLOCK
    "validator.node.env.SEQ_MAX_TX_PER_CHECKPOINT"                                = var.SEQ_MAX_TX_PER_CHECKPOINT
    "validator.node.env.P2P_MAX_PENDING_TX_COUNT"                                 = var.P2P_MAX_PENDING_TX_COUNT
    "validator.node.env.SEQ_PER_BLOCK_ALLOCATION_MULTIPLIER"                      = var.SEQ_PER_BLOCK_ALLOCATION_MULTIPLIER
    "validator.node.env.SEQ_BLOCK_DURATION_MS"                                    = var.SEQ_BLOCK_DURATION_MS
    "validator.node.env.SEQ_L1_PUBLISHING_TIME_ALLOWANCE_IN_SLOT"                 = var.SEQ_L1_PUBLISHING_TIME_ALLOWANCE_IN_SLOT
    "validator.node.env.SEQ_BUILD_CHECKPOINT_IF_EMPTY"                            = var.SEQ_BUILD_CHECKPOINT_IF_EMPTY
    "validator.node.env.AZTEC_EPOCHS_LAG"                                         = var.AZTEC_EPOCHS_LAG
    "validator.node.env.SEQ_ENFORCE_TIME_TABLE"                                   = var.SEQ_ENFORCE_TIME_TABLE
    "validator.node.env.P2P_TX_POOL_DELETE_TXS_AFTER_REORG"                       = var.P2P_TX_POOL_DELETE_TXS_AFTER_REORG
    "validator.node.env.L1_PRIORITY_FEE_BUMP_PERCENTAGE"                          = var.VALIDATOR_L1_PRIORITY_FEE_BUMP_PERCENTAGE
    "validator.node.env.L1_PRIORITY_FEE_RETRY_BUMP_PERCENTAGE"                    = var.VALIDATOR_L1_PRIORITY_FEE_RETRY_BUMP_PERCENTAGE
    "validator.node.env.BLOB_ALLOW_EMPTY_SOURCES"                                 = var.BLOB_ALLOW_EMPTY_SOURCES
    "validator.node.env.PROVER_TEST_VERIFICATION_DELAY_MS"                        = var.PROVER_TEST_VERIFICATION_DELAY_MS
    "validator.node.env.BB_CHONK_VERIFY_MAX_BATCH"                                = var.BB_CHONK_VERIFY_MAX_BATCH
    "validator.node.env.BB_CHONK_VERIFY_BATCH_CONCURRENCY"                        = var.BB_CHONK_VERIFY_BATCH_CONCURRENCY
    "validator.node.env.DEBUG_P2P_INSTRUMENT_MESSAGES"                            = var.DEBUG_P2P_INSTRUMENT_MESSAGES
    "validator.node.secret.envEnabled"                                            = true
    "validator.node.secret.mnemonic"                                              = var.VALIDATOR_MNEMONIC
    "validator.node.secret.mnemonicIndex"                                         = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.node.env.P2P_GOSSIPSUB_D"                                          = var.P2P_GOSSIPSUB_D
    "validator.node.env.P2P_GOSSIPSUB_DLO"                                        = var.P2P_GOSSIPSUB_DLO
    "validator.node.env.P2P_GOSSIPSUB_DHI"                                        = var.P2P_GOSSIPSUB_DHI
    "validator.node.env.P2P_DROP_TX_CHANCE"                                       = var.P2P_DROP_TX_CHANCE
    "validator.node.env.WS_NUM_HISTORIC_CHECKPOINTS"                              = var.WS_NUM_HISTORIC_CHECKPOINTS
    "validator.node.env.TX_COLLECTION_FILE_STORE_URLS"                            = var.TX_COLLECTION_FILE_STORE_URLS
    "validator.node.env.SEQ_SKIP_CHECKPOINT_PUBLISH_PERCENT"                      = var.SEQ_SKIP_CHECKPOINT_PUBLISH_PERCENT
    "validator.node.env.L1_TX_FAILED_STORE"                                       = var.L1_TX_FAILED_STORE
    "validator.node.adminApiKeyHash"                                              = var.ADMIN_API_KEY_HASH
  }

  # Note: nonsensitive() is required here because helm_releases is used in for_each,
  # and sensitive values cannot be used as for_each keys. The database URL will be
  # passed to pods as an env var, which is the intended behavior.
  validator_ha_settings = var.VALIDATOR_HA_REPLICAS > 0 ? {
    "validator.node.env.VALIDATOR_HA_SIGNING_ENABLED" = "true"
    "validator.node.env.VALIDATOR_HA_DATABASE_URL"    = nonsensitive(module.validator_ha_postgres[0].database_url)
    # Limit pool size per pod to avoid exhausting PostgreSQL connections
    # With 12 pods × 5 max = 60 connections (well under PostgreSQL's 500 max)
    "validator.node.env.VALIDATOR_HA_POOL_MAX"             = "5"
    "validator.node.env.VALIDATOR_HA_OLD_DUTIES_MAX_AGE_H" = tostring(var.VALIDATOR_HA_OLD_DUTIES_MAX_AGE_H)
  } : {}

  # Generate validator releases: primary (idx=0) plus N HA replicas (idx=1..N)
  validator_releases = tonumber(var.VALIDATOR_REPLICAS) > 0 ? {
    for idx in range(1 + var.VALIDATOR_HA_REPLICAS) :
    "validators${idx > 0 ? "-ha-${idx}" : ""}" => merge(local.validator_base_config, {
      name = "${var.RELEASE_PREFIX}-validator${idx > 0 ? "-ha-${idx}" : ""}"
      custom_settings = merge(
        local.validator_common_settings,
        local.validator_ha_settings,
        {
          "validator.replicaCount"                        = idx > 0 ? coalesce(var.VALIDATOR_HA_REPLICA_COUNT, var.VALIDATOR_REPLICAS) : var.VALIDATOR_REPLICAS
          "validator.node.env.VALIDATOR_HA_REPLICA_INDEX" = tostring(idx)
          "validator.node.env.PUBLISHER_KEY_INDEX_START"  = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX + (idx * (var.VALIDATOR_PUBLISHERS_PER_REPLICA * local.max_validator_nodes))
          "validator.service.p2p.announcePort"            = local.p2p_port_validators[idx]
          "validator.service.p2p.port"                    = local.p2p_port_validators[idx]
        },
        # Override image for HA releases (idx > 0) when VALIDATOR_HA_DOCKER_IMAGE is set
        idx > 0 && var.VALIDATOR_HA_DOCKER_IMAGE != "" ? {
          "global.aztecImage.repository" = local.validator_ha_image.repository
          "global.aztecImage.tag"        = local.validator_ha_image.tag
        } : {}
      )
    })
  } : {}

  p2p_bootstrap_release = {
    name  = "${var.RELEASE_PREFIX}-p2p-bootstrap"
    chart = "aztec-node"
    values = [
      "common.yaml",
      "p2p-bootstrap.yaml",
      "p2p-bootstrap-resources-${var.P2P_BOOTSTRAP_RESOURCE_PROFILE}.yaml"
    ]
    inline_values = [yamlencode({
      service = {
        p2p = { publicIP = var.P2P_PUBLIC_IP }
      }
    })]
    custom_settings = {
      "nodeType"                          = "p2p-bootstrap"
      "service.p2p.nodePortEnabled"       = var.P2P_NODEPORT_ENABLED
      "service.p2p.hostPortEnabled"       = var.P2P_HOSTPORT_ENABLED
      "service.p2p.announcePort"          = local.p2p_port_p2p_bootstrap
      "service.p2p.port"                  = local.p2p_port_p2p_bootstrap
      "node.env.P2P_MAX_PENDING_TX_COUNT" = var.P2P_MAX_PENDING_TX_COUNT
    }
    boot_node_host_path  = ""
    bootstrap_nodes_path = ""
    wait                 = true
  }

  # Define all non-bootstrap releases in a map. The p2p bootstrap release is
  # applied first so nodes cannot fetch an ENR from an old bootstrap pod.
  helm_releases = merge({
    snapshot = var.STORE_SNAPSHOT_URL != null ? {
      name   = "${var.RELEASE_PREFIX}-snapshot"
      chart  = "aztec-snapshots"
      values = []
      custom_settings = {
        "snapshots.aztecNodeAdminUrl" = local.internal_rpc_admin_url
        "snapshots.uploadLocation"    = var.STORE_SNAPSHOT_URL
        "snapshots.frequency"         = var.SNAPSHOT_CRON
        "nodeSelector.node-type"      = "network"
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = true
    } : null

    prover = var.PROVER_ENABLED ? {
      name  = "${var.RELEASE_PREFIX}-prover"
      chart = "aztec-prover-stack"
      values = [
        "common.yaml",
        "prover.yaml",
        "prover-resources-${var.PROVER_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = concat([yamlencode({
        node = {
          service = {
            p2p = { publicIP = var.P2P_PUBLIC_IP }
          }
          node = {
            logLevel = var.LOG_LEVEL
          }
        }
        broker = {
          node = {
            logLevel = var.LOG_LEVEL
          }
        }
        agent = {
          node = {
            logLevel = var.LOG_LEVEL
          }
          autoscaling = {
            keda = {
              enabled         = var.PROVER_AGENT_KEDA_ENABLED && var.PROVER_ENABLED
              pollingInterval = var.PROVER_AGENT_KEDA_POLLING_INTERVAL_SECONDS
              cooldownPeriod  = var.PROVER_AGENT_KEDA_COOLDOWN_PERIOD_SECONDS
              minReplicaCount = var.PROVER_AGENT_KEDA_MIN_REPLICAS
              maxReplicaCount = var.PROVER_AGENT_KEDA_MAX_REPLICAS
              scalingBands    = var.PROVER_AGENT_KEDA_SCALING_BANDS
              prometheus = {
                serverAddress = var.PROVER_AGENT_KEDA_PROMETHEUS_SERVER_ADDRESS
              }
            }
          }
        }
        })], local.is_kind ? [yamlencode({
        agent = {
          nodeSelector = null
          affinity     = null
          tolerations  = null
        }
      })] : [])
      custom_settings = merge(
        {
          "node.mnemonic"                                       = var.PROVER_MNEMONIC
          "node.mnemonicStartIndex"                             = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.node.proverRealProofs"                          = var.PROVER_REAL_PROOFS
          "node.node.env.PROVER_FAILED_PROOF_STORE"             = var.PROVER_FAILED_PROOF_STORE
          "node.node.env.PROVER_PROOF_STORE"                    = var.PROVER_PROOF_STORE
          "node.node.env.L1_TX_FAILED_STORE"                    = var.L1_TX_FAILED_STORE
          "node.node.env.DEBUG_FORCE_TX_PROOF_VERIFICATION"     = var.DEBUG_FORCE_TX_PROOF_VERIFICATION
          "node.node.env.KEY_INDEX_START"                       = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.node.env.PUBLISHER_KEY_INDEX_START"             = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.node.env.PUBLISHERS_PER_PROVER"                 = var.PROVER_PUBLISHERS_PER_PROVER
          "node.node.env.PROVER_NODE_DISABLE_PROOF_PUBLISH"     = var.PROVER_NODE_DISABLE_PROOF_PUBLISH
          "node.node.env.P2P_TX_POOL_DELETE_TXS_AFTER_REORG"    = var.P2P_TX_POOL_DELETE_TXS_AFTER_REORG
          "node.node.env.BLOB_ALLOW_EMPTY_SOURCES"              = var.BLOB_ALLOW_EMPTY_SOURCES
          "node.node.secret.envEnabled"                         = true
          "node.node.secret.mnemonic"                           = var.PROVER_MNEMONIC
          "node.node.secret.mnemonicIndex"                      = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "broker.node.proverRealProofs"                        = var.PROVER_REAL_PROOFS
          "broker.node.env.BOOTSTRAP_NODES"                     = "asdf"
          "broker.node.env.PROVER_BROKER_DEBUG_REPLAY_ENABLED"  = var.PROVER_BROKER_DEBUG_REPLAY_ENABLED
          "agent.node.image.repository"                         = local.prover_agent_image.repository
          "agent.node.image.tag"                                = local.prover_agent_image.tag
          "agent.node.env.CRS_PATH"                             = "/usr/src/crs"
          "agent.node.proverRealProofs"                         = var.PROVER_REAL_PROOFS
          "agent.node.env.PROVER_AGENT_POLL_INTERVAL_MS"        = var.PROVER_AGENT_POLL_INTERVAL_MS
          "agent.replicaCount"                                  = var.PROVER_AGENT_KEDA_ENABLED ? "0" : var.PROVER_REPLICAS
          "agent.node.env.BOOTSTRAP_NODES"                      = "asdf"
          "agent.node.env.PROVER_AGENT_COUNT"                   = var.PROVER_AGENTS_PER_PROVER
          "agent.node.env.PROVER_TEST_DELAY_TYPE"               = var.PROVER_TEST_DELAY_TYPE
          "agent.node.env.PROVER_AGENT_PROOF_TYPES"             = join(",", var.PROVER_AGENT_PROOF_TYPES)
          "agent.node.env.PROVER_PROOF_STORE"                   = var.PROVER_PROOF_STORE
          "agent.node.otelIncludeMetrics"                       = var.PROVER_AGENT_INCLUDE_METRICS
          "node.node.env.L1_PRIORITY_FEE_BUMP_PERCENTAGE"       = var.PROVER_L1_PRIORITY_FEE_BUMP_PERCENTAGE
          "node.node.env.L1_PRIORITY_FEE_RETRY_BUMP_PERCENTAGE" = var.PROVER_L1_PRIORITY_FEE_RETRY_BUMP_PERCENTAGE
          "node.node.env.PROVER_TEST_VERIFICATION_DELAY_MS"     = var.PROVER_TEST_VERIFICATION_DELAY_MS
          "node.node.env.BB_CHONK_VERIFY_MAX_BATCH"             = var.BB_CHONK_VERIFY_MAX_BATCH
          "node.node.env.BB_CHONK_VERIFY_BATCH_CONCURRENCY"     = var.BB_CHONK_VERIFY_BATCH_CONCURRENCY
          "node.node.env.DEBUG_P2P_INSTRUMENT_MESSAGES"         = var.DEBUG_P2P_INSTRUMENT_MESSAGES
          "node.node.env.P2P_GOSSIPSUB_D"                       = var.P2P_GOSSIPSUB_D
          "node.node.env.P2P_GOSSIPSUB_DLO"                     = var.P2P_GOSSIPSUB_DLO
          "node.node.env.P2P_GOSSIPSUB_DHI"                     = var.P2P_GOSSIPSUB_DHI
          "node.node.env.P2P_DROP_TX_CHANCE"                    = var.P2P_DROP_TX_CHANCE
          "node.node.env.P2P_MAX_PENDING_TX_COUNT"              = var.P2P_MAX_PENDING_TX_COUNT
          "node.node.env.WS_NUM_HISTORIC_CHECKPOINTS"           = var.WS_NUM_HISTORIC_CHECKPOINTS
          "node.node.env.TX_COLLECTION_FILE_STORE_URLS"         = var.TX_COLLECTION_FILE_STORE_URLS
          "node.service.p2p.nodePortEnabled"                    = var.P2P_NODEPORT_ENABLED
          "node.service.p2p.hostPortEnabled"                    = var.P2P_HOSTPORT_ENABLED
          "node.service.p2p.announcePort"                       = local.p2p_port_prover
          "node.service.p2p.port"                               = local.p2p_port_prover
        },
        # Only set web3signerUrl if proof publishing is enabled
        !var.PROVER_NODE_DISABLE_PROOF_PUBLISH ? {
          "node.node.web3signerUrl" = "http://${var.RELEASE_PREFIX}-signer-web3signer.${var.NAMESPACE}.svc.cluster.local:9000/"
        } : {}
      )
      boot_node_host_path  = "node.node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.node.env.BOOTSTRAP_NODES"
      wait                 = var.WAIT_FOR_PROVER_DEPLOY
    } : null

    rpc = {
      name  = "${var.RELEASE_PREFIX}-rpc"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "rpc.yaml",
        "rpc-resources-${var.RPC_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
          rpc = {
            enabled = true
            type    = local.is_kind ? "ClusterIP" : "LoadBalancer"
          }
        }
      })]

      custom_settings = merge({
        "replicaCount"                = var.RPC_REPLICAS
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        "service.p2p.hostPortEnabled" = var.P2P_HOSTPORT_ENABLED
        "service.p2p.announcePort"    = local.p2p_port_rpc
        "service.p2p.port"            = local.p2p_port_rpc

        # Ensure the JSON-RPC server binds the same port the probe checks
        "node.proverRealProofs"                       = var.PROVER_REAL_PROOFS
        "node.env.AWS_ACCESS_KEY_ID"                  = var.R2_ACCESS_KEY_ID
        "node.env.AWS_SECRET_ACCESS_KEY"              = var.R2_SECRET_ACCESS_KEY
        "node.env.P2P_TX_POOL_DELETE_TXS_AFTER_REORG" = var.P2P_TX_POOL_DELETE_TXS_AFTER_REORG
        "node.env.DEBUG_FORCE_TX_PROOF_VERIFICATION"  = var.DEBUG_FORCE_TX_PROOF_VERIFICATION
        "node.env.BLOB_ALLOW_EMPTY_SOURCES"           = var.BLOB_ALLOW_EMPTY_SOURCES
        "node.env.PROVER_TEST_VERIFICATION_DELAY_MS"  = var.PROVER_TEST_VERIFICATION_DELAY_MS
        "node.env.BB_CHONK_VERIFY_MAX_BATCH"          = var.BB_CHONK_VERIFY_MAX_BATCH
        "node.env.BB_CHONK_VERIFY_BATCH_CONCURRENCY"  = var.BB_CHONK_VERIFY_BATCH_CONCURRENCY
        "node.env.DEBUG_P2P_INSTRUMENT_MESSAGES"      = var.DEBUG_P2P_INSTRUMENT_MESSAGES
        "node.env.P2P_GOSSIPSUB_D"                    = var.P2P_GOSSIPSUB_D
        "node.env.P2P_GOSSIPSUB_DLO"                  = var.P2P_GOSSIPSUB_DLO
        "node.env.P2P_GOSSIPSUB_DHI"                  = var.P2P_GOSSIPSUB_DHI
        "node.env.P2P_DROP_TX_CHANCE"                 = var.P2P_DROP_TX_CHANCE
        "node.env.P2P_MAX_PENDING_TX_COUNT"           = var.P2P_MAX_PENDING_TX_COUNT
        "node.env.WS_NUM_HISTORIC_CHECKPOINTS"        = var.WS_NUM_HISTORIC_CHECKPOINTS
        "node.env.BLOB_FILE_STORE_UPLOAD_URL"         = var.BLOB_FILE_STORE_UPLOAD_URL
        "node.env.TX_FILE_STORE_ENABLED"              = var.TX_FILE_STORE_ENABLED
        "node.env.TX_FILE_STORE_URL"                  = var.TX_FILE_STORE_URL
        "node.env.TX_COLLECTION_FILE_STORE_URLS"      = var.TX_COLLECTION_FILE_STORE_URLS
      })
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    }

    fisherman = tonumber(var.FISHERMAN_REPLICAS) > 0 ? {
      name  = "${var.RELEASE_PREFIX}-fisherman"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "rpc.yaml",
        "rpc-resources-${var.RPC_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
        node = {
          logLevel = var.FISHERMAN_LOG_LEVEL
        }
      })]
      custom_settings = {
        "replicaCount"                                = var.FISHERMAN_REPLICAS
        "service.p2p.nodePortEnabled"                 = var.P2P_NODEPORT_ENABLED
        "service.p2p.hostPortEnabled"                 = var.P2P_HOSTPORT_ENABLED
        "service.p2p.announcePort"                    = local.p2p_port_fisherman
        "service.p2p.port"                            = local.p2p_port_fisherman
        "node.proverRealProofs"                       = var.PROVER_REAL_PROOFS
        "node.env.BLOB_ALLOW_EMPTY_SOURCES"           = var.BLOB_ALLOW_EMPTY_SOURCES
        "node.env.WS_NUM_HISTORIC_CHECKPOINTS"        = var.WS_NUM_HISTORIC_CHECKPOINTS
        "node.env.P2P_MAX_PENDING_TX_COUNT"           = var.P2P_MAX_PENDING_TX_COUNT
        "node.env.P2P_TX_POOL_DELETE_TXS_AFTER_REORG" = var.P2P_TX_POOL_DELETE_TXS_AFTER_REORG
        "node.secret.envEnabled"                      = true
        "node.env.FISHERMAN_MODE"                     = "true"
        "node.env.SEQ_BUILD_CHECKPOINT_IF_EMPTY"      = "true"
        "node.secret.mnemonic"                        = var.FISHERMAN_MNEMONIC
        "node.secret.mnemonicIndex"                   = var.FISHERMAN_MNEMONIC_START_INDEX
        "node.env.KEY_INDEX_START"                    = var.FISHERMAN_MNEMONIC_START_INDEX
        "node.env.VALIDATORS_PER_NODE"                = "1"
        "node.preStartScript"                         = "source /scripts/get-private-key.sh"
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    } : null

    full_node = tonumber(var.FULL_NODE_REPLICAS) > 0 ? {
      name  = "${var.RELEASE_PREFIX}-full-node"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "full-node.yaml",
        "full-node-resources-${var.FULL_NODE_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
      })]
      custom_settings = {
        "nodeType"                                    = "full-node"
        "replicaCount"                                = var.FULL_NODE_REPLICAS
        "service.p2p.nodePortEnabled"                 = var.P2P_NODEPORT_ENABLED
        "service.p2p.hostPortEnabled"                 = var.P2P_HOSTPORT_ENABLED
        "service.p2p.announcePort"                    = local.p2p_port_full_node
        "service.p2p.port"                            = local.p2p_port_full_node
        "node.proverRealProofs"                       = var.PROVER_REAL_PROOFS
        "node.env.AWS_ACCESS_KEY_ID"                  = var.R2_ACCESS_KEY_ID
        "node.env.DEBUG_FORCE_TX_PROOF_VERIFICATION"  = var.DEBUG_FORCE_TX_PROOF_VERIFICATION
        "node.env.AWS_SECRET_ACCESS_KEY"              = var.R2_SECRET_ACCESS_KEY
        "node.env.P2P_TX_POOL_DELETE_TXS_AFTER_REORG" = var.P2P_TX_POOL_DELETE_TXS_AFTER_REORG
        "node.env.BLOB_ALLOW_EMPTY_SOURCES"           = var.BLOB_ALLOW_EMPTY_SOURCES
        "node.env.PROVER_TEST_VERIFICATION_DELAY_MS"  = var.PROVER_TEST_VERIFICATION_DELAY_MS
        "node.env.BB_CHONK_VERIFY_MAX_BATCH"          = var.BB_CHONK_VERIFY_MAX_BATCH
        "node.env.BB_CHONK_VERIFY_BATCH_CONCURRENCY"  = var.BB_CHONK_VERIFY_BATCH_CONCURRENCY
        "node.env.DEBUG_P2P_INSTRUMENT_MESSAGES"      = var.DEBUG_P2P_INSTRUMENT_MESSAGES
        "node.otelIncludeMetrics"                     = var.FULL_NODE_INCLUDE_METRICS
        "node.env.P2P_GOSSIPSUB_D"                    = var.P2P_GOSSIPSUB_D
        "node.env.P2P_GOSSIPSUB_DLO"                  = var.P2P_GOSSIPSUB_DLO
        "node.env.P2P_GOSSIPSUB_DHI"                  = var.P2P_GOSSIPSUB_DHI
        "node.env.P2P_DROP_TX_CHANCE"                 = var.P2P_DROP_TX_CHANCE
        "node.env.P2P_MAX_PENDING_TX_COUNT"           = var.P2P_MAX_PENDING_TX_COUNT
        "node.env.WS_NUM_HISTORIC_CHECKPOINTS"        = var.WS_NUM_HISTORIC_CHECKPOINTS
        "node.env.TX_COLLECTION_FILE_STORE_URLS"      = var.TX_COLLECTION_FILE_STORE_URLS
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      // this Helm app will have lots of replicas, if we wait for all to come online we'll surely time out.
      wait = false
    } : null

    # Optional: transfer bots
    bot_transfers = var.BOT_TRANSFERS_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-transfers"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-token-transfer.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_TRANSFERS_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_TRANSFERS_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_TRANSFERS_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_TRANSFERS_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_TRANSFERS_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_TRANSFERS_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null

    # Optional: AMM swap bots
    bot_swaps = var.BOT_SWAPS_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-swaps"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-amm-swaps.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_SWAPS_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_SWAPS_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_SWAPS_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_SWAPS_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_SWAPS_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_SWAPS_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null

    # Optional: cross-chain message bots
    bot_cross_chain = var.BOT_CROSS_CHAIN_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-cross-chain"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-cross-chain.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_CROSS_CHAIN_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_CROSS_CHAIN_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_CROSS_CHAIN_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_CROSS_CHAIN_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_CROSS_CHAIN_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_CROSS_CHAIN_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null
  }, local.validator_releases)
}

# The p2p bootstrap release used to be an entry in the helm_releases map (applied
# via helm_release.releases["p2p_bootstrap"]). It is now its own resource so it can
# be applied before the other releases. Tell Terraform it is the same release to
# avoid destroying and recreating the running bootstrap node.
moved {
  from = helm_release.releases["p2p_bootstrap"]
  to   = helm_release.p2p_bootstrap[0]
}

resource "helm_release" "p2p_bootstrap" {
  count = var.DEPLOY_INTERNAL_BOOTNODE ? 1 : 0

  provider         = helm.gke-cluster
  name             = local.p2p_bootstrap_release.name
  repository       = "../../"
  chart            = local.p2p_bootstrap_release.chart
  namespace        = var.NAMESPACE
  create_namespace = true
  upgrade_install  = true
  reuse_values     = false
  timeout          = lookup(local.p2p_bootstrap_release, "timeout", 600)
  wait             = local.p2p_bootstrap_release.wait
  wait_for_jobs    = true

  values = concat(
    [for v in local.p2p_bootstrap_release.values : file("./values/${v}")],
    [local.common_inline_values],
    lookup(local.p2p_bootstrap_release, "inline_values", [])
  )

  dynamic "set" {
    for_each = { for k, v in merge(
      local.common_settings,
      local.p2p_bootstrap_release.custom_settings
    ) : k => v if v != null }
    content {
      name  = set.key
      value = set.value
    }
  }

  dynamic "set_list" {
    for_each = { for k, v in local.common_list_settings : k => v if v != null }
    content {
      name  = set_list.key
      value = set_list.value
    }
  }
}

# Create all helm releases using for_each
resource "helm_release" "releases" {
  for_each = { for k, v in local.helm_releases : k => v if v != null }

  provider         = helm.gke-cluster
  name             = each.value.name
  repository       = "../../"
  chart            = each.value.chart
  namespace        = var.NAMESPACE
  create_namespace = true
  upgrade_install  = true
  reuse_values     = false
  timeout          = lookup(each.value, "timeout", 600)
  wait             = each.value.wait
  wait_for_jobs    = true
  # Safe for networks without an internal bootnode: helm_release.p2p_bootstrap has count 0.
  depends_on = [helm_release.p2p_bootstrap]

  values = concat(
    [for v in each.value.values : file("./values/${v}")],
    [local.common_inline_values],
    lookup(each.value, "inline_values", [])
  )

  # Common settings
  dynamic "set" {
    for_each = { for k, v in merge(
      local.common_settings,
      each.value.custom_settings,
      # Add boot node if needed
      each.value.boot_node_host_path != "" && local.internal_boot_node_url != "" ? {
        (each.value.boot_node_host_path) = local.internal_boot_node_url
      } : {},
      each.value.bootstrap_nodes_path != "" && length(var.EXTERNAL_BOOTNODES) > 0 ? {
        (each.value.bootstrap_nodes_path) = join(",", var.EXTERNAL_BOOTNODES)
      } : {}
    ) : k => v if v != null }
    content {
      name  = set.key
      value = set.value
    }
  }

  # Common list settings
  dynamic "set_list" {
    for_each = { for k, v in local.common_list_settings : k => v if v != null }
    content {
      name  = set_list.key
      value = set_list.value
    }
  }
}

module "rpc_gateway" {
  count = local.kong_gateway_enabled ? 1 : 0

  source = "../modules/rpc-gateway"

  providers = {
    helm       = helm.gke-cluster
    kubernetes = kubernetes.gke-cluster
    google     = google
  }

  RELEASE_PREFIX     = var.RELEASE_PREFIX
  CONSUMER_NAMESPACE = var.NAMESPACE

  KONG_NAMESPACE                 = var.RPC_GATEWAY_KONG_NAMESPACE != "" ? var.RPC_GATEWAY_KONG_NAMESPACE : var.NAMESPACE
  KONG_HELM_RELEASE_NAME         = var.RPC_GATEWAY_KONG_HELM_RELEASE_NAME
  KONG_HELM_CHART_VERSION        = var.RPC_GATEWAY_KONG_HELM_CHART_VERSION
  KONG_INGRESS_CLASS             = var.RPC_GATEWAY_KONG_INGRESS_CLASS
  KONG_PROXY_SERVICE_TYPE        = var.RPC_GATEWAY_KONG_PROXY_SERVICE_TYPE
  KONG_PROXY_SERVICE_ANNOTATIONS = var.RPC_GATEWAY_KONG_PROXY_SERVICE_ANNOTATIONS
  KONG_EXTRA_HELM_VALUES         = var.RPC_GATEWAY_KONG_EXTRA_HELM_VALUES
  KONG_SERVICE_MONITOR_ENABLED   = var.RPC_GATEWAY_KONG_SERVICE_MONITOR_ENABLED
  KONG_METRICS_SERVICE_ENABLED   = var.RPC_GATEWAY_KONG_OTEL_METRICS_GCP_SECRET_NAME != ""

  API_KEY_HEADER_NAME              = var.RPC_GATEWAY_API_KEY_HEADER_NAME
  ROUTES                           = local.rpc_gateway_routes
  CONSUMERS                        = local.rpc_gateway_consumers
  EXTERNAL_SECRET_STORE_NAME       = var.RPC_GATEWAY_EXTERNAL_SECRET_STORE_NAME
  EXTERNAL_SECRET_STORE_KIND       = var.RPC_GATEWAY_EXTERNAL_SECRET_STORE_KIND
  EXTERNAL_SECRET_REFRESH_INTERVAL = var.RPC_GATEWAY_EXTERNAL_SECRET_REFRESH_INTERVAL

  CREATE_DNS                      = var.RPC_GATEWAY_CREATE_DNS
  DNS_ZONE_NAME                   = var.RPC_GATEWAY_DNS_ZONE_NAME
  DNS_TTL                         = var.RPC_GATEWAY_DNS_TTL
  FRONTEND_ENABLED                = var.RPC_GATEWAY_FRONTEND_ENABLED
  FRONTEND_STATIC_IP_ENABLED      = var.RPC_GATEWAY_FRONTEND_STATIC_IP_ENABLED
  FRONTEND_STATIC_IP_NAME         = var.RPC_GATEWAY_FRONTEND_STATIC_IP_NAME
  FRONTEND_ALLOW_HTTP             = var.RPC_GATEWAY_FRONTEND_ALLOW_HTTP
  GCP_MANAGED_CERTIFICATE_ENABLED = var.RPC_GATEWAY_GCP_MANAGED_CERTIFICATE_ENABLED

  depends_on = [helm_release.releases]
}

module "rpc_gateway_metrics_collector" {
  count = local.kong_gateway_enabled && var.RPC_GATEWAY_KONG_OTEL_METRICS_GCP_SECRET_NAME != "" ? 1 : 0

  source = "../modules/otel-metrics-collector"

  providers = {
    helm = helm.gke-cluster
  }

  NAMESPACE                               = module.rpc_gateway[0].metrics_service_namespace
  RELEASE_NAME                            = "${var.RELEASE_PREFIX}-rpc-kong-otel-collector"
  OTEL_COLLECTOR_ENDPOINT_GCP_SECRET_NAME = var.RPC_GATEWAY_KONG_OTEL_METRICS_GCP_SECRET_NAME
  SCRAPE_CONFIGS = [
    {
      job_name        = "kong"
      scrape_interval = "15s"
      metrics_path    = "/metrics"
      targets         = ["${module.rpc_gateway[0].metrics_service_name}.${module.rpc_gateway[0].metrics_service_namespace}.svc.cluster.local:${module.rpc_gateway[0].metrics_service_port}"]
      labels = {
        component = "kong"
        network   = var.RELEASE_PREFIX
      }
    }
  ]
  RESOURCE_ATTRIBUTES = {
    "service.name"    = "${var.RELEASE_PREFIX}-rpc-kong"
    "network"         = var.RELEASE_PREFIX
    "aztec.component" = "kong"
  }
  EXTERNAL_SECRET_STORE_NAME       = var.RPC_GATEWAY_EXTERNAL_SECRET_STORE_NAME
  EXTERNAL_SECRET_STORE_KIND       = var.RPC_GATEWAY_EXTERNAL_SECRET_STORE_KIND
  EXTERNAL_SECRET_REFRESH_INTERVAL = var.RPC_GATEWAY_EXTERNAL_SECRET_REFRESH_INTERVAL

  depends_on = [module.rpc_gateway]
}
