# Module for deploying Aztec (Layer 2) infrastructure
# Should be configurable/agnostic to
# - network it is deployed to
# - the k8s cluster it is deployed to
# - metrics in use
# - ingress type
# - resource profile


terraform {
  backend "local" {}
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.16.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.38.0"
    }
  }
}

provider "kubernetes" {
  alias          = "gke-cluster"
  config_path    = "~/.kube/config"
  config_context = var.K8S_CLUSTER_CONTEXT
}

provider "helm" {
  alias = "gke-cluster"
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = var.K8S_CLUSTER_CONTEXT
  }
}

module "web3signer" {
  # Only deploy web3signer if we have validators or provers that need to publish to L1
  count = tonumber(var.VALIDATOR_REPLICAS) > 0 ? 1 : 0

  source                                   = "../modules/web3signer"
  NAMESPACE                                = var.NAMESPACE
  RELEASE_NAME                             = var.RELEASE_PREFIX
  AZTEC_DOCKER_IMAGE                       = var.AZTEC_DOCKER_IMAGE
  CHAIN_ID                                 = var.L1_CHAIN_ID
  MNEMONIC                                 = var.VALIDATOR_MNEMONIC
  ADDRESS_CONFIGMAP_NAME                   = "${var.RELEASE_PREFIX}-attester-addresses"
  ATTESTERS_PER_NODE                       = tonumber(var.VALIDATORS_PER_NODE)
  NODE_COUNT                               = local.max_validator_nodes
  VALIDATOR_HA_REPLICAS                    = tonumber(var.VALIDATOR_HA_REPLICAS)
  VALIDATOR_MNEMONIC_START_INDEX           = tonumber(var.VALIDATOR_MNEMONIC_START_INDEX)
  VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX = tonumber(var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX)
  VALIDATOR_PUBLISHERS_PER_REPLICA         = var.VALIDATOR_PUBLISHERS_PER_REPLICA
  PROVER_COUNT                             = tonumber(var.PROVER_REPLICAS)
  PUBLISHERS_PER_PROVER                    = tonumber(var.PROVER_PUBLISHERS_PER_PROVER)
  PROVER_PUBLISHER_MNEMONIC_START_INDEX    = tonumber(var.PROVER_PUBLISHER_MNEMONIC_START_INDEX)

  providers = {
    helm       = helm.gke-cluster
    kubernetes = kubernetes.gke-cluster
  }
}

module "validator_ha_postgres" {
  # Only deploy HA postgres if we have validators and HA replicas > 0
  count = tonumber(var.VALIDATOR_REPLICAS) > 0 && var.VALIDATOR_HA_REPLICAS > 0 ? 1 : 0

  source             = "../modules/validator-ha-postgres"
  NAMESPACE          = var.NAMESPACE
  RELEASE_NAME       = var.RELEASE_PREFIX
  AZTEC_DOCKER_IMAGE = var.AZTEC_DOCKER_IMAGE
  # DB_PASSWORD auto-generated by module

  providers = {
    helm       = helm.gke-cluster
    kubernetes = kubernetes.gke-cluster
  }
}

locals {
  aztec_image = {
    repository = split(":", var.AZTEC_DOCKER_IMAGE)[0]
    tag        = split(":", var.AZTEC_DOCKER_IMAGE)[1]
  }

  prover_agent_image = var.PROVER_AGENT_DOCKER_IMAGE != "" ? {
    repository = split(":", var.PROVER_AGENT_DOCKER_IMAGE)[0]
    tag        = split(":", var.PROVER_AGENT_DOCKER_IMAGE)[1]
  } : local.aztec_image

  validator_ha_image = var.VALIDATOR_HA_DOCKER_IMAGE != "" ? {
    repository = split(":", var.VALIDATOR_HA_DOCKER_IMAGE)[0]
    tag        = split(":", var.VALIDATOR_HA_DOCKER_IMAGE)[1]
  } : local.aztec_image

  # Max node count: max of primary (VALIDATOR_REPLICAS) and HA pod counts
  # Determines how many attester keystores and publisher key ranges to generate
  effective_ha_count  = var.VALIDATOR_HA_REPLICAS > 0 ? coalesce(var.VALIDATOR_HA_REPLICA_COUNT, tonumber(var.VALIDATOR_REPLICAS)) : 0
  max_validator_nodes = max(tonumber(var.VALIDATOR_REPLICAS), local.effective_ha_count)

  # Detect local kind context (e.g., "kind-kind") to gate Service types
  is_kind = can(regex("^kind", var.K8S_CLUSTER_CONTEXT))

  internal_boot_node_url = var.DEPLOY_INTERNAL_BOOTNODE ? "http://${var.RELEASE_PREFIX}-p2p-bootstrap-node.${var.NAMESPACE}.svc.cluster.local:8080" : ""

  internal_rpc_url       = "http://${var.RELEASE_PREFIX}-rpc-aztec-node.${var.NAMESPACE}.svc.cluster.local:8080"
  internal_rpc_admin_url = "http://${var.RELEASE_PREFIX}-rpc-aztec-node-admin.${var.NAMESPACE}.svc.cluster.local:8880"

  # Pod image is the only thing the chart actually reads from `global` now.
  # Everything else flows under `env:` (mounted via envFrom configmap).
  common_settings = {
    "global.aztecImage.repository" = local.aztec_image.repository
    "global.aztecImage.tag"        = local.aztec_image.tag
    "global.aztecImage.pullPolicy" = local.is_kind ? "IfNotPresent" : "Always"
  }

  # Deploy-time-computed env vars (joined lists, computed paths, secrets,
  # values that come from the L1 deploy step). Per-network YAML values for the
  # same keys take precedence -- this is just the deploy-time fallback.
  common_inline_values = yamlencode({
    env = merge(
      {
        USE_GCLOUD_LOGGING                 = "true"
        L1_CHAIN_ID                        = var.L1_CHAIN_ID
        REGISTRY_CONTRACT_ADDRESS          = var.REGISTRY_CONTRACT_ADDRESS
        FEE_ASSET_HANDLER_CONTRACT_ADDRESS = var.FEE_ASSET_HANDLER_CONTRACT_ADDRESS
        SPONSORED_FPC                      = tostring(var.SPONSORED_FPC)
        TEST_ACCOUNTS                      = tostring(var.TEST_ACCOUNTS)
        LOG_JSON                           = "1"
      },
      var.NETWORK != "" ? { NETWORK = var.NETWORK } : {},
      length(var.L1_RPC_URLS) > 0 ? { ETHEREUM_HOSTS = join(",", var.L1_RPC_URLS) } : {},
      length(var.L1_CONSENSUS_HOST_URLS) > 0 ? {
        L1_CONSENSUS_HOST_URLS = join(",", var.L1_CONSENSUS_HOST_URLS)
      } : {},
      length(var.L1_CONSENSUS_HOST_API_KEYS) > 0 ? {
        L1_CONSENSUS_HOST_API_KEYS = join(",", var.L1_CONSENSUS_HOST_API_KEYS)
      } : {},
      length(var.L1_CONSENSUS_HOST_API_KEY_HEADERS) > 0 ? {
        L1_CONSENSUS_HOST_API_KEY_HEADERS = join(",", var.L1_CONSENSUS_HOST_API_KEY_HEADERS)
      } : {},
      var.OTEL_COLLECTOR_ENDPOINT != "" ? {
        OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = "${var.OTEL_COLLECTOR_ENDPOINT}/v1/metrics"
        OTEL_EXPORTER_OTLP_TRACES_ENDPOINT  = "${var.OTEL_COLLECTOR_ENDPOINT}/v1/traces"
        OTEL_EXPORTER_OTLP_LOGS_ENDPOINT    = "${var.OTEL_COLLECTOR_ENDPOINT}/v1/logs"
      } : {}
    )
  })

  common_list_settings = {}

  # Generate a set of _external_ host ports to use for P2P
  # K8s will use these values to schedule pods on appropriate machines. Using random ports here will allow it to
  # colocate pods from different services or even pods from different networks onto the same physical machine
  # (so long as the VM has enough resources)
  p2p_port_p2p_bootstrap = 40400 + (parseint(substr(md5("${var.NAMESPACE}-p2p-bootstrap"), 0, 4), 16) % 100)
  p2p_port_prover        = 40400 + (parseint(substr(md5("${var.NAMESPACE}-prover"), 0, 4), 16) % 100)
  p2p_port_rpc           = 40400 + (parseint(substr(md5("${var.NAMESPACE}-rpc"), 0, 4), 16) % 100)
  p2p_port_fisherman     = 40400 + (parseint(substr(md5("${var.NAMESPACE}-fisherman"), 0, 4), 16) % 100)
  p2p_port_full_node     = 40400 + (parseint(substr(md5("${var.NAMESPACE}-full-node"), 0, 4), 16) % 100)
  p2p_port_archive       = 40400 + (parseint(substr(md5("${var.NAMESPACE}-archive"), 0, 4), 16) % 100)

  p2p_port_validators = {
    for idx in range(1 + var.VALIDATOR_HA_REPLICAS) : idx => 40400 + (parseint(substr(md5("${var.NAMESPACE}-validator-${idx}"), 0, 4), 16) % 100)
  }

  # Validator configuration - extracted for dynamic HA release generation
  validator_base_config = {
    chart   = "aztec-validator"
    timeout = 1800
    values = [
      "common.yaml",
      "validator.yaml",
      "validator-resources-${var.VALIDATOR_RESOURCE_PROFILE}.yaml"
    ]
    inline_values = [yamlencode({
      validator = {
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
        node = {
          logLevel = var.LOG_LEVEL
        }
        # spread validator pods to different nodes to avoid having two validators with the same attester keys on the same physical node
        topologySpreadConstraints = [{
          maxSkew           = 1
          topologyKey       = "kubernetes.io/hostname"
          whenUnsatisfiable = "ScheduleAnyway" # soft constraint
          labelSelector = {
            matchLabels = {
              "app.kubernetes.io/component" = "sequencer-node"
            }
          }
          matchLabelKeys = ["apps.kubernetes.io/pod-index"]
        }]
      }
    })]
    boot_node_host_path  = "validator.node.env.BOOT_NODE_HOST"
    bootstrap_nodes_path = "validator.node.env.BOOTSTRAP_NODES"
    wait                 = true
  }

  # Per-pod env vars now flow from spartan/environments/networks/<name>.yml via
  # the loader's pre-merged var.releases.validators.env block (passed through
  # main.tf's `inline_values = [yamlencode(var.releases[each.key])]`). Only
  # values that are computed at deploy time, set k8s manifest shape, or rename
  # one chart key into a different pod env name remain here.
  validator_common_settings = {
    # K8s shape / cluster decisions (not pod env).
    "validator.service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
    "validator.web3signerUrl"               = "http://${var.RELEASE_PREFIX}-signer-web3signer.${var.NAMESPACE}.svc.cluster.local:9000/"
    "validator.mnemonic"                    = var.VALIDATOR_MNEMONIC
    "validator.mnemonicStartIndex"          = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.validatorsPerNode"           = var.VALIDATORS_PER_NODE
    "validator.publishersPerReplica"        = var.VALIDATOR_PUBLISHERS_PER_REPLICA
    "validator.publisherMnemonicStartIndex" = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX
    "validator.node.secret.envEnabled"      = true
    "validator.node.secret.mnemonic"        = var.VALIDATOR_MNEMONIC
    "validator.node.secret.mnemonicIndex"   = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.node.adminApiKeyHash"        = var.ADMIN_API_KEY_HASH
    # Renames: chart-side var name differs from pod env name.
    "validator.node.env.KEY_INDEX_START"           = var.VALIDATOR_MNEMONIC_START_INDEX
    "validator.node.env.PUBLISHER_KEY_INDEX_START" = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX
  }

  # Note: nonsensitive() is required here because helm_releases is used in for_each,
  # and sensitive values cannot be used as for_each keys. The database URL will be
  # passed to pods as an env var, which is the intended behavior.
  validator_ha_settings = var.VALIDATOR_HA_REPLICAS > 0 ? {
    "validator.node.env.VALIDATOR_HA_SIGNING_ENABLED" = "true"
    "validator.node.env.VALIDATOR_HA_DATABASE_URL"    = nonsensitive(module.validator_ha_postgres[0].database_url)
    # Limit pool size per pod to avoid exhausting PostgreSQL connections
    # With 12 pods × 5 max = 60 connections (well under PostgreSQL's 500 max)
    "validator.node.env.VALIDATOR_HA_POOL_MAX"             = "5"
    "validator.node.env.VALIDATOR_HA_OLD_DUTIES_MAX_AGE_H" = tostring(var.VALIDATOR_HA_OLD_DUTIES_MAX_AGE_H)
  } : {}

  # Generate validator releases: primary (idx=0) plus N HA replicas (idx=1..N)
  validator_releases = tonumber(var.VALIDATOR_REPLICAS) > 0 ? {
    for idx in range(1 + var.VALIDATOR_HA_REPLICAS) :
    "validators${idx > 0 ? "-ha-${idx}" : ""}" => merge(local.validator_base_config, {
      name = "${var.RELEASE_PREFIX}-validator${idx > 0 ? "-ha-${idx}" : ""}"
      custom_settings = merge(
        local.validator_common_settings,
        local.validator_ha_settings,
        {
          "validator.replicaCount"                        = idx > 0 ? coalesce(var.VALIDATOR_HA_REPLICA_COUNT, var.VALIDATOR_REPLICAS) : var.VALIDATOR_REPLICAS
          "validator.node.env.VALIDATOR_HA_REPLICA_INDEX" = tostring(idx)
          "validator.node.env.PUBLISHER_KEY_INDEX_START"  = var.VALIDATOR_PUBLISHER_MNEMONIC_START_INDEX + (idx * (var.VALIDATOR_PUBLISHERS_PER_REPLICA * local.max_validator_nodes))
          "validator.service.p2p.announcePort"            = local.p2p_port_validators[idx]
          "validator.service.p2p.port"                    = local.p2p_port_validators[idx]
        },
        # Override image for HA releases (idx > 0) when VALIDATOR_HA_DOCKER_IMAGE is set
        idx > 0 && var.VALIDATOR_HA_DOCKER_IMAGE != "" ? {
          "global.aztecImage.repository" = local.validator_ha_image.repository
          "global.aztecImage.tag"        = local.validator_ha_image.tag
        } : {}
      )
    })
  } : {}

  # Define all releases in a map
  helm_releases = merge({
    snapshot = var.STORE_SNAPSHOT_URL != null ? {
      name   = "${var.RELEASE_PREFIX}-snapshot"
      chart  = "aztec-snapshots"
      values = []
      custom_settings = {
        "snapshots.aztecNodeAdminUrl" = local.internal_rpc_admin_url
        "snapshots.uploadLocation"    = var.STORE_SNAPSHOT_URL
        "snapshots.frequency"         = var.SNAPSHOT_CRON
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = true
    } : null

    p2p_bootstrap = var.DEPLOY_INTERNAL_BOOTNODE ? {
      name  = "${var.RELEASE_PREFIX}-p2p-bootstrap"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "p2p-bootstrap.yaml",
        "p2p-bootstrap-resources-${var.P2P_BOOTSTRAP_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
      })]
      custom_settings = {
        "nodeType"                          = "p2p-bootstrap"
        "service.p2p.nodePortEnabled"       = var.P2P_NODEPORT_ENABLED
        "service.p2p.announcePort"          = local.p2p_port_p2p_bootstrap
        "service.p2p.port"                  = local.p2p_port_p2p_bootstrap
        "node.env.P2P_MAX_PENDING_TX_COUNT" = var.P2P_MAX_PENDING_TX_COUNT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = true
    } : null

    prover = {
      name  = "${var.RELEASE_PREFIX}-prover"
      chart = "aztec-prover-stack"
      values = [
        "common.yaml",
        "prover.yaml",
        "prover-resources-${var.PROVER_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = concat([yamlencode({
        node = {
          service = {
            p2p = { publicIP = var.P2P_PUBLIC_IP }
          }
          node = {
            logLevel = var.LOG_LEVEL
          }
        }
        broker = {
          node = {
            logLevel = var.LOG_LEVEL
          }
        }
        agent = {
          node = {
            logLevel = var.LOG_LEVEL
          }
        }
        })], local.is_kind ? [yamlencode({
        agent = {
          nodeSelector = null
          affinity     = null
          tolerations  = null
        }
      })] : [])
      # Per-pod env vars flow from spartan/environments/networks/<name>.yml via
      # the loader's pre-merged var.releases.prover.{node,broker,agent}.env blocks.
      # Only computed/renamed/secret values remain here.
      custom_settings = merge(
        {
          # Chart-shape / k8s shape.
          "node.mnemonic"                    = var.PROVER_MNEMONIC
          "node.mnemonicStartIndex"          = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.node.secret.envEnabled"      = true
          "node.node.secret.mnemonic"        = var.PROVER_MNEMONIC
          "node.node.secret.mnemonicIndex"   = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
          "node.service.p2p.announcePort"    = local.p2p_port_prover
          "node.service.p2p.port"            = local.p2p_port_prover
          "agent.replicaCount"               = var.PROVER_REPLICAS
          "agent.node.image.repository"      = local.prover_agent_image.repository
          "agent.node.image.tag"             = local.prover_agent_image.tag
          "agent.env.OTEL_INCLUDE_METRICS"   = var.PROVER_AGENT_INCLUDE_METRICS
          # Renames: chart-side var name differs from pod env name.
          "node.node.env.KEY_INDEX_START"           = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
          "node.node.env.PUBLISHER_KEY_INDEX_START" = var.PROVER_PUBLISHER_MNEMONIC_START_INDEX
        },
        # Only set web3signerUrl if proof publishing is enabled
        !var.PROVER_NODE_DISABLE_PROOF_PUBLISH ? {
          "node.node.web3signerUrl" = "http://${var.RELEASE_PREFIX}-signer-web3signer.${var.NAMESPACE}.svc.cluster.local:9000/"
        } : {}
      )
      boot_node_host_path  = "node.node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.node.env.BOOTSTRAP_NODES"
      wait                 = var.WAIT_FOR_PROVER_DEPLOY
    }

    rpc = {
      name  = "${var.RELEASE_PREFIX}-rpc"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "rpc.yaml",
        "rpc-resources-${var.RPC_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = concat(var.RPC_INGRESS_ENABLED ? [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
          rpc = {
            annotations = {
              "cloud.google.com/neg" = jsonencode({ ingress = true })
              "cloud.google.com/backend-config" = jsonencode({
                default = "${var.RELEASE_PREFIX}-rpc-ingress-backend"
              })
            }
          }
        }
        ingress = {
          rpc = {
            hosts = var.RPC_INGRESS_HOSTS
            annotations = {
              "kubernetes.io/ingress.class"                 = "gce"
              "kubernetes.io/ingress.global-static-ip-name" = var.RPC_INGRESS_STATIC_IP_NAME
              "ingress.gcp.kubernetes.io/pre-shared-cert"   = join(",", var.RPC_INGRESS_SSL_CERT_NAMES)
              "kubernetes.io/ingress.allow-http"            = "false"
            }
          }
        }
        })] : [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
          rpc = {
            enabled = true
            type    = local.is_kind ? "ClusterIP" : "LoadBalancer"
          }
        }
      })])

      # Pod env vars flow from var.releases.rpc.env via inline_values.
      custom_settings = {
        "replicaCount"                = var.RPC_REPLICAS
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        "service.p2p.announcePort"    = local.p2p_port_rpc
        "service.p2p.port"            = local.p2p_port_rpc
        "ingress.rpc.enabled"         = var.RPC_INGRESS_ENABLED
        # Deploy-time secrets (not in YAML).
        "node.env.AWS_ACCESS_KEY_ID"     = var.R2_ACCESS_KEY_ID
        "node.env.AWS_SECRET_ACCESS_KEY" = var.R2_SECRET_ACCESS_KEY
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    }

    fisherman = tonumber(var.FISHERMAN_REPLICAS) > 0 ? {
      name  = "${var.RELEASE_PREFIX}-fisherman"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "rpc.yaml",
        "rpc-resources-${var.RPC_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
        node = {
          logLevel = var.FISHERMAN_LOG_LEVEL
        }
      })]
      # Pod env vars flow from var.releases.fisherman.env via inline_values
      # (FISHERMAN_MODE, SEQ_BUILD_CHECKPOINT_IF_EMPTY, VALIDATORS_PER_NODE
      # come from _release_defaults.fisherman.env in network-defaults.yml).
      custom_settings = {
        "replicaCount"                = var.FISHERMAN_REPLICAS
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        "service.p2p.announcePort"    = local.p2p_port_fisherman
        "service.p2p.port"            = local.p2p_port_fisherman
        "node.secret.envEnabled"      = true
        "node.secret.mnemonic"        = var.FISHERMAN_MNEMONIC
        "node.secret.mnemonicIndex"   = var.FISHERMAN_MNEMONIC_START_INDEX
        "node.preStartScript"         = "source /scripts/get-private-key.sh"
        # Rename: chart-side var name differs from pod env name.
        "node.env.KEY_INDEX_START" = var.FISHERMAN_MNEMONIC_START_INDEX
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    } : null

    full_node = tonumber(var.FULL_NODE_REPLICAS) > 0 ? {
      name  = "${var.RELEASE_PREFIX}-full-node"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "full-node.yaml",
        "full-node-resources-${var.FULL_NODE_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
      })]
      # Pod env vars flow from var.releases.full_node.env via inline_values.
      custom_settings = {
        "nodeType"                    = "full-node"
        "replicaCount"                = var.FULL_NODE_REPLICAS
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        "service.p2p.announcePort"    = local.p2p_port_full_node
        "service.p2p.port"            = local.p2p_port_full_node
        "env.OTEL_INCLUDE_METRICS"    = var.FULL_NODE_INCLUDE_METRICS
        # Deploy-time secrets (not in YAML).
        "node.env.AWS_ACCESS_KEY_ID"     = var.R2_ACCESS_KEY_ID
        "node.env.AWS_SECRET_ACCESS_KEY" = var.R2_SECRET_ACCESS_KEY
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      // this Helm app will have lots of replicas, if we wait for all to come online we'll surely time out.
      wait = false
    } : null

    archive = var.DEPLOY_ARCHIVAL_NODE ? {
      name  = "${var.RELEASE_PREFIX}-archive"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "archive.yaml",
        "archive-resources-${var.ARCHIVE_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
      })]
      # Pod env vars flow from var.releases.archive.env via inline_values.
      # P2P_ARCHIVED_TX_LIMIT is set in _release_defaults.archive.env.
      custom_settings = {
        "nodeType"                    = "archive"
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        "service.p2p.announcePort"    = local.p2p_port_archive
        "service.p2p.port"            = local.p2p_port_archive
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    } : null

    # Blob sink: uploads blobs to filestore as it syncs
    blob_sink = var.BLOB_FILE_STORE_UPLOAD_URL != null ? {
      name  = "${var.RELEASE_PREFIX}-blob-sink"
      chart = "aztec-node"
      values = [
        "common.yaml",
        "blob-sink.yaml",
        "blob-sink-resources-${var.BLOB_SINK_RESOURCE_PROFILE}.yaml"
      ]
      inline_values = [yamlencode({
        service = {
          p2p = { publicIP = var.P2P_PUBLIC_IP }
        }
      })]
      # Pod env vars flow from var.releases.blob_sink.env via inline_values.
      custom_settings = {
        "nodeType"                    = "blob-sink"
        "service.p2p.nodePortEnabled" = var.P2P_NODEPORT_ENABLED
        # Deploy-time secrets / computed (not in YAML).
        "node.env.BLOB_FILE_STORE_UPLOAD_URL" = var.BLOB_FILE_STORE_UPLOAD_URL
        "node.env.AWS_ACCESS_KEY_ID"          = var.R2_ACCESS_KEY_ID
        "node.env.AWS_SECRET_ACCESS_KEY"      = var.R2_SECRET_ACCESS_KEY
      }
      boot_node_host_path  = "node.env.BOOT_NODE_HOST"
      bootstrap_nodes_path = "node.env.BOOTSTRAP_NODES"
      wait                 = true
    } : null

    # Optional: transfer bots
    bot_transfers = var.BOT_TRANSFERS_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-transfers"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-token-transfer.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_TRANSFERS_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_TRANSFERS_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_TRANSFERS_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_TRANSFERS_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_TRANSFERS_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_TRANSFERS_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null

    # Optional: AMM swap bots
    bot_swaps = var.BOT_SWAPS_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-swaps"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-amm-swaps.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_SWAPS_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_SWAPS_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_SWAPS_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_SWAPS_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_SWAPS_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_SWAPS_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null

    # Optional: cross-chain message bots
    bot_cross_chain = var.BOT_CROSS_CHAIN_REPLICAS > 0 ? {
      name  = "${var.RELEASE_PREFIX}-bot-cross-chain"
      chart = "aztec-bot"
      values = [
        "common.yaml",
        "bot-cross-chain.yaml",
        "bot-resources-${var.BOT_RESOURCE_PROFILE}.yaml",
      ]
      custom_settings = {
        "bot.replicaCount"       = var.BOT_CROSS_CHAIN_REPLICAS
        "bot.txIntervalSeconds"  = var.BOT_CROSS_CHAIN_TX_INTERVAL_SECONDS
        "bot.followChain"        = var.BOT_CROSS_CHAIN_FOLLOW_CHAIN
        "bot.pxeSyncChainTip"    = var.BOT_CROSS_CHAIN_PXE_SYNC_CHAIN_TIP
        "bot.botPrivateKey"      = var.BOT_CROSS_CHAIN_L2_PRIVATE_KEY
        "bot.nodeUrl"            = local.internal_rpc_url
        "bot.mnemonic"           = var.BOT_MNEMONIC
        "bot.mnemonicStartIndex" = var.BOT_CROSS_CHAIN_MNEMONIC_START_INDEX
        "bot.daGasLimit"         = var.BOT_DA_GAS_LIMIT
        "bot.l2GasLimit"         = var.BOT_L2_GAS_LIMIT
      }
      boot_node_host_path  = ""
      bootstrap_nodes_path = ""
      wait                 = false
    } : null
  }, local.validator_releases)
}

# Create all helm releases using for_each
resource "helm_release" "releases" {
  for_each = { for k, v in local.helm_releases : k => v if v != null }

  provider         = helm.gke-cluster
  name             = each.value.name
  repository       = "../../"
  chart            = each.value.chart
  namespace        = var.NAMESPACE
  create_namespace = true
  upgrade_install  = true
  force_update     = true
  recreate_pods    = true
  reuse_values     = false
  timeout          = lookup(each.value, "timeout", 600)
  wait             = each.value.wait
  wait_for_jobs    = true

  values = concat(
    [for v in each.value.values : file("./values/${v}")],
    [local.common_inline_values],
    lookup(each.value, "inline_values", []),
    # New (Phase 4): per-release Helm values passed directly from the YAML loader
    # via terraform.tfvars.json's `releases.<release_name>` map. The loader emits
    # values that already match the chart's expected shape (validator.env.*, etc.),
    # so this is a direct pass-through with no per-key mapping. The existing `set`
    # blocks below override these (kept for back-compat with current deploys).
    contains(keys(var.releases), each.key) ? [yamlencode(var.releases[each.key])] : []
  )

  # Common settings
  dynamic "set" {
    for_each = { for k, v in merge(
      local.common_settings,
      each.value.custom_settings,
      # Add boot node if needed
      each.value.boot_node_host_path != "" && local.internal_boot_node_url != "" ? {
        (each.value.boot_node_host_path) = local.internal_boot_node_url
      } : {},
      each.value.bootstrap_nodes_path != "" && length(var.EXTERNAL_BOOTNODES) > 0 ? {
        (each.value.bootstrap_nodes_path) = join(",", var.EXTERNAL_BOOTNODES)
      } : {}
    ) : k => v if v != null }
    content {
      name  = set.key
      value = set.value
    }
  }

  # Common list settings
  dynamic "set_list" {
    for_each = { for k, v in local.common_list_settings : k => v if v != null }
    content {
      name  = set_list.key
      value = set_list.value
    }
  }
}

resource "kubernetes_manifest" "rpc_ingress_backend" {
  count    = var.RPC_INGRESS_ENABLED ? 1 : 0
  provider = kubernetes.gke-cluster

  manifest = {
    apiVersion = "cloud.google.com/v1"
    kind       = "BackendConfig"
    metadata = {
      name      = "${var.RELEASE_PREFIX}-rpc-ingress-backend"
      namespace = var.NAMESPACE
    }
    spec = merge(
      {
        healthCheck = {
          checkIntervalSec   = 15
          timeoutSec         = 5
          healthyThreshold   = 2
          unhealthyThreshold = 2
          type               = "HTTP"
          port               = 8080
          requestPath        = "/status"
        }
      },
      var.RPC_CLOUD_ARMOR_POLICY_NAME != "" ? {
        securityPolicy = {
          name = var.RPC_CLOUD_ARMOR_POLICY_NAME
        }
      } : {},
      var.RPC_INGRESS_SESSION_AFFINITY != "" ? {
        sessionAffinity = {
          affinityType = var.RPC_INGRESS_SESSION_AFFINITY
        }
      } : {},
      var.RPC_INGRESS_LOG_SAMPLE_RATE != null ? {
        logging = {
          enable     = true
          sampleRate = var.RPC_INGRESS_LOG_SAMPLE_RATE
        }
      } : {}
    )
  }
}
